### ISSUE TITLE
warning: lower/upper bound of variable redefined

### ISSUE THREAD

**Issue by jrlooker** [Pyomo/pyomo#100]
Hi,

I'm regularly getting the following warning from Pyomo when solving MIPs:
"warning: lower bound of variable 'X' redefined"
I also get the same warning for the upper bound. The variable X is binary.

I'm using Pyomo 5.0.1.

Is this a bug? Should I be concerned?

Thanks,
Jason

**Comment by jsiirola** [comment]
Can you provide more information?  That looks like a warning from the MIP solver and not from Pyomo.  A small (preferably, minimal) example exhibiting the warning would be most helpful.

**Comment by jrlooker** [comment]
Sorry for my slow response.

I'm using GLPSOL: GLPK LP/MIP Solver, v4.60. 

I'm solving a dynamic problem and the binary variable that is the subject of the warning is initialised to either 0 or 1, but the solver returns either 0.0 or 1.0 for the solution. Does this help?

I don't have a small example readily available but if you require it, I may be able to generate one.

**Comment by jsiirola** [comment]
This is a warning tossed by glpsol, and not a Pyomo bug.  The most likely thing is that you are defining a bounded variable (likely a binary variable), and then separately declaring (redundant) constraints that impose bounds on the variable.  For example, given:

    m.x = Var(within=Binary)

`m.x` is defined with a lower bound of 0 and an upper bound of 1.  If you later declare constraints akin to

    m.x >= 0

then glpsol interprets these constraints as "new" bounds and tosses the warning.  It shouldn't change the solution, although it may effect glpsol's performance.

**Comment by jrlooker** [comment]
Thanks, John
