### ISSUE TITLE
EOS property models and UI in IDARS

### ISSUE THREAD

**Issue by hbeden** [Pyomo/pyomo#1000]
Hi, 
I want to ask whether EOS property model in idaes can be used in a flowsheet optimization model. I found examples in folder use a special property.py file.

The other thing is whether there is a UI for ideas in developing.

Regards,
Eden

**Comment by qtothec** [comment]
@hbeden Did you intend to post this issue in the IDAES repository, perhaps?

**Comment by hbeden** [comment]
There is no response in that place. Only one issue.

**Comment by hbeden** [comment]
@qtothec, I post it here because you are here. I know you are author of some IDAES codes.

**Comment by jghouse88** [comment]
@hbeden IDAES currently does not support CEOS if that is what you are asking. However, it will be made available in upcoming releases. Also, yes the EOS models will be suitable for flowsheet optimization. For further issues on IDAES, please post them on idaes-pse repo and we will get back to you ASAP. You can also email us on idaes-support@idaes.org.

**Comment by qtothec** [comment]
Closing as resolved.
