### ISSUE TITLE
Bug in CBCplugin

### ISSUE THREAD

**Issue by RainSunGone** [Pyomo/pyomo#1001]
I've spotted a bug in my implementation of: https://github.com/Pyomo/pyomo/pull/874

In `pyomo/solvers/plugins/solvers/CBCplugin.py`
Line 479 should read 
```python
optim_value = float(tokens[6])
```
Instead of 
```python
optim_value = float(tokens[6][:-1])
```

Shall I raise a PR to fix?

**Comment by jsiirola** [comment]
Yes, please open a PR.  Also please include (if possible) a test case that demonstrated the bug / exercises the solution.  Thank you!
