### ISSUE TITLE
Bug in passing boolean parameters to GAMS

### ISSUE THREAD

**Issue by Johanna1234** [Pyomo/pyomo#1019]
Somwhere between Version 5.4.3 and 5.6.1 pyomo changed way passing boolean parameters to GAMS.

In pyomo versions <= 5.4.3 the boolean parameters where passed as binaries. That is the right way because GAMS does not have boolean parameters or variables.
With pyomo 5.6.1 GAMS raises error 140 "unknown symbol" because it can not handle stings "TRUE"/"False" in equations.

**Comment by jsiirola** [comment]
@Johanna1234 Can you provide a small (ideally, minimal) example of what you are doing to aid in debugging?

**Comment by Johanna1234** [comment]
the model does not make sense but I think it shows what I meant

```python
from pyomo.environ import *
import random

model = AbstractModel()

model.T = Set(initialize=range(10), ordered=True)

model.price = Param(initialize=10, within=NonNegativeReals)
model.active_start = Param(initialize=True, within=Boolean)
model.power = Param(initialize=5, within=NonNegativeReals)

def demand_init(model, t):
    demand = random.sample(range(30), 10)
    return demand[t]

model.demand = Param(model.T, initialize=demand_init, within=NonNegativeReals)

# the next line declares variable
model.is_active = Var(model.T, domain=Boolean)

def obj_expression(model):
    return summation(model.is_active) * model.power * model.price 

model.OBJ = Objective(rule=obj_expression)

def constraint1_rule(model):
    return (sum(model.is_active[t] for t in model.T) + model.active_start) * model.power >= sum(model.demand[t] for t in model.T)

# the next line creates one constraints
model.Constraint1 = Constraint(rule=constraint1_rule)

# solve model
instance = model.create_instance()
opt = SolverFactory('gams', options={'optcr': 0.01}, solver_io='gms')
opt.solve(instance, keepfiles=True) 
```

pyomo 5.6.1: 

![image](https://user-images.githubusercontent.com/45566892/57706565-45b8ee00-7666-11e9-8711-9db357a65aed.png)

pyomo 5.4.3:

![image](https://user-images.githubusercontent.com/45566892/57706679-83b61200-7666-11e9-8cc7-d8e29380da21.png)

**Comment by qtothec** [comment]
@jsiirola Is `domain=Boolean` just an alias for `domain=Binary` or does it do something different?

**Comment by ghackebeil** [comment]
Alias, mostly (as in `is` comparison would fail):

https://github.com/Pyomo/pyomo/blob/e504fbecf9128c17d01f8f9665ce5c9f8179a0f8/pyomo/core/kernel/set_types.py#L250
https://github.com/Pyomo/pyomo/blob/e504fbecf9128c17d01f8f9665ce5c9f8179a0f8/pyomo/core/kernel/set_types.py#L251

**Comment by qtothec** [comment]
Thanks @ghackebeil.

After looking at this on my computer, it looks like the issue is in this `Param`:
```
model.active_start = Param(initialize=True, within=Boolean)
```

In the constraint, the parameter is being added as part of an algebraic expression: 
```
(sum([...]) + model.active_start) * model.power >= sum([...])
```

That formulation is not mathematically correct, because the algebraic operation of addition is not defined for values of `True` or `False` (e.g. what does `x = True - False` mean?). You probably mean to have a `Param` of domain `Binary`:
```
model.active_start = Param(initialize=1, within=Binary)
```
Alternatively, you could cast your parameter value to `int`:
```
(sum([...]) + int(model.active_start)) * model.power >= sum([...])
```

**Comment by gseastream** [comment]
Is there anything more to be done with this issue or should it be closed?

**Comment by blnicho** [comment]
I'm not sure what code change modified this behavior between versions 5.4.3 and 5.6.1 but I think @qtothec adequately addressed the modeling question and offered great alternatives for avoiding this issue. At this point I don't think anything else need to be done so this can be closed.
