### ISSUE TITLE
Sympy Error

### ISSUE THREAD

**Issue by aereoyo** [Pyomo/pyomo#1020]
DeveloperError: Internal Pyomo implementation error:
	"sympy expression type 'im' not found in the operator map"
	Please report this to the Pyomo Developers.

**Comment by qtothec** [comment]
Are you working with complex numbers? Can you tell us what function in Pyomo you were calling (or provide the full stack trace)?

**Comment by blnicho** [comment]
Closing this as no additional information has been received. @aereoyo if you are still seeing an issue please reopen this and provide more detailed information to help us diagnose the problem.
