### ISSUE TITLE
Constrained regressions using pyomo

### ISSUE THREAD

**Issue by yzheng27** [Pyomo/pyomo#1022]
Hi, I want to construct a regression with certain constraints on the coefficient and model results. My objective is to minimize error. There are two types of variables to be optimized

1. param that used to transform certain input columns (param)
2. regressions coefficient (beta)

I set lower and upper bounds for beta and param variables. The only constraint i want to have is when I plug in the beta to look at the decomposition of model, the total impact of base variables should be non-negative. 

When I set up all except the non-negative base constraint, I got the optimal solution. But it seems like I only got the optimal solution for beta, the resultant param values are the same as the initialization and do not satisfy their bounds. 

When I included all the setting, it exceeds maximum iteration even I set a high max_iter. 

Please correct me if I set up things wrong and let me know your advice to tackle this kind of problem using pyomo. Thank you!

```
def incorporate_adstock(original_data, model):
    tmp_x = original_data.copy()
    imp_col = [i for i in tmp_x.columns if 'impression' in i]
    for col in imp_col:
        decay = model.decay[col].value
        dr = model.dr[col].value
        tmp_x[col] = tsa.filters.filtertools.recursive_filter(tmp_x[col], 1-decay) ** dr
    return tmp_x

def nonnegative_base(model):
    base_col = [i for i in beta if re.search('const|base', i)]
    base = [sum(model.data[base][j-1]*model.beta[base] for base in base_col) for j in model.nrow]
    output = [i < 0 for i in base]
    return sum(output)

def minimize_rmse(model):
    error = sum((model.y[i-1] - model.fitted[i-1])**2 for i in model.nrow)/len(model.y) 
    return error

model = ConcreteModel()
beta = list(lb_beta.keys())
decay = list(lb_decay.keys())
dr = list(lb_dr.keys())
model.beta = Var(beta, domain=Reals, bounds = beta_bound, initialize = initialize)
model.decay =  Var(decay, domain=PositiveReals, bounds = decay_bound, initialize = initialize)
model.dr = Var(dr, domain = PositiveReals, bounds = dr_bound, initialize = initialize)
model.nrow = RangeSet(1, numdata)
model.y = y
model.data = incorporate_adstock(model_input, model)
model.fitted = [sum(model.data[b][j-1]*model.beta[b] for b in beta) for j in model.nrow]

# model.nonnegativebase = Constraint(expr = 0 == nonnegative_base(model))
model.obj = Objective(rule = minimize_rmse, sense = minimize)
solver = 'ipopt' 
opt = SolverFactory(solver)
# opt.options["halt_on_ampl_error"] = "yes" 
# opt.options['max_iter'] = 1000
opt.solve(model, tee=True)

```

**Comment by qtothec** [comment]
For general modeling questions, I invite you to pose your question on the [user forum](https://groups.google.com/forum/#!forum/pyomo-forum) or [StackOverflow](https://stackoverflow.com/questions/tagged/pyomo). The Github issues system is more for discussions/concerns targeting changes to the codebase.
