### ISSUE TITLE
pynumero installation typo

### ISSUE THREAD

**Issue by dthierry** [Pyomo/pyomo#1024]
The line :
`cp lib/libpynumero_* ../../extensions/lib/Linux/`
Should be:
`cp asl_interface/libpynumero_* ../../extensions/lib/Linux/`
Can anybody confirm this?
This can be found in the file 
` pyomo/pyomo/contrib/pynumero/doc/source/installation.rst `

**Comment by blnicho** [comment]
I can confirm this. @santiagoropb also knows about this and other documentation updates that need to be made. I think the plan is to include these changes in #804
