### ISSUE TITLE
[PEP] Standardizing on location to link examples and documentation from outside pyomo development

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#1027]
There have been numerous examples and documentation or documentation snippets that have been created by the people outside the development group. The purpose of this PEP is to discuss the process by which we should link to these external examples, etc.

I propose we setup a section on the front page of our website, and also on our GitHub wiki page. Other thoughts?

**Comment by michaelbynum** [comment]
@carldlaird Can you point to an example? I'm not sure exactly what you are referring to.

**Comment by michaelbynum** [comment]
@carldlaird Nevermind. I am caught up.

**Comment by qtothec** [comment]
We may also want to clarify the extent to which we promise that these examples will be kept up to date. As far as I know, we don't have a system in place to at least notify folks when upstream changes are likely to break things that they are doing.

**Comment by carldlaird** [comment]
We agreed to post these on the GitHub page, in read-the-docs, and on the Pyomo website. 

@blnicho agreed to do this.
