### ISSUE TITLE
5.6.2 GAMS writer probelm: AttributeError: '_GeneralExpressionData' object has no attribute '_associativity'

### ISSUE THREAD

**Issue by natalieisenberg** [Pyomo/pyomo#1029]
I have noticed that for the same Pyomo model, using the GAMS writer in Pyomo 5.6.2 gives this error:

 AttributeError: '_GeneralExpressionData' object has no attribute '_associativity'

Which I believe is being raised in the gams_writer.py "visit" function. I do not get this error with Pyomo 5.6.1 for that same model.

**Comment by blnicho** [comment]
Do you have a small example you can share that recreates this behavior?

**Comment by natalieisenberg** [comment]
I can try to make a simple example! But it may take some trial-and-error.

**Comment by jsiirola** [comment]
I believe it is caused by a model with an `Expression` component in it.  PR #1031 should fix that specific issue.

**Comment by blnicho** [comment]
Looks like @jsiirola tracked down the problem already so don't worry about an example. We should have a fix merged shortly and we'll be cutting a patch release tomorrow.
