### ISSUE TITLE
[PEP] Clean up Pyomo / Pyutilib console scripts

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#1040]
We've had discussions about this in the past, but its time to make it official. I think we need to cut back on the number of console scripts we install, biggly.

Here is the list of scripts added to my bin directory after a fresh Pyomo install.

By Pyutilib:
 - checkCopyright
 - dispatch_srvr
 - lbin
 - lpython
 - pypi_downloads
 - pyutilib_test_driver
 - replaceCopyright
 - test.pyutilib

By Pyomo:
 - computeconf
 - evaluate_xhat
 - kill_pyro_mip_servers
 - launch_pyro_mip_servers
 - OSSolverService
 - phsolverserver
 - pyomo
 - pyomo_ns
 - pyomo_nsc
 - pyomo_old
 - pyomo_python
 - pyro_mip_server
 - readsol
 - results_schema
 - runbenders
 - runef
 - runph
 - scenariotreeserver
 - test.pyomo

This exceeds the number of console scripts in my system bin directory (associated with all python packages I've ever installed, over multiple Python versions) by almost a factor of two.

Let's discuss how to clean this up.

**Comment by michaelbynum** [comment]
I agree.

**Comment by jsiirola** [comment]
I agree.  As an opening proposal:

Pyutilib:
   - Keep
   - Deprecate immediately, replace with "executable modules" (e.g., `python -m pyutilib.foo`), remove the console script in 5.8
      - checkCopyright
      - lbin
      - lpython
      - pypi_downloads
      - replaceCopyright
      - test.pyutilib (assuming that we can make coverage work correctly)
   - Deprecate immediately, do not replace, remove the console script in 5.8
      - dispatch_srvr
      - pyutilib_test_driver

By Pyomo:
   - Keep
      - pyomo
   - Deprecate immediately, replace with pyomo subcommands, remove the console script in 5.7
      - computeconf
      - evaluate_xhat
      - phsolverserver
      - pyomo_python
      - runbenders
      - runef
      - runph
      - test.pyomo (assuming that we can make coverage work correctly)
   - Deprecate immediately, remove the console script in 5.7
      - kill_pyro_mip_servers
      - launch_pyro_mip_servers
      - OSSolverService
      - pyomo_ns
      - pyomo_nsc
      - pyro_mip_server
      - readsol
      - results_schema
      - scenariotreeserver
   - Remove immediately
      - pyomo_old

That said, many of these scripts appear to be related to PySP, so @ghackebeil, @DLWoodruff, and @jwatsonnm should weigh in as to if they have users/customers who use/rely on them.

**Comment by jwatsonnm** [comment]
Parallel PySP users rely on the dispatch_srvr script in PyUtilib - that will be needed for as long as PySP 1.0 is alive. 

Similarly, we need pyomo_ns from Pyomo.

Some PySP users do use the pyro_mip_server script, but I would prefer that they did not - and am therefore favor in deprecation without replacement.

**Comment by DLWoodruff** [comment]
runef and runph are both documented in the book and used quite a bit.
