### ISSUE TITLE
Syntax error with GAMS writer

### ISSUE THREAD

**Issue by TheHuangs** [Pyomo/pyomo#1041]
I use GAMS to solve a model in the IDAES framework, I use 'symbolic_solver_labels=True' to show the real variables and equations name. but there are syntax errors with the names, which can not start with " number" or   "_ " in GAMS, which are as shown below.
2_control_volume_properties_out_0_0__conc_mol_comp_Ethanol__16_
_volume_rate_reaction_stoichiometry_constraint_0_0_Liq_H2O__29_

**Comment by blnicho** [comment]
@TheHuangs are you working with one of the example/workshop models distributed with the IDAES framework or building your own? Are you able to use GAMS with `symbolic_solver_labels=False`?

**Comment by TheHuangs** [comment]
I can use it when it's false, I have tested several examples in the example folder of idaes. My platform is windows.

**Comment by blnicho** [comment]
I can confirm that `symbolic_solver_labels=True` works for a pure Pyomo implementation of a knapsack problem solved using GAMS. Still checking if this is a hierarchical modeling issue on the Pyomo or the IDAES side.

**Comment by TheHuangs** [comment]
The names of variables and equations  for IDAES modle are too long, below is an example ’_volume_rate_reaction_stoichiometry_constraint_0_0_LiqH2O__29’
I think this name is not complete. The name should start with the flowsheet name(fs), and followed a unit name(R101), then control_volume.  
So I guess The whole name should be fs_R101_control_volume_rate_reaction_stoichiometry_constraint_0_0_LiqH2O__29.
I believe that GAMS writer cut off the beginning part of names, so sometimes leave a name started with number or _. The underlying reason is that the whole name for the IDAES variables and equations are too long.

**Comment by gseastream** [comment]
This is related to #683. I hadn't considered accidentally slicing symbol names such that they start with underscores when making the ShortNameLabeler. Looks like there's now multiple reasons to make the gams writer ensure that symbols don't start with underscores.
