### ISSUE TITLE
Whether MindtPy solvers is available?

### ISSUE THREAD

**Issue by TheHuangs** [Pyomo/pyomo#1046]
Hi, @qtothec , whether Mindpy solver is available for the public? and would you like to provide a GDP example? I failed to find an example in the pyomo example folder.

**Comment by blnicho** [comment]
@TheHuangs the MindtPy code that is currently distributed with Pyomo can be found here: https://github.com/Pyomo/pyomo/tree/master/pyomo/contrib/mindtpy. A few small examples can be found in the `tests` subdirectory. This package is still under active development so additional enhancements to this part of the code base are waiting to be merged in open pull requests or being developed on separate forks and branches. Basic documentation on the MindtPy solver can be found here: https://pyomo.readthedocs.io/en/latest/contributed_packages/mindtpy.html
