### ISSUE TITLE
Variable indexed by Any

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#1050]
It came as a bit of a surprise to me that ``m.maybe = Var(Any)`` throws an error:
RuntimeError: Cannot iterate over abstract Set 'Any' before it has been constructed (initialized).

 ``m.maybe=Var(Any, dense=False)`` works as expected, which makes some sense after digging into the code. But it seems like this is something that should at least be documented, especially since this is unique to indexing a Var by Any. (And I think this is still a reasonable thing to do since VarList does not give you control over the names of the keys.)

**Comment by blnicho** [comment]
It looks like this was partially documented in an old rst file that was lost during the documentation reorganization (https://github.com/Pyomo/pyomo/blob/cc58252fca1bc489789527038ea4a1c290b6b726/doc/attic/old_sphinx_files/tutorial/index.rst) but I agree that our current documentation should include this point either in the section describing `Var` components or in the section on "Working with Pyomo models"

**Comment by jsiirola** [comment]
This should definitely be included in the Var documentation.

In addition, this is indeed a poor error message.  PEP #326 would introduce more consistent handling of infinite Set objects.  At that point, we could do one of two things:

1. Produce a more informative error message when creating Vars indexed by infinite sets, including hinting at declaring them with `dense=False`.
2. Automatically assume `dense=False` if `dense` is not specified for Vars indexed by infinite Sets (we would still need to produce the error message if dense was explicitly set to True).

**Comment by emma58** [comment]
#2184 added a nice warning when you don't specify `dense=False`, so closing this.
