### ISSUE TITLE
Ipopt solver cannot deal with exponent less than one

### ISSUE THREAD

**Issue by linmeishang** [Pyomo/pyomo#1062]
Hi, 

my Ipopt solver sometimes cannot deal with exponent less than one. 

`
def production_function(model, i): 
    return prod(model.x[i,j]**model.b[j] for j in model.Inputs)
model.Q = Expression(model.Crops, rule=production_function)
`
Every time i set model.b[j] < 1, this warning occurs: **ValueError: Cannot load a SolverResults object with bad status: error.** 
if i set model.b[j] >= 1,  model can be solved. 

Can anybody help me? Thanks a lot!

**Comment by blnicho** [comment]
Are you initializing your variable `model.x`? The default initialization value is 0 which will lead to evaluation errors with negative exponents.

**Comment by blnicho** [comment]
Issues on the Pyomo GitHub page are meant for bug-reports and feature requests. If you have modeling or implementation questions please ask them on the Pyomo forum or on StackOverflow.

**Comment by linmeishang** [comment]
> Are you initializing your variable `model.x`? The default initialization value is 0 which will lead to evaluation errors with negative exponents.
Yes, I have initialized variable model.x. 
`model.Crops = Set() # set Crops := cereal rapes maize ;
model.Inputs = Set() # set Inputs := land labor capital fertilizer;
model.x = Var(model.Crops, model.Inputs, initialize = 50.0, within=NonNegativeReals) `

> Issues on the Pyomo GitHub page are meant for bug-reports and feature requests. If you have modeling or implementation questions please ask them on the Pyomo forum or on StackOverflow.

thanks for telling me!
