### ISSUE TITLE
Pyomo test dependencies

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#1064]
I tested Pyomo on a machine today that does not have GAMS installed, and I got a GDP test failure due to the GAMS not being used.

There are two related issues that need to be addressed:

1. When pyomo tests call the solver available() method, they should pass the argument False, so an exception isn't generated.

2. We should have at least one CI test that has *no* solvers available.  This will test a condition that developers may not see often, but which new users will see frequently.

**Comment by blnicho** [comment]
@whart222 we do have a Jenkins job that runs tests with no solvers available and it looks like this GDP test failure is only 1 commit old. Seems like just a mistake in forgetting the `exception_flag=False` option on one test.

**Comment by jsiirola** [comment]
@whart222: what would you think about changing the default value for the exception flag?  I am not familiar with a case where we want or rely on it being True...
