### ISSUE TITLE
CUIDs for components indexed by Any

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#1069]
It seems that Component UIDs don't behave the same way when you index by Any. I ran into this with Disjunctions, but here's a simple example with Constraints:
```
from pyomo.environ import *

m = ConcreteModel()
m.x = Var()
m.a = Constraint(Any)
@m.Constraint([0,1])
def b(m, i):
    return m.x >= i

m.a[0] = m.x >= 8

m.pprint()

if ComponentUID(m.b[0]).find_component(m) is m.b[0]:
    print("Life is good")

if ComponentUID(m.a[0]).find_component(m) is None:
    print("Should this happen?")
```
Both of the prints statements run... I should expect m.a to behave like m.b, right?

**Comment by blnicho** [comment]
Looks like the problem has to do with indices not being flattened when a component is indexed by Any:

    m.b[(0,)]  # returns the ConstraintData for index 0
    m.a[(0,)]  # Throws a KeyError
