### ISSUE TITLE
Inconsistency asking a Block to find itself

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#1072]
Blocks behave differently than Models when you ask them to find themselves:
```
from pyomo.environ import *

m = ConcreteModel()
m.b = Block()

if m.find_component(m) is m:
    print("Model returns itself.")

if m.b.find_component(m.b) is None:
    print("But block returns None.")
```
This is an issue if you have passed a Block as the argument to a transformation and want it to behave as if that Block is a Model (and probably other times we want to pretend that Blocks are Models).

**Comment by emma58** [comment]
OK, this makes some sense, but I think it means that we cannot let CUIDs be ways to specify targets for transformations or anything like this. Because unless I am missing something, there can be no error checking if you only have the CUID because it could be in the wrong context. 

In the extreme case, I can break things by giving you the CUID in the wrong context when multiple trees are involved. This is soon to be a moot point, but in the current implementation of bigm, I can do this:
```
m = ConcreteModel()
b = Block() # Suppose I'm crazy and I forget this isn't attached to anything
# also suppose m has disjunctions
TransformationFactory('gdp.bigm').apply_to(m, targets=ComponentUID(b))
```
Because I didn't specify `m` as the context in the CUID, and (I guess?) because `m`  and `b` are both root nodes, `ComponentUID(b).find_component_on(m)` returns `m`. So the above would not only not complain, it would transform all of m. And I'm not sure how to prevent this because how would I know that the CUID was crazy? There's nothing `find_component` could do about it, right, since it started with the CUID and didn't get to generate it in the context it needed?

And in the above example, if someone had called bigm on `m.b` and specified `targets=ComponentUID(m.b)`, how would I verify that `m.b` is indeed a (nonstrict) subcomponent of `m.b`?

**Comment by mrmundt** [comment]
In an effort to clean up old issues, we are moving some design discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
