### ISSUE TITLE
'SumExpression' object is not iterable

### ISSUE THREAD

**Issue by Sdinesh7** [Pyomo/pyomo#1079]
[a.zip](https://github.com/Pyomo/pyomo/files/3347378/a.zip)

'SumExpression' object is not iterable......i get this error at thus line model.nt[j] = model.ntm1[j] + model.q[j]*R_2_j(model, j, -1) + model.q[j]*(R_1_j(model,j, 0) + G_e_j(model,j, 0)) - model.s[j]*G_e_j(model,j, 0) in below code

**Comment by blnicho** [comment]
Issues on the Pyomo GitHub page are meant for bug-reports and feature requests. If you have modeling or implementation questions please ask them on the Pyomo forum or on StackOverflow.
