### ISSUE TITLE
Crashes when running on diet-local variable 'opt' referenced before assignment

### ISSUE THREAD

**Issue by julesbacon** [Pyomo/pyomo#108]
When running Pyomo 5.1.1 on the diet example, it crashes with the following output:

pyomo solve --solver-manager=neos --solver=cbc diet.py diet.dat

[    0.00] Setting up Pyomo environment

[    0.00] Applying Pyomo preprocessing actions

[    0.00] Creating model

[    0.08] Applying solver

Job 5221021 submitted to NEOS, password='AboTtVvN'

Check the following URL for progress report :

https://www.neos-server.org/neos/cgi-bin/nph-neos-solver.cgi?admin=results&jobnumber=5221021&pass=AboTtVvN

Job 5221021 dispatched

password: AboTtVvN

---------- Begin Solver Output -----------

Condor submit: 'neos.submit'

Condor submit: 'watchdog.submit'

Job submitted to NEOS HTCondor pool.

[   26.96] Pyomo Finished

ERROR: Unexpected exception while running model:

local variable 'opt' referenced before assignment

The problem may be associated with this commit: https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FPyomo%2Fpyomo%2Fcommit%2Fc27c98459e2ace9c28863e951be2d54d7531cbbe&sa=D&sntz=1&usg=AFQjCNHTjhXdnpE9SVBeOznx1zZKI2IeKA

**Comment by whart222** [comment]
This is fixed with commit https://github.com/Pyomo/pyomo/commit/c667585581231b2c7b829583b3f871aab32f08f2 .  We'll try to process a patch release for 5.1 this week.
