### ISSUE TITLE
recursions with constraints

### ISSUE THREAD

**Issue by cognoscentai** [Pyomo/pyomo#1081]
I'm interested in defining a recursion with constraints as follows:

l_(t) = a * l_(t_1) + b * x(t_1)
lb <= l_(t) <= ub, for all t

where x is a binary control variable in {0,1}.

I didn't find much documentation on this problem. I attempted to code this myself in pyomo but without success. Any advice would be greatly appreciated.

**Comment by blnicho** [comment]
Issues on the Pyomo GitHub page are meant for bug-reports and feature requests. If you have modeling or implementation questions please ask them on the Pyomo forum or on StackOverflow.
