### ISSUE TITLE
Bug when using summation() with empty vectors and GAMS as a solver 

### ISSUE THREAD

**Issue by Oriloni** [Pyomo/pyomo#1084]
When using summation(x,y) with at least one empty vector, pyomo produces an empty parentheses in the corresponding constraint/objective function, see the following instance.pprint() output:
```
2 Objective Declarations
    obj : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : maximize :  + () + () + () + x_u[1]*x_l[1]
```
It is passed on to GAMS as
`c6.. GAMS_OBJECTIVE =e=  + () + () + () + x3*x5 ;`
and GAMS fails to compile such a model.

**Comment by blnicho** [comment]
This doesn't have a minimal example to check for this behavior but I couldn't find a way to call `summation` with an empty vector to produce the reported Objective function without an error being raised so I think this can be closed.
