### ISSUE TITLE
More helpful error message when trying to fix an Expression

### ISSUE THREAD

**Issue by andrewlee94** [Pyomo/pyomo#1091]
The IDAES tools make extensive use of `Expressions` in places, which is leading some inexperienced (and the occasional experienced) user to try to `fix` these (which obviously results in an exception). Whilst the resulting error message (_GeneralExpressionData object has no method fix) is meaningful to an experienced user, it is not clear to inexperienced users what this means.

In order to provide more guidance to inexperienced users, I am suggesting adding a `fix` method to `Expressions` which raises an exception with a more useful error message. The error should inform the user that the component they are trying to fix is in fact an `Expression` and cannot be fixed, and some guidance on how to proceed.

Similar messages would be useful for other common actions on `Vars`, e.g. `unfix`, `setlb` and `setub`.

**Comment by eslickj** [comment]
Related to https://github.com/IDAES/idaes-dev/issues/329

**Comment by blnicho** [comment]
Resolution of this issue has been moved to IDAES. See https://github.com/IDAES/idaes-dev/pull/830
