### ISSUE TITLE
Add interface to OSQP

### ISSUE THREAD

**Issue by bstellato** [Pyomo/pyomo#1096]
It would be great to have an interface to [OSQP](https://github.com/oxfordcontrol/osqp). I see some users already asked for it https://github.com/oxfordcontrol/osqp/issues/166

Unfortunately I am not familiar with Pyomo internals. Any help would be appreciated. 

Thanks!

**Comment by amir-hoseyn77** [comment]
Has anything changed?

**Comment by jsiirola** [comment]
I think this would be great, but unfortunately, I don't know of anyone on the development team who is actively working on it.  PRs are always welcome (and if someone wants to take this on, we are always happy to chat / provide pointers).

I took a quick look at the Python bindings for OSQP and it doesn't look too bad: the interface is a pretty standard numpy-based interface.  The challenge with writing the solver interface will be the "compiler" that generates the matrix representation of a general Pyomo model.  I think you could leverage `generate_standard_repn`, although I suspect that rewriting that to directly compile to numpy may be more efficient (rewriting `generate_standard_repn` is already on my to-do list...)

**Comment by mrmundt** [comment]
Tracking this in the [Archived Design Discussions wiki page](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
