### ISSUE TITLE
Allow pint units in the input dictionary for abstract models

### ISSUE THREAD

**Issue by larsschellhas** [Pyomo/pyomo#1100]
Handling units in pyomo should work just as if you handle units in other python code.
If I want to instantiate an abstract model from a python dictionary, it should be able to hand in pint quantities as parameters.

**Comment by mrmundt** [comment]
In an effort to clean up old issues, we are moving some design discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).

**Comment by galina-tmh** [comment]
I would highly appreciate instantiation of abstract model based on input given as pint quantities.
@mrmundt, could you please tell whether this issue is resolved or just been archived?

**Comment by mrmundt** [comment]
@galina-tmh - It is archived. It is not on our critical path to incorporate this; however, we welcome Pull Requests for enhancements that we do not have the bandwidth to address.
