### ISSUE TITLE
Pass options to gams/cplew

### ISSUE THREAD

**Issue by sdementen** [Pyomo/pyomo#1105]
How can I pass the 'threads' option to CPLEX when using the gams solver factory?

**Comment by blnicho** [comment]
See [this answer](https://stackoverflow.com/questions/54915415/solvefactorygams-modify-optca-and-optcr) on StackOverflow for an example of passing solver options when using solvers from GAMS

**Comment by sdementen** [comment]
Fantastic! Thank you!
Is there some place in pyomo documentation where this could be added?
