### ISSUE TITLE
Baron .bar writer error

### ISSUE THREAD

**Issue by natalieisenberg** [Pyomo/pyomo#1113]
The Baron file writer (**baron_writer.py**) in the expression tree parsing (class ToBaronVisitor, visit() method) seems to be checking "is" type as opposed to "is instance" of a type. Specifically, I have a certain constraint that has an "NPV_PowExpression" object that is being written as a string to the.bar file (meaning, the ** operator for power hasn't been replaced with the "^" Baron requires). I think this is happening at line 102 of the baron_writer.py where type is checked against "is EXPR.PowExpression," since NPV_PowExpression is an instance of PowExpression and not a PowExpression type itself.

**Comment by qtothec** [comment]
Wow, you really dug in and figured out the root cause of the issue.
