### ISSUE TITLE
Confusing error message defining a 2D array Param with domain/within and initialize specified

### ISSUE THREAD

**Issue by joseortiz3** [Pyomo/pyomo#1124]
I am confused by an error message that does not help when trying to create a `Param` that should be real numbers and initialized by passing 2D array values:

```python
>>> import pyomo
>>> import pyomo.environ as pe

>>> a = [[1,1,1,1,1],[1,1,1,1,1]]
>>> model = pe.ConcreteModel()
>>> model.a = pe.Param(domain=pe.Reals, initialize=a)

ERROR: Constructing component 'a' from data=None failed: ValueError: Error
    retrieving immutable Param value (a):
    	The Param value is undefined and no default value is specified.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\block.py", line 568, in __setattr__
    self.add_component(name, val)
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\block.py", line 1008, in add_component
    val.construct(data)
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\param.py", line 869, in construct
    self._initialize_from(self._rule)
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\param.py", line 818, in _initialize_from
    _init = self[idx]
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\indexed_component.py", line 356, in __getitem__
    return self._getitem_when_not_present(index)
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\param.py", line 482, in _getitem_when_not_present
    % ( idx_str,) )
ValueError: Error retrieving immutable Param value (a):
	The Param value is undefined and no default value is specified.
```
Note that this mysterious error message only occurs when _both_ domain and initialize are specified.

I think this is either a bug, or something that needs to be caught earlier with a different error message.

System info: Pyomo 5.6.6 (I noticed your package doesn't have a `__version__` attribute...)

**Comment by blnicho** [comment]
The problem is that you're not using a valid data structure to initialize the `Param` and you haven't provided indexing sets to specify that the `Param` is indexed. When you leave out `domain=Reals` and things seem to work, you're actually getting a singleton parameter that contains the list of lists you passed in. I'm assuming the behavior you actually want is to have a 2D parameter and to check that the value of the parameter at each index is in the specified domain. To do that you should use a dictionary or a rule to initialize your parameter:

```
from pyomo.environ import *
m = ConcreteModel()

# Initialize using a rule
a = [[1,1,1,1],[1,1,1,1]]
def init_a(m, i,j):
    return a[i,j]
m.a = Param([0,1], [0,1], domain=Reals, initialize=init_a)

# Initialize using a dictionary
b = {(0,0}:1, (0,1):1, (1,0):1, (1,1):1}
m.b = Param([0,1], [0,1], domain=Reals, initialize=b)
```

I agree that the error message you're seeing doesn't help with debugging but I think if you had printed the parameter or tried to use it later in a constraint it would have become clear that there was a problem with the declaration. I'm going to close this.

**Comment by joseortiz3** [comment]
`pyomo` is extremely difficult to use with its error messages, strict but unstated requirements for data structures, and lack of flexibility with handling data. For instance if a Parameter is indexed by any ordered set of cardinality 10, new users expect they can pass any data structure that has cardinality 10 to initialize, just as they can with `numpy`, `pandas`, etc. The learning curve is really steep with pyomo because of these requirements and lack of helpful error messages. And I don't think the issue should be closed because it's clear there is a problem the user interface providing misleading and unhelpful error messages in this instance.

**Comment by blnicho** [comment]
Oops, you are correct, I have a small typo in my initialization rule. It should have been `return a[i][j]`. But the cryptic `TypeError: list indices must be integers or slices, not tuple` message that is thrown is from Python not Pyomo. You would get the same error message anywhere you try to index into `a` using `[i,j]`.

The development team acknowledges that some of our error messages are not the most intuitive for new users so if you have ideas on how they can be improved, PRs are always welcome.

**Comment by joseortiz3** [comment]
Actually I think it would be better to rewrite the issue. The issue is really lack of argument validation inside the `Param` constructor (or it's superclass, not sure of its inheritance). So I'll close this an open a new issue.
