### ISSUE TITLE
Param constructor throws unhelpful cryptic error messages when domain=Reals and initialize=2d array

### ISSUE THREAD

**Issue by joseortiz3** [Pyomo/pyomo#1126]
New users (like me) are unfamiliar with `pyomo`'s quirks and are extremely confused when they try to make a `Param` but end up with an unhelpful error message from six function calls deep.

```python
>>> import pyomo
>>> import pyomo.environ as pe

>>> a = [[1,1,1,1,1],[1,1,1,1,1]]
>>> model = pe.ConcreteModel()
>>> model.a = pe.Param(domain=pe.Reals, initialize=a)

ERROR: Constructing component 'a' from data=None failed: ValueError: Error
    retrieving immutable Param value (a):
    	The Param value is undefined and no default value is specified.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\block.py", line 568, in __setattr__
    self.add_component(name, val)
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\block.py", line 1008, in add_component
    val.construct(data)
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\param.py", line 869, in construct
    self._initialize_from(self._rule)
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\param.py", line 818, in _initialize_from
    _init = self[idx]
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\indexed_component.py", line 356, in __getitem__
    return self._getitem_when_not_present(index)
  File "C:\Users\Joey\Python37\lib\site-packages\pyomo\core\base\param.py", line 482, in _getitem_when_not_present
    % ( idx_str,) )
ValueError: Error retrieving immutable Param value (a):
	The Param value is undefined and no default value is specified.
```

The actual error, I believe, is that `Param` could be a two-element 1-D set (each element being a 1x5 matrix), or a 10-element 2-D set (each element being a single value), and `pyomo` needs the user to specify which it is because no default is assumed. Correct me if I'm wrong.

Whatever the actual explanation is, this error message deeply confuses new users.

One possible fix is to define a decorator which handles errors like this one, looks at the arguments, and sees if a known error condition applies for which there is a simple explanation, and provides the explanation, along with the original error message. This requires no modification of the existing code, only the addition of new code.

Another possible fix is simply handle two dimensional rectangular arrays by assuming what the user wants.

**Comment by blnicho** [comment]
This error message was updated at some point and this example now produces:
```
ValueError: Invalid parameter value: a[None] = '[[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]', value type=<class 'list'>.
	Value not in parameter domain Reals
```

I think this is much more clear than the originally reported error message so this can be closed.

**Comment by joseortiz3** [comment]
@blnicho I still don't know if this new error message is complaining that `a` is `<class 'list'>`, or the fact that the first element of `a` is `<class list>`.
