### ISSUE TITLE
Gurobi Python interface error

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#113]
Somewhere between 2c5e8d4220dc1681a5c80f9bb00366ddccd7a64a and 14dc91f875acc41b261db8f1c429f17f97ab08d8, a change was made that seems to affect the Gurobi python interface. Code that executes properly in the former commit raises the following error:
I should note that the module six is available in the venv used.

```
ERROR: "[base]/pyomo/pyomo/opt/base/solvers.py", 599, solve
        Solver (gurobi) returned non-zero return code (1)
ERROR: "[base]/pyomo/pyomo/opt/base/solvers.py", 604, solve
        Solver log:
        Traceback (most recent call last):
          File "<stdin>", line 4, in <module>
          File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/solvers/plugins/solvers/GUROBI_RUN.py", line 12, in <module>
            import six
        ImportError: No module named six
```
This issue also affects IDAES/models#190.

**Comment by ghackebeil** [comment]
This happened in https://github.com/Pyomo/pyomo/pull/102. The user's original fix was correct, and we directed them to do the wrong thing.
