### ISSUE TITLE
DeveloperError: 'Derived component SimpleSet failed to define set_value() for scalar instances.'

### ISSUE THREAD

**Issue by NicoLapas** [Pyomo/pyomo#1136]
An error occurs when setting the value

DeveloperError: Internal Pyomo implementation error:
	'Derived component SimpleSet failed to define set_value() for scalar instances.'

from pyomo.environ import *
model = ConcreteModel()

model.a = Set(initialize=[1,2,3])
model.b = Set(initialize=[1,2,3])
model.c = Set(initialize=[4,5,6], ordered=True)

model.c_diff =Set()
for i in model.a:
    for j in model.b:
        model.c_diff = model.c[i]-model.c[j]

![set_value error](https://user-images.githubusercontent.com/55826185/66895762-d324b380-eff3-11e9-9351-8dcca14d42cb.JPG)

**Comment by blnicho** [comment]
Could you give a little more context on what you're trying to do? It looks like you are trying to create a new Set containing the "distances" between any two members of set `model.c`. What do you expect the value of `model.c_diff` to be?

**Comment by NicoLapas** [comment]
I came across this error trying to find the fastest solution in finding the differences between phase angles and found it a curious one. Maybe I missunderstand the Set() definition function in this case.

Reformulating the problem into a Param() with a def calculation and a return solved the issue.
