### ISSUE TITLE
What is the difference between variable() and Var()

### ISSUE THREAD

**Issue by jacknightking** [Pyomo/pyomo#1142]
hi~
i want to understand What is the difference between variable() and Var(),when i try to define the decision variable ,i find two ways to do so,i  wanna to know whether is any difference between two method,thx

**Comment by jacknightking** [comment]
I notice there is two way to describe a pyomo model,pyomo.kernel vs pyomo.environ,could i mix use two way to define one model?

**Comment by michaelbynum** [comment]
The Pyomo components in `pyomo.environ` and `pyomo.kernel` are mostly independent. They currently should not be used together. There may be some slight performance differences between the two, but I cannot say anything with certainty. There are some stylistic and feature differences between the two. I suggest choosing the one you enjoy working with more. However, if you are building a package on top of Pyomo, then you also may want to consider compatibility with other packages/metasolvers/etc. based on Pyomo.
