### ISSUE TITLE
Work with SCIP concurrent solver

### ISSUE THREAD

**Issue by MisterVulcan** [Pyomo/pyomo#1144]
SCIP compiled with `TPI={tny, omp}` enables running SCIP in concurrent solving mode, which according to the [documentation](https://scip.zib.de/doc/html/CONCSCIP.php):

> ...a concurrent solve can be started by using the concurrentopt command instead of the optimize command in the SCIP shell, or by calling the interface function SCIPsolveParallel().

AFAIK there isn't a ready way to invoke this thru pyomo, although you _can_ pass related solver parameters (e.g. `parallel/maxnthreads`) to SCIP. [It appears that](https://github.com/SCIP-Interfaces/PySCIPOpt/issues/229) the SCIP devs have worked on this problem with the PySCIPOpt interface, at least, but I'd like to know if there's a way to get concurrent solving/parallel SCIP working thru Pyomo. If it's as simple as calling a different command, should be doable, right?

**Comment by blnicho** [comment]
@MisterVulcan I don't think anyone on the dev team works with SCIP regularly enough to answer this. Maybe try repeating this question on the Pyomo forum where a broader audience will see it. If you figure out a way to get it working please let us know and we can document it somewhere. In the meantime I'm going to close this.
