### ISSUE TITLE
Conflict between `is_fixed` and `value`

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1147]
When a `ProductExpression` has a child fixed to 0, then `is_fixed` returns `True`. This seems fine to me. The problem is that the expression cannot be evaluated if the other child does not have a value. I'm not sure what the behavior should be, but I think `is_fixed` and `value` should not conflict like this. What do others think? See the example below:

```
>>> import pyomo.environ as pe
>>> from pyomo.core.expr.numvalue import is_fixed
>>> m = pe.ConcreteModel()
>>> m.x = pe.Var()
>>> m.y = pe.Var()
>>> m.x.fix(0)
>>> e = m.x * m.y
>>> is_fixed(e)
True
>>> pe.value(e)
ERROR: evaluating object as numeric value: y
        (object: <class 'pyomo.core.base.var.SimpleVar'>)
    No value for uninitialized NumericValue object y
ERROR: evaluating object as numeric value: x*y
        (object: <class 'pyomo.core.expr.numeric_expr.ProductExpression'>)
    No value for uninitialized NumericValue object y
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pyomo/pyomo/core/expr/numvalue.py", line 226, in value
    tmp = obj(exception=True)
  File ".../pyomo/pyomo/core/expr/numeric_expr.py", line 223, in __call__
    return evaluate_expression(self, exception)
  File ".../pyomo/pyomo/core/expr/visitor.py", line 973, in evaluate_expression
    return visitor.dfs_postorder_stack(exp)
  File ".../pyomo/pyomo/core/expr/visitor.py", line 518, in dfs_postorder_stack
    flag, value = self.visiting_potential_leaf(_sub)
  File ".../pyomo/pyomo/core/expr/visitor.py", line 893, in visiting_potential_leaf
    return True, value(node)
  File ".../pyomo/pyomo/core/expr/numvalue.py", line 230, in value
    % (obj.name,))
ValueError: No value for uninitialized NumericValue object y
```

**Comment by michaelbynum** [comment]
I think I agree...

**Comment by qtothec** [comment]
I'm not sure that I agree that `is_fixed()` should resolve to True. What if you have `z = x` and the following:

```
>>> import pyomo.environ as pe
>>> from pyomo.core.expr.numvalue import is_fixed
>>> m = pe.ConcreteModel()
>>> m.x = pe.Var()
>>> m.y = pe.Var()
>>> m.x.fix(0)
>>> m.z = pe.Var()
>>> e = m.x * (m.y / m.z)
>>> is_fixed(e)
True
```

**Comment by michaelbynum** [comment]
@qtothec That is a good example... I am torn...

**Comment by qtothec** [comment]
To be fair, what I am suggesting is that `0 * y / 0` is not `fixed`, because the value is somewhat undefined. You could make the perfectly reasonable argument that this is a value `fixed` to `NaN`.

**Comment by blnicho** [comment]
I think I still agree with Carl even with Qi's example. I think that this special handling of 0 in product expressions saves us extra work in most cases so I would be reluctant to change this default behavior. I think reporting `0 * y / 0` as `fixed` seems self-consistent to me and if you really care if a fixed expression is "evaluatable" then you should call `value` on it.

**Comment by ghackebeil** [comment]
+1
