### ISSUE TITLE
Documentation unavailable

### ISSUE THREAD

**Issue by josiahjohnston** [Pyomo/pyomo#115]
The documentation for Pyomo 5.x is unavailable on the [Pyomo documentation website](http://www.pyomo.org/documentation) which only provides a link to v4.1. Also, the link to [PySP documentation](https://software.sandia.gov/trac/pyomo/export/HEAD/pyomo.doc/trunk/pysp/pyspdoc.pdf) is broken.

**Comment by jsiirola** [comment]
PySP paper link updated.  Automatic builds of the Pyomo Online Documentation have been fixed.  Version string updated to the current release (ec74f52)
