### ISSUE TITLE
Improve the NL writer

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#1151]
Improve the performance of the NL writer - several suggestions have been proposed:

1. profile and see if there is low hanging fruit
2. look at implementing a binary NL format
3. look at implementing a C-based writer

Still need to gather data on these options to see which has the most promise.

**Comment by whart222** [comment]
I think we should call these out as separate activities.

**Comment by whart222** [comment]
Should we close this?

Option (2) is redundant with #177 .
Option (3) is redundant with #1158

**Comment by jsiirola** [comment]
Archived on the master Performance Proposals Issue (#1430).  Closing this performance proposal until active development has begun.
