### ISSUE TITLE
Performance suggestion: Pyomo import performance

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1152]
Importing pyomo can take a long time depending on what packages are installed.

**Comment by whart222** [comment]
I would like to see specific use cases articulated.  I appreciate the general concern that @jsiirola mentioned recently:  parts of PyUtilib and Pyomo do checks at import time that we can/should defer.

But what are examples where the import time of Pyomo is problematic?  I've tried to work on this issue before, but I couldn't replicate the slow import times that others have verbally quoted.
