### ISSUE TITLE
Performance Suggestion: "automatic" persistent solvers

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1154]
When re-solving the same model with minor changes, we may be able to "automatically" detect what changed and only update what needs updated.

**Comment by whart222** [comment]
I've implemented ideas like these in COEK, so we have evidence that this is feasible.  A key question is whether the time needed to do these checks in Pyomo will be fast enough to call this an optimization.  We can check this with the use cases I've used with POEK and COEK.

**Comment by jsiirola** [comment]
Archived on the master Performance Proposals Issue (#1430).  Closing this performance proposal until active development has begun.
