### ISSUE TITLE
Testing Performance

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#1156]
This issue isn't really about performance that end users will see but about improving our unit and integration tests to enable developer productivity/performance. During periods of active development our CI and testing infrastructure quickly becomes backlogged and it can take **hours** to know if your recent commit breaks anything. I think it would be worthwhile to take a closer look at the test suite being run on every PR/commit and try to reduce the run time to just a few minutes. 

A couple ideas for tackling this:

- Look for repeat/redundant tests
- Increase use of testing categories
- Implementation efficiency and consistency across similar tests in different parts of the code base, updating old tests

**Comment by qtothec** [comment]
Has anyone looked into using Github Actions for de-bottlenecking some of the testing? Looks like it's free for public repos?

**Comment by qtothec** [comment]
It looks like we can have some automated testing built in to Github. See #1194

**Comment by jsiirola** [comment]
Archived on the master Performance Proposals Issue (#1430).  Closing this performance proposal until active development has begun.
