### ISSUE TITLE
Matrix/Vector Representations

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#1159]
The key idea is to extend Pyomo's representation system to enable the expression of matrix/vector representations.  While this does not improve the efficiency of Pyomo's core expression system, it would offer users an alternative that is likely more performant.  Generally, Matrix/Vector expressions would be smaller, and hence the operations needed to canonicalize them would be a smaller burden when interfacing with solvers.

Note that this we have a preliminary Matrix representation in Pyomo kernel.  However, a key element of this approach would be to define a Vector representation for parameters and variables.  Or to define a convention for using Pyomo's existing Variable/Parameter objects in that manner. But for the hackathon our goal should be to demonstrate the potential performance win.

NOTE:  I think it would make sense to include the use of numpy matrix/vector data and scipy.sparse matrix/vector data in our performance hacking.  Many users will naturally gravitate to the use of these data formats, and thus I think it would be a mistake to limit the scope of this activity to custom matrix/vector objects.

Related Issues: #685 #468 #31 #87

**Comment by jsiirola** [comment]
Archived on the master Performance Proposals Issue (#1430).  Closing this performance proposal until active development has begun.
