### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by burkovae** [Pyomo/pyomo#1167]
Just out of curiousity, is there a reason for this dead code?

https://github.com/Pyomo/pyomo/blob/4f882680ed15de09dbbf4e25deeeadd56eb54263/pyomo/core/base/PyomoModel.py#L741

**Comment by jsiirola** [comment]
It is legacy code from the old Coopr days.  I am pretty sure it was left in as a "reminder" of how we used to do certain things -- but at this point, it should be safe (and a good idea) to remove it.

The "pyomo solution process" used to proceed through the following process:
  1. create the abstract model
  2. create a concrete instance by applying data
  3. "preprocess" the instance to gather various statistics and clean up some data structures
  4. write the instance to some output format (LP or NL)
  5. invoke the solver
  6. process the solver output

A number of years ago, as transformations became more prevalent and users began to write more complex scripts, we realized that the "preprocess" step was very specific to the "old" workflow and didn't map well onto the current "concept of operations" so it was removed.
