### ISSUE TITLE
with cplex, solver_io='python' is much slower than executable=(solver_path) 

### ISSUE THREAD

**Issue by songbotao** [Pyomo/pyomo#1169]
With cplex, when the model is large, the method of solver_io='python' is much slower than executable=(solver_path) . When the model is small, the method of solver_io='python' is the same as  than executable=(solver_path) . 
I would know how about this problem, and why the difference happen

**Comment by songbotao** [comment]
The version of my pyomo is 5.6.6, the version of my pyomo is 12.9

**Comment by jsiirola** [comment]
Archived on the master Performance Proposals Issue (#1430).  Closing this performance proposal until active development has begun.

**Comment by mrmundt** [comment]
This is a duplicate to #51 ; we are working on refactoring the solver interfaces and will aim to address this as part of that effort.
