### ISSUE TITLE
Long timeout checking NEOS availability

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#117]
Following from #109: running

`pyomo help --solvers`

results in a long (2 minute) timeout if the computer is connected to a network but cannot  access the NEOS servers (e.g., is behind a firewall).  Note, if the computer is not connected to a network, the command completes in less than 2 seconds.

**Comment by whart222** [comment]
This is caused when Pyomo tries to list the kestrel solvers on NEOS.  The "solution" is to set a smaller timeout value.

**Comment by jsiirola** [comment]
This appears to be fixed by 2babf45.  Correctly getting/setting the proxy for systems behind a proxy that does not forward port 3333/3332 will result in an immediate connection failure (thereby avoiding the long timeout)
