### ISSUE TITLE
 Unallowed character (/) found in CPLEX, ValueError in windows 10

### ISSUE THREAD

**Issue by Arbustofly** [Pyomo/pyomo#1176]
Hello, (this is related with: Pyomo#809 and #923 ) 

I am using snakemake to manage my worflow, and when calling cplex solver, I am getting the following error:

ValueError: Unallowed character (/) found in CPLEX log file path/name.
        For portability reasons, only [a-zA-Z0-9 ~:.-_] are allowed.

As spoted on the previous fixed reported issues, it is related to the path/name:
...pyomo\solvers\plugins\solvers\CPLEX.py
 
I am using Windows10 pro, and anaconda3.

Can you have a look on that, please?

Thanks a lot,
David

**Comment by blnicho** [comment]
What version of Pyomo are you using and what environment are you using? (are you using something like cygwin on Windows?)

**Comment by Arbustofly** [comment]
Hello, thank you,
I am using Pyomo 5.6.7, no I am not using cygwin, I am using Pyomo in an Anaconda Environment, the environment is created solely for running PyPSA-Eur, here is the link:

https://pypsa-eur.readthedocs.io/en/latest/installation.html 

The process works like this:
I configured a yaml file,then I run snakemake, which will then manage the process workflow, executing different scripts from a snakefile.

**Comment by Arbustofly** [comment]
According to the PyPSA development team:
It seems it is a problem between linking snakemake and pyomo, logs files are not found by Pyomo, and therefore generates the error:

A quick solution is:
In the `Snakefile` use "\\" in the solver log filename.
in..
solver="logs\\{network}..."

Below is the link for the google group of PyPSA.

https://groups.google.com/forum/#!topic/pypsa/3_uB7DmQKzY
