### ISSUE TITLE
Running network_flow.py example generates error

### ISSUE THREAD

**Issue by Togogermini** [Pyomo/pyomo#1177]
I tried to run the example file "examples/pyomo/connectors/network_flow.py" from the command line using the following command: _pyomo solve network_flow.py network_flow.dat --solver='glpk'_ but got the error below:

WARNING: DEPRECATED: The Connector component is deprecated. It has been
    replaced by Port in the pyomo.network package.
...

WARNING: DEPRECATED: The Connector component is deprecated. It has been
    replaced by Port in the pyomo.network package.

ERROR: Unexpected exception while running model:
        Unexpected expression (type SimpleConnector)
errorcode: 1
retval: None

I followed the recommended way to install pyomo and all its dependencies and solvers using conda. From the warning message it looks as if the file has not been updated to use ports instead of connectors. I converted all the connectors to ports but got a different error.

**Comment by blnicho** [comment]
This is a very old example that is not tested and uses deprecated syntax. If you want more information on how to use `pyomo.network` please take a look at the documentation: https://pyomo.readthedocs.io/en/stable/modeling_extensions/network.html

I'm going to close this issue as it's part of a much broader issue with the examples directory #101
