### ISSUE TITLE
Pyomo installation with Cython

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#1178]
Although there are hooks in Pyomo to cythonize parts of the expression system, I don't think that these are used by default during installation.  We should consider doing this as part of our assessment of performance enhancements for Pyomo.

This may require revising the Conda build to pre-compile with Cython.

**Comment by jsiirola** [comment]
Archived on the master Performance Proposals Issue (#1430).  Closing this performance proposal until active development has begun.

**Comment by blnicho** [comment]
Now that we're distributing Cythonized wheels with our releases can this be closed?
