### ISSUE TITLE
Upgrading NEOS Dependencies

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#1179]
It's clear from user feedback that the use of NEOS with Pyomo has become commonplace.  Consequently, I recommend that we review the dependencies needed to support NEOS and make them required dependencies for installation of Pyomo.

Currently, after a user installs Pyomo they cannot run *any* solvers unless they do additional installations.  This would fix that by making NEOS always available for use.  Per installation instructions on pyomo.org, the user needs to install pyomo.extras to get the packages used for NEOS solvers.

**Comment by jsiirola** [comment]
What packages are needed for NEOS support?

**Comment by jsiirola** [comment]
@whart222: I just looked through the NEOS interface and could not find any imports from anything other than standard libraries.  Further, the SLIM Travis build (Pyomo with ONLY its required dependencies) still executes a NEOS test (and despite the test name, this does involve solving a simple problem with CBC on NEOS):
```
test_kestrel_plugin (pyomo.neos.tests.test_neos.TestKestrel) ... ok
```

I believe that there is nothing to do and that this issue can be closed.

**Comment by whart222** [comment]
I agree.  We *used* to have a dependency on suds.  I'm not sure when that was changed, but the installation documentation needs to be updated on pyomo.org.
