### ISSUE TITLE
Update pyomo.org documentation

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#1183]
The installation instructions on pyomo.org differ in several respects from our tutorial documentation:

- Pyomo does not need pyomo.extras to use NEOS, but pyomo.org says it does.
- The pyomo.org documentation doesn't reference pyomo.solvers

There are probably more differences, but these two came up recently.

**Comment by blnicho** [comment]
Does it make sense to make the link to "installation instructions" on pyomo.org point to the installation page on readthedocs? That way we wouldn't have to worry about updating instructions in two places and our installation instructions would never be contradictory.

**Comment by carldlaird** [comment]
This sounds reasonable to me.

**Comment by blnicho** [comment]
The installation instructions on pyomo.org have been updated, I think this can be closed.
