### ISSUE TITLE
Define custom expression objects to short-circuit common checks

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#1184]
For example, checkout the perf_explicit_canonical branch, which defines the X_LinearExpression class.  In the pmedian1a.py example, these expressions are used to declare linear expressions with constant coefficients and non-fixed variables.

In a comparison with pmedian8, pmedian1a.py is about 25% than pmedian1.py when creating an LP file.

**Comment by jsiirola** [comment]
Archived on the master Performance Proposals Issue (#1430).  Closing this performance proposal until active development has begun.
