### ISSUE TITLE
Default domain for mutable Params

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#1185]
Suppose I have:
```
from pyomo.environ import *

m = ConcreteModel()

m.x = Var(bounds=(0, 10))
m.param = Param(initialize=5, mutable=True)
m.cons = Constraint(expr=m.x >= m.param)
m.obj = Objective(expr=m.x)

m.param = '10' #oops

# Now the error we get doesn't tell us where or what the problem is.
SolverFactory('cplex').solve(m)
# TypeError: unsupported operand type(s) for -: 'str' and 'int'
```
This is dumb on my part, but I doubt I'll be the last. I think the question is what the default domain for Params should be. Right now it looks like it is Any. So I could have saved myself by doing:
```
m.param = Param(initialize=5, mutable=True, within=Reals)
```
and I would get a good error message when I tried to set `m.param` to a string. But my concern is that the `TypeError` certainly isn't what led me to that answer. And in addition, this seems inconsistent because the writer is clearly expecting a number, but, by default, Param doesn't validate that its value is a number.

**Comment by blnicho** [comment]
I just ran into this for a case where a Param was being set to a Pyomo expression (instead of the value of that expression) and the error thrown when calling Ipopt was completely unhelpful. I agree with @emma58 that Reals might be a better default domain for Params since that is the implicit expectation in the writers.

**Comment by qtothec** [comment]
I agree. Easy for users to burn themselves by loading in data to a Param assuming that it's going to be interpreted as a numeric value, but their data source encoded things as strings.

Do we have anyone using Params with non-numerics? I think most people would just go with `dict` for that case.

**Comment by jsiirola** [comment]
Note that the Book documents this "feature":
> A Param object can contain any value: string, floating point, etc. The default domain for parameters is `Any`, so by default no domain validation is performed. However, it is often valuable to specify the space of valid parameter values to provide checking of the input data. Similar to the `Set` component, there are two ways to validate parameter values. First, the domain of feasible parameter values can be specified using the within option:
> `model.Z = Param(within=Reals)`
