### ISSUE TITLE
Mindtpy error with stale variables when no linear constraints exist

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#1187]
This issue is being opened based on a post by @julian-belina: https://github.com/Pyomo/pyomo/issues/1139#issuecomment-555036213

The example file is:
```
from pyomo.environ import *

#Create a simple model
model = ConcreteModel()

model.x = Var(bounds=(1.0,10.0),initialize=5.0)
model.y = Var(within=Binary)

model.c1 = Constraint(expr=(model.x-3.0)**2 <= 50.0*(1-model.y))
model.c2 = Constraint(expr=model.x*log(model.x)+5.0 <= 50.0*(model.y))

model.objective = Objective(expr=model.x, sense=minimize)

#Solve the model using MindtPy
SolverFactory('mindtpy').solve(model, mip_solver='glpk', nlp_solver='ipopt',tee=True) 

model.objective.display()
model.display()
model.pprint()
```

The issue lies in that the first master problem does not involve the variable `y` at all, so its value is not updated by the optimizer. Note that both constraints are nonlinear, and OA cuts appear not to have been added for some reason.

**Comment by julian-belina** [comment]
I am using Pyomo 5.67 and receive the following error when running the Code

> ValueError: Numeric value 0.22709088990648157 (<class 'float'>) is not in domain Binary

Furthermore i get the following warning:

> WARNING: DEPRECATED: The differentiate function in pyomo.core.base.symbolic
> has been deprecated. Please use the differentiate function in
> pyomo.core.expr. (deprecated in TBD,will be removed in 5.7)
> WARNING: DEPRECATED: The differentiate function in pyomo.core.base.symbolic
> has been deprecated. Please use the differentiate function in
> pyomo.core.expr. (deprecated in TBD,will be removed in 5.7)

**Comment by qtothec** [comment]
@julian-belina The deprecation warning was fixed in #1188, which should make its way into the next release. @bernalde is aware of the former issue.

**Comment by jwlevis** [comment]
The issue for this specific problem can be addressed by adding the constraint y <=1, since it is linear and involves y.

**Comment by julian-belina** [comment]
@jwlevis adding the constraint yields the new following error:

> ERROR: evaluating object as numeric value: y
>         (object: <class 'pyomo.core.base.var.SimpleVar'>)
>     No value for uninitialized NumericValue object y
>         Key : Lower : Body : Upper
>         None :  None : None :  None
>     c2 : Size=1

Initializing y removes the error but the solver dosent seem to change the starting values. I tried different initilization variants for x and y and the solver stops at the initialization values.


One Example:

```
from pyomo.environ import *

#Create a simple model
model = ConcreteModel()

model.x = Var(bounds=(1.0,10.0),initialize=7.0)
model.y = Var(within=Binary,initialize=0)

model.c1 = Constraint(expr=(model.x-3.0)**2 <= 50.0*(1-model.y))
model.c2 = Constraint(expr=model.x*log(model.x)+5.0 <= 50.0*(model.y))
model.c3 = Constraint(expr= model.y<=1)

model.objective = Objective(expr=model.x, sense=minimize)

#Solve the model using MindtPy
solver=SolverFactory('mindtpy')
solver.CONFIG._data['iteration_limit']._data=100
solver.solve(model, mip_solver='glpk', nlp_solver='ipopt',tee=True)

model.objective.display()
model.display()
model.pprint()
```

>  ...
>  INFO: ---MindtPy Master Iteration 99---
>  INFO: MIP 100: Solve master problem.
>  INFO: MIP 100: OBJ: 1.0  LB: 1.0  UB: inf
>  INFO: MindtPy unable to converge bounds after 100 master iterations.
>  INFO: Final bound values: LB: 1.0  UB: inf
> 
> 
>   Variables:
>     x : Size=1, Index=None
>         Key  : Lower : Value : Upper : Fixed : Stale : Domain
>         None :   1.0 :   7.0 :  10.0 : False : False :  Reals
>     y : Size=1, Index=None
>         Key  : Lower : Value : Upper : Fixed : Stale : Domain
>         None :     0 :     0 :     1 : False : False : Binary
> 
>   Objectives:
>     objective : Size=1, Index=None, Active=True
>         Key  : Active : Value
>         None :   True :   7.0
