### ISSUE TITLE
Scenario Tree model consructed using networkx has set assign error

### ISSUE THREAD

**Issue by DLWoodruff** [Pyomo/pyomo#119]
What I tried to do is not reasonable and makes no sense, really; however,
it says "contact developers" so I am doing that.

# setassign.py "bug" report DLW Feb 2016
from pyomo.environ import *
import networkx
import pyomo.pysp.scenariotree.tree_structure_model as ptm

G = networkx.DiGraph()
G.add_node("Foo")
G.add_node("Bar")
G.add_edge("Foo", "Bar", probability = 1.0)

tree_model = ptm.ScenarioTreeModelFromNetworkX(G)
# The stage names should have been passed in above, but if you do this assignment
# you get told to contact the developers (maybe so that they can say "don't do that")
tree_model.Stages = ["FirstStage", "SecondStage"]

$ python setassign.py 
Traceback (most recent call last):
  File "setassign.py", line 12, in <module>
    tree_model.Stages = ["FirstStage", "SecondStage"]
  File "/home/david/software/pyomo/pyomo/pyomo/core/base/block.py", line 535, in __setattr__
    _set_value(val)
  File "/home/david/software/pyomo/pyomo/pyomo/core/base/indexed_component.py", line 654, in set_value
    % (self.__class__.__name__,))
pyomo.util._config.DeveloperError: Internal Pyomo implementation error:
	'Derived component OrderedSimpleSet failed to define set_value() for scalar instances.'
	Please report this to the Pyomo Developers.

**Comment by ghackebeil** [comment]
Closing this ticket and starting a new one to discuss the more basic question: Should Set support `set_value`? (#121)
