### ISSUE TITLE
DAE with flexible end points

### ISSUE THREAD

**Issue by DingXiangYuanZhiXing** [Pyomo/pyomo#1199]
My problem has flexible endpoint within a bound, so is there anyway to accomplish it?
`m.e = ContinuousSet(bounds=(e_0, e_f))`
`e_f` is flexible.

**Comment by qtothec** [comment]
This is better as a [StackOverflow question](https://stackoverflow.com/questions/ask?tags=pyomo), but short answer is yes. You will need to do a change of variables reformulation.
