### ISSUE TITLE
glpk: invalid literal for int() with base 10: 'c'

### ISSUE THREAD

**Issue by danstender** [Pyomo/pyomo#12]
Hi,
we have a problem with the glpk solver:
```
 pyomo solve --solver=glpk diet1.py diet.dat
[    0.00] Setting up Pyomo environment
[    0.00] Applying Pyomo preprocessing actions
[    0.00] Creating model
[    0.07] Applying solver
invalid literal for int() with base 10: 'c'
[    0.08] Pyomo Finished
ERROR: Unexpected exception while running model:
	Error parsing solution data file, line 1
$ exit
```
Pyomo is 4.3.11388, glpksol is 4.60.

**Comment by jsiirola** [comment]
Thanks for the report.

This is a known problem with glpk 4.60 that has been fixed on trunk. You can either downgrade glpk or switch to Pyomo trunk (a new release is planned, but may not be out for another couple weeks).

John

On Jun 26, 2016, at 2:33 PM, Daniel Stender <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
we have a problem with the glpk solver:

pyomo solve --solver=glpk diet1.py diet.dat
[ 0.00] Setting up Pyomo environment
[ 0.00] Applying Pyomo preprocessing actions
[ 0.00] Creating model
[ 0.07] Applying solver
invalid literal for int() with base 10: 'c'
[ 0.08] Pyomo Finished
ERROR: Unexpected exception while running model:
Error parsing solution data file, line 1
$ exit

Pyomo is 4.3.11388, glpksol is 4.60.

-

**Comment by danstender** [comment]
Great! Thx for info and quick reply.

We're going to package the latest snapshot then, that could be done easily.

Best,
DS
