### ISSUE TITLE
Issues with NEOS solvers and solution output

### ISSUE THREAD

**Issue by gnowzil** [Pyomo/pyomo#1201]
I'm with the NEOS team and I'm trying to figure out some issues with Pyomo+NEOS.

It seems that 
`pyomo solve --solver=<solver> --solver-manager=neos model.py`
works only if `<solver>` has an explicit plugin (e.g., any of the solvers in pyomo/solvers/plugins/solvers).  This is mentioned in #910.  

The following seems to work for any NEOS-valid solver:
```
manager = SolverManagerFactory('neos')
results = manager.solve(model,opt='<solver>')
```

Is there a bug with the first method?  And if not, I assume that the second method is the way to go?  I dug around a little bit and it looks like the first method tries to create `SolverFactory(<solver>)` but this results in an unknown solver for some of the NEOS solvers.

Furthermore, in either case, no solution seems to be returned.  I don't see any error messages, but printing the results always shows 
```
Solution: 
- number of solutions: 0
  number of solutions displayed: 0
```
I'm not sure what Pyomo is expecting from NEOS, but if there's anything we can do on our end to fix this, let me know.

**Comment by blnicho** [comment]
@gnowzil thanks for the note, it is certainly possible that this is a bug. We're hoping to rework Pyomo's solver interfaces this December which might fix this and leave us with a more robust interface to NEOS.

**Comment by gnowzil** [comment]
Hi,  I just wanted to follow up on this.  We've been getting some queries about pyomo on NEOS.  I ran small examples through all of the solvers available and was met with varying degrees of success.  I'm not an expert in using Pyomo so I may be doing this incorrectly, but I've summarized what I have seen below.

- cbc, conopt, cplex, mosek, and snopt appeared to work and returned a solution.
- filter sqp, knitro, l-bfgs-b, lancelot, lgo, loqo, minlp, minos, minto, ooqp appeared to work if I use the command `python myexample.py`, with `SolverManagerFactory('neos')` and the `solve` call in the script, but failed if I used `pyomo solve --solver-manager=neos --solver=<solver> mymodel.py`, where `mymodel.py` only has the model.  
- bonmin, couenne, and filmint didn't work at all.
- raposa is listed as a solver, but not recognized when solving with a `pyomo solve` call.  

Let me know if there's anything we can do to help.  One thing that could be causing problems is the return of solutions from NEOS -- we made some minor changes here and we may not be returning something that Pyomo expects.

**Comment by carldlaird** [comment]
Thanks for the information. We will discuss this at our next meeting...

**Comment by whart222** [comment]
Some further feedback on the issues that are noted above:

* I'm seeing NEOS queue failures for minto and raposa.  I'm not sure what is going on.  Perhaps NEOS is returning a *.ZIP file that we need to open up to get the *.sol file

* I added raposa to the documentation in Pyomo, so it's listed as a solver in my fork.  It seems to be launched.

* On a simple problem, the following solver generate the correct solution (using a script interface):
  * snopt, bonmin, cbc, conopt, couenne, cplex, filmint, filter, ipopt, knitro, lancelot, lgo, loqo, minlp, minos, mosek, snopt

* ooqp fails when I hand it a maximization problem, and solves the same problem when minimizing

* l-bfgs-b fails even on trivial problems (!)
