### ISSUE TITLE
Performance Suggestion: Add "compiled" model support

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#1203]
This issue considers the addition of "compiled" models. That is, if we have a model that we know we want to re-solve repeatedly with small changes, can we generate a "compiled" version of some sort that allows us to do this much more rapidly.

I (@carldlaird) have prototyped a version for linear models that allows some changes.

**Comment by qtothec** [comment]
How do we want to define "small" changes? RHS updates? Activation/deactivation of constraints?

**Comment by jsiirola** [comment]
Archived on the master Performance Proposals Issue (#1430).  Closing this performance proposal until active development has begun.
