### ISSUE TITLE
Assignment to a set

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#121]
Consider the following simple model:

```
model = ConcreteModel()
model.s = Set(initialize=[1,2,3])
...
```

The set `model.s` may or may not be used as an index for other components (it's an orthogonal issue). Should we support the following syntax?

```
model.s = [3,9]
```

That is, should `set_value` in simple set objects be defined to accept some iterable object and redefine the set to include the members of the iterable? This seems like a natural generalization of the same functionality defined for `set_value` on `Var` and `Param`.

Note that right now the line in question produces a very confusing error:
```
pyomo.util._config.DeveloperError: Internal Pyomo implementation error:
'Derived component OrderedSimpleSet failed to define set_value() for scalar instances.'
Please report this to the Pyomo Developers. 
```

**Comment by joseortiz3** [comment]
Hi there. Completely new user here, ran into this extremely confusing error message. So your saying that sets are, for now, completely immutable? I was expecting that sets are essentially indices, and as such could be reindexed (with a behavior identical to `pandas`, hope you are familiar). I was trying to start with an `AbstractModel` with a couple non-specified `Set`s and several multi-dimensional `Param`eters indexed by one or more of the sets, such that I could later specify all the indices and data. But it looks like for now users must start with a `ConcreteModel` specifying all the indices and data to begin with?

**Comment by qtothec** [comment]
No need for the newbie disclaimer. What Gabe is describing doesn't seem to be the same issue that you have. The behavior that you are going for with `AbstractModel` ought to be currently supported, so I suspect that you are seeing something related, but different.

**Comment by joseortiz3** [comment]
@qtothec Thanks for this. I will undoubtedly learn more about pyomo in the upcoming months and will better understand what is going and report back. Thanks again.
