### ISSUE TITLE
Updating PySP to be compatible with NetworkX 2.4

### ISSUE THREAD

**Issue by jonmather** [Pyomo/pyomo#1212]
I'm a new user of PySP, and see that it's currently incompatible with the latest version of NetworkX. The main objection seems to be the G.node vs. G.nodes syntax which was changed when moving from version 1.11 to 2 of NetworkX. 

Would a pull request fixing this be something of interest to the community or is it likely to break everyone's code?

**Comment by blnicho** [comment]
I believe this was already fixed in #1141. This fix is included in the most recent Pyomo release 5.6.7

**Comment by jonmather** [comment]
Yep, it seems I was on 5.6.6. Thanks.

**Comment by DLWoodruff** [comment]
A pull request fixing this that does not break everyone's code would
definitely be of interest!

A pull request that fixes this, but breaks everyone's code with a clear
message plus documentation would also be of interest, but note that many
tests would also have to be changed and and least one new test would have
to be added.
   Dave
