### ISSUE TITLE
Var fix implementation

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#1219]
We have an interesting implementation of variable fixing to support both `var.fix()` and `var.fix(value)`:
https://github.com/Pyomo/pyomo/blob/ccde78cab8cabaf8822b66f741b63bd2797777d0/pyomo/core/base/var.py#L894

However, does it ever make sense to `var.fix(None)`? If not, it would be far more clear to implement as an optional argument.

**Comment by ghackebeil** [comment]
My opinion is that it may or may not makes sense for a user to do this. However, it is very easy for a variable to be put into this state (fixed=True, value=None) by setting those attributes.

If you wanted to put together a pull request that preserves the current behavior, but replaces the *args syntax with an optional keyword argument, you could just as easily use a class as the default value and to:
```python
class _noarg(object):
    pass

def fix(self, val=_noarg):
    if val is not _noarg:
        self.value = val
    self.fixed = True
```
This will still support the `fix(None)` case, in case anyone is using it.

**Comment by ghackebeil** [comment]
I guess the question is: Would this PR be worth your time?

**Comment by jsiirola** [comment]
I certainly like the idea of moving away from `fix(self, *arg)` - I guarantee that we are not checking for nearly enough edge cases (like `m.x.fix(5, 2)`?).

@ghackebeil's proposal is the right way to go (and we have flavors of the `_noarg` or `NotSpecified` class littered all over the codebase).

**Comment by ghackebeil** [comment]
I believe all implementations are correctly checking that at most one arg is provided, so this change would really be just about stylistic preference.

**Comment by qtothec** [comment]
@ghackebeil is correct that the current implementation correctly checks for the multi-argument case, but there was non-zero confusion when I skimmed over the code (trying to implement something else). It's a mostly-invisible change, so I think I'll put together a small PR to adjust it.

**Comment by ghackebeil** [comment]
In that case I would recommend making the keyword name “value” instead of “val”.

Would you mind make this change the the variable in kernel as well?
