### ISSUE TITLE
Error getting NEOS results

### ISSUE THREAD

**Issue by bpierpont** [Pyomo/pyomo#122]
New to Pyomo, but in 5.1.1 on both Mac and Windows, I am unable to get a NEOS job to return results. I've tested with several examples and with SolverStudio models (which solve successfully with local CBC solver).

Using CBC on NEOS, I get the following error:

> ---------- Begin Solver Output -----------
> Condor submit: 'neos.submit'
> Condor submit: 'watchdog.submit'
> Job submitted to NEOS HTCondor pool.
> [    8.99] Pyomo Finished
> ERROR: Unexpected exception while running model:
> 	local variable 'opt' referenced before assignment

Using CPLEX on NEOS, I get the following error:

> ---------- Begin Solver Output -----------
> Condor submit: 'neos.submit'
> Condor submit: 'watchdog.submit'
> Job submitted to NEOS HTCondor pool.
> [   17.02] Pyomo Finished
> ERROR: Unexpected exception while running model:
> 	Cannot load a SolverResults object with bad status: error

I've seen others reference this bug as well (https://groups.google.com/forum/#!topic/pyomo-forum/CRzG4l-3E2A).

**Comment by bpierpont** [comment]
Confirmed that uninstalling Pyomo 5.1.1 and installing 4.4.1 fixes this issue.

**Comment by jsiirola** [comment]
The problematic commit was reverted in c667585 (on 22 Jan 17).  It will be available in the 5.2 release.
