### ISSUE TITLE
SOL File Output Error with ipopt.3.13.0

### ISSUE THREAD

**Issue by GYskyfall** [Pyomo/pyomo#1239]
When I use the latest ipopt3.13.0, I get the following error

`ValueError: Error reading '/tmp/tmpr26w60q7.pyomo.sol': could not convert string to float: 'p\n'.`

for example:
when I run Ampl Car Example, the ipopt amplinterface output seems right

```
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.0000000e+01 9.90e+01 9.01e-02  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.8797756e+01 9.31e+01 9.33e+00  -1.0 3.02e+02  -2.0 9.91e-03 6.00e-02h  1
   2  2.4816447e+01 9.17e+01 8.39e+00  -1.0 2.42e+03    -  2.08e-02 1.47e-02h  1
   3  2.9435505e+01 8.84e+01 7.76e+00  -1.0 8.58e+02    -  8.03e-02 3.54e-02h  1
   4  4.3462514e+01 7.77e+01 4.23e+00  -1.0 8.35e+02    -  1.36e-01 1.22e-01h  1
   5  6.0314813e+01 6.72e+01 3.27e+00  -1.0 7.87e+02    -  3.23e-01 2.34e-01h  1
   6  8.5775737e+01 7.09e+01 1.11e+01  -1.0 5.93e+02    -  5.97e-01 9.90e-01H  1
   7  8.6909683e+01 2.12e-01 1.46e+01  -1.0 2.08e+01    -  1.66e-01 9.90e-01h  1
   8  5.5706769e+01 1.27e+02 1.43e+03  -1.0 3.50e+02    -  1.29e-01 9.90e-01f  1
   9  5.2376868e+01 1.26e+02 4.44e+03  -1.0 9.97e+02    -  1.28e-01 2.27e-02f  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10  6.2640446e+01 1.33e+01 6.43e+03  -1.0 1.37e+02    -  5.06e-01 9.91e-01h  1
  11  5.5306976e+01 1.62e+01 3.28e+05  -1.0 3.14e+02    -  2.68e-02 2.70e-01f  1
  12  5.6575999e+01 4.13e-01 8.90e+05  -1.0 2.83e+01    -  4.86e-01 1.00e+00h  1
  13  4.5625447e+01 2.64e+01 1.55e+06  -1.0 2.45e+02    -  6.10e-01 9.66e-01f  1
  14  3.4917694e+01 1.09e+01 1.33e+06  -1.0 3.62e+02    -  8.24e-02 5.70e-01F  1
  15  2.4767429e+01 2.77e+01 1.11e+06  -1.0 2.62e+02    -  2.10e-01 5.41e-01f  1
  16  1.9851326e+01 2.46e+01 7.13e+05  -1.0 1.18e+02    -  3.66e-01 4.33e-01h  1
  17  1.7774888e+01 2.14e+01 5.74e+05  -1.0 1.28e+02    -  2.13e-01 2.93e-01h  1
  18  1.7472950e+01 1.25e+01 2.90e+05  -1.0 3.53e+01    -  4.82e-01 4.35e-01h  1
  19  1.7117294e+01 6.18e+00 2.00e+05  -1.0 1.03e+02    -  3.76e-01 5.01e-01h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  20  1.7752639e+01 8.45e-01 1.15e-02  -1.0 2.20e+01    -  1.00e+00 1.00e+00h  1
  21  1.6936754e+01 8.99e-01 4.85e+03  -1.7 1.16e+01    -  9.53e-01 1.00e+00h  1
  22  1.6825590e+01 4.49e-02 1.49e-04  -1.7 5.74e+00    -  1.00e+00 1.00e+00h  1
  23  1.6604662e+01 7.50e-02 1.44e-03  -2.5 3.26e+00    -  1.00e+00 1.00e+00h  1
  24  1.6595564e+01 1.88e-04 1.05e-06  -2.5 1.83e-01    -  1.00e+00 1.00e+00h  1
  25  1.6556525e+01 2.47e-03 2.18e+03  -5.7 6.01e-01    -  9.87e-01 1.00e+00h  1
  26  1.6556268e+01 1.12e-07 9.31e-10  -5.7 4.89e-03    -  1.00e+00 1.00e+00h  1
  27  1.6556242e+01 1.00e-08 9.31e-10  -8.6 3.92e-04    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 27

                                   (scaled)                 (unscaled)
Objective...............:   1.6556242099452163e+01    1.6556242099452163e+01
Dual infeasibility......:   9.3132257461547852e-10    9.3132257461547852e-10
Constraint violation....:   9.9997737933896879e-09    9.9997737933896879e-09
Complementarity.........:   8.1870528530484747e-07    8.1870528530484747e-07
Overall NLP error.......:   9.9997737933896879e-09    8.1870528530484747e-07


Number of objective function evaluations             = 30
Number of objective gradient evaluations             = 28
Number of equality constraint evaluations            = 30
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 28
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 27
Total CPU secs in IPOPT (w/o function evaluations)   =      0.016
Total CPU secs in NLP function evaluations           =      0.000
EXIT: Optimal Solution Found.

```
but pyomo can't get the result from the ipopt

**Comment by ghackebeil** [comment]
Can you attach the sol file to this ticket? That will allow us to update our sol file parser to handle some potentially new case. It would also be helpful to attach the ipopt log file and nl file. They should all be in the same location with different file extensions.

You may need to add keepfiles=True to the solve call to prevent those temporary files from being deleted.

**Comment by GYskyfall** [comment]
here are the files
[files.zip](https://github.com/Pyomo/pyomo/files/3986472/files.zip)

**Comment by GYskyfall** [comment]
> Can you attach the sol file to this ticket? That will allow us to update our sol file parser to handle some potentially new case. It would also be helpful to attach the ipopt log file and nl file. They should all be in the same location with different file extensions. You may need to add keepfiles=True to the solve call to prevent those temporary files from being deleted.
> […](#)
> On Dec 19, 2019, at 7:05 PM, GYskyfall ***@***.***> wrote: ﻿ When I use the latest ipopt3.13.0, I get the following error ValueError: Error reading '/tmp/tmpr26w60q7.pyomo.sol': could not convert string to float: 'p\n'. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

here are the files
[files.zip](https://github.com/Pyomo/pyomo/files/3986474/files.zip)

**Comment by ghackebeil** [comment]
I ran your NL file with my older version of Ipopt and it produced a SOL file that is nearly identical to yours, except yours has the letter `p` on 4 random lines instead of a floating point number. I've have no idea why this would be the case.

It looks like the spots where `p`s appear in your file correspond to values in my SOL file that are zero or very very close to zero.

This is baffling. Perhaps there is a bug in the version of ASL that is compiled into your Ipopt? That is the library that writes the SOL file.

**Comment by GYskyfall** [comment]
ok, I will try other version of ASL

> I ran your NL file with my older version of Ipopt and it produced a SOL file that is nearly identical to yours, except yours has the letter `p` on 4 random lines instead of a floating point number. I have no idea why this would be the case.
> 
> It looks like the spots where `p`s appear in your file correspond to values in my SOL file that are zero or very very close to zero.
> 
> This is baffling. Perhaps there is a bug in the version of ASL that is compiled into your Ipopt? That is the library that writes the SOL file.
Thanks, I will try other version of ASL

**Comment by ghackebeil** [comment]
worst case, we can add special handling of `p` to mean zero, but I'd want to understand where that is coming from before doing so

**Comment by ghackebeil** [comment]
Please reopen if this continues to be an issue, and we will figure something out.

**Comment by janhaa** [comment]
Hi, I am experiencing the same issue.
My colleague is developing the original code on a Windows machine while we run the final product on a Ubuntu machine.

Any ideas?

**Comment by janhaa** [comment]
Downgrade to ipopt 3.12.13 solved it for me!

**Comment by eslickj** [comment]
Just in case anyone searches and stumbles onto this issue like I did.  The problem is not with the ASL, it's the APML app code in Ipopt 3.13.  I replaced just the AMPL app code in 3.13 with the code in 3.12 and that seems to work fine. At least that narrows the problem to a couple of files.  I will file an issue for Ipopt if no one has yet.
