### ISSUE TITLE
Error running feasibility.py example in pynumero

### ISSUE THREAD

**Issue by notesofdabbler** [Pyomo/pyomo#1240]
When I run the feasibility.py [example](https://github.com/Pyomo/pyomo/blob/master/pyomo/contrib/pynumero/examples/feasibility.py) from pynumero, I get the following error. 

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-73f05656338d> in <module>
      1 # build nlp initialized at the solution
----> 2 nlp = PyomoNLP(model)

~/anaconda3/lib/python3.6/site-packages/pyomo/contrib/pynumero/interfaces/nlp.py in __init__(self, model)
   1482             nl_file = filename+".nl"
   1483 
-> 1484             super(PyomoNLP, self).__init__(nl_file)
   1485             self._model = model
   1486 

~/anaconda3/lib/python3.6/site-packages/pyomo/contrib/pynumero/interfaces/nlp.py in __init__(self, model, **kwargs)
    856 
    857         # ampl interface
--> 858         self._asl = _asl.AmplInterface(self._model)
    859 
    860         # ToDo: remove this after new pynumero libraries get merged in conda-forge

~/anaconda3/lib/python3.6/site-packages/pyomo/contrib/pynumero/extensions/asl.py in __init__(self, filename, nl_buffer)
     32             raise RuntimeError(
     33                 "ASL interface is not supported on this platform (%s)"
---> 34                 % (os.name,) )
     35 
     36         if nl_buffer is not None:

RuntimeError: ASL interface is not supported on this platform (posix)
```
Pyomo version I am using is 5.6.8 and my platform is Mac OS HighSierra (I also got this error when running in Linux Ubuntu 16.04). The notebook where I was trying out this example is [here]. I wanted to check if I need to install anything additional to make this work.

**Comment by qtothec** [comment]
You might need to do `pyomo download-extensions` and `pyomo install-extensions`. I don't work much with pynumero yet, so I haven't tried myself.

**Comment by blnicho** [comment]
Also take a look at the PyNumero installation instructions here: https://github.com/Pyomo/pyomo/blob/master/pyomo/contrib/pynumero/doc/source/installation.rst

**Comment by notesofdabbler** [comment]
Thanks for pointing me to the installation instructions. The code worked fine after I installed pynumero_libraries with the command
```
conda install -c conda-forge pynumero_libraries
```
