### ISSUE TITLE
Fixed variables are not always updated correctly in persistent solvers

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1244]
Fixed variables are not updated correctly in the persistent solvers if they are fixed before the constraints/objectives they are used in get added to the solver. If that happens, the variables get replaced by their values when `generate_standard_repn` is called. This should be easy to fix by setting the `compute_values` argument to `False` when `generate_standard_repn` is called.

**Comment by mrmundt** [comment]
@michaelbynum - did you fix this within APPSI?

**Comment by michaelbynum** [comment]
This is fixed.
