### ISSUE TITLE
NEOS Gateway Timeout

### ISSUE THREAD

**Issue by jkgiesler** [Pyomo/pyomo#125]
I have been getting the following exception running jobs on NEOS in pyomo 5.1.1 in both Ubuntu and Windows:
```<ProtocolError for www.neos-server.org:3333/RPC2: 504 Gateway Time-out>```

I believe this is due to a time-out in the call to ```self.kestrel.neos.getIntermediateResults()``` here: https://github.com/Pyomo/pyomo/blob/79404732c451ec9f143dbdd47d2e372ac1695d8d/pyomo/neos/plugins/kestrel_plugin.py#L205-L215

My fix to this problem has been to check ```self.kestrel.neos.getJobStatus()``` until the job is no longer in 'Waiting' status and then proceed with  the call to ```self.kestrel.neos.getIntermediateResults()```. This seems to fix the problem for me, but it relies on checking at a regular time interval and repeated queries to NEOS. I don't believe this is the best solution. Any suggestions?

**Comment by jrlooker** [comment]
I'm also experiencing this NEOS time-out issue on larger problems when using CPLEX. It seems that if the problem is large enough to take longer than 2 minutes to solve, then the time-out occurs, otherwise it's fine.

**Comment by jkgiesler** [comment]
@jrlooker in case you are curious here is the modification I made to kestrel_plugin.py. Submitting larger problems have worked fine for me since making this change.

https://gist.github.com/jkgiesler/bbc3b6c4fef93d174db46c821bc82cc4#file-kestrel_plugin-py-L213

**Comment by jrlooker** [comment]
Thanks for your help. Your fix seems to be working for me too.

**Comment by jrlooker** [comment]
I spoke too soon. I'm now getting "ValueError: no Options line found" from pyomo/opt/plugins/sol.py lines 47 and 86, when the job runs for over 30mins.

**Comment by jkgiesler** [comment]
@jrlooker that sounds to me like it is failing to parse the solution file. I'm unfamiliar with CPLEX on NEOS, so I don't know if I can be of any more help. When you get this error message does it still say it is running on the NEOS webconsole?

**Comment by jrlooker** [comment]
@jkgiesler I don't want to waste your time debugging my code. I think you're right: when my code attempts to load the results, it appears there's nothing there. I wonder if it's related to issue #122 "Error getting NEOS results"? Thanks again for your help.
