### ISSUE TITLE
log_infeasible_constraints behavior seems to change significantly from 5.6.7 -> 5.6.8

### ISSUE THREAD

**Issue by tharwan** [Pyomo/pyomo#1251]
I have used to the log_infeasible_constraits function to check output from cbc, because it would sometimtes produce wired results under some circumstances. 

I used a logger to catch all output of log_infeasible_constraints and if there was any I would throw an error. 

Now after upgrading to 5.6.8, it appears there is also output for constraints if they are not infeasible. Is that intentional?

I assume commit 5e0b43bb043f902c2df59bef09397c96f7049ebf somehow broke the logging?

**Comment by qtothec** [comment]
Fixed already in https://github.com/Pyomo/pyomo/pull/1226, but won't go out until the next release, unless you want to update from github master.

Apologies for that.
