### ISSUE TITLE
Support for quadratic objective using gurobi

### ISSUE THREAD

**Issue by marcovc** [Pyomo/pyomo#1252]
Gurobi 9.0 supports quadratic objective functions and constraints. Does the current Pyomo version takes advantage of this for such a problem?

**Comment by michaelbynum** [comment]
Yes. Pyomo’s interfaces to Gurobi support quadratic objectives and constraints.

**Comment by marcovc** [comment]
Thanks, it seems that when equality quadratic constraints are present, gurobi exists with the error:
```
ERROR 10021: Quadratic equality constraints
```

To bypass this, it requires adding the "NonConvex=2" parameter. Just letting you know in case this something Pyomo should be doing automatically.

Thanks

**Comment by michaelbynum** [comment]
@marcovc Thank you. We appreciate that.
