### ISSUE TITLE
Approaches for parallel testing

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1254]
I'm trying to find the best way to run parallel tests (MPI). So far, I am aware of two mechanisms to do this. If anyone knows of better approaches, or has opinions on these approaches, please let me know.

1. Subprocess - use subprocess to execute mpirun. This would have the advantage of catching errors.
2. mpirun nosetests

**Comment by jwatsonnm** [comment]
Take a look at Gabe's branch-and-bound library - name escapes me. He has good examples of how to do this.

**Comment by DLWoodruff** [comment]
Hi Michael,
  Gabe recommended a runtests package and David M. has tried it out.
For Gabe's stuff, see:
https://github.com/ghackebeil/pybnb
  David W.

**Comment by michaelbynum** [comment]
@jwatsonnm @DLWoodruff Thank you both! This is very helpful.

**Comment by ghackebeil** [comment]
I can walk you through the key files used for testing, if it will help.

**Comment by jsiirola** [comment]
@michaelbynum: given PRs #1314, #1331, and #1278 have been merged, can this issue be closed?
