### ISSUE TITLE
`CPLEXDirect` (and `CPLEXPersistent`) do not support v12.10

### ISSUE THREAD

**Issue by ruaridhw** [Pyomo/pyomo#1260]
1. Install `cplex==12.10.0`
2. Run a model using the persistent solver
3. The following error occurs

```
  File "...venv/lib/python3.7/site-packages/cplex/_internal/_ostream.py", line 66, in __init__
    raise TypeError("outputfile must have a write method")
TypeError: outputfile must have a write method
```

This is due to `pyomo/solvers/plugins/solvers/cplex_direct.py` line 112, (in `_apply_solver`) using a call to `set_results_stream()` that is now deprecated. A deprecation warning was raised in version 12.9.

The fix looks pretty straightforward; `CPLEXDirect._log_file` is a string path whereas `Cplex.set_results_stream()` expects a file-like object.

**Comment by blnicho** [comment]
@ruaridhw if you have an idea for how to fix this PRs are always welcome. We should make sure any fix for this is also backwards compatible with older versions of CPLEX.
