### ISSUE TITLE
PyNumero support on Windows

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#1261]
We need to make sure PyNumero installs/runs on Windows and make sure any extra installation steps are well documented. Some discussion on this was started in #1253. When this is resolved we also need to make sure to enable the tests currently being skipped on Windows.

**Comment by santiagoropb** [comment]
@blnicho  the easiest way to get those tests running would be to update the conda recipe. In fact, if I remember correctly thats how the travis tests are run. First it gets the libraries from conda-forge and then pyomo uses them. One will need then to push my latest version of the cmake project to   https://github.com/conda-forge/pynumero_libraries-feedstock and also edit the recipe to manage the windows built. The cmake project works on windows. I have tested that few months ago.

**Comment by santiagoropb** [comment]
I will update the repo https://github.com/santiagoropb/pynumero_libraries this coming weekend for you to get that cmake project

**Comment by blnicho** [comment]
@santiagoropb thanks for the guidance!

**Comment by santiagoropb** [comment]
@blnicho I updated the repo with the cmake project. Instructions are provided in the README for all different options available (IPOPT, AMPL-MP, ASL, HSL). I tested building the project from clean with a conda environment with its own gcc and cmake and all the options worked fine. Next thing will be to make a release of that project and link it with the conda recipe.

**Comment by santiagoropb** [comment]
@blnicho @jsiirola  do you have a windows machine to test if the conda recipe is working on windows? I reworked the recipe yesterday and now builds a .dll for windows so the command:

`conda install -c conda-forge pynumero_libraries`

should now work on windows as well. I dont have a machine to test if ctypes can successfully use the .dll in pynumero

**Comment by blnicho** [comment]
@santiagoropb I tried installing the pynumero_libraries package using that conda command but I think there is still a step missing in the installation instructions for moving the .dll downloaded by conda into the libs folder where PyNumero expects them to be. Or maybe a better solution might be for PyNumero to search more broadly for the .dll? 

Once I moved the .dll I was able to run all of the PyNumero examples successfully on Windows
