### ISSUE TITLE
bug in pynumero example: sensitivity.py

### ISSUE THREAD

**Issue by notesofdabbler** [Pyomo/pyomo#1269]
It seems like the [sensitivity.py](https://github.com/Pyomo/pyomo/blob/master/pyomo/contrib/pynumero/examples/sensitivity.py) code is not calculating the sensitivity correctly. The sensitivity based x_new is a bit different from the result obtained by solving the perturbed NLP in the code. The cause of this seems to be the creation of `Np`

```
Np = BlockMatrix(2, 1)
Np[0, 0] = nlp.extract_submatrix_hessian_lag(pyomo_variables_rows=nlp.get_pyomo_variables(), pyomo_variables_cols=[m.eta1, m.eta2])
Np[1, 0] = nlp.extract_submatrix_jacobian(pyomo_variables=[m.eta1, m.eta2], pyomo_constraints=nlp.get_pyomo_constraints())
```
It seems that in this example Np should be 9x2 matrix with all zeros except elements (8, 1) and (9, 2) which should be one (based on eq 13 in this [reference paper](http://www.optimization-online.org/DB_FILE/2011/04/3008.pdf)). 

I have a [jupyter notebook](https://github.com/notesofdabbler/learn_pyomo/blob/master/wk_pynumero/wk_sensitivity.ipynb) that recreates this example and the proposed modification which seems to fix the issue.

**Comment by michaelbynum** [comment]
@notesofdabbler Thanks. If you already have a fix, can you create a pull request?

**Comment by carldlaird** [comment]
@santiagoropb Can you look at this quickly?

**Comment by notesofdabbler** [comment]
Sorry, I noticed a mistake in the modification I did. I will recheck my modified code later today and see if the modification I did was the problem and whether the issue I raised is still relevant or not.

**Comment by notesofdabbler** [comment]
I have now fixed my code in this [jupyter notebook](https://github.com/notesofdabbler/learn_pyomo/blob/master/wk_pynumero/wk_sensitivity.ipynb). I would appreciate a review of this proposed modification.

**Comment by santiagoropb** [comment]
@notesofdabbler the matrix Np is calculated according to equation 24. In that context I don't think it should be a matrix of only zeros and ones.

**Comment by notesofdabbler** [comment]
@santiagoropb Thanks for your quick review and response. You are correct that `Np` is not a matrix of zeros and ones in the context of eq 24. However, the code is not calculating `new_x` correctly since the columns of Np are also in M and therefore `ds = [dx1: 0, dx2: 0, dx3:0, deta1: 1, deta2: 1]`. 

It looks like using eq 24 with the following modifications will fix the sensitivity calculation:
1. M[0, 0] matrix is a submatrix with just the variables `m.x1, m.x2, m.x3` and M[1, 0] has only  constraints `m.const1, m.const2`.
2. Np would also need to just have the variables `m.x1, m.x2, m.x3` for Np[0, 0] and constraints `m.const1, m.const2` for Np[1, 0]
3. Changing `Np.tocsc() to -Np.tocsc()` in `ds = spsolve(M.tocsc(), Np.tocsc())`

When I tried this modification in the [jupyter notebook](https://github.com/notesofdabbler/learn_pyomo/blob/master/wk_pynumero/wk_sensitivity.ipynb), it seems to fix the issue.

The alternative way that fixes the issue is using eq 13 based Np (matrix of zeros and ones) since 
eq 13 is a variant of eq 24 when there are explicity equations with a set of variables `w` set equal
to the parameters `p`. In this case matrix `M` as calculated in sensitivity.py doesn't have to be changed.

**Comment by santiagoropb** [comment]
@notesofdabbler you are certainly right! thanks for catching this. I will make a PR tonight to correct the example.

**Comment by santiagoropb** [comment]
#1271 corrects the example

**Comment by notesofdabbler** [comment]
@santiagoropb Thanks very much for looking into this and fixing the example.
