### ISSUE TITLE
[PEP] Formalize repo management / testing process

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#1274]
## Proposal
This PEP proposes that we standardize development practices to leverage GitHub forks for all development.  Developers should do all development on forks of the main Pyomo/pyomo repository.  Collaborative development may occur on a single fork or through multiple forks and PRs at the discretion of the fork owner.  The PMC will approve any branches that exist on Pyomo/pyomo.

This PEP proposes that Pyomo/pyomo will start out with ~~three~~ **two** branches:
 - `master`
 - `doc-testbuild`
 - ~~`IDAES`~~ (IDAES should fork pyomo into their own organization and manage their branch there)

We will set up a single Github Action workflow that will test all branches with `linux/python3.7/nightly`.  As this will be set up on master, it will also apply to all forks (unless the fork owner changes the configuration locally).  This will provide quick "sanity tests" for ongoing development.

## Motivation
Many of our `[WIP]` and `[IDEA]` PRs are left open to gain access to the test harness.  By setting up the GitHub action to build a simple test suite, developers can get 95% of the test information without clogging the full PR test infrastructure.  

Moving development onto forks will ensure that branch testing does not impact the Pyomo organization's 20-concurrent test limit (the development branch builds will count against the developer's limit and not the organization's).  This will also clean up the main repository so that when new developers fork the main repository their fork is not immediately populated with a large number of branches.

**Comment by mrmundt** [comment]
@jsiirola - I'll start work on the workflow. Please keep me updated on the status of the branch-movement discussion.

**Comment by michaelbynum** [comment]
I like this proposal.

**Comment by jsiirola** [comment]
IDAES has moved to a fork (IDAES/pyomo).  I propose that we hold off on removing the Pyomo/pyomo@IDAES branch for ~2 weeks to give us a chance to inform the team and get the developers moved over.

**Comment by carldlaird** [comment]
@jsiirola I like this as well.

**Comment by whart222** [comment]
I have been unenthusiastic about this proposal when we've discussed it.  Moving development onto personal forks hides active development from other developers unless they know where to look.  This proposal also requires that Pyomo developers to have a higher level of git expertise to robustly work on forks (e.g. to ensure that their forks are synchronized appropriately to the Pyomo/pyomo master).

Maybe the limit on concurrent testing motivates this change.  But that needs to be weighed against the possibility that this will discourage the integration of new Pyomo developers.

**Comment by carldlaird** [comment]
@whart222 I agree that git can be a bit of a pain (especially merging master from original repos into fork). However, I don't know if this will discourage integration of new developers. Especially since the proposed process (working with forks) seems to me to be the recommended (and googlable) process for most GitHub projects.

**Comment by mrmundt** [comment]
@whart222 @carldlaird I agree with Carl, and also bring to the table the point that there is a lot of active development displayed in our Issues and PRs, which is a generally respected practice.

**Comment by jsiirola** [comment]
(Reopening this PEP, it was accidentally closed by #1294)

**Comment by mrmundt** [comment]
I'd like to revisit this PEP. The ability to test "locally" (e.g., a smaller suite on their fork) has been available for several years now, and we have updated the documentation to reflect this. Do we still wish to push for the latter half of this PEP (`doc-testbuild` and a nightly workflow to test any branches that exist within the main repo)?

**Comment by jsiirola** [comment]
@mrmundt: I believe that we can close this PEP as complete and NOT stand up the `doc-testbuild branch: the doc builder action on GHA (that runs for all PRs) covers that use case without the need for a dedicated branch.  We are down to only the "main" branch, and I think we can leave it that way.

**Comment by mrmundt** [comment]
@jsiirola - Agreed. Closing.
