### ISSUE TITLE
Add GAMS to OSX Github Actions

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#1279]
Can we add a GAMS installation to the OSX workflow?  The URL for a self-extracting zip file is: https://d37drm4t2jghv5.cloudfront.net/distributions/24.8.5/macosx/osx_x64_64_sfx.exe

**Comment by mrmundt** [comment]
Ironically, I had JUST started a branch on my own fork to test this out. I was having issues with it yesterday (Github Runner issues), but I'm working past those.

**Comment by mrmundt** [comment]
@jsiirola - #1280 might need to be incorporated for GAMS to work on Mac. The Github Runner is on MacOS 10.15 (Catalina), and it has been consistently refusing to play ball with the older distribution executable. 
```

Install GAMS...

/Users/runner/runners/2.164.0/work/_temp/eb58c216-c052-423c-bb53-e5ff4148d349.sh: line 6: ./osx_x64_64_sfx.exe: Bad CPU type in executable
```
I tried the newest distribution (30.1.0), and that issue doesn't occur.

**Comment by jsiirola** [comment]
Sounds reasonable.  Let's start standing this up with 30.1.0 (and we can look at moving linux/windows either at the same time or later - full resolution of #1280 may take a while, as that involves things like updating modules and Travis/Appveyor).

**Comment by mrmundt** [comment]
@jsiirola - The PR for this has been added.
