### ISSUE TITLE
DAE transformations on connectors

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#128]
Need to test the DAE transformations on ContinuousSet indexed connectors and make sure things work as expected.

**Comment by eslickj** [comment]
This seems that it may be the last sticking point for applying the DAE transformation at the end of model creation.

**Comment by qtothec** [comment]
@eslickj I'm going to interpret that as "This should be high priority".

**Comment by blnicho** [comment]
This is waiting on the discussion in #290 to be resolved. The problem has to do with re-expanding connectors that were expanded prior to applying a discretization. I can either add special handling for Connectors in the discretization transformations or Connector re-expansion can be built into the updated Connector design.

**Comment by blnicho** [comment]
Fixed in #583
