### ISSUE TITLE
Update GAMS version for Jenkins/Github

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#1280]
We currently test against an older GAMS version.  Should we consider moving to the current GAMS version (as of the time of writing, 30.1.0)?

We should probably resolve #1279 first.

**Comment by blnicho** [comment]
Yes, I think moving to the current version is a good idea.

**Comment by mrmundt** [comment]
#1279 introduces GAMS 30.1.0 to MacOS (since older distributions have issues installing on Mac 10.15), so that's one thing already done.

**Comment by mrmundt** [comment]
This has been done.
