### ISSUE TITLE
Request: add assertRaisesRegex support to TestCase

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#1283]
We use `assertRaisesRegexp` all over the code base because of python 2.7 support, but the current naming is deprecated. I suggest that we add a compatibility shim so that we can use the new naming, something to the effect of the solution proposed here:
https://github.com/MagicStack/httptools/issues/1#issuecomment-217630158

This was mentioned in #1272.

**Comment by jsiirola** [comment]
This makes sense.  I just pushed a PR to PyUtilib that implements a simple shim for Python 2.  Assuming that gets merged, we can start transitioning over to `assertRaisesRegex`
