### ISSUE TITLE
Definition of a variable imported in plain text

### ISSUE THREAD

**Issue by SlowLearner22** [Pyomo/pyomo#1284]
I am working in optimization in the presence of uncertainty using stochastic collocation methods.

I receive a text file which contains the values of several variables, each one in a row (I will attach it). 

In the file there are just three rows, so I would not have any issues copying and pasting each row; however, in the future there will be manymore rows. I need to somehow automate this. 

I have attempted to simply read the text file 
```

h = open("savedWindXPython.txt","r")
c=h.readline()
h.close
```
and then use this c, a string, to define the variable. The following error appeared: `AttributeError: 'NoneType' object has no attribute 'is_relational'`
I searched and found [exec](https://www.programiz.com/python-programming/methods/built-in/exec). However, the same error appeared again. 

These are my two attempts at reading the variable from the text file
```
m.Wind_lammda1             = Var(m.N, domain = Reals) #

def Wind_lammda1_definition(model, i):
    #return m.Wind_lammda1[i] == exec(c)
    return m.Wind_lammda1[i] ==c
m.Wind_lammda1_const = Constraint(m.N, rule = Wind_lammda1_definition) 
[savedWindXPython.txt](https://github.com/Pyomo/pyomo/files/4159728/savedWindXPython.txt)

```

 I have found [this document](https://pyomo.readthedocs.io/en/stable/working_abstractmodels/data/storing_data.html). This leads me to believe that what I am doing is compleely impossible. Has someone attempted something like this before?

Please bear in mind that I am not a professional programmer but a engineering student. My knowledge about python and pyomo is self-taught and limited. 

Note that `Sinc` has been defined before in my code.

This is the text file that I am trying to read:
[savedWindXPython.txt](https://github.com/Pyomo/pyomo/files/4159745/savedWindXPython.txt)

Regards.

**Comment by blnicho** [comment]
Github issues are meant for bug reports and feature requests. This question is better suited for the [Pyomo forum](https://groups.google.com/forum/?hl=en#!forum/pyomo-forum). Take a look at past forum posts, I think there was a recent question very similar to yours.
