### ISSUE TITLE
Drop Travis Tests

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1286]
Can we drop a subset of the travis tests now that GitHub actions are working? It looks like the common tests are the nightly linux 3.5, 3.6, 3.7, and 3.8 tests. Is there more to be added to the Github Actions workflows before these can be fully replaced?

**Comment by jsiirola** [comment]
We are still working to get solvers available on github actions. I would hold off deprecating Travis tests until the solvers are available. We also need to think about slim and pypy builds.

**Comment by ghackebeil** [comment]
So part of the advantage of the Travis setup of that we offload a large amount of package setup time offline. We are also less prone to third party server outages that we pull packages from.

I’m just curious, but what about the GitHub actions workflow is getting around that? Is that there are so many more parallel builds available that setup time is no longer an issue?

I suppose they could also incorporate our test docker images the way Travis does as well (assuming docker is supported on their Linux images).

Gabe

**Comment by mrmundt** [comment]
We did this!
