### ISSUE TITLE
Quadratic term not identified by generate_standard_repn

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1287]
```
>>> import pyomo.environ as pe                                                                                                                                                                                               
>>> from pyomo.repn.standard_repn import generate_standard_repn
>>> m = pe.ConcreteModel()
>>> m.x = pe.Var()
>>> m.y = pe.Var()
>>> print(generate_standard_repn((m.x + m.y)**2, quadratic=True))

constant:       0
linear vars:    []
linear var ids: []
linear coef:    []
quadratic vars:    []
quadratic var ids: []
quadratic coef:    []
nonlinear expr:
(x + y)**2
nonlinear vars: ['x', 'y']
```

**Comment by carldlaird** [comment]
@michaelbynum good catch. We should also consider adding an explicit QuadraticExpression object like we have for LinearExpression.

**Comment by johwiebe** [comment]
@michaelbynum I also just came across this issue. I noticed that there is a test which asks for this behaviour. Is this by design for some reason?
https://github.com/Pyomo/pyomo/blob/79205167333552a840d9e468a5ac188d4fa758c3/pyomo/repn/tests/test_standard.py#L3121-L3157

**Comment by michaelbynum** [comment]
@johwiebe The test you mentioned does not actually expect this behavior. The key is the `quadratic=False` keyword argument to the `generate_standard_repn` function. When `quadratic=False`, quadratic terms are not identified (only linear).

**Comment by johwiebe** [comment]
@michaelbynum I think that's just the first part of the test. On line 3141 the same expression is tested with `quadratic=True`:
https://github.com/Pyomo/pyomo/blob/79205167333552a840d9e468a5ac188d4fa758c3/pyomo/repn/tests/test_standard.py#L3141-L3157
The expected outcome with and without `quadratic=False` seems to be the same.

**Comment by michaelbynum** [comment]
@johwiebe Oh, I apologize. I did not scroll far enough. Good catch. I don't think this behavior is by design.
