### ISSUE TITLE
Issue Branching Priorities

### ISSUE THREAD

**Issue by ruaridhw** [Pyomo/pyomo#1299]
Several commercial solvers allow for issuing branching directions and priorities for variables of MIP problems however Pyomo doesn't support this.

See [Gurobi](https://www.gurobi.com/documentation/9.0/refman/branchpriority.html), [CPLEX](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.10.0/ilog.odms.cplex.help/CPLEX/FileFormats/topics/ORD.html), [GAMS](https://www.gams.com/latest/docs/UG_LanguageFeatures.html#UG_LanguageFeatures_SettingPrioritiesForBranching)

One should be able to apply a "direction" and "priority" for variables which are read and applied by the solver upon solve time.

Note, this is highly solver-specific and will require separate implementations for the Shell vs Persistent solvers. For example, the CPLEXSHELL solver can write a `.ord` file to disk in exactly the same manner as the warm start file which is then read by the CPLEX script. Meanwhile, the CPLEXDirect solver would utilise `self._solver_model.order.set()`

I would be happy to raise a PR given some design direction:
1. Should this be implemented using the `Suffix` interface? If not, would a simple `List[Tuple[PyomoVar, PriorityType, BranchDirectionType]]` passed in as a `solver.solve()` kwarg be sufficient? 
2. Is it acceptable to only implement this for CPLEXSHELL and CPLEXDirect for now?

**Comment by ruaridhw** [comment]
Or perhaps this could just be a mutable attribute of the variables themselves (via `_GeneralVarData` or `_VarData`, I'm not sure which...) that is then read off within `_presolve()`?

**Comment by ghackebeil** [comment]
Hi @ruaridhw, thanks for putting this together! And sorry for the delay in getting you some feedback on this.

This is certainly functionality we want to support for this solver interface. I think a solution using the Suffix component is more likely to make it through the approval process. Most of the team is weary of adding additional slots to the base variable object as it is already quite bloated.

Also, @michaelbynum is doing a lot of work to improve the solver interfaces right now. So just starting with the CPLEXSHELL is certainly okay. One of us can probably migrate this into the CplexDirect quite easily after that.

I'll try to post some example code to do this with the Suffix component in the next day or so if that will help.

**Comment by ruaridhw** [comment]
Thanks @ghackebeil. I've raised #1300 as an implementation of this using the Suffix component.

Might need some help getting the [2.7 pipeline](https://github.com/Pyomo/pyomo/runs/455982973?check_suite_focus=true) to pass though as I've not really any clue what this error message is suggesting...
