### ISSUE TITLE
Default Windows conda install requires pint?

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#1336]
I just helped someone install `pint` to fix a fresh install of Pyomo. We should either resolve https://github.com/Pyomo/pyomo/issues/899 or add `pint` as a formal requirement... or update the commit that conda is using if it's been resolved already.

**Comment by blnicho** [comment]
@qtothec I was unable to recreate this with a fresh Windows conda install running Python 3.7.1 and Pyomo 5.6.8. If this is still an issue I would like to get it resolved before we cut the next release but I'm not sure what else to try to recreate this.

**Comment by carldlaird** [comment]
@blnicho Looks like you beat me to this. I agree that we have not reproduced this issue yet. 
@qtothec Did you get any more information on this? Was there an IDAES import in the file as well or something else we missed?

**Comment by qtothec** [comment]
I haven't been able to follow up with the person, and I wasn't physically present during the installation (only the troubleshooting, in which I install pint and it worked). I think we close this until it comes up again. The person in question isn't working on IDAES, so I don't think that was the cause.
