### ISSUE TITLE
pyomo/contrib/parmest/ Invalid index error for component

### ISSUE THREAD

**Issue by toichiserada** [Pyomo/pyomo#1340]
Hi

I'm trying to estimate the parameter 'Boiler[1].eta' with paramest.py. My theta_names looks like this: theta_names = ['Boiler[1].eta'].

Unfortunately i get this error message:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyomo/pysp/phutils.py", line 482, in extractComponentIndices
    % (str(tuple(index_template)), component.name))
ValueError: The index ('1].eta',) is not valid for component named: Boiler

If i pause the program at the end of the execution of my model_function and execute the following line:
model.Boiler[1].eta 
I get this: 
<pyomo.core.base.var.SimpleVar at 0x12090e748>
So the variable actually exists in my model.

Is this a Bug or did i do something wrong? 
The index ('1].eta',) looks also a bit chopped up. Maybe there is a Problem?

Greetings
Jakob

**Comment by DLWoodruff** [comment]
It may take a few days to look into this.

**Comment by toichiserada** [comment]
Okay! Thank you :)

**Comment by toichiserada** [comment]
May i ask how long this will approximately take to fix this bug?

**Comment by ThomasPTW** [comment]
I had a similar problem. Maybe it has something to do with the block architecture of the model

**Comment by toichiserada** [comment]
Here is a minimal example for this Issue.

`#!/usr/bin/env python
# coding: utf-8

from matplotlib.pyplot import plot
import matplotlib.pyplot as plt
import pandas as pd

from pyomo.environ import *
import pyomo.contrib.parmest.parmest as parmest


def model_function(data):
    model = AbstractModel()

    model.T = Set(ordered=True)

    model.J = Set(initialize=[1])

    instance = model.create_instance(data={None: {
        'T': {None: [0, 1, 2, 3], 'J': [1]}
    }})

    def boiler_rule(A, u):
        A.eta = Var(bounds=(0, 1), initialize=0.5)
        A.eta.fix()
        A.cost_per_kWh = Param(initialize=1)

        A.P_in = Var(instance.T, within=NonNegativeReals)
        A.P_out = Var(instance.T, within=NonNegativeReals)

        # constraint efficiancy
        def eta_constraint_rule(A, t):
            return A.P_out[t] == A.P_in[t] * A.eta

        A.constraint_eta = Constraint(instance.T, rule=eta_constraint_rule)

    instance.Boiler = Block(instance.J, rule=boiler_rule)
    instance.Boiler.construct()

    instance.demand = Param(instance.T, initialize={0: 0, 1: 600, 2: 900, 3: 1200})
    instance.cost_error = Param(initialize=100)

    def Bilanz_Regel(instance, t):
        return instance.demand[t] == instance.Boiler[1].P_out[t]

    instance.balance = Constraint(instance.T, rule=Bilanz_Regel)

    instance.Zielfunktion = Objective(expr=sum(
        instance.Boiler[1].P_in[t] * instance.Boiler[1].cost_per_kWh * instance.cost_error for t in instance.T))
    return instance


def parameter_estimation():
    """Estimate Parameter Boiler[1].eta"""
    data = {'T': [0, 1, 2, 3],
            'P_in': {0: 0.0, 1: 1200.0, 2: 1800.0, 3: 2400.0},
            'P_out': {0: 0.0, 1: 600.0, 2: 900.0, 3: 1200.0}}
    data = [data]

    # theta_names
    # The third argument is a list of variable names that the user wants to estimate.
    # The list contains strings with Var names from the Pyomo model.
    theta_names = ['Boiler[1].eta']

    # objective_function
    def objective_function(model, data):
        expr = 0
        for t in data['T']:
            # (observed_value - value_calculated_form_model)^2*1/nr_time_steps
            # Achtung: Geht davon aus, dass alle Zeitschritte gleich lang sind.
            # Muss für variable Schrittweite ggf. angepasst werden.
            # P_in
            expr += ((data['P_in'][t] - model.Boiler[1].P_in[t]) ** 2) * (1 / len(data['T']))
            # P_out
            expr += ((data['P_in'][t] - model.Boiler[1].P_out[t]) ** 2) * (1 / len(data['T']))
        return expr

    pest = parmest.Estimator(model_function, data, theta_names, objective_function)
    obj, theta = pest.theta_est()


def solve_model():
    """this represents a normal solve of the model, without parameter estimation."""
    instance = model_function()
    # solver
    result = SolverFactory('glpk').solve(instance, tee=True)
    print(result)

    # plotte Verbrauch, den die Anlagen erfüllen müssen
    plt.figure(1)
    plot(pd.Series(instance.demand.extract_values()), drawstyle='steps-post')
    plt.show();
    print('Demand')

    # plotte die bereitgestellte Leistung P_out der Anlagen 1(blau) und 2(orange)
    # der Verbrauch ist noch mal gepunktet dargestellt
    plt.figure(2)
    plot(pd.Series(instance.Boiler[1].P_out.extract_values()), drawstyle='steps-post')

    plot(pd.Series(instance.demand.extract_values()), 'k:', drawstyle='steps-post')
    plt.legend(['Boiler 1', 'demand'])
    plt.show();

    print(instance.Boiler[1].P_in.extract_values())
    print(instance.Boiler[1].P_out.extract_values())


# solve_model([])
parameter_estimation()`

**Comment by toichiserada** [comment]
from matplotlib.pyplot import plot
import matplotlib.pyplot as plt
import pandas as pd

from pyomo.environ import *
import pyomo.contrib.parmest.parmest as parmest


def model_function(data):
    model = AbstractModel()

    model.T = Set(ordered=True)

    model.J = Set(initialize=[1])

    instance = model.create_instance(data={None: {
        'T': {None: [0, 1, 2, 3], 'J': [1]}
    }})

    def boiler_rule(A, u):
        A.eta = Var(bounds=(0, 1), initialize=0.5)
        A.eta.fix()
        A.cost_per_kWh = Param(initialize=1)

        A.P_in = Var(instance.T, within=NonNegativeReals)
        A.P_out = Var(instance.T, within=NonNegativeReals)

        # constraint efficiancy
        def eta_constraint_rule(A, t):
            return A.P_out[t] == A.P_in[t] * A.eta

        A.constraint_eta = Constraint(instance.T, rule=eta_constraint_rule)

    instance.Boiler = Block(instance.J, rule=boiler_rule)
    instance.Boiler.construct()

    instance.demand = Param(instance.T, initialize={0: 0, 1: 600, 2: 900, 3: 1200})
    instance.cost_error = Param(initialize=100)

    def Bilanz_Regel(instance, t):
        return instance.demand[t] == instance.Boiler[1].P_out[t]

    instance.balance = Constraint(instance.T, rule=Bilanz_Regel)

    instance.Zielfunktion = Objective(expr=sum(
        instance.Boiler[1].P_in[t] * instance.Boiler[1].cost_per_kWh * instance.cost_error for t in instance.T))
    return instance


def parameter_estimation():
    """Estimate Parameter Boiler[1].eta"""
    data = {'T': [0, 1, 2, 3],
            'P_in': {0: 0.0, 1: 1200.0, 2: 1800.0, 3: 2400.0},
            'P_out': {0: 0.0, 1: 600.0, 2: 900.0, 3: 1200.0}}
    data = [data]

    # theta_names
    # The third argument is a list of variable names that the user wants to estimate.
    # The list contains strings with Var names from the Pyomo model.
    theta_names = ['Boiler[1].eta']

    # objective_function
    def objective_function(model, data):
        expr = 0
        for t in data['T']:
            # (observed_value - value_calculated_form_model)^2*1/nr_time_steps
            # Achtung: Geht davon aus, dass alle Zeitschritte gleich lang sind.
            # Muss für variable Schrittweite ggf. angepasst werden.
            # P_in
            expr += ((data['P_in'][t] - model.Boiler[1].P_in[t]) ** 2) * (1 / len(data['T']))
            # P_out
            expr += ((data['P_in'][t] - model.Boiler[1].P_out[t]) ** 2) * (1 / len(data['T']))
        return expr

    pest = parmest.Estimator(model_function, data, theta_names, objective_function)
    obj, theta = pest.theta_est()


def solve_model():
    """this represents a normal solve of the model, without parameter estimation."""
    instance = model_function()
    # solver
    result = SolverFactory('glpk').solve(instance, tee=True)
    print(result)

    # plotte Verbrauch, den die Anlagen erfüllen müssen
    plt.figure(1)
    plot(pd.Series(instance.demand.extract_values()), drawstyle='steps-post')
    plt.show();
    print('Demand')

    # plotte die bereitgestellte Leistung P_out der Anlagen 1(blau) und 2(orange)
    # der Verbrauch ist noch mal gepunktet dargestellt
    plt.figure(2)
    plot(pd.Series(instance.Boiler[1].P_out.extract_values()), drawstyle='steps-post')

    plot(pd.Series(instance.demand.extract_values()), 'k:', drawstyle='steps-post')
    plt.legend(['Boiler 1', 'demand'])
    plt.show();

    print(instance.Boiler[1].P_in.extract_values())
    print(instance.Boiler[1].P_out.extract_values())


# solve_model([])
parameter_estimation()

**Comment by toichiserada** [comment]
#!/usr/bin/env python
# coding: utf-8

from matplotlib.pyplot import plot
import matplotlib.pyplot as plt
import pandas as pd

from pyomo.environ import *
import pyomo.contrib.parmest.parmest as parmest


def model_function(data):
    model = AbstractModel()

    model.T = Set(ordered=True)

    model.J = Set(initialize=[1])

    instance = model.create_instance(data={None: {
        'T': {None: [0, 1, 2, 3], 'J': [1]}
    }})

    def boiler_rule(A, u):
        A.eta = Var(bounds=(0, 1), initialize=0.5)
        A.eta.fix()
        A.cost_per_kWh = Param(initialize=1)

        A.P_in = Var(instance.T, within=NonNegativeReals)
        A.P_out = Var(instance.T, within=NonNegativeReals)

        # constraint efficiancy
        def eta_constraint_rule(A, t):
            return A.P_out[t] == A.P_in[t] * A.eta

        A.constraint_eta = Constraint(instance.T, rule=eta_constraint_rule)

    instance.Boiler = Block(instance.J, rule=boiler_rule)
    instance.Boiler.construct()

    instance.demand = Param(instance.T, initialize={0: 0, 1: 600, 2: 900, 3: 1200})
    instance.cost_error = Param(initialize=100)

    def Bilanz_Regel(instance, t):
        return instance.demand[t] == instance.Boiler[1].P_out[t]

    instance.balance = Constraint(instance.T, rule=Bilanz_Regel)

    instance.Zielfunktion = Objective(expr=sum(
        instance.Boiler[1].P_in[t] * instance.Boiler[1].cost_per_kWh * instance.cost_error for t in instance.T))
    return instance


def parameter_estimation():
    """Estimate Parameter Boiler[1].eta"""
    data = {'T': [0, 1, 2, 3],
            'P_in': {0: 0.0, 1: 1200.0, 2: 1800.0, 3: 2400.0},
            'P_out': {0: 0.0, 1: 600.0, 2: 900.0, 3: 1200.0}}
    data = [data]

    # theta_names
    # The third argument is a list of variable names that the user wants to estimate.
    # The list contains strings with Var names from the Pyomo model.
    theta_names = ['Boiler[1].eta']

    # objective_function
    def objective_function(model, data):
        expr = 0
        for t in data['T']:
            # (observed_value - value_calculated_form_model)^2*1/nr_time_steps
            # Achtung: Geht davon aus, dass alle Zeitschritte gleich lang sind.
            # Muss für variable Schrittweite ggf. angepasst werden.
            # P_in
            expr += ((data['P_in'][t] - model.Boiler[1].P_in[t]) ** 2) * (1 / len(data['T']))
            # P_out
            expr += ((data['P_in'][t] - model.Boiler[1].P_out[t]) ** 2) * (1 / len(data['T']))
        return expr

    pest = parmest.Estimator(model_function, data, theta_names, objective_function)
    obj, theta = pest.theta_est()


def solve_model():
    """this represents a normal solve of the model, without parameter estimation."""
    instance = model_function()
    # solver
    result = SolverFactory('glpk').solve(instance, tee=True)
    print(result)

    # plotte Verbrauch, den die Anlagen erfüllen müssen
    plt.figure(1)
    plot(pd.Series(instance.demand.extract_values()), drawstyle='steps-post')
    plt.show();
    print('Demand')

    # plotte die bereitgestellte Leistung P_out der Anlagen 1(blau) und 2(orange)
    # der Verbrauch ist noch mal gepunktet dargestellt
    plt.figure(2)
    plot(pd.Series(instance.Boiler[1].P_out.extract_values()), drawstyle='steps-post')

    plot(pd.Series(instance.demand.extract_values()), 'k:', drawstyle='steps-post')
    plt.legend(['Boiler 1', 'demand'])
    plt.show();

    print(instance.Boiler[1].P_in.extract_values())
    print(instance.Boiler[1].P_out.extract_values())


# solve_model([])
parameter_estimation()
```

**Comment by toichiserada** [comment]
I created a minimal example for this issue!
```
from matplotlib.pyplot import plot
import matplotlib.pyplot as plt
import pandas as pd

from pyomo.environ import *
import pyomo.contrib.parmest.parmest as parmest


def model_function(data):
    model = AbstractModel()

    model.T = Set(ordered=True)

    model.J = Set(initialize=[1])

    instance = model.create_instance(data={None: {
        'T': {None: [0, 1, 2, 3], 'J': [1]}
    }})

    def boiler_rule(A, u):
        A.eta = Var(bounds=(0, 1), initialize=0.5)
        A.eta.fix()
        A.cost_per_kWh = Param(initialize=1)

        A.P_in = Var(instance.T, within=NonNegativeReals)
        A.P_out = Var(instance.T, within=NonNegativeReals)

        # constraint efficiancy
        def eta_constraint_rule(A, t):
            return A.P_out[t] == A.P_in[t] * A.eta

        A.constraint_eta = Constraint(instance.T, rule=eta_constraint_rule)

    instance.Boiler = Block(instance.J, rule=boiler_rule)
    instance.Boiler.construct()

    instance.demand = Param(instance.T, initialize={0: 0, 1: 600, 2: 900, 3: 1200})
    instance.cost_error = Param(initialize=100)

    def Bilanz_Regel(instance, t):
        return instance.demand[t] == instance.Boiler[1].P_out[t]

    instance.balance = Constraint(instance.T, rule=Bilanz_Regel)

    instance.Zielfunktion = Objective(expr=sum(
        instance.Boiler[1].P_in[t] * instance.Boiler[1].cost_per_kWh * instance.cost_error for t in instance.T))
    return instance


def parameter_estimation():
    """Estimate Parameter Boiler[1].eta"""
    data = {'T': [0, 1, 2, 3],
            'P_in': {0: 0.0, 1: 1200.0, 2: 1800.0, 3: 2400.0},
            'P_out': {0: 0.0, 1: 600.0, 2: 900.0, 3: 1200.0}}
    data = [data]

    # theta_names
    # The third argument is a list of variable names that the user wants to estimate.
    # The list contains strings with Var names from the Pyomo model.
    theta_names = ['Boiler[1].eta']

    # objective_function
    def objective_function(model, data):
        expr = 0
        for t in data['T']:
            # (observed_value - value_calculated_form_model)^2*1/nr_time_steps
            # Achtung: Geht davon aus, dass alle Zeitschritte gleich lang sind.
            # Muss für variable Schrittweite ggf. angepasst werden.
            # P_in
            expr += ((data['P_in'][t] - model.Boiler[1].P_in[t]) ** 2) * (1 / len(data['T']))
            # P_out
            expr += ((data['P_in'][t] - model.Boiler[1].P_out[t]) ** 2) * (1 / len(data['T']))
        return expr

    pest = parmest.Estimator(model_function, data, theta_names, objective_function)
    obj, theta = pest.theta_est()


def solve_model():
    """this represents a normal solve of the model, without parameter estimation."""
    instance = model_function()
    # solver
    result = SolverFactory('glpk').solve(instance, tee=True)
    print(result)

    # plotte Verbrauch, den die Anlagen erfüllen müssen
    plt.figure(1)
    plot(pd.Series(instance.demand.extract_values()), drawstyle='steps-post')
    plt.show();
    print('Demand')

    # plotte die bereitgestellte Leistung P_out der Anlagen 1(blau) und 2(orange)
    # der Verbrauch ist noch mal gepunktet dargestellt
    plt.figure(2)
    plot(pd.Series(instance.Boiler[1].P_out.extract_values()), drawstyle='steps-post')

    plot(pd.Series(instance.demand.extract_values()), 'k:', drawstyle='steps-post')
    plt.legend(['Boiler 1', 'demand'])
    plt.show();

    print(instance.Boiler[1].P_in.extract_values())
    print(instance.Boiler[1].P_out.extract_values())


# solve_model([])
parameter_estimation()
```

**Comment by DLWoodruff** [comment]
This particular error message is created by Pyomo and has to do with how you are trying to create a ConcreteModel starting from an abstract model. It is not a bug in parmest. In this case, I recommend changing to a ConcreteModel from the start, e.g.,
def model_function():
    instance= ConcreteModel()
    instance.T = Set(ordered=True, initialize=[0,1,2,3])
    instance.J = Set(initialize=[1])

After you fix that, there are a lot of other troubles (e.g., parmest wants to pass in the data, but you have it all hard-wired). If you need help, you should write to the Pyomo forum or send me an email directly, rather than opening an issue, though.

**Comment by DLWoodruff** [comment]
OK. There is a bug in Parmest concerning Vars on blocks and I want to do a major revision to take
care of it. I will start on it today, but it will take a few days.
