### ISSUE TITLE
Can CBC plugin now allow quadratic objective?

### ISSUE THREAD

**Issue by goroderickgo** [Pyomo/pyomo#1355]
It seems like CBC can accept MIQPs, but the Pyomo solver plugin raises an error because the solver is set to `quadratic_objective = False`. Does anyone know if the comments in the referenced lines have been addressed in newer versions of the CBC solver?

https://github.com/Pyomo/pyomo/blob/eeea54ec280ae04df438c5a20565e3b92afb8315/pyomo/solvers/plugins/solvers/CBCplugin.py#L164-L169

**Comment by mrmundt** [comment]
We have opened #1926 to track all CBC enhancement/feature requests and will close this issue.
