### ISSUE TITLE
Change name or symantics of expr.to_string()

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#136]
The name `to_string`suggests that the method should **return** a representation of itself as a string. However, this method behaves more like a `pprint` method because it prints the string (possibly to an output stream).

I think we should either change the name to match the behavior (e.g., something like `pprint`) or change the semantics of this method to something more in line with the current name.

**Comment by blnicho** [comment]
Looks like this was resolved in #272
