### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by LeoHenrik** [Pyomo/pyomo#1365]
Hi, today I tried to do a model in pyomo but all my parameter had the problem invalid syntax, model.rtmw_max= Param(model.lineas, initialize=dict(enumerate(bu)), bu is a vector with informacion and it had the same longest as model.lineas so I dont know what is the problem?. Someone can help me please.

**Comment by LeoHenrik** [comment]
i'm using python 3.7.7 and Pyomo 5.6.8

**Comment by blnicho** [comment]
Could you post your code and the full error message?

**Comment by LeoHenrik** [comment]
from __future__ import division
from pyomo.environ import *
from red.read import excel2net
from red.create import setbus, setbranch, branchnames, setvariable
from red.create1 import *
from red.makePTDF import makePTDF
from red.makeBdc import makeBdc
from utils.arr2dict import arr2dict
from pyomo.environ import SolverFactory
from numpy import zeros, array

def setmodel(file):
        
    # ============================================================================
    # Importación de datos desde archivo Excel
    # ============================================================================

    #Parametros de la linea
    print("Inicio del Script ")
    print("Leyendo información ...")
    net = excel2net(file)
    bus = setbus(net)#Nodos
    branch = setbranch(net, bus)#Set lineas
    bu = branch[:, 5]/100#max
    bl = branch[:, 6]/100#min
    xc = branch[:,3]/100
    nb = bus.shape[0] #Numero de nodos
    nbr = branch.shape[0]#Numero de lineas
    A = makeBdc(bus, branch)#Matriz 
    inc = A.toarray()*-1

    #Funcion leer parametros oferta de oportunidad inyeccion
    ex_ooi = readofertas_ooi(file)
    vooi_m=VOOI_M(bus,ex_ooi)#Ofertas con respecto al nodo
    p_ooi= setvariable(ex_ooi['precio_ooi'])#Precio de la ofertas
    nex_ooi = ex_ooi.shape[0]#Numero de ofertas de inyeccion

    print("Leyendo información de ofertas")
    #Funcion leer parametros oferta de oportunidad retiro
    ex_oor = readofertas_oor(file)
    voor_m=VOOR_M(bus,ex_oor)#Ofertas con respecto al nodo
    p_oor= setvariable(ex_oor['precio_oor'])#Precio de la ofertas - flexibilizacion
    nex_oor = ex_oor.shape[0]#Numero de ofertas de retiro

    # Inicio del modelo de optimización
    model=ConcreteModel()

    #sets
    model.nodos= Set(initialize=range(0, nb))#numero de nodos
    model.lineas= Set(initialize=range(0, nbr))#Numero de lineas
    model.n_foo_r = Set(initialize=range(0, nex_oor))#numero de ofertas de retiro
    model.n_foo_i = Set(initialize=range(0, nex_ooi))#numero de ofertas de inyeccion

    #Parametros

    # Parametros de la red
    model.rtmw_min= Param(model.lineas, initialize=dict(enumerate(bl))
    model.rtmw_max= Param(model.lineas, initialize=dict(enumerate(bu))
    model.Inc = Param(model.lineas, model.nodos, initialize=arr2dict(inc))
    model.xc = Param(model.lineas, initialize=dict(enumerate(xc))

    #Oferta de oportunidad de retiro
    model.fr= Param(model.n_foo_r, initialize=dict(enumerate(p_oor))#Oferta bloques 1
    model.pr_ofertado = Param(model.n_foo_r, model.nodos, initialize=arr2dict(inc))#Magnitud de la oferta MW-h

    #Oferta de oportunidad de inyeccion
    model.fi= Param(model.n_foo_i, initialize=dict(enumerate(p_ooi))#Precio de bloques - Oferta de oportunidad de inyeccion
    model.pi_ofertado= Param(model.n_foo_i, model.nodos, initialize=arr2dict(vooi_m))#Magnitud de la oferta MW-h

    #Variabeles
    model.pr= Var(model.n_foo_r, domain=NonNegativeReals)#Parte aceptada de cada bloques de las ofertas de oportunidad de retiro
    model.pi= Var(model.n_foo_i, domain=NonNegativeReals)#Parte aceptada de cada bloques de las ofertas de oportunidad de inyeccion
    model.inyeccion= Var(model.nodos)
    model.retiros= Var(model.nodos)
    model.ref_angular= Var(model.nodos, default=0.0)

    print("Ecuación de Función Objetivo Max")
    def objfunc(model):
        return  sum(model.fr[i,h])*sum(model.pr[i]) - sum(model.fi[j,h])*sum(model.pi[j])
        for i in model.n_foo_r 
        for j in model.n_foo_i 
        for h in model.nodos
    model.OBJ= Objective(rule=objfunc, sense=maximize)

    print("Restricciones del Modelo de Optimización")

    def pi_restriccion(model):
        return (model.pi[i]<=model.pi_ofertado[i]
        for i in model.n_foo_i)#numero de ofertas de contratos firmes
    model.pi_constraint= Constraint(rule=pi_restriccion)

    def pr_restriccion(model):
        return (model.pr[i]<=model.pr_ofertado[i]
        for i in model.n_foo_r)
    model.pr_constraint= Constraint(rule=pr_restriccion)

    print('Restricciones de tranmision')
    #Restricciones de transmision
    def inyec(model,nodos):
        return (model.inyeccion_nodos[nodos]  == sum(model.pi[i,nodos])
        for i in model.n_foo_i
    model.inyec_constraint= Constraint(model.nodos,rule=inyec)

    def retiro(model,nodos):
        return (model.retiro[nodos] == sum(model.pr[i,nodos])
        for i in model.n_foo_r
    model.retiro_constraint= Constraint(model.nodos,rule=retiro)

    #Los multiplicadore o variable duales de esta restriccion son los precios nodales
    def balance_inyeccion_retiro(model,nodos):
        return (model.inyeccion_nodos[nodos] +  inc[lineas,nodos]*model.rtmw_c[lineas] == mode.retiro[nodos]
        for lineas in model.lineas)
    model.balance_inyeccion_retiro= Constraint(model.nodos,rule=retiro)

    def rtmw_restriccion(model):
        return (model.rtmw_min[lineas]<=model.rmtw[lineas]<=model.rtmw_max[lineas]
        for lineas in model.lineas)
    model.rtmw_constraint= Constraint(rule=rtmw_restriccion)


    def flujo_potencia_actica(model,nodos):
        return (model.xc[linea]*model.rtmw[lineas]+sum(inc[nodos,lineas])*model.ref_angular[nodos]
        for lineas in model.lineas)
    model.flujo_potencia_actica_constraint= Constraint(model.nodos,rule=flujo_potencia_actica)

    model.dual = Suffix(direction=Suffix.IMPORT)

    print("Construcción del modelo terminada.")

    opt = SolverFactory('ipopt')
    results = opt.solve(instance) # solves and updates instance
    instance.display()

    
    # Cálculo de Precios Nodales
    # =============================================================================
    print("Calculando Precios Nodales")

    Sigma = zeros(nb)
    for c in model.nodos:
        Sigma[c] = model.dual[model.balance_inyeccion_retiro[c]]

    Lambda = model.dual[model.balance_inyeccion_retiro]

    PON = (H.T @ Sigma) + Lambda
return 0

**Comment by LeoHenrik** [comment]
The parameter what you see with dict(enumerate(var)) the variable what that have var is a row vector, and the other with arr2dict is a function what make one array in a dictionary . All my error is 

    model.rtmw_max= Param(model.lineas, initialize=dict(enumerate(bu))
        ^
SyntaxError: invalid syntax

**Comment by blnicho** [comment]
It's a Python syntax error. You're missing a close parenthesis on all of your Param declaration lines. Should be:
   `model.rtmw_max= Param(model.lineas, initialize=dict(enumerate(bu)))`

**Comment by LeoHenrik** [comment]
Thanks yestedar i was vey tierd i could see that problem.

ERROR: Constructing component 'pr_ofertado' from data=None failed: KeyError:
    "Index '(2, 0)' is not valid for indexed component 'pr_ofertado'" 

Do you understand that problem??'
