### ISSUE TITLE
Network expansion fails with port variables using indexed sets

### ISSUE THREAD

**Issue by sbruche** [Pyomo/pyomo#1369]
I encountered a problem when assigning variables with indexed sets to ports and calling the network expansion (pyomo version 5.6.9). In this case the ExpandArcs class detects mismatched indices on the ports and raises an error:

> line 186, in _validate_and_expand_port_set
>     if v[1] >= 0 and len(v[0].index_set() ^ _v.index_set()):
> TypeError: unsupported operand type(s) for ^: '_IndexedSetData' and '_IndexedSetData'

See the following test code below:

```
import pyomo.environ as pyomo
import pyomo.network as network

m = pyomo.ConcreteModel()

idx = {0: [(0, 0), (1, 0), (2, 0)],
       1: [(3, 1), (4, 1), (5, 1)]}

m.steps = pyomo.Set(initialize=[stp for slc in idx for stp in idx[slc]])
m.slices = pyomo.Set(initialize=idx.keys(), ordered=True)
m.idx = pyomo.Set(m.slices, within=m.steps, initialize=idx)

# Block 0 with outlet port
m.c_0 = pyomo.Block()
m.c_0.add_component('OUT', network.Port())
def subblock_c_0_rule(b, slc):
    b.X = pyomo.Var(b.model().idx[slc], within=pyomo.NonNegativeReals)
    port = b.parent_block().OUT
    port.add(b.X, 'X_%s' % slc, port.Extensive)
m.c_0.subblocks = pyomo.Block(m.slices, rule=subblock_c_0_rule)

# Block 1 with inlet port
m.c_1 = pyomo.Block()
m.c_1.add_component('IN', network.Port())
def subblock_c_1_rule(b, slc):
    b.X = pyomo.Var(b.model().idx[slc], within=pyomo.NonNegativeReals)
    port = b.parent_block().IN
    port.add(b.X, 'X_%s' % slc, port.Extensive)
m.c_1.subblocks = pyomo.Block(m.slices, rule=subblock_c_1_rule)

m.add_component('arc', network.Arc(src=m.c_0.OUT, dest=m.c_1.IN))
# m.pprint()
pyomo.TransformationFactory("network.expand_arcs").apply_to(m)
```

Right now I'm using a workaround to run the model by delaring the port variables with newly defined sorted python sets, but I guess this is not how it is suppposed to be done:

```b.X = pyomo.Var(sorted(set(b.model().idx[slc])), within=pyomo.NonNegativeReals)```

**Comment by jsiirola** [comment]
The Set rewrite fixed set operations on indexed sets.  This example runs cleanly on master.
