### ISSUE TITLE
parse output and write Pyomo plugin for MIPCL 

### ISSUE THREAD

**Issue by chenhuims** [Pyomo/pyomo#138]
Hi experts, 

I am using MIPCL (http://mipcl-cpp.appspot.com/) as a solver to solve mixed integer linear programing problems. But I have hard time to parse the solution into a table format so that I can clearly see the optimal value for each parameter. The reason is due to that MIPCL is not supported in SolverFactory(). Is there a better way to parse the output of the solution? Moreover, I am considering to write a plugin for MIPCL so that it can be directly invoked by SolverFactory(). But this seems to be a very difficult task. Any instructions around this aspect would be really appreciated. 

Best,
Chenhui

**Comment by ghackebeil** [comment]
Great! We would be happy to accept a new solver interface. The most time consuming part of this is definitely parsing whatever solution format that solver writes (or extracting it from some object if you are using a Python interface to the solver). Look at the `_load` method of the ASL [sol](https://github.com/Pyomo/pyomo/blob/master/pyomo/opt/plugins/sol.py) file parser for an example of what kind of things need to go into the "results object".

Rather than try to figure out the plugin system, I would suggest to organizing everything into a single function that does the following:

```python
def solve(model):
    # write the model to a file
    _, smap_id = model.write('test.mps')

    # launch the solver using something like an os.system call (assuming it's an external shell program)
    rc = os.system('mipcl test.mps')
    assert rc == 0

    # parse the solution into a results object
    results = SolverResults()
    results._smap_id = smap_id
    ...

    # load the solution
    model.solutions.load_from(results)
```

Assuming that all works, we could easily reorganize it into a solver plugin. Note that the `smap_id` step will enable you to store the results under the names used in the MPS / solver solution file, and the `load_from` step will automatically map those names to the modelling components they are associated with. At a minimum, you would just need to store solution values of the primal variables in the results object (but you could extend this to other information using suffixes).

**Comment by chenhuims** [comment]
Thanks a lot for the instruction! I agree that writing a single function to parse the solution could be simpler. However, the solution file stores the values of the parameters as a list of pairs like "x001  200". I could not figure out the mapping between the name "x001" and the variable that I define in Pyomo file. 

Btw, I can't directly run `_, smap_id = model.write('test.mps')` but instead can first use `model.create_instance()` to create an instance and then write the instance to .mps file with `instance.write()`. When I use `_, smap_id = instance.write()`, I can't get the mapping of the names and the value of `smap_id` is an integer.

**Comment by ghackebeil** [comment]
You don't need the mapping to write the parser. You just need to populate the results object with the solution associated with the symbols in the solution file. The mapping between these symbols and components on the model is stored in a symbol map (associated with `smap_id`) hidden somewhere on the model after it is written to a file (I don't know why we don't just return the symbol map). When the results object (tagged with the smap_id) gets loaded into the instance, it will use the symbol map associated with the `smap_id` to translate the "x001"-like symbols into objects on the model.

If for some reason you need to look at the symbol map, you can access it via `instance.solutions.symbol_map[smap_id]`.

If you want the file to be written using symbols more closely matching the names of components on the model, you can use pass the option `io_options={"symbolic_solver_labels": True}` into the `.write` method.

**Comment by chenhuims** [comment]
The problem is that for MIPCL I can't import solver by `solver = SolverFactory("mipcl", executable="C:\Program Files\MIPCL\mip\bin\mps_mipcl.exe", solver_io="lp", is_mip = True)
` and use `solver.solve(instance)` to solve the concert optimization problem defined by
`instance = model.create_instance("mydata.dat")`. 

I can only write the problem to a .mps file using `instance.write("myproblem.mps")` and solve it using the windows command `mps_mipcl myproblem.mps`.

**Comment by ghackebeil** [comment]
Pyomo solver interfaces (things that get returned from `SolverFactory`) work by (1) writing the model to a file, (2) invoking the solver with the file as input (you can do this with one of a few Python modules, e.g., `os.system('mps_mipcl myproblem.mps')`, or see the [subprocess](https://docs.python.org/2/library/subprocess.html) module if [os.system](https://docs.python.org/2/library/os.html#os.system) does not work on Windows), and (3) parsing the solver solution file into a results object.

What I have said is that writing the code for step (3) is the most time consuming part. Once that is done, we can easily reorganize the code into something that gets returned by `SolverFactory`. The example code I provided did steps (1) and (2), except you would replace 'mipcl test.mps' with 'mps_mipcl test.mps'.

**Comment by onebitbrain** [comment]
@ghackebeil @chenhuims any progress on this?  Here are some example mps files and corresponding solution files.  It seems parsing this would be relatively straight forward.  1st line is objective, followed by unordered columns value if feasible.  Also this is all kwds args.
![kwds](https://user-images.githubusercontent.com/4357912/27712137-e10cb318-5ce2-11e7-910c-05d68a989f8d.PNG)






[infeas.mps.txt](https://github.com/Pyomo/pyomo/files/1113604/infeas.mps.txt)
[infeas.sol.txt](https://github.com/Pyomo/pyomo/files/1113605/infeas.sol.txt)
[slpmd4.mps.txt](https://github.com/Pyomo/pyomo/files/1113606/slpmd4.mps.txt)
[slpmd4.sol.txt](https://github.com/Pyomo/pyomo/files/1113607/slpmd4.sol.txt)
[slpmd5.mps.txt](https://github.com/Pyomo/pyomo/files/1113609/slpmd5.mps.txt)
[slpmd5.sol.txt](https://github.com/Pyomo/pyomo/files/1113608/slpmd5.sol.txt)

**Comment by jsiirola** [comment]
MIPCL appears to have been removed and is no longer distributed.  Closing this issue.
