### ISSUE TITLE
Error with TransformationFactory('core.relax_integers')

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#1383]
When I use `TransformationFactory('core.relax_integrality').apply_to(m)`, a warning came up.

`WARNING: DEPRECATED: core.relax_integrality is deprecated.  Use core.relax_integers  (deprecated in TBD)`

When I changed the code to `TransformationFactory('core.relax_integers').apply_to(m)`, an error came up:

```
TransformationFactory('core.relax_integers').apply_to(m)
AttributeError: 'NoneType' object has no attribute 'apply_to'
```

**Comment by qtothec** [comment]
That's a typo. Try `core.relax_integer_vars`.

**Comment by qtothec** [comment]
@jsiirola Would it be difficult for `TransformationFactory` to return an object that raises an error listing the valid transformations if you happen to give it an invalid argument, instead of returning `None`, as it currently does?

**Comment by jsiirola** [comment]
@qtothec: I don't think that something that provides a more informative error would be too difficult to implement; we already do something similar for the `SolverFactory`.  I will submit two PR's: the first will fix the typo in the deprecation warning (and I expect it will be reviewed / merged quickly).  The second will draft the change to the TransformationFactory, which will probably have a longer discussion/review process.
