### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'is_expression_type'

### ISSUE THREAD

**Issue by armaghan7bhr** [Pyomo/pyomo#1400]
I'm trying to calculate the temperature along a pipeline by using 2 for loops, one for time and one for different points along the pipe. and finally, I get (return) the outlet temperature of the pipe (which is at n_nodes=2500000 or the last point in self.block.all_x) 
This is a part of my code:
```
            self.block.all_time = Set(initialize=range(n_steps), ordered=True)
            self.block.all_x = Set(initialize=range(1, self.n_nodes + 1), ordered=True)
```

Then I've defined the variables as:

`           self.block.temperature_out_cv = Var(lines, self.block.all_time, self.block.all_x)`

And finally, we have the calculation of the temperatures at different times:
```
            for j in self.block.all_x:
                def _bc_temp_out(b, l, t):
                    if mass_flow.all() == 0:
                        return Constraint.Skip
                    elif t == 0:
                        return b.temperature_out_cv[l, t, j] == float(self.params['temperature_init_cv_' + l].v())
                    else:
                        for i in range(t+1):
                            if i == 0:
                                b.temperature_out_cv[l, i, j] = float(self.params['temperature_init_cv_' + l].v())
                            else:
                                if j == 1:
                                    return b.temperature_out_cv[l, i, j] == (b.temperature_out_cv[l, i - 1, j] + b.u[
                                        i] * time_step / self.params['delta_x'].v() * b.temperatures[l, i]
                                                                     + time_step / Z * Tg[i]) / (
                                                                            1 + b.u[i] * time_step / self.params[
                                                                        'delta_x'].v()
                                                                            + time_step / Z)
                                else:
                                    return b.temperature_out_cv[l, i, j] == (b.temperature_out_cv[l, i - 1, j] + b.u[
                                        i] * time_step / self.params['delta_x'].v() * b.temperature_out_cv[
                                                                         l, i, j - 1]
                                                                     + time_step / Z * Tg[i]) / (
                                                                            1 + b.u[i] * time_step / self.params[
                                                                        'delta_x'].v()
                                                                            + time_step / Z)

                self.block.add_component('_bc_temp_out' + str(j), Constraint(lines, self.block.all_time, rule=_bc_temp_out))
```

but I get the error below:

```
ERROR: Rule failed when generating expression for constraint
  File "C:\Users\Armaghan Bhr\Anaconda3\envs\dhopt\lib\site-packages\pyomo\core\base\constraint.py", line 779, in construct
    bbThor._bc_temp_out1 with index ('supply', 1): AttributeError: 'Series'
    ndx)
    object has no attribute 'is_expression_type'
ERROR: Constructing component 'bbThor._bc_temp_out1' from data=None failed:
  File "C:\Users\Armaghan Bhr\Anaconda3\envs\dhopt\lib\site-packages\pyomo\core\base\misc.py", line 57, in apply_indexed_rule
    return rule(model, *index)
  File "C:\Users\Armaghan Bhr\Desktop\modesto-master\modesto\pipe.py", line 1723, in _bc_temp_out
    AttributeError: 'Series' object has no attribute 'is_expression_type'
    + time_step / Z * Tg[i]) / (
  File "C:\Users\Armaghan Bhr\Anaconda3\envs\dhopt\lib\site-packages\pyomo\core\expr\numvalue.py", line 772, in __add__
    return _generate_sum_expression(_add,self,other)
  File "C:\Users\Armaghan Bhr\Anaconda3\envs\dhopt\lib\site-packages\pyomo\core\expr\numeric_expr.py", line 1720, in _generate_sum_expression
    if not (_other.__class__ in native_types or _other.is_expression_type()):
  File "C:\Users\Armaghan Bhr\Anaconda3\envs\dhopt\lib\site-packages\pandas\core\generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'is_expression_type'
```

**Comment by blnicho** [comment]
What are the data types of `time_step`, `Z`, and `Tg[i]`? Based on the error I'm guessing one of those is a pandas data series object(and not a numeric value) which can't be used directly in a Pyomo expression.

**Comment by armaghan7bhr** [comment]
According to the code below, Tg is a pandas series, but after getting this as a weatherdata parameter, I used `Tg = self.params['Tg'].v()`. so it's not used directly and I cannot understand where the error comes.
` def create_params(self):
        params = Component.create_params(self)
        params.update({
            'diameter': DesignParameter('diameter',
                                        'Pipe diameter',
                                        'DN (mm)', mutable=True),
            'Tg': WeatherDataParameter('Tg',
                                       'Undisturbed ground temperature',
                                       'K'),`

[https://github.com/energyville/modesto/blob/master/modesto/parameter.py](url), here the weather data is defined as a time series parameter.
And later in the code, I have:

`        Tg = self.params['Tg'].v()
        time_step = self.params['time_step'].v()`

`        pipe_catalog = self.get_pipe_catalog()
        self.Rs = pipe_catalog['Rs']
        self.Di = pipe_catalog['Di']`

`            surface = np.pi * self.Di[dn] ** 2 / 4 
             self.cp = 4180 
            Z = surface * self.rho * self.cp * self.Rs`

and finally, to set up the model, I get the parameters below:
`  time_step = 300  
# Ambient temperature
    t_amb = ut.read_time_data(path=resource_filename('modesto', 'Data/Weather'),
                              name='extT.csv')

    # Ground temperature
    t_g = pd.Series(12 + 273.15, index=t_amb.index)`

**Comment by blnicho** [comment]
I recommend printing out each of the terms in your expression along with their types to confirm that they are what you expect. Any of the constants you're pulling from a pandas object should be resolving to `int` or `float` types. 

Issues on the Pyomo GitHub page are meant for bug-reports and feature requests. If you have modeling or implementation questions please ask them on the Pyomo forum or on StackOverflow.

**Comment by armaghan7bhr** [comment]
Thanks for your reply but when I print them, I still get the same error
