### ISSUE TITLE
Pyomo + Gurobi issue: ERROR: Solver (gurobi) returned non-zero return code (1)

### ISSUE THREAD

**Issue by rsg73** [Pyomo/pyomo#1404]
I am running a simple model with Pyomo using the Gurobi solver.  I am calling Gurobi with the following line:

`pyomo.SolverFactory('gurobi')`

I have two Win10 machines that have a nearly identical Anaconda + Gurobi config.  When I run the script on one machine, everything is fine and program produces the intended on-screen output (i.e. results).

**Results Machine 1:**

> Total Volume = 235000.0 gallons
> 
> Total Profit = 100425.0 dollars
> 
> Profit = 42.7 cents per gallon
> 
> Process finished with exit code 0

On the second machine, Gurobi is called correctly and a result file is produced with correct results.  
However, I receive the following message upon termination of the program.

**Results Machine 2:**

> ERROR: Solver (gurobi) returned non-zero return code (1)
> 
> ERROR: Solver log: The system cannot find the path specified. 
> 
> Using license
>     file C:\Users\xxxx\gurobi.lic Read LP format model from file
>     C:\Users\xxxx\AppData\Local\Temp\tmpo36tlpw_.pyomo.lp Reading time = 0.00
>     seconds x15: 16 rows, 15 columns, 71 nonzeros Gurobi Optimizer version
>     9.0.2 build v9.0.2rc0 (win64) Optimize a model with 16 rows, 15 columns
>     and 71 nonzeros Model fingerprint: 0x89b78bb0 Coefficient statistics:
>       Matrix range     [4e-02, 1e+02] Objective range  [5e-02, 2e+00] Bounds
>       range     [0e+00, 0e+00] RHS range        [1e+00, 7e+04]
>     Presolve removed 6 rows and 6 columns Presolve time: 0.00s Presolved: 10
>     rows, 9 columns, 38 nonzeros

    Iteration    Objective       Primal Inf.    Dual Inf.      Time
           0    1.1250000e+05   1.632750e+04   0.000000e+00      0s 4
           1.0042500e+05   0.000000e+00   0.000000e+00      0s

> Solved in 4 iterations and 0.00 seconds Optimal objective 
> 1.004250000e+05 Traceback (most recent call last):   
> 
> File "C:/xxxx/Python Projects/gasoline_optimization.py", line 81, in
> <module> solver.solve(m)   
> 
> File
> "C:\Users\xxxx\anaconda3\lib\site-packages\pyomo\opt\base\solvers.py",
> line 600, in solve "Solver (%s) did not exit normally" % self.name)
> pyutilib.common._exceptions.Application
> 
> Error: Solver (gurobi) did not exit normally

This error message is specific for Gurobi.  CBC does not generate these errors.  IPOPT does not generate these errors.  None of the solvers on my machine generate these errors - they all run without problems and generate the same result.

I have spent several hours investigating this issue and am out of ideas.  Things that have been ruled out are:

1.  Gurobi is installed in the proper location and the license is active
2.  All necessary paths have been added to Windows
3.  All permissions seem to be OK/Installation locations correct.
4.  Conda Environment is correct

The issue seems to be with the final log output.  While debugging it seemed to be related to the creation of the ".gurobi.log" file, which does not persist in the Temp location following the optimization.  

It appears that I lack the debugging chops to get to the bottom of this at the moment, so any input would be appreciated.

System: 

- Windows 10/Anaconda 4.8.3 (Python 3.7)
- Pyomo 5.6.9
- Gurobi 9.02

Thanks

**Comment by mrmundt** [comment]
Hello, @rsg73. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
