### ISSUE TITLE
Allow SOS constraints in CBCPlugin

### ISSUE THREAD

**Issue by Yaevon** [Pyomo/pyomo#1406]
Since at least version 2.9.9 (oldest binaries I tested with) cbc handles both SOS1 and SOS2 constraints in .lp files
CBCPlugin disables them by default, explicitly commenting about it; that's from years ago

https://github.com/Pyomo/pyomo/blob/766f81aebbce51249e29dc88280a68b351344d4c/pyomo/solvers/plugins/solvers/CBCplugin.py#L170-L174

Can we enable SOS1, SOS2 either by default, or if cbc version is greater than some tested version?

**Comment by mrmundt** [comment]
We have opened #1926 to track all CBC enhancement/feature requests and will close this issue.
