### ISSUE TITLE
Confuse the `EnforceQuotas_rule ` in Birge and Louveaux’s Farmer Problem

### ISSUE THREAD

**Issue by YMMS** [Pyomo/pyomo#1408]
Hello, I am fresh man to use AMLs with pyomo.

Currently, I read the tutorial about [Stochastic Programming](https://pyomo.readthedocs.io/en/stable/modeling_extensions/pysp.html).

In section `ReferenceModel.py`, how to understand a rule return a tuple and what is the purpose:
```
def EnforceQuotas_rule(model, i):
    return (0.0, model.QuantitySubQuotaSold[i], model.PriceQuota[i])

model.EnforceQuotas = Constraint(model.CROPS, rule=EnforceQuotas_rule)
```

Thx in advance.

**Comment by jsiirola** [comment]
See the [Constraint online documentation](https://pyomo.readthedocs.io/en/stable/pyomo_modeling_components/Constraints.html)

**Comment by YMMS** [comment]
> See the [Constraint online documentation](https://pyomo.readthedocs.io/en/stable/pyomo_modeling_components/Constraints.html)

@jsiirola Thanks for yours kindly replay. I get your guidance as follow:
```
model.x = Var()

def aRule(model):
   return model.x >= 2
model.Boundx = Constraint(rule=aRule)

def bRule(model):
   return (2, model.x, None)
model.boundx = Constraint(rule=bRule)
```
So the function：
```
def EnforceQuotas_rule(model, i):
    return (0.0, model.QuantitySubQuotaSold[i], model.PriceQuota[i])
```
is equivalent to：

0 <= `model.QuantitySubQuotaSold[i]` <= `model.PriceQuota[i]`
