### ISSUE TITLE
Defining Integer Variables in Model Files - Documentation Issue

### ISSUE THREAD

**Issue by jcforaker** [Pyomo/pyomo#141]
According to your online user guide (https://software.sandia.gov/downloads/pub/pyomo/PyomoOnlineDocs.html#_variables), you mention using domain=PositiveInteger for integer variables and within=NonNegativeReals for continuous variables.  It would be nice for you to include within=NonNegativeIntegers for integer variables in your documentation.  I had issues when I tried to use PositiveInteger in my model file.

**Comment by blnicho** [comment]
This information is already included in the online user guide under the heading "Predefined virtual sets" (https://software.sandia.gov/downloads/pub/pyomo/PyomoOnlineDocs.html#_predefined_virtual_sets)
