### ISSUE TITLE
Solver (baron) returned non-zero return code (1)

### ISSUE THREAD

**Issue by hamta** [Pyomo/pyomo#1414]
I install Baron solver on windows and I use pyomo in Spyder. I move baron.exe to current directory.
My invocation is like this:

  ```
  from pyomo.opt import SolverFactory
     ...
    opt = SolverFactory('baron') 
    opt.solve(instance,keepfiles=True,tee=True)
```

when I run my code, this error appears:

   ```
 Solver log file: 'C:\Users\~\AppData\Local\Temp\tmpumg5hxvr.baron.log'
    Solver solution file: 'C:\Users\~\AppData\Local\Temp\tmpbmx1pfpt.baron.soln'
    Solver problem files: ('C:\\Users\\~\\AppData\\Local\\Temp\\tmpygo80gcy.pyomo.bar',)
    C:\Users\~\baron.exe: can't open C:\Users\~\AppData\Local\Temp\tmpygo80gcy.pyomo.bar.nl
    ERROR: Solver (baron) returned non-zero return code (1)
    ERROR: See the solver log above for diagnostic information.
    Traceback 
    ApplicationError: Solver (baron) did not exit normally
```

But There is not the log file: `C:\Users\~\AppData\Local\Temp\tmpumg5hxvr.baron.log`
How can I fix this problem?
Thanks for your helps in advance.

**Comment by mrmundt** [comment]
Hello, @hamta. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
