### ISSUE TITLE
Issues creating sets of nested tuples

### ISSUE THREAD

**Issue by Chuck-a-Knight** [Pyomo/pyomo#142]
I believe I've found an issue when trying to create sets using nested tuples as set elements. In the code below I create a list of tuples containing tuples as elements:

from pyomo.environ import *
from pyomo.opt import SolverFactory
import sys

model = ConcreteModel()
CHOICES = [((1,2,3), 4,3), ((1,2,2), 4,3), ((1,3,3), 4,3)]
print(CHOICES)
model.CHOICES = Set(initialize=CHOICES)
print("Model creation complete.")
model.write(filename='bug.lp', io_options={'symbolic_solver_labels':True})
exit(0)

When I try to run this code I get the following error:

WARNING: converting to the 'pyomo solve' subcommand
[    0.00] Setting up Pyomo environment
[    0.00] Applying Pyomo preprocessing actions
[((1, 2, 3), 4, 3), ((1, 2, 2), 4, 3), ((1, 3, 3), 4, 3)]
ERROR: Constructing component 'CHOICES' from data=None failed:
        ValueError: The value=(1, 2, 3, 4, 3) does not have dimension=3, which is needed for set=CHOICES
[    0.01] Pyomo Finished
ERROR: Unexpected exception while loading model:
        The value=(1, 2, 3, 4, 3) does not have dimension=3, which is needed for set=CHOICES

I didn't see anything in the documentation forbidding this, did I miss something?

**Comment by jsiirola** [comment]
In this case, you have to inform the `Set` of the dimensionality of the data (although you shouldn't need to).  Specifying `dimen=None` correctly disables the error checking. However, I would also expect specifying dimen=5 to work, and it doesn't:
```
ValueError: Dimension argument differs from the data in the initialize list
```

**Comment by Chuck-a-Knight** [comment]
It seems that the solution just pushes the issue father into the model. The code below illustrates how this forces all method calls to use a linearized version of the arguments. 

from pyomo.environ import *
from pyomo.opt import SolverFactory
import sys

model = ConcreteModel()

CHOICES = [((1,2,3), 4,3), ((1,2,2), 4,3), ((1,3,3), 4,3)]
print(CHOICES)

model.S_CHOICES = Set(dimen=None, initialize=CHOICES)
print("Set creation complete.")

# Note that a is a 3-tuple, but because Pyomo throws away information about nested tuples
# during its creation this fails
#def Bounds_rule(model, a, b, c):
#    return (0, model.PI_MAX_NUM_CARGOES[tsc])
# But this works (and is ugly)
def Bounds_rule(model, a1, a2, a3, b, c):
    return (0, b)
model.V_CHOICES = Var( \
	model.S_CHOICES, \
    within=NonNegativeIntegers, \
    bounds=Bounds_rule)
print("Variable creation complete.")

# And so the issue propagates and the constraint method needs to be linearized 
#def Constraint_rule(model, a, b, c):
#    if a[0] != a[1]:
#    	return Constraint.Feasible
#    else:
#    	return Constraint.Infeasible    		
def Constraint_rule(model, a1, a2, a3, b, c):
    if a1 != a2:
    	return Constraint.Feasible
    else:
    	return Constraint.Infeasible    		
model.C_CHOICES = Constraint( \
	model.S_CHOICES, \
    rule=Constraint_rule)

def Objective_rule(model):
    return sum(model.V_CHOICES[a] for a in model.S_CHOICES)
model.objective = Objective(rule=Objective_rule, sense=maximize)

model.write(filename='bug.lp', io_options={'symbolic_solver_labels':True})
exit(0)

**Comment by jsiirola** [comment]
That is expected behavior.
