### ISSUE TITLE
Give starting values for a solution?

### ISSUE THREAD

**Issue by Fernando3161** [Pyomo/pyomo#1425]
Hello! 
I am looking to give starting values to optimization problems, with the goal of reducing calculation times.

Is there a guideline or a tutorial for this issue?

Regards
FP

**Comment by jsiirola** [comment]
See https://pyomo.readthedocs.io/en/stable/working_models.html#warm-starts.

GitHub issues are intended to support the development of Pyomo (bug reports, feature requests, etc).  In the future, please direct user support / modeling questions either to the mailing list (pyomo-forum@googlegroups.com) or StackOverflow.
