### ISSUE TITLE
Pyomo performance enhancement list

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#1430]
# List of Open Pyomo Performance Enhancement Ideas

This issue compiles individual ideas for improving Pyomo's overall performance.  Each idea is tied to a (closed, but unresolved) issue where discussion specific to that idea is archived.  The intent is that when an idea will receive active developer attention, that issue will be re-opened.

## Expressions 
- #1202: Re-evaluate the need for NPV expression objects 
- #1184: Define custom expression objects to short-circuit common checks 
- #1161: Using Python macros to accelerate Pyomo expression kernels 
- ▶️ #1153: Expression templates 
- #1073: Revisit design of method used to create the canonical repn 
- #324: Reconsider performance of expressions with many constants 

## Solver interfaces 
- ▶️ #1169: with cplex, solver_io='python' is much slower than executable=(solver_path)
- #1160: Fast(er) direct solver interfaces 
- #1158: Use C/C++ extensions for file writers 
- #1154: "automatic" persistent solvers 
- #1151: Improve the NL writer 
- #251: Huge memory consumption while generating model file 
- #177: Enable creating of NL files with binary data 
- #1030: Redesign of Pyomo Solvers 
- #677:  Shift to using unsorted problem files with Python 3.6 and later 
- #106: Fast serialization of solutions to/from disk 

## Modeling components 
- #1203: Add "compiled" model support 
- #1192: Implement Parallel Blocks 
- #1165: Investigate "array-like" components
- #1159: Matrix/Vector Representations 

## Packaging and distribution 
- ▶️ #1178: Pyomo installation with Cython 

## Other 
- #1157: Profile Pyomo.DAE and identify bottlenecks
- #1156: Testing Performance

**Comment by bernalde** [comment]
Hi, I just wanted to make you aware of this technical report recently published by independent researchers https://www.mii.lt/files/doc/lt/doktorantura/ataskaitine_konferencija/n009_ma_2020_jusevicius.pdf
Contrary to what was shown in the JuMP paper, Pyomo is not trailing that badly behind other AMLs. They have a Github repository where they used the GAMS Model library to benchmark AMPL, GAMS, AIMMS, JuMP and Pyomo https://github.com/vaidasj/alg-mod-rev

**Comment by carldlaird** [comment]
Thanks, @bernalde.

**Comment by jsiirola** [comment]
This issue has been superseded by the corresponding wiki page: https://github.com/Pyomo/pyomo/wiki/Performance-enhancement-ideas
