### ISSUE TITLE
Pynumero Organization

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1434]
I would like do the following reorganization in pynumero:

- move `pynumero/extensions/ma27_interface.py` to `pynumero/linalg/ma27_interface.py`
- move `pynumero/extensions/ma57_interface.py` to `pynumero/linalg/ma57_interface.py`
- move `pynumero/extensions/tests/test_ma27_interface.py` to `pynumero/linalg/tests/test_ma27_interface.py`
- move `pynumero/extensions/tests/test_ma57_interface.py` to `pynumero/linalg/tests/test_ma57_interface.py`
- move `pynumero/extensions/asl.py` to `pynumero/asl.py` (we may need a directory for this later, but I don't think we do right now)
- remove `pynumero/extensions` (including the `lib` directory)

**Comment by michaelbynum** [comment]
@Robbybp @jsiirola @carldlaird @santiagoropb Thoughts/opinions?

**Comment by carldlaird** [comment]
This seems reasonable to me.

**Comment by jsiirola** [comment]
I think that makes sense.  In addition, what do you think of:
- rename `ma27_interface.py` to `ma27.py` (similar rename of the test module)
- rename `ma57_interface.py` to `ma57.py` (similar rename of the test module)
- rename `mumps_solver.py` to `mumps.py` 

...the argument being consistency between the 3 linear solvers.  I could be convinced of a different naming convention for the three linalg interfaces, as there is a '`mumps`' module from pymumps, and I have slight concerns about duplicating the module name (as we have seen confusion from users when the same thing happened in pyutilib).

**Comment by michaelbynum** [comment]
I think the renaming you suggested is a good idea. I'm not terribly concerned about duplicating the `mumps` name here, because the API is very different from that of pymumps. As soon as anyone tries using the module, that should be clear.
