### ISSUE TITLE
Ipopt error: Unknown keyword "hessian_constant"

### ISSUE THREAD

**Issue by sartorg** [Pyomo/pyomo#144]
Using Ipopt 13.2.6 with Pyomo 5.1.1. and Python 2.7.10 gives me the following error when trying to add the option `hessian_constant = yes` (see list of options [here](https://www.coin-or.org/Ipopt/documentation/node44.html)):

```
linear_solver=ma27
Unknown keyword "hessian_constant"
max_iter=1000
max_cpu_time=20
honor_original_bounds=no
acceptable_tol=0.001
linear_solver=ma27
Unknown keyword "hessian_constant"
max_iter=1000
max_cpu_time=20
honor_original_bounds=no
acceptable_tol=0.001
ERROR: "[base]/site-packages/pyomo/opt/base/solvers.py", 599, solve
	Solver (asl) returned non-zero return code (1)
ERROR: "[base]/site-packages/pyomo/opt/base/solvers.py", 602, solve
	See the solver log above for diagnostic information.
```

Couldn't find any reason why Pyomo should through this error.

**Comment by blnicho** [comment]
This looks like a bug. I can recreate this error when setting the 'hessian_constant' option from a Pyomo script but if I specify it from an ipopt.opt file, IPOPT recognizes it just fine. As a work-around, create a file called ipopt.opt, add the line "hessian_constant yes", and place the file in the same directory as your model file.

**Comment by ghackebeil** [comment]
This is not a bug with Pyomo or Ipopt. Ipopt only exposes a subset of its options through the command line. To see the list of available command-line options for Ipopt, one would type:
```bash
ipopt -=
```
To see the list of options available through an options file, one would type:
```bash
ipopt --print-options
```
Note that in the next Pyomo release (and this is currently available on master), you can prefix "options file only" Ipopt options with 'OF_' and the Ipopt solver plugin in Pyomo will automatically create a temporary options file and pass that to Ipopt. Any option not starting with 'OF_' will be passed as a command-line option.

**Comment by sartorg** [comment]
Thanks, nice to know about this improvement in the new release!
