### ISSUE TITLE
Add Xpress to our CI platforms

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#1444]
@bknueven pointed out that FICO distributes Xpress with a community license (5000 variable/constraint limit) on PyPI. We should add this community version to our testing harnesses on Travis, Github Actions, and Jenkins.

**Comment by jsiirola** [comment]
@mrmundt, can you take a look at getting this set up?

**Comment by mrmundt** [comment]
@jsiirola - Absolutely!
