### ISSUE TITLE
Command for pyomo nameserver is wrong in the Pyro doc part

### ISSUE THREAD

**Issue by aknaut** [Pyomo/pyomo#145]
In the pyro doc within pyomo (pyomo/doc/GettingStarted/current/pyro.txt) I think the following command is wrong: `pyomo-ns`

Instead it should be written `pyomo_ns` as mentioned in the scripting part.

**Comment by qtothec** [comment]
Thanks @aknaut. In the future, you can simply make the correction and open a pull request.

**Comment by jsiirola** [comment]
04ed57d resolved this (committed as part of PR #159)
