### ISSUE TITLE
How to learn pyomo quickly?

### ISSUE THREAD

**Issue by tuchao1996** [Pyomo/pyomo#1497]
recommend some source? thx

**Comment by qtothec** [comment]
You can consult:

- the Pyomo online documentation: https://pyomo.readthedocs.io/en/latest/
- the Pyomo book: https://www.springer.com/gp/book/9783319588193
- general math programming books
- StackOverflow: https://stackoverflow.com/questions/tagged/pyomo
- The users forum: https://groups.google.com/forum/#!forum/pyomo-forum
- the examples directory: https://github.com/Pyomo/pyomo/tree/master/examples
- external example repositories:
  - https://github.com/jckantor/ND-Pyomo-Cookbook
  - https://github.com/grossmann-group/gdplib

This venue is more for bug reports and other developer use.
