### ISSUE TITLE
Pysp package: can't load the data from the set declaration?

### ISSUE THREAD

**Issue by sjwj1314** [Pyomo/pyomo#1498]
I am working on the two-stage stochastic programming problem which takes the same scenario structure as the farmer examples.
In the code, the model.nodes should be the positive integers, and the model.feeders should be within the model.nodes. And I do include 1 to 9 in the model.nodes, but the error that value 1 is not within model.nodes always exist.
![图片](https://user-images.githubusercontent.com/44237395/84568804-8678be80-adb4-11ea-8c26-db02fea653cf.png)
I am very confused about the error message, and any suggestion is wanted. Thank you.

**Comment by DLWoodruff** [comment]
If you have a version of your files that you can send to me off the forum,
I will take a look at it.
  Best,
    Dave Woodruff

**Comment by sjwj1314** [comment]
It's a great honor for me to receive a reply from you, and thank you very much.
I am trying to work on the distribution system reconfiguration based on mobile emergency generators(MEGs) from a resilience perspective. The objective is minimizing the outage duration of loads caused by damaged branches.
To test the optimization model, the modified IEEE 9-bus system is applied.  After some debugging tries, I still can't address the error. And here are the entire files. [ver3(9bus)_simplified.zip](https://github.com/Pyomo/pyomo/files/4776065/ver3.9bus._simplified.zip)
Thanks for your support again.

**Comment by sjwj1314** [comment]
It's a great honor for me to receive your reply, and thank you very much.
I try to replace model.nodes = pyo.RangeSet(within=pyo.PositiveIntegers) with model.nodes = pyo.RangeSet(1,9), and the code is compiled successfully without any error message.
Thank you for your kind support again.
