### ISSUE TITLE
Change in scope causes x = 1 aliased Var value assignment to fail

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#15]
```
m = ConcreteModel()
m.x = Var(domain=Binary)
x = m.x
if x is not None:
    x.display()  # works properly
    x = 1
    x.display()  # error, because x is now an int
```
If I had used `x.value = 1`, this would not be a problem, but I recall @jsiirola telling me that the recommended usage was direct assignment, i.e. `x = 1` since there is talk of `value` changing to be a property. This would seem to be an unintentional consequence.

**Comment by jsiirola** [comment]
Unfortunately, this is not something that is fixable.  The `x = 1` line is parsed and processed by Python as a simple (Python) variable assignment.  There is no way for code to circumvent that behavior.  

I generally prefer:
`m.x = 1`
over
`m.x.value = 1`

The trick here is that `m.x = 1` hooks into the `Block`'s `__setattr__` method to direct the value to the component's (in this case, `Var`'s) `set_value()` method.  That method performs additional error checking, including domain / bounds checking.  The `m.x.value = 1` approach (currently) directly sets the `value` attribute, bypassing all error/consistency checking.
