### ISSUE TITLE
How to Change CPLEX Settings

### ISSUE THREAD

**Issue by jiaguo000** [Pyomo/pyomo#150]
I'm trying to change the cplex MILP gap. In command prompt, I typed "cplex", then hit "Enter". Then I typed "set mip tolerances absmipgap 0.05" to change the optimality gap to be 5%. However, when pyomo is solving the MILP, it still keeps the optimality gap 1e-006. I'm wondering how I can change the cplex parameter...

**Comment by jwatsonnm** [comment]
You just need to set the solver option (on the solver plugin) “mipgap_tolerances_absmipgap” to 0.05. The translation between CPLEX interactive to Pyomo is straightforward, if clunky.

jpw

**Comment by jiaguo000** [comment]
Thank you. But where is the solver plugin? Is it in the cplex software package I've installed? I can't find it...

**Comment by jwatsonnm** [comment]
Are you running from a python script, or from the pyomo command line utility?

Jpw

Sent from my iPad

On May 30, 2017, at 3:55 PM, jiaguo000 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you. But where is the solver plugin? Is it in the cplex software package I've installed? I can't find it...

-

**Comment by jiaguo000** [comment]
I'm running from a python script.

**Comment by qtothec** [comment]
I assume that you have in your code an invocation of SolverFactory in your script:
```
solver = SolverFactory('cplex')
solver.options['absmipgap'] = 0.05
```
I'm not sure on the naming of 'absmipgap', but I think you can probably figure it out.

This would make a good question on StackOverflow ;-)
https://stackoverflow.com/questions/ask?tags=pyomo

**Comment by jiaguo000** [comment]
Yes. I tried your method and it is solved now. Thank you :)
