### ISSUE TITLE
Pyomo gives a different solution from GAMS with same  CPLEX solver?

### ISSUE THREAD

**Issue by zwenju** [Pyomo/pyomo#1508]
Hi Pyomo Team,, Thanks First.

I try to solve a LP problem that may be have several solutions.
I found  GAMS gives a different from pyomo with same cplex solver .

I try to find out  the reasons.

Are there any example to  set the  cplex solver  parameter in PYOMO?
cplex has many algorithms to solve LP.
I want to set the specific  algorithm ( primial simplex algorithm)  in cplex.  

thanks a lot.

**Comment by jsiirola** [comment]
To be clear, by "different solutions", are you getting a different objective, or the same objective (within tolerance) and only a different solution vector (i.e., is the problem degenerate)?

First, Pyomo's CPLEX interface does not use the same executable as GAMS, so it is possible that the two solvers are not the same (same build or even same version).  Also, for degenerate problems, the exact solution you receive is determined by the solver's internal choices, and those choices are influenced by the order in which the variables and constraints are added to the solver.  We have no control over the GAMS interface to the solver, so there is no reason to believe that GAMS passes the constraints in the same order that Pyomo does, so there is no reason that it will return the same solution vector for degenerate problems.

Finally, for setting solver-specific options, please see https://pyomo.readthedocs.io/en/stable/working_models.html#sending-options-to-the-solver

**Comment by zwenju** [comment]
Great thanks,  the reason is what you mention.
