### ISSUE TITLE
How to set Pyomo solver timeout and return the optimal solution currently found?

### ISSUE THREAD

**Issue by zz23333** [Pyomo/pyomo#1512]
I'm using scip ampl as pyomo solver. Sometimes the solving process will fall into an endless loop, which means that the solving process will not stop. So, I set the timelimit to make it stop. 
But I want to know how the solver can return the optimal(feasible,infeasible) solution currently found. 
`solver = SolverFactory("scip")
solver.solve(model,timelimit=100)`
I use those codes to set timelimit, when it reaches the timelimit, no solutions returned.

I would appreciate if someone could give me some help!

**Comment by mrmundt** [comment]
Hello, @zz23333. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
