### ISSUE TITLE
All Different Constraint in Pyomo

### ISSUE THREAD

**Issue by sankalpsharmaa** [Pyomo/pyomo#1527]
As per my understanding, currently, there is no way to setup a constraint that programs variables to take different values from each other. All other major solvers like CPLEX and Gurobi have this functionality. Am I missing out on something or is there a genuine lack of this capability in status quo?

**Comment by jsiirola** [comment]
Please note that GitHub Issues are for reporting bugs, requesting features, and managing the evolution of the Pyomo codebase.  General user support questions should be directed either to the mailing list (pyomo-forum@googlegroups.com) or StackOverflow.

If you are referring to the `alldiff` constraint from Constraint Programming, you are correct: at the moment, Pyomo does not support that as an explicit operator.  That said, to my knowledge, neither does Gurobi or the CPLEX MIP solver.  In general, `alldiff` is an explicit constraint for Constraint programming solvers (like the CPLEX CP optimizer) and modeling environments that support CP solvers (like the AMPL constraint programming extensions).

Assuming that the variables you want to enforce `alldiff` over are discrete, there is a standard reformulation for expressing that to a MIP solver that uses N*M binares (where N is the number of variables and M is the number of discrete values that the variables may take)
