### ISSUE TITLE
How to access the dual solution of Baron in Pyomo?

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#1537]
I tried a small example to access the dual solution of Baron, but it doesn't work.
The code is the following:

```
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.x = Var()
>>> m.obj = Objective(expr=m.x ** 2)
>>> m.con = Constraint(expr=m.x >= 2)
>>> m.dual = Suffix(direction=Suffix.IMPORT)
>>> result = SolverFactory('baron').solve(m)
>>> m.dual.pprint()
dual : Direction=Suffix.IMPORT, Datatype=Suffix.FLOAT
    Key : Value

```
The dual is empty.

When I change the solver to GUROBI, the output is as expected.

```
>>> result = SolverFactory('gurobi').solve(m)
>>> m.dual.pprint()
dual : Direction=Suffix.IMPORT, Datatype=Suffix.FLOAT
    Key : Value
    con :   4.0
```

**Comment by ghackebeil** [comment]
I believe I have seen for some small test cases that Baron will not return a dual solution when the problem is solved within its presolve phase. This might be the case.

**Comment by ZedongPeng** [comment]
> I believe I have seen for some small test cases that Baron will not return a dual solution when the problem is solved within its presolve phase. This might be the case.

Thanks for your advice. Just now I tried several cases, `rsyn0805h, fac1, fac2, fac3, batchs201210m, ball_mk2_10, clay0203h, batch` in [MINLPlib](http://minlplib.org/instances.html). Only the batch example successfully returns the duals. Some of the other examples are not solved within its presolve phase but still didn't return the duals. It's a little uncontrollable and wired.

**Comment by ZedongPeng** [comment]
I checked the manual of Baron. There is one option to control the calculation of duals. However, it cannot guarantee that a dual solution will always be available.

![image](https://user-images.githubusercontent.com/15854830/86076050-66552a80-ba57-11ea-835d-0ecdf39e7fac.png)

**Comment by jsiirola** [comment]
@ZedongPeng, Thank you for digging  up that option!  I just submitted a PR (#1538) that adds that option any time a user requests dual or rc information (via a Suffix on the model), and that completely resolved the apparent "inconsistency" as to when Baron would return duals we were observing in our solver tests.
