### ISSUE TITLE
None with SolverManagerFactory('pyro')

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#1547]
I trying parallel solving in Pyomo.
When I tested the [solving-multiple-instances-in-parallel example ](https://pyomo.readthedocs.io/en/stable/working_models.html#solving-multiple-instances-in-parallel), solver_manager created in my computer is None and "Failed to create solver manager." is reported. Is there any other package I need to install to use `SolverManagerFactory('pyro')`?

Btw, the example is written in Python2. I would recommend updating it to Python 3.

**Comment by carldlaird** [comment]
@DLWoodruff Any thoughts on this one?

**Comment by Roytjoo** [comment]
Yeah does it have to do with the pyomo.extras, can anyone verify? source: https://stackoverflow.com/questions/46202299/solving-optimisation-sub-instances-in-parallel-using-pyomo-traceback

**Comment by ZedongPeng** [comment]
> Yeah does it have to do with the pyomo.extras, can anyone verify? source: https://stackoverflow.com/questions/46202299/solving-optimisation-sub-instances-in-parallel-using-pyomo-traceback

Hi Roy. Thanks a lot for your reply. I checked my Python environment. It didn't have `Pyro4` installed. After I installed it, the error is fixed.
