### ISSUE TITLE
Slow creation and high-memory consumption of a Pyomo model with exponential function

### ISSUE THREAD

**Issue by asuncionjc** [Pyomo/pyomo#1548]
Hi, everyone,

my name is [Asunción Jiménez-Cordero](https://www.researchgate.net/profile/Asuncion_Jimenez-Cordero) from the [Group OASYS](https://sites.google.com/view/groupoasys/home?authuser=0) in the University of Málaga (Spain).

My problem is explained below:

I have to solve an optimization problem which an objective function that has three nested sums as well as an exponential function. The constraints also requires the computation of an exponential function. The number of terms in the sum may be large. Therefore the resolution of the optimization problem is a challenge.

Below, I provide you a minimum working example (MWE):

```python
import pyomo.environ as pe
from pyomo.core.util import quicksum

def my_model_definition(number_of_features,
                                    number_of_time_periods,
                                    data_train,
                                     a_parameter):

  my_model = AbstractModel()
  
  # Parameters
  my_model.number_of_features = number_of_features
  my_model.number_of_time_periods = number_of_time_periods
  my_model.data_train = data_train # dimensions number_of_time_periods x number_of_features (This is a pandas dataframe)
  my_model.a_parameter = a_parameter # dimensions number_of_time_periods (This is a numpy array)

  # Indexes
  my_model.indexes_features = pe.RangeSet(my_model.number_of_features)
  my_model.indexes_time_periods = pe.RangeSet(my_model.number_of_time_periods)

  # Variables
  my_model.x_variables = pe.Var(my_model.indexes_features,
                               within=pe.NonNegativeReals)
  my_model.y_variables = pe.Var(my_model.indexes_time_periods,
                                within=pe.NonNegativeReals)

  
  my_model.objective_function = pe.Objective(rule = my_objective_function,
                                             sense = pe.minimize)
  my_model.constraint = pe.Constraint(my_model.indexes_time_periods,
                                     rule= my_constraint)

  return my_model

# Objective function:

def my_objective_function(my_model):
  objective_value = quicksum(args=[
            model.y[time_period_1] * model.y[time_period_2] * pe.exp(-quicksum(args=[
            ((my_model.data_train.iloc[feature - 1, time_period_1 - 1] -  my_model.data_train.iloc[feature - 1, time_period_2 - 1])**2)* model.x[feature] for
                feature in model.indexes_features], linear=False))
            for time_period_2 in model.indexes_time_periods
            for time_period_1 in model.indexes_time_periods], linear=False)
  return objective_value

# Let us formulate a toy example constraint:

def my_constraint(my_model,
                  time_period):
  left_hand_side  = sum(model.a_parameter[time_period_1 - 1] * model.a_parameter[time_period - 1] * pe.exp(-quicksum(
        args=[((my_model.data_train.iloc[feature - 1, time_period_1 - 1] -  my_model.data_train.iloc[feature - 1, time_period - 1])**2) * model.x[feature] for
              feature in model.indexes_features],
        linear=False)) * model.y[time_period_1] for time_period_1 in model.indexes_time_periods)
  constraint_value = left_hand_side == 0

    return constraint_value

```

Obviously the larger the parameters named "number_of_features" and "number_of_time_periods", the most difficult is the creation of the model.

Two issues are derived for the creation of the above optimization problem:

1) High-memory consumption. Indeed for medium-size parameters, my code crushes (even in a cluster) because of a lack of memory.
2) Slow speed when creating the instance of the model.

I have used [memory-profiler](https://pypi.org/project/memory-profiler/) to check where are the most-memory consuming parts but I have obtained no clear conclusions.

I include some of the metrics that I have obtained from different choices of the parameters "number_of_time_periods" and "number_of_features"

```

- Example 1:
   - number_of_time_periods = 48.
   - number_of_features = 146.
   - elapsed time create model = 50 seconds (approximately).
   - memory consumption = 110 Mb (approximately).

- Example 2:
   - number_of_time_periods = 648.
   - number_of_features = 146.
   - elapsed time create model = 8233 seconds (approximately). So more than 3 hours just creating the model.
   - memory consumption = 5 Gb (approximately).

- Example 3:
   - number_of_time_periods = 1200.
   - number_of_features = 146.
   - elapsed time create model = 26800 seconds (approximately 8 hours creating the model).
   - memory consumption = crashes when solving the optimization problem.

```
Ideally, my model should be solved with number_of_time_periods = 8000 (approximately) and number_of_features = 146. As you can observe by the above metrics, so far it is impossible for me to manage such large numbers.

Have you had similar issues? If that is the case, have you managed to fix them? How?

If further details or information is required, please do not hesitate to contact me.

Thank you in advance,

Kind regards,

Asunción

**Comment by mrmundt** [comment]
Hello, @asuncionjc. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.

**Comment by asuncionjc** [comment]
Thank you for the info @mrmundt 😀 I'll ask the question using your suggestions
