### ISSUE TITLE
Error while importing pyomo from matlab

### ISSUE THREAD

**Issue by antvig** [Pyomo/pyomo#156]
Hi,

When importing pyomo.environ from matlab, I get an error coming from cbc configuration : 

```
>> mod = py.importlib.import_module('pyomo.environ');
Error using processmngr>run_command (line 657)
Python Error: AttributeError: 'NoneType' object has no attribute 'flush'

Error in CBCplugin>configure_cbc (line 51)
    results = pyutilib.subprocess.run( [cbc_exec,"-stop"], timelimit=1000)

Error in __init__><module> (line 33)
configure_cbc()

Error in __init__>load (line 13)
    import pyomo.solvers.plugins.solvers

Error in __init__>_import_packages (line 67)
        pkg.load()

Error in __init__><module> (line 70)
_import_packages()

Error in <frozen importlib>_call_with_frames_removed (line 222)

Error in <frozen importlib>exec_module (line 665)

Error in <frozen importlib>_load_unlocked (line 673)

Error in <frozen importlib>_find_and_load_unlocked (line 958)

Error in <frozen importlib>_find_and_load (line 969)

Error in <frozen importlib>_gcd_import (line 986)

Error in __init__>import_module (line 126)
    return _bootstrap._gcd_import(name[level:], package, level)
```

**Comment by jsiirola** [comment]
How are you installing / configuring Pyomo to be called from within MATALB?  This looks like a problem with `pyutilib.subprocess.processmngr` where the `sys.stdout` or `sys.stderr` are set to `None` instead of a valid file handle.

**Comment by antvig** [comment]
The issue comes from Matlab which replace sys.stdout with a new object (MexPrinter) to redirect the stdout to matlab console. However stderr is not redefined in Matlab, thus, set to None.

**Comment by jsiirola** [comment]
I believe that this has been fixed by Pyutilib/pyutilib@8c67340.  You can update your installed PyUtilib to the master branch to try it out.  @whart222: can we cut another PyUtilib patch release before the next Pyomo patch release?

**Comment by antvig** [comment]
Thanks for the patch.
The sys.stdout.flush() is also happening in shellcmd.py files which lead to the same error : 

`Error using shellcmd>_apply_solver (line 240)
Python Error: AttributeError: 'MexPrinter' object has no attribute 'flush'
`

I get around this by defining a flush function for MexPrinter object (in matlab  source code)

**Comment by mohammedzmar** [comment]
could you tell me please how did you define a flush function for mexprinter object
