### ISSUE TITLE
Error using IntegerSet as a Var domain

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#1569]
The following was reported on the [forum](https://groups.google.com/d/msgid/pyomo-forum/f2766be1-8292-4d5f-8c74-4f9fa522bb27o%40googlegroups.com?utm_medium=email&utm_source=footer):

[...] I wasn't able to create "Var" objects. To give an example, my code looks the following way:
```
model= ConcreteModel()
model.counter=Set(initialize=counter) where "counter" is the unique list of items in a particular list
model.volume=Var(model.counter,domain=IntegerSet,initialize=1)
```
When I run the code, error occurs at the place where I create my Var object and the message says: "`TypeError: __new__() takes 1 positional argument but 3 were given`

**Comment by blnicho** [comment]
`IntegerSet` has been deprecated so closing this.
