### ISSUE TITLE
Scaling transformation does not work with References

### ISSUE THREAD

**Issue by Robbybp** [Pyomo/pyomo#1571]
References break the scaling transformation because it renames the underlying components, then tries to scale the now-broken `Reference` components. Some options:
1. Rename all components (breaking references), then don't try to scale references
2. Don't rename components
3. Create new, renamed components but don't delete the old components

I think I'm in favor of option 1 for now as long as we document that the scaling transformation breaks references. Maybe we can have a `rename_scaled_components` option?

**Comment by carldlaird** [comment]
I wonder if this exposes another problem - are the referenced variables scaled twice? I guess we don't know if it fails.

**Comment by Robbybp** [comment]
This supersedes https://github.com/Pyomo/pyomo/issues/1571

**Comment by Robbybp** [comment]
I think we try to scale the referenced variables twice, but fail when we get to the Reference.

**Comment by carldlaird** [comment]
@blnicho Any thoughts?
