### ISSUE TITLE
Cannot load a SolverResults object with bad status: aborted

### ISSUE THREAD

**Issue by Chris-Zheng-1** [Pyomo/pyomo#1572]
I am a beginner of Pyomo and I construct a MINLP model to solve community partition. When I solve the model, it turns such error:
<img width="928" alt="截屏2020-07-25 下午5 35 22" src="https://user-images.githubusercontent.com/61665570/88461648-39046c80-ce9d-11ea-8c76-af5322b587d8.png">
How could I solve this problem?

**Comment by bernalde** [comment]
Hi, can you provide us with more details about your problem? Maybe a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example)? I would also suggest you visit the [Pyomo forum](https://groups.google.com/forum/?nomobile=true#!forum/pyomo-forum) where you can find examples and other answered questions.

**Comment by qtothec** [comment]
Which MINLP solver are you using? Some solvers will report `aborted` because of a license failure.

**Comment by blnicho** [comment]
Issues on the Pyomo GitHub page are meant for bug-reports and feature requests. If you have modeling or implementation questions please ask them on the Pyomo forum or on StackOverflow.
