### ISSUE TITLE
Data Command File Param: Default only

### ISSUE THREAD

**Issue by rhshadrach** [Pyomo/pyomo#1573]
When I write code to produce a data command file and there is a parameter with a default value, I only write out the parameters that do not equal the default value. This leaves me with the edge case where all parameters are equal to the default value, in which case I write out something like this:

    param A default 0.0 := ;

Pyomo doesn't seem to like this though. I was able to get it to work by using `.`:

    param A default 0.0 := . .;

for a 1-dim parameter, but perhaps it would be nice if the former were supported.

**Comment by mrmundt** [comment]
In an effort to clean up issues, we are moving some discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
