### ISSUE TITLE
Remove old GLPK interfaces

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#1580]
We currently have 4 interfaces for GLPK:

  1. LP files for `glpsol`>=4.58
  2. LP files for `glpsol`>=4.42
  3. LP files for `glpsol`<4.42
  4. Direct interface through "glpk" python package

(1) is regularly tested.  The others are not. 
 - I just manually ran `test.pyomo --cat glpk -v` with GLPK 4.40 and 4.57.  In both cases, there were 23 test failures (out of 282 tests).  Most test failures had to do with getting the wrong solver status back.
 - (4) is explicitly disabled.  I re-enabled it and got a recent version of the glpk python bindings installed.  The direct interface has not tracked changes in the solver interface (errors about ephemeral options).

Version information:
- GLPK 4.58 was released 2016-02-18.  
- RHEL8 distributes GLPK 4.65 (through EPEL)
- RHEL7 distributes GLPK 4.52 (through EPEL)
- RHEL6 distributes GLPK 4.40

Unless someone wants to take over the interface anfd get it working again, I believe that we should remove (4): it was disabled more than 4 years ago.

I would like to hear others' thoughts about preserving support for the system glpk on RHEL6 or RHEL7...

**Comment by bacalfa** [comment]
Does it mean I shouldn't be using [`glpk`](https://anaconda.org/conda-forge/glpk) from Anaconda?

**Comment by jsiirola** [comment]
GLPK from Anaconda is fine and will be continued to be supported.  Anaconda (conda-forge) currently distributes 4.65 (and we actually use it for our Windows testing).

I should note that the conda-forge GLPK package includes GLPK (i.e., the `glpsol` executable), but not the glpk python bindings - that is a separate package available from PyPI; unfortunately also named "glpk"

**Comment by jsiirola** [comment]
This is a follow-on of #404.
