### ISSUE TITLE
pyomo.extras support in Python 3.8

### ISSUE THREAD

**Issue by bacalfa** [Pyomo/pyomo#1581]
I have Python 3.8.5 and can't install `pyomo.extras`. It seems it's not supported.

**Comment by jsiirola** [comment]
@bacalfa, `pyomo.extras` is deprecated and is really not necessary for any users.  For all intents and purposes, you can replicate installing `pyomo.extras` with:
```
pip install sympy xlrd openpyxl PyYAML pymysql "ipython[notebook]" pyro4
```
...or the `conda install` equivalent.  Of those optional dependencies, your are not likely to be using any of them, with the possible exception of `sympy`, `pyyaml`, and `pyro4`.
