### ISSUE TITLE
solution loading when using Pyro

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#1588]
I am using **Pyro** for parallelly solving multiple models. The [example](https://pyomo.readthedocs.io/en/stable/working_models.html?highlight=parallel#solving-multiple-instances-in-parallel) in the online document is really helpful and works well.

I also tried solving different blocks in parallel. It also works well. The example code is as follows.

```
action_handle_map = {}  # maps action handles to instances

# Create a solver
optsolver = SolverFactory('cplex')

# create a solver manager
# 'pyro' could be replaced with 'serial'
solver_manager = SolverManagerFactory('pyro')
if solver_manager is None:
    print("Failed to create solver manager.")
    sys.exit(1)

#
# A simple model with binary variables and
# an empty constraint list.
#
model = ConcreteModel()
model.n = Param(default=4)
model.b1 = Block()
model.b2 = Block()
model.b1.x = Var(RangeSet(model.n), within=Binary)
model.b2.x = Var(RangeSet(model.n), within=Binary)


def o_rule(block):
    return summation(block.x)


model.b1.o = Objective(rule=o_rule)
model.b2.o = Objective(rule=o_rule)

model.b1.c = ConstraintList()
model.b2.c = ConstraintList()


# Create two model instances
model.b2.x[1] = 1
model.b2.x[1].fixed = True

# send them to the solver(s)
action_handle = solver_manager.queue(
    model.b1, opt=optsolver, warmstart=False, tee=True)
action_handle_map[action_handle] = "Original"
action_handle = solver_manager.queue(
    model.b2, opt=optsolver, warmstart=False, tee=True)
action_handle_map[action_handle] = "One Var Fixed"

# retrieve the solutions
for i in range(2):  # we know there are two instances
    this_action_handle = solver_manager.wait_any()
    solved_name = action_handle_map[this_action_handle]
    results = solver_manager.get_results(this_action_handle)
    print("Results for", solved_name)
    print(results)
```

However, when I used Pyro to solve bigger models(ConcreteModel), I found the solution will not be automatically loaded to the model, even when I set `load_solutions=True`. In the results, a solution will be displayed.

> `'Solution': [OrderedDict([('number of solutions', 1), ('number of solutions displayed', 1)])`

>     x4460:
>       Value: 200.47500000000002
>     x4461:
>       Value: 196.60500000000002
>     x4462:
>       Value: 193.455
>     x4463:
>       Value: 190.305
>     x4464:
>       Value: 188.01000000000002
>     x4465:
>       Value: 184.86
>     x4466:
>       Value: 182.43
>     ...

It really gave me a hard time to find the correct function to load the solutions.
For concrete model, the function is `model.solutions.load_from(results)`.
For abstract model, I am not sure yet(might be the same or `model.load_solution(result.solution(0))`).

My guess for why the solution is not automatically loaded is due to the delay according to [this answer](https://stackoverflow.com/a/50118384/14077954). 

I am not sure if it's the default setting of Pyro SolverManagerFactory that not load solutions for big models. If so, I'd suggest adding some notes in the doc mentioning how to load solutions manually.

**Comment by ZedongPeng** [comment]
btw, when I use Pyro, I often need to open many terminals. One for pyomo_ns, one for dispatch_srvr, and several pyro_mip_server. Is there a more compact way to do this? like a bash script?

**Comment by jsiirola** [comment]
This is expected, albeit not necessarily desired, behavior.  Because the solves are happening on remote processes, the solver interface cannot load the results directly back into the model and are instead returned in the results object.  You are correct that you have to call:
```python
model.solutions.load_from(results)
```
There is no analogue for AbstractModel, because an abstract model has not been constructed: it has no data, and no variables, so there is nothing to load the solution into.

As for the processes, this is an issue for Windows, but on Linux / OSX, I generally launch the server processes as background processes (with `&`)

**Comment by ZedongPeng** [comment]
Thank you @jsiirola . I'll try the background processes. 
I think this issue is solved by your comment and can be closed.
