### ISSUE TITLE
Error while using covariance estimation feature in parmest

### ISSUE THREAD

**Issue by notesofdabbler** [Pyomo/pyomo#1599]
I was trying to use parmest for a simple series reaction A->B->C with estimation of covariance using the following command but it gives an error.
```
obj, theta, cov = pest.theta_est(calc_cov=True)
```
The following [notebook](https://github.com/notesofdabbler/learn_pyomo/blob/master/wk_parmest/ABC_parmest_with_Cov.ipynb) has the example and the results of the above command where the error occurs. I would appreciate any suggestions on how to address the issue.

Also, to run this code I had to make the following change in line 104 of [inverse_reduced_hessian.py](https://github.com/Pyomo/pyomo/blob/master/pyomo/contrib/interior_point/inverse_reduced_hessian.py)
```
# current line 104 which gives another error
(v.has_ub() and v.ub - pyo.value(b) <= bound_tolerance):
# changed b to v in the line above
(v.has_ub() and v.ub - pyo.value(v) <= bound_tolerance):
```

**Comment by adowling2** [comment]
Here is the error message:

```


/home/paperspace/anaconda3/envs/my_pyomoenv/lib/python3.8/site-packages/pyomo/contrib/interior_point/interface.py:410: RuntimeWarning: divide by zero encountered in true_divide
  duals_primals_ub/(self._nlp.primals_ub() - primals))

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-29-e2f8914f31ed> in <module>
      1 # First tried collocation method. Max iterations are exceeded
      2 pest = parmest.Estimator(ABC_model, data, theta_names, tee = True)
----> 3 obj, theta, cov = pest.theta_est(calc_cov=True)

~/anaconda3/envs/my_pyomoenv/lib/python3.8/site-packages/pyomo/contrib/parmest/parmest.py in theta_est(self, solver, return_values, bootlist, calc_cov)
    796         assert isinstance(bootlist, (type(None), list))
    797 
--> 798         return self._Q_opt(solver=solver, return_values=return_values,
    799                            bootlist=bootlist, calc_cov=calc_cov)
    800 

~/anaconda3/envs/my_pyomoenv/lib/python3.8/site-packages/pyomo/contrib/parmest/parmest.py in _Q_opt(self, ThetaVals, solver, return_values, bootlist, calc_cov)
    508 
    509                 # calculate the reduced hessian
--> 510                 solve_result, inv_red_hes = inv_reduced_hessian_barrier(self.ef_instance, 
    511                     independent_variables= ind_vars,
    512                     solver_options=self.solver_options,

~/anaconda3/envs/my_pyomoenv/lib/python3.8/site-packages/pyomo/contrib/interior_point/inverse_reduced_hessian.py in inv_reduced_hessian_barrier(model, independent_variables, bound_tolerance, solver_options, tee)
    118     linear_solver = ScipyInterface(compute_inertia=False)
    119     linear_solver.do_symbolic_factorization(kkt)
--> 120     linear_solver.do_numeric_factorization(kkt)
    121 
    122     n_rh = len(ind_var_indices)

~/anaconda3/envs/my_pyomoenv/lib/python3.8/site-packages/pyomo/contrib/interior_point/linalg/scipy_interface.py in do_numeric_factorization(self, matrix, raise_on_error)
     31         except RuntimeError as err:
     32             if raise_on_error:
---> 33                 raise err
     34             if 'Factor is exactly singular' in str(err):
     35                 res.status = LinearSolverStatus.singular

~/anaconda3/envs/my_pyomoenv/lib/python3.8/site-packages/pyomo/contrib/interior_point/linalg/scipy_interface.py in do_numeric_factorization(self, matrix, raise_on_error)
     27         res = LinearSolverResults()
     28         try:
---> 29             self._lu = splu(matrix)
     30             res.status = LinearSolverStatus.successful
     31         except RuntimeError as err:

~/anaconda3/envs/my_pyomoenv/lib/python3.8/site-packages/scipy/sparse/linalg/dsolve/linsolve.py in splu(A, permc_spec, diag_pivot_thresh, relax, panel_size, options)
    335         _options["SymmetricMode"] = True
    336 
--> 337     return _superlu.gstrf(N, A.nnz, A.data, A.indices, A.indptr,
    338                           csc_construct_func=csc_construct_func,
    339                           ilu=False, options=_options)

RuntimeError: Factor is exactly singular
```

This appears to be an issue in `inv_reduced_hessian_barrier`; it thinks the KKT matrix is singular. @michaelbynum @carldlaird any ideas? I did not see anything wrong in the model after a quick inspection. One guess is to try solving the problem without bounds (only equality constraints).

**Comment by notesofdabbler** [comment]
It looks my bound on initial conditions was causing issues. When I relaxed it a bit:
```
    #m.ca = Var(m.time, initialize = ca0, bounds = (0, ca0))
    #m.cb = Var(m.time, initialize = cb0, bounds = (0, ca0))
    #m.cc = Var(m.time, initialize = cc0, bounds = (0, ca0))
    m.ca = Var(m.time, initialize = ca0, bounds = (-1e-3, ca0+1e-3))
    m.cb = Var(m.time, initialize = cb0, bounds = (-1e-3, ca0+1e-3))
    m.cc = Var(m.time, initialize = cc0, bounds = (-1e-3, ca0+1e-3))
```
the code ran. However, the covariance matrix generated has negative diagonal elements
```
array([[-0.13200115,  0.02026257],
       [ 0.02026257, -0.01809481]])
```
I am not sure why that is happening.

**Comment by adowling2** [comment]
@notesofdabbler Yes, the covariance matrix calculation is not well-defined if a variable is against a bound. Figure 7-2 in *Nonlinear Parameter Estimation* by Bard (1974) illustrates the issue. A common practice is to transform the variables to remove the bounds (inequality constraint). For example, log/exponential transformation implies a parameter is positive. I am open to any suggestions on alternative approaches. The reference I gave above is classic but dated.

All of that being said, we should have the covariance estimation feature fail more gracefully in this case. I really appreciate you pointing out the issue.

The negative diagonal elements is very interesting. Did you commit this result to your example repository? If so, can you post a link to the specific commit?

Under the hood parmest is extracting the reducing Hessian of the least squares optimization problem. It is possible the solver converged to a point that is not the local minimum. I ask for the link above to look at the Ipopt log.

**Comment by notesofdabbler** [comment]
@adowling2 Sorry, I meant to provide a link. Here is the [notebook](https://github.com/notesofdabbler/learn_pyomo/blob/master/wk_parmest/ABC_parmest_with_Cov.ipynb). It looks like IPOPT converged to optimal solution. Also, in this case I initialized `k1` and `k2` to the optimal values and removed the bounds on them.

**Comment by notesofdabbler** [comment]
@adowling2 I had a chance to revisit this example again and I think I found the issue causing the negative diagonals in the covariance matrix. The inverse reduced hessian is getting calculated correctly. But the number of data points used is not correct. Since parmest allows dictionaries as data, I was using a dictionary of one element to hold the time series data for 3 components. So there are 20 time points x 3 components = 60 data points. But parmest is thinking that number of data points is 1 since it is calculated as `n = len(self.callback_data)` in line 483 of [parmest.py](https://github.com/Pyomo/pyomo/blob/main/pyomo/contrib/parmest/parmest.py). So if I take the estimated covariance matrix from parmest and multiply by `(1 - 2)/(60 -2)`, then I get the correct covariance matrix. The details are in this [notebook](https://github.com/notesofdabbler/learn_pyomo/blob/master/wk_parmest/ABC_parmest_with_Cov.ipynb).

**Comment by notesofdabbler** [comment]
@adowling2 I also have a workaround for the issue of runtime error `RuntimeError: Factor is exactly singular` that was discussed in this thread [previously](https://github.com/Pyomo/pyomo/issues/1599#issuecomment-674626591). I captured it in this [notebook](https://github.com/notesofdabbler/learn_pyomo/blob/master/wk_parmest/ABC_parmest_chk_inv_red_hess_fixinit.ipynb). Initially I had the initial conditions in the following way:
```
    def _initcon(m):
        yield m.ca[m.time.first()] == ca0
        yield m.cb[m.time.first()] == cb0
        yield m.cc[m.time.first()] == cc0
    m.initcon = pyo.ConstraintList(rule = _initcon)
```
This is the portion that seems to cause the issue. When I removed this and replaced it with fixing the variables at first time point as follows, that seemed to resolve the issue

```
    for t in m.time:
        if t == 0:
            m.ca[t].fix(ca0)
            m.cb[t].fix(cb0)
            m.cc[t].fix(cc0)
        else:
            m.ca[t] = ca0
            m.cb[t] = 0.0
            m.cc[t] = 0.0
            m.ca[t].setlb(0.0)
            m.ca[t].setub(ca0)
            m.cb[t].setlb(0.0)
            m.cb[t].setub(ca0)
            m.cc[t].setlb(0.0)
            m.cc[t].setub(ca0)
```

**Comment by adowling2** [comment]
@notesofdabbler What was causing the negative eigenvalues? You have piqued my curiosity.

@michaelbynum @kaklise @Robbybp @carldlaird `parmest` now uses `inverse_reduced_hessian` from `pyomo.contrib.interior_point.inverse_reduced_hessian`. Any idea on why changing from:

```
def _initcon(m):
        yield m.ca[m.time.first()] == ca0
        yield m.cb[m.time.first()] == cb0
        yield m.cc[m.time.first()] == cc0
    m.initcon = pyo.ConstraintList(rule = _initcon)
```

to 

```
    for t in m.time:
        if t == 0:
            m.ca[t].fix(ca0)
            m.cb[t].fix(cb0)
            m.cc[t].fix(cc0)
        else:
            m.ca[t] = ca0
            m.cb[t] = 0.0
            m.cc[t] = 0.0
            m.ca[t].setlb(0.0)
            m.ca[t].setub(ca0)
            m.cb[t].setlb(0.0)
            m.cb[t].setub(ca0)
            m.cc[t].setlb(0.0)
            m.cc[t].setub(ca0)
```

for the initial condition specification would cause the reduced Hessian to be singular?

@notesofdabbler Can you point us to a version of the notebook that had the singular reduced Hessian? When you get the singular reduced Hessian, were you also specifying the same initial condition and bounds? 

@kaklise This nice example highlights that parmest is extremely flexible in how users specify the data. Any ideas on how best to calculate the number of data points, which is needed to compute the covariance matrix?

@kaklise @Robbybp I wonder if we should add k_aug's reduced Hessian calculation back into parmest in the long-term. This would allow us to calculate the covariance matrix two ways; for edge cases like negative eigenvalues, this would give insights into if it is a reduced Hessian calculation bug or a problem formulation issue.

@notesofdabbler Check out this Pyomo utility package for NLP model diagnostics:
https://idaes.github.io/examples-pse/latest/Examples/Tools/degeneracy_hunter_doc.html

`check_variable_bounds` is a really useful utility function. The covariance calculation because much harder (the theory is less mature) if the regressed parameters are at a bound.

**Comment by notesofdabbler** [comment]
@adowling2 The eigenvalues were not negative. The inverse_reduced_hessian was getting calculated correctly once the factor singular error was resolved. The negative elements in diagonal of covariance were a result of incorrect assumption on number of data points (n = 1). Since number of parameters were (p = 2), the calculation of `cov = 2 * sse / (n - p) * inv_red_hes` resulted in negative diagonal elements. 

I have captured the issues and workarounds in this [notebook](https://github.com/notesofdabbler/learn_pyomo/blob/master/wk_parmest/ABC_parmest_with_Cov_test.ipynb). 

Also, thanks for pointing me to degeneracy_hunter_doc.

**Comment by kaklise** [comment]
Thanks for pointing out this issue.  Parmest allows for several input data formats, and a list of dictionaries (or a list of dataframes) is a common data format when working with timeseries data.  In the covariance calculation, n currently stores the number of scenarios and this needs to be updated to store the number of data points.  I can update the code to compute n based on the data format, however, the data could include components that should not be counted as data points.  I'll test out some options using the examples you provided.

**Comment by kaklise** [comment]
@adowling2 @notesofdabbler After looking at a few examples, I think the best short term solution is to require the user to supply the number of data points when computing the covariance matrix.  This avoids a miscalculation when the data (dictionary or dataframe) contains extra information.  This could occur for several reasons, including the case where the user changes the objective function supplied to the `Estimator` class without changing the data format.  

In the long term, we might want to refactor `theta_est` into multiple methods that estimate parameters, compute the covariance, or return reconciled data.

I'll update the code and add this example to our parmest tests.  In the example, I initialized the ca, cb, and cc variables when they were defined and didn't run into issues computing the inverse reduced hessian.
