### ISSUE TITLE
Deprecate the old 'pyomo' command syntax

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#160]
In earlier releases, we supported commands like
`  pyomo --solver=glpk foo.py bar.dat`
And we moved to a nested pyomo command, which uses the following syntax:
`  pyomo solve --solver=glpk foo.py bar.dat`

However, to enable graceful transition for users, we added a hack to transition to the old syntax if it looks like the user is not specifying a valid subcommand.  However, this leads to confusing error messages, and I think it's time to deprecate that hack and start throwing warnings that this hack will be removed in an upcoming release.

**Comment by mrmundt** [comment]
This has already been done.

**Comment by mrmundt** [comment]
Reopening until I submit a PR to turn it into a true deprecation warning instead of just a "warning."
