### ISSUE TITLE
XPRESS Solver plugin has some oddities

### ISSUE THREAD

**Issue by mrmundt** [Pyomo/pyomo#1601]
When completing the work for #1517 , I ran across an oddity in the `XPRESS` plugin. Namely, in `pyomo/solvers/plugins/solvers/XPRESS.py `, starting at line `372`, there are a lot of undefined variable names and references. 

I am sure this would cause issues once we we are able to test XPRESS and want to keep the oddities on our radar.

The note from 1517:

> ### TODO: What is going on here with field_name, and shortly thereafter, with variable_status and whatnot? They've never been defined.
> ### It seems like this is trying to mimic the CPLEX solver but has some issues

**Comment by bknueven** [comment]
I have noticed this too, and in my own testing, the XPRESS plugin is broken for modern versions of XPRESS. Until somebody re-writes it, it may be better if `SolverFactory(“xpress”)` returned an XpressDirect solver instance.
