### ISSUE TITLE
Cannot recover solution produced by ipopt

### ISSUE THREAD

**Issue by baseb0l** [Pyomo/pyomo#1602]
I am using pyomo-ipopt. I get "Restoration phase converged to a feasible point that is unacceptable to the filter for the original problem. Restoration phase in the restoration phase failed."

Then for results = opt.solve(instance, load_solutions=True, tee=True)

I get ValueError: Cannot load a SolverResults object with bad status: error

I would like to recover the solution produced by Ipopt.

**Comment by mrmundt** [comment]
Hello, @baseb0l. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
