### ISSUE TITLE
Option file for using solver from GAMS

### ISSUE THREAD

**Issue by wenjingsu16** [Pyomo/pyomo#1604]
Is there a way to add the solver specific option file when I call solver through GAMS in Pyomo? 

I am calling GAMS knitro solver. I added the io_options['add_options']=['optfile=1;'] and have knitro.opt file in the same directory as my python script. But it does not seem to work. The settings of knitro are not changed based on the knitro.opt file. optfile=1 also seems to be a model attribute instead of option for GAMS model.

**Comment by gseastream** [comment]
I don't know about knitro specifically, but if `optfile` is a model attribute, perhaps try using `'GAMS_MODEL.optfile = 1;'`. The model name in the GAMS script is `GAMS_MODEL`, so you can use that name in `add_options` for model attributes. You can find more info about the GAMS interface in the [docs](https://pyomo.readthedocs.io/en/stable/library_reference/solvers/gams.html).

**Comment by wenjingsu16** [comment]
Thanks for your response. Sorry I was not clear about the solver. I meant that optfile is an option for GAMS with other solvers besides Knitro. I did check the docs and did not find anything. But I will try to add_options =['GAMS_MODEL.optfile = 1;'].

**Comment by bernalde** [comment]
Hello, there is the possibility that you can make your GAMS code to generate that option file. An example below with DICOPT enabling its feasibility pump option.

result = SolverFactory('gams').solve(
    m, solver='dicopt', tee=True,
    add_options=[
        '$onecho > dicopt.opt',
        'feaspump 1',
        'maxcycles 0',
        '$offecho',
        'GAMS_MODEL.optfile=1',
    ]
);

**Comment by blnicho** [comment]
@wenjingsu16 did the suggestions from @gseastream and @bernalde work for you? Can this issue be closed?

**Comment by wenjingsu16** [comment]
Hi,

Sorry for the late reply. Let me try and close it if it solves today. Thanks.

**Comment by wenjingsu16** [comment]
Hi,

I tried to use the code as below. Pyomo still does not seem to read the option file for the GAMS solver. But I am able to generate GAMS code in which opt file =1. Thanks.
>results = opt.solve(model,solver='knitro',tee=True,logfile=True,keepfiles=True,add_options=['GAMS_MODEL.optfile=1'])

**Comment by Ishanki** [comment]
Hi,

I've been trying to pass DICOPT options to GAMS using
```
solver=SolverFactory('gams')
options = {}
options['maxcycles'] = 30
results = solver.solve(m, tee=True, options = options, solver = 'dicopt')
```
etc., but this returns a _ValueError: GAMS writer passed unrecognized io_options: maxcycles = 30_. I've also tried 
`solver.options['maxcycles'] = 30`
but no luck. Is this a Pyomo or GAMS issue, or am I doing something wrong?

**Comment by gseastream** [comment]
Is `maxcycles` something typically defined in a DICOPT options file? If so you may need to use the `add_options=["GAMS_MODEL.optfile = 1;"]` keyword argument to solve (or pass `io_options={"add_options": ["GAMS_MODEL.optfile = 1;"]}`), and then place the options file in your working directory. If there's a way in GAMS to use that option without a file, then you can use the `add_options` argument to add any list of lines you want to the GAMS model file.

**Comment by baseb0l** [comment]
The following worked for me when using pyomo->gams->knitro from the directory /Users/MyDir/

opt = SolverFactory('gams')
opts = {}
opts["solver"] = "knitro"
with open("tmp/knitro.opt", "w") as f:
    f.write("algorithm 2\n")
addOp = ['GAMS_MODEL.optfile=1;']
opt.solve(instance, io_options=opts, load_solutions=True, tee=True, add_options=addOp,
          tmpdir='/Users/MyDir/tmp')
