### ISSUE TITLE
mindtpy variable being passed a float instead of NonNegativeInteger

### ISSUE THREAD

**Issue by mez3252** [Pyomo/pyomo#1605]
Hi I'm new to pyomo, I was just trying to get this simple program running. 

import pyomo.environ as pyomo
import ipopt

def optimization_function2( m ):

    x = [ pyomo.value(m.b1l),  pyomo.value(m.b1u)]

    print( 'x: {}'.format( x ) )
    outVal = 1/(1+(x[0]-4)**2) + 1/(1+(x[1]-10)**2)
    print( 'outVal: {}'.format( outVal ) )
    return outVal

model = pyomo.ConcreteModel()
model.b1l = pyomo.Var( within=pyomo.NonNegativeIntegers , bounds=(0,46), initialize=2 )
model.b1u = pyomo.Var( within=pyomo.NonNegativeIntegers, bounds=(1,47), initialize=7 )
model.cons = pyomo.ConstraintList()
model.cons.add( model.b1u - model.b1l >= 1 )
model.OBJ = pyomo.Objective( rule=optimization_function2 )
solver = pyomo.SolverFactory('mindtpy')
solver.solve(model, tee=True )

But it seems on the first iteration the optimization variable is being passed a float instead of NonNegativeInteger. 

 python3 ./optimization_test.py
x: [2, 7]
outVal: 0.30000000000000004
INFO: ---Starting MindtPy---
INFO: Original model has 1 constraints (0 nonlinear) and 0 disjunctions, with
    2 variables, of which 0 are binary, 2 are integer, and 0 are continuous.
INFO: NLP 1: Solve relaxed integrality
INFO: NLP 1: OBJ: 0.30000000000000004  LB: 0.30000000000000004  UB: inf
Traceback (most recent call last):
  File "./optimization_test.py", line 27, in <module>
    solver.solve(model, tee=True )
  File "/g/g13/code/lib/python3.7/site-packages/pyomo/contrib/mindtpy/MindtPy.py", line 408, in solve
    MindtPy_initialize_master(solve_data, config)
  File "/g/g13/code/lib/python3.7/site-packages/pyomo/contrib/mindtpy/initialization.py", line 58, in MindtPy_initialize_master
    init_rNLP(solve_data, config)
  File "/g/g13/code/lib/python3.7/site-packages/pyomo/contrib/mindtpy/initialization.py", line 103, in init_rNLP
    config, ignore_integrality=True)
  File "/g/g13/code/lib/python3.7/site-packages/pyomo/contrib/gdpopt/util.py", line 200, in copy_var_list_values
    v_to.set_value(value(v_from, exception=False))
  File "/g/g13/code/lib/python3.7/site-packages/pyomo/core/base/var.py", line 176, in set_value
    if valid or self._valid_value(val):
  File "/g/g13/code/lib/python3.7/site-packages/pyomo/core/base/var.py", line 189, in _valid_value
    (val, type(val), self.domain, self.name))
ValueError: Numeric value `4.491231465379228` (<class 'float'>) is not in domain NonNegativeIntegers for Var b1l

**Comment by ZedongPeng** [comment]
Hi. I reproduced your code and the error didn't show up in my local environment(master branch). I think it's a bug that we have fixed but your pyomo code is not up-to-date. You can solve this by updating your pyomo package.
Btw, in your example, you have a constant objective function, this might make the mip solver cry in some case.

**Comment by bernalde** [comment]
Can this issue be closed? If not please let us know @mez3252

**Comment by bernalde** [comment]
I have also tried reproducing this issue and the error using the exact same code as above has to do with the definition of the objective function value.
A slight modification of the code as follows:
```
import pyomo.environ as pyomo
model = pyomo.ConcreteModel()
model.b1l = pyomo.Var(within=pyomo.NonNegativeIntegers,
                      bounds=(0, 46), initialize=2)
model.b1u = pyomo.Var(within=pyomo.NonNegativeIntegers,
                      bounds=(1, 47), initialize=7)
model.cons = pyomo.ConstraintList()
model.cons.add(model.b1u - model.b1l >= 1)


def optimization_function2(m):
    outVal = 1/(1+(m.b1l-4)**2) + 1/(1+(m.b1u-10)**2)
    return outVal


model.OBJ = pyomo.Objective(rule=optimization_function2)
solver = pyomo.SolverFactory('mindtpy')
solver.solve(model, tee=True)
```
Yields a correct behavior from MindtPy:
```
INFO: ---Starting MindtPy---
INFO: Original model has 1 constraints (0 nonlinear) and 0 disjunctions, with
    2 variables, of which 0 are binary, 2 are integer, and 0 are continuous.
INFO: Objective is nonlinear. Moving it to constraint set.
INFO: rNLP is the initial strategy being used.
INFO: NLP 1: Solve relaxed integrality
INFO: NLP 1: OBJ: 0.07101865185857859  LB: -inf  UB: inf
INFO: ---MindtPy Master Iteration 0---
INFO: MIP 1: Solve master problem.
INFO: MIP 1: OBJ: 0.0710186513629814  LB: 0.0710186513629814  UB: inf
INFO: NLP 2: Solve subproblem for fixed binaries.
INFO: NLP 2: OBJ: 0.07101864383111128  LB: 0.0710186513629814  UB:
    0.07101864383111128
INFO: MindtPy exiting on bound convergence. LB: 0.0710186513629814 + (tol
    0.0001) >= UB: 0.07101864383111128
```
This issue can be closed.
