### ISSUE TITLE
Resolve issue with solver tests

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#161]
With the conversion to kernel, some solver tests fail:
`pyomo test-solvers glpk`

Specifically, the `pyomo/solvers/tests/testcases.py` file has an error due to the use of kernel classes.

See line 309:
`model_class.model.solutions.load_from(results,                      default_variable_value=opt.default_variable_value())`

This indicates a change in model management that was unexpected.  Is there a new plan for solver management???

**Comment by ghackebeil** [comment]
I wouldn't call it a new plan for solver management. The kernel block implementation just has a different style for explicitly loading a solution from the results object (more similar to the original syntax on Pyomo models). There is currently no "solutions database" object. I'm certainly up for a discussion about whether or not we should move that into the kernel though. Here is a comparison of the syntax for now:

In both Kernel and AML, the default behavior looks the same
```python
results = opt.solve(model)
```
This automatically loads the solution and returns the results object with an empty solutions container.

When `load_solutions=False`, for the AML one does the following
```python
model.solutions.load_from(results)
```
The block implementation in Kernel just has a simple method called `load_solution` that you pass a solutions object into:
```python
model.load_solution(results.solution)
```

**Comment by ghackebeil** [comment]
Just pushed workaround (28daddbaa9536daf34e6039e57a683b129eab697). Forgot to reference this issue in the commit message.

**Comment by ghackebeil** [comment]
The original issue with the tests has been fixed. This can be reopened as a design discussion if needed.
