### ISSUE TITLE
What is a suitable solver for black box function in Pyomo

### ISSUE THREAD

**Issue by chuongask** [Pyomo/pyomo#1614]
Dear All,
I am using Pyomo to solve a problem, where the objective function is a lookup function on a given data frame (I think this objective function is a black-box function.) I run it but it seems that the model did not call this lookup function and it only evaluates the objective value at the initial point. Could you please let me know if there is something wrong? And what is  a suitable solver for black-box function in Pyomo? Thank you.
My code is as follows:

import numpy as np
import pandas as pd
from numpy import empty
d1 =pd.read_csv('C:/Users/subdata.csv', sep=',')  # 10 columns and 1000 rows
d2 = d1.rename(columns={"Unnamed: 0": "row_number"}) # rename "Unnamed: 0" by "row_number"

# create hash as a colum 
d2.insert(9, "hash",
d2['V1'].astype(str) + d2['V2'].astype(str) + d2['V3'].astype(str) + d2['V4'].astype(str) + d2[
'V5'].astype(str) + d2['V6'].astype(str) + d2['V7'].astype(str) + d2['V8'].astype(str))

cols = ['row_number', 'hash', 'V9', 'V10']

def lookupfunction(vector):
# create vector hash, vector=[1,2], vectorhash=12
vectorhash = ""
for i in vector:
vectorhash = str(vectorhash) + str(i)

lookup = d2[d2["hash"] == vectorhash]
if len(lookup) == 1:
lookupf = lookup.loc[:, cols]
lookupfV9 = lookupf.loc[:, "V9"].tolist()[0] #get value of V9
lookupfV10 = lookupf.loc[:, "V10"].tolist()[0]  #get value of V10 
return [lookupfV9, lookupfV10]
else:
return []

# define the objective function
def object(vector):
if lookupfunction(vector) == []:
return []
else:
f= 1/2*lookupfunction(vector)[0]+1/2*lookupfunction(vector)[1]
return f

# Pyomo model
from pyomo.environ import *
model = ConcreteModel()

model.n = range(8)
model.x = Var(model.n, domain=Integers, bounds=(1,5))

# initialize an initial point u in our dataframe d2
for k in model.x:
model.x[k].value = u[k]

# Change variable x to v, which a-list type
model.v=[model.x[0].value,model.x[1].value,model.x[2].value,model.x[3].value,model.x[4].value,\
model.x[5].value,model.x[6].value,model.x[7].value]

model.obj = Objective(expr=object(model.v), sense=minimize)
opt = SolverFactory('glpk')

results = opt.solve(model, tee=True)

print(value(model.obj),)
model.display()

**Comment by mrmundt** [comment]
Hello, @chuongask. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.

**Comment by wangyexiang** [comment]
> Dear All, I am using Pyomo to solve a problem, where the objective function is a lookup function on a given data frame (I think this objective function is a black-box function.) I run it but it seems that the model did not call this lookup function and it only evaluates the objective value at the initial point. Could you please let me know if there is something wrong? And what is a suitable solver for black-box function in Pyomo? Thank you. My code is as follows:
> 
> import numpy as np import pandas as pd from numpy import empty d1 =pd.read_csv('C:/Users/subdata.csv', sep=',') # 10 columns and 1000 rows d2 = d1.rename(columns={"Unnamed: 0": "row_number"}) # rename "Unnamed: 0" by "row_number"
> 
> # create hash as a colum
> d2.insert(9, "hash", d2['V1'].astype(str) + d2['V2'].astype(str) + d2['V3'].astype(str) + d2['V4'].astype(str) + d2[ 'V5'].astype(str) + d2['V6'].astype(str) + d2['V7'].astype(str) + d2['V8'].astype(str))
> 
> cols = ['row_number', 'hash', 'V9', 'V10']
> 
> def lookupfunction(vector):
> 
> # create vector hash, vector=[1,2], vectorhash=12
> vectorhash = "" for i in vector: vectorhash = str(vectorhash) + str(i)
> 
> lookup = d2[d2["hash"] == vectorhash] if len(lookup) == 1: lookupf = lookup.loc[:, cols] lookupfV9 = lookupf.loc[:, "V9"].tolist()[0] #get value of V9 lookupfV10 = lookupf.loc[:, "V10"].tolist()[0] #get value of V10 return [lookupfV9, lookupfV10] else: return []
> 
> # define the objective function
> def object(vector): if lookupfunction(vector) == []: return [] else: f= 1/2_lookupfunction(vector)[0]+1/2_lookupfunction(vector)[1] return f
> 
> # Pyomo model
> from pyomo.environ import * model = ConcreteModel()
> 
> model.n = range(8) model.x = Var(model.n, domain=Integers, bounds=(1,5))
> 
> # initialize an initial point u in our dataframe d2
> for k in model.x: model.x[k].value = u[k]
> 
> # Change variable x to v, which a-list type
> model.v=[model.x[0].value,model.x[1].value,model.x[2].value,model.x[3].value,model.x[4].value, model.x[5].value,model.x[6].value,model.x[7].value]
> 
> model.obj = Objective(expr=object(model.v), sense=minimize) opt = SolverFactory('glpk')
> 
> results = opt.solve(model, tee=True)
> 
> print(value(model.obj),) model.display()

Dear sir, do you solve this problem?@chuongask
