### ISSUE TITLE
About "ReactionNetwork" in Dynamic Systems in <Pyomo Workshop: Summer 2018>

### ISSUE THREAD

**Issue by smile-abyss** [Pyomo/pyomo#1617]
Dear,

I haven't find the class 'ReactionNetwork' in Dynamic Systems in the powerpoint <Pyomo Workshop: Summer 2018>, but this class is used many times in the page259-267. So I'm confused and eager for your help.

Best wishes!

**Comment by jsiirola** [comment]
See: [examples/dae/ReactionKinetics.py](https://github.com/Pyomo/pyomo/blob/master/examples/dae/ReactionKinetics.py).
