### ISSUE TITLE
Including python-louvain in main Pyomo test files

### ISSUE THREAD

**Issue by rahuljoglekar47** [Pyomo/pyomo#1626]
Hi,

For PR #1526 (https://github.com/Pyomo/pyomo/pull/1526), could the following pip command be included in the main Pyomo test files (from https://pypi.org/project/python-louvain/):

`pip install python-louvain`

**Comment by blnicho** [comment]
@mrmundt could you take a look at getting this package added to our testing infrastructure?

**Comment by mrmundt** [comment]
@rahuljoglekar47 , @blnicho - Any particular version?

**Comment by bernalde** [comment]
No particular requirements here. We have worked with 0.13 and 0.14 so either makes sense. If I had to choose, I would go with 0.14 since they "[solved bugs](https://python-louvain.readthedocs.io/en/latest/)" for that one (none that has affected us so far).

**Comment by jsiirola** [comment]
I believe that 0.14 is now available on Jenkins.

**Comment by blnicho** [comment]
Reopening this issue pending resolution of the docker PR: https://github.com/Pyomo/docker_scripts/pull/14

**Comment by mrmundt** [comment]
Closing again because we no longer use the Docker image.
