### ISSUE TITLE
IndexedComponent wildcard slicer silently fails to work as expected

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#163]
**Expected** behavior: `m.x[:]` works like in MATLAB and gives the same result as `m.x[:, :]` below.
**Observed** behavior: `m.x[:]` silently returns an empty list.
Looking at the unit test in `pyomo\core\tests\unit\test_indexed.py`, function `test_wildcard_slice`, it appears that the observed behavior is intended behavior. I would argue that it ought to change, or that it should at least issue a warning.
```
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.x = Var(['A', 'B', 'C'], [1, 2, 3])
>>> for v in m.x[:]:
...     print(v.name)
... 
>>> for v in m.x[:, :]:
...     print(v.name)
... 
x[A,1]
x[A,2]
x[A,3]
x[C,1]
x[C,2]
x[C,3]
x[B,1]
x[B,2]
x[B,3]
```

**Comment by jsiirola** [comment]
This particular behavior is expected.  `:` matches a single index (equivalent to `.` in regular expressions).  If you want to match any number of indices (similar to `.*` in regular expressions), then you use an ellipsis (`...`).  It is indeed different behavior from MATLAB.  MATLAB does not have the concept of ellipsis, so they force `:` to do double duty.  The explicit separation of match-one from match-any is particularly useful (and removes ambiguity) when you have jagged sets.

I did debate whether or not to throw a warning when a "slice" did not match any indices in a component and elected not to for the same reasons that `re.match` does not complain if the line does not match: there are legitimate reasons to iterate over a subset of a jagged set if it exists.

**Comment by qtothec** [comment]
Didn't know about the `...` notation. That certainly works. Thanks.
