### ISSUE TITLE
Solver returned non-zero return code (-6)

### ISSUE THREAD

**Issue by tonxxd** [Pyomo/pyomo#1647]
Hello, 
I am experiencing issues when solving a problem iteratively.

My code try to solve the same model multiple times changing a parameter
```python
solverInstance = SolverFactory(solver)
for i in range(0,10):
   model.upper_bound = i
   solverInstance.solve(model)
```

It works most of the time but randomly it crashes with the status code (-6) and I can solve the issue only restarting the kernel (with jupyter notebook)

It happens both with gurobi and cbc so I guess is something related to the pyomo library.
I found this issue on StackOverflow which is very similar to mine 
https://stackoverflow.com/questions/54991843/pyomo-breaks-when-solving-iteratively
but there is no solution provided.

Any ideas?

**Comment by michaelbynum** [comment]
```
from pyomo.opt import check_optimal_termination
import warnings

solverInstance = SolverFactory(solver)
for i in range(0, 10):
    model.upper_bound = i
    results = solverInstance.solve(model, load_solutions=False)
    if check_optimal_termination(results):
        model.solutions.load_from(results)
    else:
        warnings.warn('solver exited with termination condition {term} for i = {i}'.format(term=results.solver.termination_condition, i=i))
```

**Comment by tonxxd** [comment]
Thanks @michaelbynum 
I tried to make the change but it didn't solve the issue :/
Still getting `ERROR: Solver (gurobi) returned non-zero return code (-6)` after more or less 10 iterations

**Comment by michaelbynum** [comment]
Can you post the full stack trace? Also, are you using the LP interface?

**Comment by tonxxd** [comment]
I don't get any specific error in the output, just
```
ERROR: Solver (gurobi) returned non-zero return code (-6)
ERROR: See the solver log above for diagnostic information.
Solver (gurobi) did not exit normally
```

This is the logging of the iteration immediately before the one the throws the error (even though is not always the same with deterministic input data)

```
Using license file /gurobi.lic
Read LP format model from file /tmp_4.0_3/tmpft17f40w.pyomo.lp
Reading time = 0.05 seconds
x6961: 12265 rows, 6961 columns, 32863 nonzeros
Read MIP start from file /tmp_4.0_3/tmpeteu55g3.gurobi.mst
Changed value of parameter logfile to my.log
   Prev:   Default: 
Gurobi Optimizer version 9.0.3 build v9.0.3rc0 (mac64)
Optimize a model with 12265 rows, 6961 columns and 32863 nonzeros
Model fingerprint: 0xe49fcd62
Variable types: 1777 continuous, 5184 integer (5184 binary)
Coefficient statistics:
  Matrix range     [1e+00, 5e+00]
  Objective range  [2e-02, 1e+00]
  Bounds range     [1e+00, 1e+02]
  RHS range        [1e+00, 9e+01]

User MIP start did not produce a new incumbent solution
User MIP start violates constraint c_u_x12203_ by 5.000000000

Presolve removed 8579 rows and 4063 columns
Presolve time: 0.06s
Presolved: 3686 rows, 2898 columns, 12606 nonzeros
Variable types: 29 continuous, 2869 integer (2327 binary)

Root relaxation: infeasible, 452 iterations, 0.01 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 infeasible    0               - infeasible      -     -    0s

Explored 0 nodes (452 simplex iterations) in 0.11 seconds
Thread count was 8 (of 8 available processors)

Solution count 0

Model is infeasible
Best objective -, best bound -, gap -
WARNING: Loading a SolverResults object with a warning status into
    model=unknown;
        message from solver=Model was proven to be infeasible.
```

And after this one I cannot use the solver anymore, it enters some kind of crashed state so I have to restart the kernel

**Comment by mrmundt** [comment]
@tonxxd - Is this still a concern? 

If so, @michaelbynum , are you able to recreate the issue?

**Comment by tonxxd** [comment]
Hi @mrmundt, I ended up using a similar library (python-mip) because I couldn't solve the issue. So I can't tell you if it is happening.

**Comment by kanishka-ghosh** [comment]
@mrmundt @michaelbynum @blnicho I am having the same issue with a class example problem.  The error occurs whenever a plot is generated using `matplotlib.pyplot` in a Jupyter notebook followed by iterative calls to IPOPT.
@adowling2 will provide a link to a notebook on GitHub

**Comment by jsiirola** [comment]
@kanishka-ghosh, please open a new issue referencing this issue if you think it is related. In the new issue, please provide the full error, stack trace, and a (minimal) working example.
