### ISSUE TITLE
Can the Pyomo model be solved using heuristic algorithms?

### ISSUE THREAD

**Issue by hangtianzhang** [Pyomo/pyomo#1650]
I used Pyomo to build a model of an integrated energy system, and now I have two problems:

1) Can pyomo be used for multi-objective optimization at the same time, and if so, what should I do?

2) I want to use heuristic solving algorithms, such as genetic algorithm, particle swarm algorithm, how can I add a solution package to Pyomo?

**Comment by jsiirola** [comment]
In the future, support questions are more appropriately asked on either the users' or developers' mailing lists.

Pyomo can model multiple objectives (simply declare more than one Objective, or a single indexed Objective).  However, at this time, Pyomo does not have a specific interface to a multi-objective solver (e.g., NSGA-II) -- although several solvers (cplex, gurobi) have some degree of support for multiple objectives.  You can, of course do the "standard" reformulation tricks (e.g., weighted sum of objectives, epsilon-constraint reformulations, goal programming, etc.) to convert a multi-objective problem to one (or more) single objective problems.

Adding solver interfaces to Pyomo boils down to declaring a new class that derives from (or re-implements) the `OptSolver` interface, and then registering that new class with the `SolverFactory`.  Unfortunately it is a little more complicated than we would like at the moment: the solver interfaces are some of the oldest parts of Pyomo and were originally designed for a slightly different use-case from how they are used today.  We are working on a rewrite/simplification of the interfaces that will hopefully make things more straightforward, but that is likely still several months out.  In the mean time, you might find looking at the Baron / Gams interfaces as a starting point (in `pyomo/solvers/plugins/solvers`) as a good starting point for interfacing with solvers through sub-processes.  I am working on a relatively simple direct (in-memory, no subprocess) solver interface to Cyipopt, and expect that to be available through the `pynumero` contributed package within a week.

If you develop new solver interfaces and want them to be included in Pyomo, then the best route is to create a PR that implements the interfaces as a new module in `pyomo/contrib`.
