### ISSUE TITLE
Skip stale=True variables in store_to function

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#1658]
I am now solving a model iteratively. In different iterations, I'll fix the value of some variables. Since the I wanna record the optimal solution of each iteration, I use the [`store_to`](https://github.com/Pyomo/pyomo/blob/1e3bb15da5107ac769bcfc029861b7b22e7c5949/pyomo/core/base/PyomoModel.py#L290) function (`model.solutions.store_to(result)`). Since I'll also fix some variables in each iteration, the `stale` flag of these variable will become `True` after solving. The fixed variables in each iteration may not be the same.
However, the store_to function will skip the variables whose `stale` flag is `True`.

```
if obj.stale:
    continue
```
Ref: https://github.com/Pyomo/pyomo/blob/1e3bb15da5107ac769bcfc029861b7b22e7c5949/pyomo/core/base/PyomoModel.py#L321

I quite understand that this will improve the efficiency of storing and loading solutions. However, if I am not loading the solution right after storing, it will cause some problems. For example, after 10 iterations, I wanna load the solution of the 3rd iteration. Since the variables fixed in iteration 3 and iteration 10 are not the same. The `stale` flag of all variables is not the same. The loading will be incomplete or even wrong.(There are many options in [`load_from`](https://github.com/Pyomo/pyomo/blob/1e3bb15da5107ac769bcfc029861b7b22e7c5949/pyomo/core/base/PyomoModel.py#L206) function to control these stuff. But I am not quite familiar ). 

I am now manually setting the `stale` flag to `True` before storing the solutions. Is it possible to add an option in the `store_to` function, which stops skipping the `stale=True` variables?

**Comment by blnicho** [comment]
@ZedongPeng seems like a reasonable use-case to me. Feel free to submit a PR with this change and we'll take a look.
