### ISSUE TITLE
mpec functionality doesn't work

### ISSUE THREAD

**Issue by damdaepark** [Pyomo/pyomo#1665]
Seems like Pyomo's _mpec_ module doesn't work.
Below is the code for testing it.

**Expected results:**
Either y-x**2+1 or y should be zero

**What I got:**
y-x**2+1 = 0.2426 and y = -0.4139

```
from pyomo.environ import *
from pyomo.mpec import *

M = ConcreteModel()
M.x = Var(bounds=(-1,2))
M.y = Var()

M.o  = Objective(expr=(M.x - 1 - M.y)**2)
M.c1 = Constraint(expr=M.x**2 <= 2)
M.c2 = Constraint(expr=(M.x - 1)**2 + (M.y - 1)**2 <= 3)
M.c3 = Complementarity(expr=complements(M.y - M.x**2 + 1 >= 0, M.y >= 0))

solver = SolverFactory('ipopt')
results = solver.solve(M, tee=True)
```

Below is the version I'm using

```
>>> import pyomo
>>> print(pyomo.__version__)
5.7.1
```

**Comment by emma58** [comment]
You are missing a call to a transformation: Before you call solve, you need something like 
```
TransformationFactory('mpec.simple_nonlinear').apply_to(M)
```
Though you may need to check the assumptions: I think the transformation may assume your variables are non-negative.

**Comment by jsiirola** [comment]
This is another case where writers not complaining about unrecognized active components is causing user issues.  See the discussion on #309 for more background.  I would advocate leaving this issue open until that root problem is resolved.

**Comment by damdaepark** [comment]
Applying the mpec transformation is working for this problem as  @emma58 said.

But it seems like that this Complementarity function doesn't support the _(Set, rule=)_ approach, which other Pyomo functions generally do.

I hope this to be covered in the later releases.

Thanks to all.

**Comment by whart222** [comment]
@emma58 I don't think the transformation makes assumptions about variable bounds.

**Comment by whart222** [comment]
@damdaepark The Complements() component is supposed to work with the (Set, rule=) syntax.  If you have an example where it does not work, please share it.

**Comment by emma58** [comment]
@whart222, okay, I wondered. The docstring needs updating then.

**Comment by damdaepark** [comment]
(Set, rule=) syntax worked as @whart222 mentioned.

I figured out that the problem was from using _mpec_ in combination with _dae_, such as:

```
from pyomo.environ import *
from pyomo.mpec import *
from pyomo.dae import *

m = ConcreteModel()

m.t = ContinuousSet(bounds=(0, 1))
m.x = Var(m.t, bounds=(-1,1))
m.y = Var(m.t, bounds=(-1,1))
m.o  = Objective(rule=lambda m: sum((m.x[i] - 1 - m.y[i])**2 for i in m.t))
m.c1 = Constraint(m.t, rule=lambda m, i: m.x[i]**2 <= 2)
m.c2 = Constraint(m.t, rule=lambda m, i: (m.x[i] - 1)**2 + (m.y[i] - 1)**2 <= 3)
m.c3 = Complementarity(m.t, rule=lambda m, i:(m.y[i] - m.x[i]**2 + 1 >= 0, m.y[i] >= 0))

TransformationFactory('dae.finite_difference').apply_to(m, wrt=m.t, nfe=1)
TransformationFactory('mpec.simple_nonlinear').apply_to(m)

solver = SolverFactory('ipopt')
results = solver.solve(m, tee=True)
```

In this case, I got the error as below:

> **Exception has occurred: TypeError**
> Found component Unit.con_mpec2 of type <class 'pyomo.mpec.complementarity.Complementarity'> indexed by a ContinuousSet. Components of this type are not currently supported by the automatic discretization transformation in pyomo.dae. Try adding the component to the model after discretizing. Alert the pyomo developers for more assistance.
> 

And reversing sequences like below doesn't work at all.
```
TransformationFactory('mpec.simple_nonlinear').apply_to(m)
TransformationFactory('dae.finite_difference').apply_to(m, nfe=2, wrt=m.t)
```

So I choose to reformulate the problem without _mpec_.

Thanks to all.
