### ISSUE TITLE
Solver doesn't show solution

### ISSUE THREAD

**Issue by marph91** [Pyomo/pyomo#1666]
Hi,
I just started using pyomo and experienced a strange behaviour. When solving via command line, a solution is displayed. When solving via `SolverFactory.solve()`, solving succeeds, but the solution isn't displayed.

[MWE](https://pyomo.readthedocs.io/en/stable/pyomo_overview/simple_examples.html):
```
import pyomo.environ as pyo

model = pyo.ConcreteModel()
model.x = pyo.Var([1,2], domain=pyo.NonNegativeReals)
model.OBJ = pyo.Objective(expr = 2*model.x[1] + 3*model.x[2])
model.Constraint1 = pyo.Constraint(expr = 3*model.x[1] + 4*model.x[2] >= 1)
```

Solving via command line `pyomo solve simple.py --solver='glpk'`. The last part of `results.yaml` looks as follows:
```
# ----------------------------------------------------------
#   Solution Information
# ----------------------------------------------------------
Solution: 
- number of solutions: 1
  number of solutions displayed: 1
- Gap: 0.0
  Status: feasible
  Message: None
  Objective:
    OBJ:
      Value: 0.666666666666666
  Variable:
    x[1]:
      Value: 0.333333333333333
  Constraint: No values
```

Solving via `SolverFactory.solve()` by adding the following lines to the script:
```
opt = pyo.SolverFactory('glpk')
results = opt.solve(model, tee=True)
print(results)
```
Output:
```
> python3 simple.py

...

Solver: 
- Status: ok
  Termination condition: optimal
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
  Error rc: 0
  Time: 0.009434223175048828
Solution: 
- number of solutions: 0
  number of solutions displayed: 0
```

I'm using Opensuse 15.2 with Python 3.7.6 and pyomo 5.7.1. This issue might be related to #910.

**Comment by DLWoodruff** [comment]
Take a look here:

https://pyomo.readthedocs.io/en/stable/working_models.html#accessing-variable-values

**Comment by marph91** [comment]
Thanks for the hint. When applying this, I can access the variables. But the printout of the solutions still seems to be wrong.

**Comment by KrishnaThali** [comment]
If you want the optimized results, you can use: 

model.get_values() and store it into a variable.

Hope this helps..

**Comment by mrmundt** [comment]
Hello, @marph91. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
