### ISSUE TITLE
Incomplete result of IPOPT

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#1671]
I am using ipopt to solve NLP.
A simple example is below:

```
import pyomo.environ as pyo
model = pyo.ConcreteModel()
model.x1 = pyo.Var(bounds=(1, 5), initialize=1.0)
model.x2 = pyo.Var(bounds=(1, 5), initialize=5.0)
model.x3 = pyo.Var(bounds=(1, 5), initialize=5.0)
model.x4 = pyo.Var(bounds=(1, 5), initialize=1.0)
model.obj = pyo.Objective(
    expr=model.x1*model.x4*(model.x1 + model.x2 + model.x3) + model.x3)
model.inequality = pyo.Constraint(
    expr=model.x1*model.x2*model.x3*model.x4 >= 25.0)
model.equality = pyo.Constraint(
    expr=model.x1**2 + model.x2**2 + model.x3**2 + model.x4**2 == 40.0)

ipopt = pyo.SolverFactory('ipopt')
results = ipopt.solve(model)
print(results)
model.obj.display()
```

The output is 

```
Problem: 
- Lower bound: -inf
  Upper bound: inf
  Number of objectives: 1
  Number of constraints: 2
  Number of variables: 4
  Sense: unknown
Solver: 
- Status: ok
  Message: Ipopt 3.12.12\x3a Optimal Solution Found
  Termination condition: optimal
  Id: 0
  Error rc: 0
  Time: 0.0436861515045166
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

obj : Size=1, Index=None, Active=True
    Key  : Active : Value
    None :   True : 17.014017257042685
```

Obviously, the lower bound and upper bound is not successfully passed to `results`.

Can this be fixed?

**Comment by jsiirola** [comment]
What output are you expecting?  Ipopt is a local solver and does not provide any bounding information.  Are you expecting the final objective value to also be reported as the upper bound for the problem?

**Comment by ZedongPeng** [comment]
> What output are you expecting? Ipopt is a local solver and does not provide any bounding information. Are you expecting the final objective value to also be reported as the upper bound for the problem?

Yes. If I use ipopt from GAMS, the upper bound will be provided.
Btw, I am not sure the value of the lower bound should be unified. `nan` from GAMS and `-inf` from direct ipopt.

```
Problem: 
- Name: /var/folders/pj/1113b24j7b3083zbt19pjxqm0000gn/T/tmpzzd3teqg/model.gms
  Lower bound: nan
  Upper bound: 17.0140172890097
  Number of objectives: 1
  Number of constraints: 3.0
  Number of variables: 5.0
  Number of binary variables: None
  Number of integer variables: 0.0
  Number of continuous variables: 5.0
  Number of nonzeros: 13.0
  Sense: minimize
Solver: 
- Name: GAMS (30, 3, 0, 0)
  Status: ok
  Return code: 0
  Message: None
  User time: 0.069000455550849
  System time: None
  Wallclock time: None
  Termination condition: locallyOptimal
  Termination message: None
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

obj : Size=1, Index=None, Active=True
    Key  : Active : Value
    None :   True : 17.014017289009697
```

**Comment by blnicho** [comment]
> Btw, is it efficient to use the value() function to calculate the objective value? 

Yes, in fact the `pyo.value()` function is the recommended way to access the objective value

`pyo.value(model.obj)`

**Comment by ZedongPeng** [comment]
> > Btw, is it efficient to use the value() function to calculate the objective value?
> 
> Yes, in fact the `pyo.value()` function is the recommended way to access the objective value
> 
> `pyo.value(model.obj)`

Thanks. I think this issue can be closed.
