### ISSUE TITLE
Using CoolProp inside Pyomo model

### ISSUE THREAD

**Issue by icarofvilasboas** [Pyomo/pyomo#1689]
I'm trying to use CoolProp functions inside a Pyomo model, but an error occurs when I run an command like:
`cp_work_fluid = PropsSI('C','P',101325,'T',Tm + 273.15,'INCOMP::S800')`
where Tm is an Pyomo Var type and this message is shown:
```
TypeError: Implicit conversion of Pyomo NumericValue type `sum' to a float is
disabled. This error is often the result of using Pyomo components as
arguments to one of the Python built-in math module functions when
defining expressions. Avoid this error by using Pyomo-provided math
functions.
```
How can I use CoolProp to calculate thermodynamic properties of fluids? If I can't use this, is there a library that works with pyomo?

**Comment by mrmundt** [comment]
Hello, @icarofvilasboas. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
