### ISSUE TITLE
Two questions related with .nl and .osil file formats

### ISSUE THREAD

**Issue by ozancakiroglu95** [Pyomo/pyomo#1691]
I have a few questions,

1) I want to write my model inside ".osil" file but it gives "NotImplementedError" although it looks among supported file formats. Did you remove OSIL file writer from Pyomo? If so, are you planning to include it again at the future?

2) Is there any way of reading ".nl" files and solving it with Pyomo? (i.e: by connecting to AMPL Solver Library)

Thanks in advance

**Comment by mrmundt** [comment]
Hello, @ozancakiroglu95. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
