### ISSUE TITLE
bilevel is not working

### ISSUE THREAD

**Issue by zwenju** [Pyomo/pyomo#1700]
Dear pyomo team,

I try to use pyomo bilevel to solve the following problem,  however,  the code is not working.
Could you give me some help ?
Best
`
import pyomo.environ  as pe
from pao.bilevel import *

M = pe.ConcreteModel()
M.lamb1 = pe.Var(within = pe.NonNegativeReals, initialize=0.5)
M.lamb2 = pe.Var(within = pe.NonNegativeReals, initialize=0.5)
M.sub = SubModel()
M.sub.y = pe.Var(within = pe.Reals, bounds = (0,1), initialize=0.5)
M.sub.x = pe.Var(within = pe.Reals, bounds = (0,1), initialize=0.5)

def obj(M):   
    model = M.model()
    FO = - model.sub.y + model.lamb1 * ( 2 * model.sub.x * model.sub.y \
                            + model.sub.x * model.sub.x \
                            - model.sub.y * model.sub.y - model.sub.x) \
        + model.lamb2 * ( - model.sub.x * model.sub.y \
                            - 0.3 * model.sub.x * model.sub.x \
                            - 0.2 * model.sub.y * model.sub.y \
                            - 0.5 * model.sub.x  \
                            + 1.5 * model.sub.y )  
    return FO

M.sub.o = pe.Objective(rule= obj, sense=pe.minimize)                   
M.o = pe.Objective(rule= obj, sense=pe.maximize)
opt = pe.SolverFactory('ipopt')

status = opt.solve(M)
print (value(M.o), value (M.lamd1), value(M.lamd2) )

`

![image](https://user-images.githubusercontent.com/27112868/98822397-c4653600-246b-11eb-8150-f7bba62c5166.png)

**Comment by emma58** [comment]
This is related to #309. 

@zwenju, the `SubModel` component is silently ignored when the model is passed to ipopt (since ipopt cannot handle bilevel problems directly). You will need to use a bilevel-specific solver or transformation available from PAO.

**Comment by emma58** [comment]
This is a bug, but since it is already logged in #309, I'm closing this issue.

@zwenju, if you encounter any issues with PAO going forward, please raise them on https://github.com/or-fusion/pao.

**Comment by zwenju** [comment]
Thank you  Johnson。
