### ISSUE TITLE
Error from PyNumero: Variables fixed using bounds is not currently supported

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#1701]
I am using the `evaluate_hessian_lag` function in PyNumero. 
I tested it with many examples(the integral relaxation of MINLPs). For some example, it reports the error
> RuntimeError: Variables fixed using bounds is not currently supported.

The related code in Pynumero is [here](https://github.com/Pyomo/pyomo/blob/a37b3ce0ac8511eff7c4535f0a105af072359743/pyomo/contrib/pynumero/interfaces/ampl_nlp.py#L140)

An example that will report this error is [here](https://github.com/grossmann-group/pyomo-MINLP-benchmarking/blob/14c45bf2f9c8b8a75265272e1857e30119810e93/models_nonconvex_simple2/casctanks.py#L345) 

The above definition can not easily be avoided if I choose to automatically generate pyomo model files from gams model files.

I saw the comment `# TODO: is the "fixed" check necessary?` in [line 133](https://github.com/Pyomo/pyomo/blob/a37b3ce0ac8511eff7c4535f0a105af072359743/pyomo/contrib/pynumero/interfaces/ampl_nlp.py#L133).

Can Pynumero support variables fixed using bounds with minor updates?

Thanks.

**Comment by michaelbynum** [comment]
This will require some thought and discussion. This should probably be an algorithm specific check rather than an AslNLP check. One easy workaround would be to actually fix any variables that are implicitly fixed by their bounds before handing the model to PyNumero.

**Comment by bernalde** [comment]
Is this a common enough change to be written as a Pyomo transformation?

**Comment by bknueven** [comment]
Bumping this issue. I'm running into this using the `evaluate_jacobian` method on `PyomoNLP` (through IDAES). In our example, we have variables with tiny *actual* bounds (e.g., `(1e-10, 1e-8)`). (In practice this variable is scaled.)

It would be straightforward to change this check to use [`numpy.isclose`](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html) with carefully chosen `atol` and `rtol`.

**Comment by Robbybp** [comment]
Should this be closed now that https://github.com/Pyomo/pyomo/pull/2121 is merged?
