### ISSUE TITLE
Access Duals with pyomo's Kernel lib

### ISSUE THREAD

**Issue by iamharshit** [Pyomo/pyomo#1704]
Hi Pyomo Team,

Keep up the Great work!

Actually Was trying to access the dual variable's value with [pyomo's kernel library](https://pyomo.readthedocs.io/en/stable/library_reference/kernel/index.html#the-kernel-library). 
Though tried accessing duals via the [same method (as in our regular aml lib)](https://pyomo.readthedocs.io/en/stable/library_reference/kernel/index.html#the-kernel-library) but no success. 

(Couldn't find same in pyomo's docs, hence opening an issue)

**Comment by mrmundt** [comment]
@ghackebeil - Is this an available feature in `kernel`?

**Comment by ghackebeil** [comment]
Yes, it works the same. Very likely this has to do with the solver just not returning duals with the solution.

**Comment by mrmundt** [comment]
Thanks, @ghackebeil

Given that it should work, @iamharshit , for help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
