### ISSUE TITLE
Explanation of keyword arguments 'solver_capability' classpyomo.repn.plugins.gams_writer.ProblemWriter_gams missing in the documentation

### ISSUE THREAD

**Issue by BrunoMorabito** [Pyomo/pyomo#1715]
The explanation solver_capabilityis missing from this class. What do we need to pass into this argument?
```
class ProblemWriter_gams(AbstractProblemWriter):

    def __init__(self):
        AbstractProblemWriter.__init__(self, ProblemFormat.gams)

[docs]    def __call__(self,
                 model,
                 output_filename,
                 solver_capability,
                 io_options):
        """
        Write a model in the GAMS modeling language format.

        Keyword Arguments
        -----------------
        output_filename: str
            Name of file to write GAMS model to. Optionally pass a file-like
            stream and the model will be written to that instead.
        io_options: dict
            - warmstart=True
                Warmstart by initializing model's variables to their values.
            - symbolic_solver_labels=False
                Use full Pyomo component names rather than
                shortened symbols (slower, but useful for debugging).
            - labeler=None
                Custom labeler. Incompatible with symbolic_solver_labels.
            - solver=None
                If None, GAMS will use default solver for model type.
            - mtype=None
                Model type. If None, will chose from lp, nlp, mip, and minlp.
            - add_options=None
                List of additional lines to write directly
                into model file before the solve statement.
                For model attributes, <model name> is GAMS_MODEL.
            - skip_trivial_constraints=False
                Skip writing constraints whose body section is fixed.
            - file_determinism=1
                | How much effort do we want to put into ensuring the
                | GAMS file is written deterministically for a Pyomo model:
                |     0 : None
                |     1 : sort keys of indexed components (default)
                |     2 : sort keys AND sort names (over declaration order)
            - put_results=None
                Filename for optionally writing solution values and
                marginals.  If put_results_format is 'gdx', then GAMS
                will write solution values and marginals to
                GAMS_MODEL_p.gdx and solver statuses to
                {put_results}_s.gdx.  If put_results_format is 'dat',
                then solution values and marginals are written to
                (put_results).dat, and solver statuses to (put_results +
                'stat').dat.
            - put_results_format='gdx'
                Format used for put_results, one of 'gdx', 'dat'.

        """
```

**Comment by blnicho** [comment]
I think the `solver_capability` is a way of checking if a model has features that are compatible with a particular solver but I'm not sure what the expected type is or how this argument interacts with the overall Pyomo solver infrastructure. Since the GAMS solver/interface is a way to access a wide variety of sub-solvers that handle many different types of problems, I'm not sure it makes sense to specify anything for the `solver_capability` in this case.

**Comment by jsiirola** [comment]
`solver_capability` is a holdover from the original design of `coopr.opt`, where the solver was independent of the problem writer.  The `solver_capability` was a way for the solver to negotiate with the writer to get the input file written out in the correct format.  For most interfaces (especially "meta" solver interfaces like the GAMS writer), it should be sufficient to just pass it `lambda x: True`.

**Comment by gseastream** [comment]
I think writers are usually called via `model.write(...)`, which seems to take a default of `None` for `solver_capability`. But if calling the writer directly via `WriterFactory(format)`, I suppose it seems weird to require that argument and not have a default.

**Comment by mrmundt** [comment]
Hello, @BrunoMorabito. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
