### ISSUE TITLE
CPLEX ERROR: CPLEX Error  5002: 'c_e_x40335_' is not convex.

### ISSUE THREAD

**Issue by LeoHenrik** [Pyomo/pyomo#1723]
I have a model that have somo quadratic constraint how can i set cplex? or what can i do to make cplex work?

**Comment by mrmundt** [comment]
Hello, @LeoHenrik. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
