### ISSUE TITLE
Problem Param mutable 

### ISSUE THREAD

**Issue by LeoHenrik** [Pyomo/pyomo#1726]
I declare two Param mutable:

model.c = pe.Set(initialize=range(0, 80)) 
model.F_value= pe.Param(model.c, initialize=0, mutable=True)
model.s_value = pe.Param(initialize=10, mutable=True)
model.F = pe.Var(model.c)

I'm using this parameter in constraints but i have problems when pyomo tries to read that parameter

def eq_Fe_d_l_rule(model,c):
     return model.Fe_d[c] <=  min(model.Bu[c] - model.Fe_disc[c] , model.s_value)
 model.eq_Fe_l_g = pe.Constraint(model.c, rule=eq_Fe_d_l_rule)

def eq_Fe_eq_rule(model,c):
       return model.F[c]== (model.Fe_disc[c]) + model.Fe_d[c]
model.eq_Fe_eq = pe.Constraint(model.c,rule=eq_Fe_eq_rule)

ValueError: Constraint 'eq_Fe_l_g[0]' encountered a strict inequality expression ('>' or '<'). All constraints must be formulated using using '<=', '>=', or '=='.

Pyomo 5.6.9 (CPython 3.8.1 on Windows 10)

I tried debug the problem and read the param when I tried to read as: 

model.Fe_disc[0]
<pyomo.core.base.param._ParamData object at 0x1A5A7928>

the only way that I read was doning model.Fe_disc[0].value and I get the informacion of the parameter but i tried using that in the constraint but when i did that i couldn chainge the value of the parameter after run the modal.

**Comment by blnicho** [comment]
The problem is that you're trying to use Python's built-in `min` function in a Pyomo expression which is not supported.
