### ISSUE TITLE
[PEP] Python Version Support

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1730]
This is a proposal regarding Pyomo's commitment for Python version support. I propose we support each minor Python version until it's documented end-of-life (https://devguide.python.org/devcycle/#end-of-life-branches). At the time of the first Pyomo release after the end-of-life of a minor python version, we would remove tests for said Python version (probably right after the release). This would then allow future pull requests to include features that are incompatible with older Python versions. If this proposal is accepted, we would immediately drop support (and stop testing) for both Python 2.7 and Python 3.5 since both have already reached their end-of-life. Additionally, dropping a minor python version would result in bumping the minor Pyomo version (i.e., you cannot drop support for a Python version in a patch release).

**Comment by jsiirola** [comment]
I agree with this (and I believe that this was generally agreed to in a Dev/PMC meeting).  I believe that the Dev team / PMC have already agreed that Pyomo 5.7.2 will be the last release supporting Python 2.7 and 3.5, with 6.0 only supporting 3.6 - 3.9.

I would like to propose that dropping a minor python version would result in bumping the minor Pyomo version (i.e., you cannot drop support for a Python version in a patch release).

**Comment by michaelbynum** [comment]
Agreed. Nice clarification.

**Comment by michaelbynum** [comment]
I updated the PEP based on suggestions from @jsiirola

**Comment by michaelbynum** [comment]
This PEP has been approved. We will close this issue after I update the online docs.
