### ISSUE TITLE
Update manylinux builder once Python 3.9 is added

### ISSUE THREAD

**Issue by mrmundt** [Pyomo/pyomo#1754]
We use a Marketplace GitHub Action to build our manylinux wheels for release. The main branch of this does not yet have Python 3.9 support, but there is a PR waiting for approval that would add it:

https://github.com/RalfG/python-wheels-manylinux-build/pull/33

Once this PR is merged, we will need to update the release workflow.

**Comment by blnicho** [comment]
@mrmundt looks like the PR you were waiting on was merged a couple days ago.

**Comment by mrmundt** [comment]
@blnicho - Yup! I integrated the change into the Python 2.7 removal PR (#1763)
