### ISSUE TITLE
Assistance on collecting solutions within CPLEX and retrieving them from PYOMO

### ISSUE THREAD

**Issue by blendmeister** [Pyomo/pyomo#1767]
I would like to seek some advice on modeling the following:

I am currently invoking solvers, CPLEX, in particular, via Pyomo.

As I am solving my problem sequentially, i.e., the top-level subproblem results are being used to generate the model of the next subproblem.

To prevent cycling and suboptimality, I would like to be able to retrieve all the solutions of the top-level subproblem so as to generate and solve all possible realizations of the next subproblem.

Appreciate your kind guidance.

Thank you!

**Comment by adowling2** [comment]
Can you post a minimum working example or a toy problem that shows the subproblems?

**Comment by mrmundt** [comment]
Hello, @blendmeister. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
