### ISSUE TITLE
Is NEOS solver in Pyomo package updated?

### ISSUE THREAD

**Issue by KrishnaThali** [Pyomo/pyomo#1784]
As per the link from NEOS twitter page, they say an Email address needs to be added before submitting the job. Is the pyomo for NEOS solver updated accordingly? Please find the links below for more info:

https://twitter.com/NeosOpt/status/1336360894884966401

https://neos-guide.org/content/FAQ#email - Refer to 10th question.

Request you to please provide the update ASAP.

**Comment by blnicho** [comment]
This was fixed in #1782 and #1783.
