### ISSUE TITLE
Pyomo model solver weird error message

### ISSUE THREAD

**Issue by ijokeke** [Pyomo/pyomo#1787]
I received this error message (pix attached) when I tried solving a PDE problem in pyomo using IPOPT. Please can someone give an insight on what could be causing the issue. Thanks!
![Error message](https://user-images.githubusercontent.com/76780006/104464871-6ba43d80-5581-11eb-9a60-d42d4874e77a.PNG)

**Comment by blnicho** [comment]
Could you share your model implementation?

**Comment by ijokeke** [comment]
Hi Bethany,

How are you doing? Nice to hear from you again. You most likely wouldn't
remember me; we met at the FOCAPD 2019 during the IDAES workshop.

Anyways, about sharing my model, do you want me to share it with you via
Teams or other platforms?

Regards,
Ikenna

**Comment by blnicho** [comment]
If you can add it to this GitHub issue that would be most convenient otherwise you can email it to me.

**Comment by ijokeke** [comment]
Ok. I have attached the model in this email. I am curious to know why Pyomo
is returning the weird error message that this stage of the model
development.

Thanks!

**Comment by blnicho** [comment]
@ijokeke when you reply to a GitHub email it strips the attachment off and posts your response on GitHub. You'll have to either add your model to the GitHub issue via the website interface (preferred if the model is small and not proprietary) or email it to me at blnicho (at) sandia (dot) gov.

**Comment by blnicho** [comment]
This has been resolved off-line. The issue was adding `DerivativeVar` components to the model **after** applying the discretization transformations.
