### ISSUE TITLE
Bug in mindtpy: Two undefined functions

### ISSUE THREAD

**Issue by mrmundt** [Pyomo/pyomo#1799]
@bernalde 

In `pyomo.contrib.mindtpy.nlp_solve`, there is this section (lines 184-189):

```
    elif config.strategy == 'PSC':
        # !!THIS SEEMS LIKE A BUG!! - mrmundt #
        add_psc_cut(solve_data, config)
    elif config.strategy == 'GBD':
        # !!THIS SEEMS LIKE A BUG!! - mrmundt #
        add_gbd_cut(solve_data, config)
```

The two functions `add_psc_cut` and `add_gbd_cut` are undefined. Are these living on a branch somewhere and need to be added, or at the very least, can an exception be raised?

**Comment by ZedongPeng** [comment]
We will remove these two functions in the next PR.

**Comment by ZedongPeng** [comment]
We have commented the related code in PR #1847 .

**Comment by ZedongPeng** [comment]
Since PR #1847 has fixed this issue, I think this issue can be closed.
