### ISSUE TITLE
Window pops up when calling a solver

### ISSUE THREAD

**Issue by antvig** [Pyomo/pyomo#183]
I use Pyomo from matlab.
When a solver is called, a window pops up. 

I avoided this behavior by setting shell argument to TRUE in the run function (module shellcmd).
However, I'm not sure it is the best way to do it...

    def _execute_command(self,command):
        """
        Execute the command
        """

        start_time = time.time()

        try:
            if 'script' in command:
                _input = command.script
            else:
                _input = None

            [rc, log] = run(
                command.cmd,
                stdin = _input,
                timelimit = self._timelimit,
                env   = command.env,
                tee   = self._tee,
                shell = True
             )
        except WindowsError:
            err = sys.exc_info()[1]
            msg = 'Could not execute the command: %s\tError message: %s'
            raise ApplicationError(msg % (command.cmd, err))
        sys.stdout.flush()

        self._last_solve_time = time.time() - start_time

        return [rc,log]

**Comment by blnicho** [comment]
@antvig it is not clear from your comment if you have a question or if this is even really Pyomo-related so I'm closing this. Submit a new issue with more information if you are still having trouble.

**Comment by gvkcps** [comment]
I am having the same problem @antvig, when I call the pyomo solve function from Matlab a cmd window pops up everytime... Could you elaborate on how you solved this problem? What's the location of this module shellcmd that you modified? Thanks.
