### ISSUE TITLE
Encapsulate hierarchical block parameters

### ISSUE THREAD

**Issue by kornerc** [Pyomo/pyomo#1846]
Dear Pyomo-Team,

I want to make a hierarchical Pyomo block library (Pyomo version 5.7.3).
E.g. write a block for an ideal energy storage then write another block which extends the ideal energy block with added losses.
When initializing such a block which consists of sub-blocks, I want to have the sub-blocks encapsulated, so that I don't have to care how the internal structure of the sub-blocks.

Below is an example of how I envision this, where the functionality of the block `inner` is extended with functionality of the block `outer`.
```python
from pyomo.environ import *


def inner():
    """
    Inner block
    """
    block = Block()

    block.i_min = Param(domain=Reals)
    block.i_max = Param(domain=Reals)

    block.i = Var(bounds=(block.i_min, block.i_max))

    return block


def outer():
    """
    Outer block
    """
    block = Block()

    # add a nested block "inner"
    block.inner = inner()

    block.offset = Param(domain=Reals)

    block.o = Var(domain=Reals)
    block.o_rule = Constraint(rule=lambda b: b.o == b.inner.i + b.offset)

    return block


model = AbstractModel()

# the model consist of a block "outer" which in turn has a nested block "inner"
model.outer = outer()

model.obj = Objective(expr=model.outer.o)

instance = model.create_instance(data={None: {
    'outer': {None: {
        'offset': {None: .1},
        'inner': {None: {
            'i_min': {None: -2.},
            'i_max': {None: 2.},
        }},
    }},
}})

solver = SolverFactory('glpk')
solver.solve(instance)
instance.pprint()
```
However, during initialization `create_instance()`, data has also to be provided for the block `inner`.
Instead I want to initialize the model in the following way.
```python
instance = model.create_instance(data={None: {
    'outer': {None: {
        'offset': {None: .1},
        'i_min': {None: -2.},
        'i_max': {None: 2.},
    }},
}})
```
To accomplish that I can modify the function `outer` but don't want to modify the function `inner`.

I tried to create duplicate parameters `i_min` and `i_max` in the `outer` block and couple them with the corresponding parameters of the block `inner`.
```python
def outer():
    block = Block()

    # duplicated parameters
    block.i_min = Param(domain=Reals)
    block.i_max = Param(domain=Reals)

    # add a nested block "inner"
    block.inner = inner()

    # link the parameters of the inner and outer block
    block.i_min_couple = Constraint(rule=lambda b: b.i_min == b.inner.i_min)
    block.i_max_couple = Constraint(rule=lambda b: b.i_max == b.inner.i_max)
    # ...
```
However, this results in an error and it feels wrong to couple parameters with constraints
```
ERROR: evaluating object as numeric value: outer.inner.i_min
        (object: <class 'pyomo.core.base.param.SimpleParam'>)
    Error retrieving immutable Param value (outer.inner.i_min):
    	The Param value is undefined and no default value is specified.
```
Is there a way in Pyomo of solving this issue?

Thanks in advance,
Clemens

**Comment by michaelbynum** [comment]
I recommend using concrete models for this application. If you use a concrete model, you can instantiate the model however you want.

**Comment by kornerc** [comment]
@michaelbynum thank you for your reply.
With a concrete model, the code from above could be similar to this:
```python
from pyomo.environ import *


def inner(i_min, i_max):
    """
    Inner block
    """
    block = Block()

    block.i_min = Param(domain=Reals, initialize=i_min)
    block.i_max = Param(domain=Reals, initialize=i_max)

    block.i = Var(bounds=(block.i_min, block.i_max))

    return block


def outer(offset, i_min, i_max):
    """
    Outer block
    """
    block = Block()

    # add a nested block "inner"
    block.inner = inner(i_min=i_min, i_max=i_max)

    block.offset = Param(domain=Reals, initialize=offset)

    block.o = Var(domain=Reals)
    block.o_rule = Constraint(rule=lambda b: b.o == b.inner.i + b.offset)

    return block


model = ConcreteModel()

# the model consist of a block "outer" which in turn has a nested block "inner"
model.outer = outer(i_min=-2., i_max=2., offset=.1)

model.obj = Objective(expr=model.outer.o)

solver = SolverFactory('glpk')
solver.solve(model)
model.pprint()
```

Nevertheless, do you see any possibility that something similar could also be achieved with an abstract model?
I was also having a look into manipulating the attribute `_decl_order` to achieve that but without any success (which would be of course bad practice because this is a private attribute).

If this is not the case I'll will adjust my implementation to use concrete models instead of abstract models.

**Comment by jsiirola** [comment]
You can make something work for Abstract models, but it ends up being rather convoluted (for the record, I agree with @michaelbynum that this is better implemented using concrete models, or as you originally noted with nested data).  The trick to get what you want is to rely on a *mutable* `Param` and "fix up" the inner `Param` value *after* it is constructed using a `BuildAction` (basically a callback that is run during the model construction process):
```python
from pyomo.environ import *

def inner():
    """
    Inner block
    """
    block = Block()

    block.i_min = Param(domain=Reals, mutable=True)
    block.i_max = Param(domain=Reals, mutable=True)

    block.i = Var(bounds=(block.i_min, block.i_max))

    return block

def outer():
    """
    Outer block
    """
    block = Block()

    # add a nested block "inner"
    block.inner = inner()

    block.offset = Param(domain=Reals)

    # duplicated parameters
    block.i_min = Param(domain=Reals)
    block.i_max = Param(domain=Reals)

    # Propagate local Params to the inner block
    @block.BuildAction()
    def propagate_i_values(b):
        b.inner.i_min = value(b.i_min)
        b.inner.i_max = value(b.i_max)

    block.o = Var(domain=Reals)
    block.o_rule = Constraint(rule=lambda b: b.o == b.inner.i + b.offset)

    return block

model = AbstractModel()

# the model consist of a block "outer" which in turn has a nested block "inner"
model.outer = outer()

model.obj = Objective(expr=model.outer.o)

instance = model.create_instance(data={None: {
    'outer': {None: {
        'offset': {None: .1},
        'i_min': {None: -2.},
        'i_max': {None: 2.},
    }},
}})
```

**Comment by kornerc** [comment]
Thanks **a lot** for your quick replies and for solving this issue.

Now I know the two possibilities which are applicable!
