### ISSUE TITLE
No type() method for _BlockData, _DisjunctData, and _DisjunctionData

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#185]
If I have the model
```
m = ConcreteModel()
m.b = Block([0,1])
```
I would expect `m.b[0].type() is Block` to be true, but instead there is an AttributeError that _BlockData does not have the attribute 'type.' The same is also true for _DisjunctData and _DisjunctionData objects (that they don't have a type() attribute.)

**Comment by blnicho** [comment]
Have you updated your Pyomo checkout recently? When I try your code snippets on master they produce your expected result.

**Comment by emma58** [comment]
Oops, sorry. I meant `m.b[0].type()` I just updated, and I still get the AssertionError (when I am actually asking for the ctype of the _BlockData).

**Comment by qtothec** [comment]
@emma58 You can edit your original post. It seems that the idiom you've identified also applies to `Constraint` and `Var`:
```
m.v = Var([0, 1])
m.v[0].type() --> AttributeError
m.c = Constraint([0, 1])
m.c[0].type() --> DeveloperError
```

**Comment by jsiirola** [comment]
@qtothec:  this is now fixed for all IndexedComponents.  However, Constraints still produce exceptions:

```
m.c = Constraint([0,1])
m.c[0].type() --> KeyError
```
As Constraints cannot be created by default (unlike Var, Block, Disjunct, etc), accessing an undefined index generates a KeyError (mush like a dict would).
