### ISSUE TITLE
Only upload coverage for 'main' branch on Pyomo/pyomo

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#1860]
It appears that codecov does not differentiate between the `main` branch on `Pyomo/pyomo` and the main branch on forks.  As a result, whenever someone updates their fork, codecov reports the coverage for that fork on the main `Pyomo/pyomo` badge (and as the main report).

We should update the GHA driver o only upload coverage results for `main` branches originating from the `Pyomo/pyomo` fork.

(At the same time, we should rename the `.github/workflows/pr_master_test.yml` driver file).

**Comment by mrmundt** [comment]
@jsiirola - Are you referring to the `pr_main_test` or the `push_branch_test` file?

I ask because, in theory, the `push_branch_test` isn't supposed to run on `main`:
```
  push:
    branches-ignore:
      - main
```
