### ISSUE TITLE
Cannot iterate over uninitialized mutable param

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1862]
```
import pyomo.environ as pe

m = pe.ConcreteModel()
m.p = pe.Param([1, 2, 3], mutable=True)
for k, v in m.p.items():
    print(k, v)
```
Produces no output.

**Comment by jsiirola** [comment]
This is (unfortunately) intentional behavior, and arises from the decision to have the `IndexedComponent` iterators be sparse iterators by default.
