### ISSUE TITLE
How the python coding in Docker container calls Gurobi solver that is installed on other servers not in Docker container itself?

### ISSUE THREAD

**Issue by YanxiLiuuuu** [Pyomo/pyomo#1865]
Hello, 

I am trying to use a Docker container to call Gurobi solver, which is installed on other servers.  My project requires me to use Gurobi sovler, but I am not able to add a Gurobi solver into the Docker container. So, I am wondering if there a way that the python codings in Docker container can call Gurobi solver that is outsides the Docker containers. 

Thanks!

**Comment by mrmundt** [comment]
Hello, @YanxiLiuuuu. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
