### ISSUE TITLE
How to add to a set in pyomo?

### ISSUE THREAD

**Issue by SamiraFallah** [Pyomo/pyomo#1881]
I am trying to run this code (some important part of the code is here):

```
Master = AbstractModel()
Master.intIndices = Set(initialize=INTVARS)
Master.constraintSet = Set(initialize=CONS)
Master.conIndices = Set(initialize=CONVARS)
Master.intPartList = Set()

Master.dualVarSet = Master.constraintSet * Master.intPartList

Master.theta = Var(domain=Reals, bounds = (None, None))
Master.intVars = Var(Master.intIndices, domain=NonNegativeIntegers, bounds=(0, 10))
Master.dualVars = Var(Master.dualVarSet, domain=Reals, bounds = (None, None))
max_iters = 1000
opt = SolverFactory("couenne")
for i in range(max_iters):
    Master.intPartList.add(i)
```
    
but it shows me this error on the last line:
`RuntimeError: Cannot access add on AbstractOrderedSimpleSet 'intPartList' before it has been constructed (initialized).`

Can somebody help me?

**Comment by blnicho** [comment]
The problem is that you're working with an abstract model instead of a concrete model instance. I'd recommend changing your first line to:

`Master = ConcreteModel()`

**Comment by SamiraFallah** [comment]
I fixed the issue. The issue was that we were trying to change an object of the master before creating an instance which is not possible in the abstractModel. The quick way to fix it was to create a temporary python list and initialize the master object with that list and change the python list in each iteration. In summary, changing from:
```Master.intPartList = Set()
for i in range(max_iters):
  Master.intPartList.add(i)
  instance = Master.create_instance()```
 to:
 ```listTemp = []
Master.intPartList = Set(initialize=listTemp)
for i in range(max_iters):
  listTemp.append(i)
  instance = Master.create_instance()```

**Comment by SamiraFallah** [comment]
In our case, we have a MILNP that is changing in each iteration. That's why I used abstractModel instead of `concreteModel`. But I fixed the issue with the previous message. I added a temporary list, then I change the list in each iteration before initializing the master object. Thanks!

**Comment by jsiirola** [comment]
The problem with your solution is that it completely recreates the Master instance at each iteration.  This ends up being a $O(n^2)$ operation.

There are simpler ways to handle this by using a rule:
```python
def intPartList(m):
    return list(range(max_iters))
Master.intPartList = Set(initialize=intPartList)
```
or a `RangeSet`:
```python
Master.max_iters = Param(initialize=1000)
# Note that this makes a list 1 .. 1000 and not 0 .. 999
Master.intPartList = RangeSet(Master.max_iters)
```

That said, what you probably want to do is to create the Set as an empty set in the `Master` model, create the concrete instance *once*, and then add the new index to the set on the *concrete instance* within the loop (as well as any additional constraints, etc).  That way you don't recreate everything at every iteration, reducing the $O(n^2)$ operation to an $O(n)$ one.

**Comment by SamiraFallah** [comment]
I should have posted the whole code. My whole model must change in each iteration that is why I use an abstractModel. And we need to increment one of the sets and then initializing the master object. I guess the way that I did is the only way to do that. But if you could suggest to me any better ways that could reduce the order, I really appreciate it. 
You can see the whole code at this repository:
[(https://github.com/tkralphs/ValueFunction)]

**Comment by jsiirola** [comment]
While your model must change in each iteration, it is important to note that you are only *adding* cuts (not modifying or removing any previously-generated constraints).  The following is a way to avoid having to regenerate the entire model at each iteration, using a ConcreteModel as @blnicho suggested.  The trick is knowing that (at least for relatively current versions of Pyomo):
- it is OK to declare a Constraint over an empty Set (the correct thing happens and no constraints are generated)
- when you retrieve a valid index for (most) indexed objects and the index hasn't been created yet, then the object is created dynamically using the normal construction operations - including firing any relevant rules - before returning it to you.

I left the bulk of your model unchanged: edits are indicated by comments.
```python
# Concrete models are relaly the way to go in most situations, particularly for iterative algorithms like this
Master = ConcreteModel()
Master.intIndices = Set(initialize=INTVARS)
Master.constraintSet = Set(initialize=CONS)
Master.conIndices = Set(initialize=CONVARS)
# Declare this set to be empty: we will add members to it later during the loop
Master.intPartList = Set()
Master.dualVarSet = Master.constraintSet * Master.intPartList
Master.theta = Var(domain=Reals, bounds = (None, None))
Master.intVars = Var(Master.intIndices, domain=NonNegativeIntegers, 
                     bounds=(0, 10))
Master.dualVars = Var(Master.dualVarSet, domain=Reals, bounds = (None, None))

def objective_rule(model):
    return model.theta
Master.objective = Objective(rule=objective_rule, sense=maximize)

def theta_constraint_rule(model, k):
    return (model.theta <=
            sum(OBJ[j]*model.int_part_list[k][j] for j in INTVARS)
            - sum(OBJ[j]*model.intVars[j] for j in INTVARS)
            + sum(MAT[(i, j)]*model.dualVars[(i, k)]*(model.intVars[j] - 
                                                    model.int_part_list[k][j]) 
                for j in INTVARS for i in CONS))
Master.theta_constraint = Constraint(Master.intPartList,
                                     rule=theta_constraint_rule)

def dual_constraint_rule(model, j, k):
    return (sum(MAT[(i, j)]*model.dualVars[(i, k)] for i in CONS) <= OBJ[j])
Master.dual_constraint = Constraint(Master.conIndices, Master.intPartList,
                                    rule=dual_constraint_rule)

Master.int_part_list = [dict((i, 0) for i in INTVARS)]

debug_print = False
opt = SolverFactory("couenne")
for i in range(max_iters):
    # Note that as we are working with a ConcreteModel, we can directly manipulate 
    # it and don't have to create a new concrete instance in each iteration
    Master.intPartList.add(i)
    # Trigger the new constraints to be generated
    Master.theta_constraint[i]
    list(Master.dual_constraint[j, i] for j in Master.conIndices)
    # Solve the updated model
    results = opt.solve(Master)
    # The following is not needed: solutions are loaded automatically
    # Master.solutions.load_from(results)
    print('Solution in iteration', i) 
    #for j in Master.intVars:
    #    print(j, Master.intVars[j].value)
    # Personally, I prefer:
    Master.intVars.pprint()

    print('Theta:', Master.theta.value)
    if Master.theta.value < .01:
        print("Finished!")
        for int_part in Master.int_part_list:
            print('Solution:', int_part)
            print('Right-hand side: [',) 
            for k in CONS:
                print(sum(MAT[(k, l)]*int_part[l] 
                          for l in INTVARS),)
            print(']') 
        break
    if debug_print:
        for i in Master.dualVars:
            print(i, Master.dualVars[i].value)
        print(Master.dualVars[(0,0)].value)
        for k in range(len(Master.int_part_list)):
            for j in CONVARS:
                print(j, k, OBJ[j],) 
                print(sum(MAT[(i, j)]*Master.dualVars[(i, k)].value 
                          for i in CONS))
        for k in range(len(Master.int_part_list)):
            for j in INTVARS:
                print(k, sum((MAT[(i, j)])*Master.dualVars[(i, k)].value - 
                             OBJ[j] for i in CONS),)
    Master.int_part_list.append(dict((i, round(Master.intVars[i].value)) 
                                     for i in INTVARS))
```

**Comment by tkralphs** [comment]
Thanks, @jsiirola and @blnicho for this insight. Instance generation is not really a bottleneck, but I now see that it does make more sense to do this as a concrete model.

What was strange to me at first is that the original code was working at one time. I have a vague theory that it was working because the abstract set class is built on top of Python's set implementation, which has an `add()` method that was still working, although you might not have intended people to use it. It looks like you later realized should be disabled. One comment is that the error that you get when you try to use a disabled method is pretty hard to interpret. 
https://github.com/Pyomo/pyomo/blob/07b741f045b22552d94ff2cecc8b46df33f490c3/pyomo/core/base/util.py#L62-L86
If the problem is just that the user has called a method that is disabled, shouldn't the error just say that?

**Comment by jsiirola** [comment]
@tkralphs: Yup! There was a problem in the initial implementation of many of the "scalar" Pyomo components where they could be implicitly manipulated as if they were concrete components before they had been constructed.  This caused confusion at best and errors at worst.  A relatively recent (about a year ago) rewrite of the Set component made the scalar Set objects behave like their indexed counterparts and disallow any manipulation until after they have been constructed (i.e., you cannot manipulate an abstract component as if it were a concrete component).  We are (slowly) promulgating that to all the other Pyomo components as well.

Do you have a suggestion as to a more helpful exception message?

**Comment by SamiraFallah** [comment]
@jsiirola: Thanks! I thought we could not implement the algorithm with the `concreteModel`.  But as Dr. Ralphs said it would save time with not rebuilding the model in each iteration and probably would not change much the whole execution time. I need to do some experiments to see the difference if there are any.
Anyways, I am a newbie to pyomo and I would really appreciate the time and your consideration.

**Comment by tkralphs** [comment]
@jsiirola As a user without intimate knowledge of the implementation, I guess I fundamentally don't know what it means that the object cannot be manipulated until "after it is constructed (initialized)." In my mind, when an object is instantiated in Python, it's constructor is called and it therefore has been constructed by definition. I guess what you mean by "constructed" is something more like "initialized," meaning that there is a concrete data structure passed in that is storing the data, i.e., the constructor was called with the argument `initialize`. But that doesn't work either. If I do
```python
from pyomo.environ import *
m = AbstractModel()
myList = []
m.s = Set(initialize=myList)
m.s.add(i)
```
I get the same error. I realize now that this is not really the right thing to do, but the error that results seems to indicate this should work. After all, it says `cannot access add until ... has been constructed (initialized)`.

In playing around, it looks to me like one just cannot use the `add()` method under any circumstances with an abstract set. If that's the case, it seems more straightforward to just say "The `add()` method has been disabled and should not be used with abstract sets." If I'm wrong and it can actually be used in some circumstances, then I can make another suggestion once I understand when it can actually be used.

**Comment by tkralphs** [comment]
Nice, thanks!
