### ISSUE TITLE
Please install GAMS in Codecov testing framework

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#193]
I finally figured out why the coverage on my GAMS solver is so low. I'm pretty sure GAMS is not installed on whatever Codecov runs on. If you look at the coverage report for [pyomo/solvers/plugins/solvers/GAMS.py](https://codecov.io/gh/Pyomo/pyomo/src/540e3aba172a2ebc76404b1d25ff3b63eb92ebd0/pyomo/solvers/plugins/solvers/GAMS.py), it doesn't cover anything in the solve() methods. Instead, it appears to create both the 'direct'/'python' and the 'shell'/'gms' solvers, checks if they are available, realizes they are not, and then tells me it didn't really see all that much of my code.

![image](https://user-images.githubusercontent.com/28630589/28639897-d328fa14-7217-11e7-9014-609e81fe8538.png)

So, it'd be swell if GAMS could be installed in the testing framework? If so, be advised that in order to test the direct/python solver, the API needs to be installed, which is pretty straightforward. Instructions for that can be found [here](https://www.gams.com/latest/docs/apis/examples_python/index.html) in the first 2 sections of the page.

**Comment by ghackebeil** [comment]
Is GAMS free? If not, I don't think we would be able to install it on Travis.

**Comment by qtothec** [comment]
@ghackebeil The trial version of GAMS is free. You're limited to small models, but that should be sufficient for testing.

**Comment by ghackebeil** [comment]
If you can put together a set of bash commands that download GAMS (e.g., using wget) and install the python bindings, that should be pretty easy to incorporate it into the Travis file.

**Comment by qtothec** [comment]
```
wget https://d37drm4t2jghv5.cloudfront.net/distributions/24.8.5/linux/linux_x64_64_sfx.exe
chmod u+x linux_x64_64_sfx.exe
./linux_x64_64_sfx.exe
PATH=${PATH}:$CWD/gams24.8_linux_x64_64_sfx
python $CWD/gams24.8_linux_x64_64_sfx/apifiles/Python/api/setup.py install
```
This is kind of fragile, because it will break when the GAMS version changes. In addition, the path to the setup.py depends on the python version. As written, it works for 2.7. I'm also not sure if `$CWD` is a thing.

**Comment by gseastream** [comment]
@qtothec I don't think it will break when the version changes, since the 24.8.4 link is still an active link and downloads the version 24.8.4 version of the GAMS installer. Also, I don't think $CWD is a thing.

**Comment by ghackebeil** [comment]
Why don't you try adding that to the .travis file on your branch (somewhere around line 79). It's pretty straightforward, each line that starts with ` - ` is a new shell command. You can put it in an if statement based on the Python version if you want (there is an example just before that line).
