### ISSUE TITLE
Issue using component_objects method of pyomo.core.kernel.component_block.block

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#194]
When I integrated my GAMS solver into the pyomo.solvers testing infrastructure, I saw that it was erroring on the kernel tests. I got as far as I could to get my solver to support kernel blocks, but then I got an error trying to use the component_objects() and component_data_objects() methods of a kernel block. This error is replicated here:

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyomo.core.kernel import *
>>> block
<class 'pyomo.core.kernel.component_block.block'>
>>> variable
<class 'pyomo.core.kernel.component_variable.variable'>
>>> blob = block()
>>> blob.vee = variable()
>>> dir(blob)
['__abstractmethods__', '__class__', '__deepcopy__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getstate__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_active', '_byctype', '_child_storage_delimiter_string', '_child_storage_entry_string', '_ctype', '_decrement_active', '_flag_vars_as_stale', '_increment_active', '_is_categorized_object', '_is_component', '_is_container', '_order', '_parent', 'activate', 'active', 'block_data_objects', 'blocks', 'child', 'child_key', 'children', 'clone', 'collect_ctypes', 'component', 'component_data_objects', 'component_map', 'component_objects', 'components', 'ctype', 'deactivate', 'generate_names', 'getname', 'load_solution', 'local_name', 'name', 'parent', 'parent_block', 'postorder_traversal', 'preorder_traversal', 'preorder_visit', 'root_block', 'valid_problem_types', 'vee', 'write']
>>> list(blob.component_objects())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gseastre/pyomo/src/pyomo/pyomo/core/kernel/__init__.py", line 248, in _component_objects
    for component in self.components(*args, **kwds):
  File "/home/gseastre/pyomo/src/pyomo/pyomo/core/kernel/component_block.py", line 699, in components
    for item in child.components(
AttributeError: 'variable' object has no attribute 'components'
```

What is going on here? I see that the other solvers are able to pass the kernel tests (like cplex), but I can't figure out how to support it in my solver. Kernel blocks also seem to just require a completely different set of interactions with its own versions of certain attributes (for example they don't have a .type() method, something I use in my writer for regular models), so if I added support for kernels, would that really constitute creating 2 separate solvers, chosen based on whether it is a regular block or a kernel block? Because that is what it seems like to me...

Furthermore, should I even worry about supporting kernel tests? On the bright side, the GAMS solver passes all the other tests in pyomo.solvers.tests.checks.test_pickle, so it looks pretty good to me anyway :)

**Comment by ghackebeil** [comment]
This particular error has to do with how you are import the kernel. For now, it's meant to be used through the `import pyomo.kernel` namespace. If you use things directly from `pyomo.core.kernel` before importing `pyomo.kernel`, it skips some critical setup.

I would say don't worry about supporting kernel for now. I'll be able to quickly scan through the GAMS writer and find the spots that need to be fixed.

**Comment by gseastream** [comment]
The error code shown above is the same error produced by the nosetests themselves, so whatever the tests do, it gets the same `'variable' object has no attribute 'components' error` when I try to iterate through component_objects(). Either way, I'm fine leaving it aside.

**Comment by ghackebeil** [comment]
I can't find any kernel test models that forget to use the `pyomo.kernel` import (at least on master). Did you add any new models? If not, can you give me more specifics on which test this occurred on so I can chase down a possible bug?

**Comment by gseastream** [comment]
Yeah so I just finished running the nosetests again to see the error, and it actually does get through iterating through component_objects()... Not sure why I remembered otherwise. Sorry 'bout that. I'll bring let you know if some similar error shows up again.

**Comment by gseastream** [comment]
I went through and got the solver to support kernels. It wasn't too bad, but I did add an analog of the labeler attribute to the ICategorizedObject class, the same thing that was added to the ComponentData class for regular models in order to handle labeling of components when written to the model file. It passes all the test_pickle tests now.

As a side note/new question, for some reason I am unable to execute `from pyomo.kernel import block` within a script, but the same command works in an interactive python prompt. Is there any reason for this? I was able to get around it by importing from pyomo.core.kernel, which didn't cause an issue because I only needed the class references for comparisons. Here is the error code I got:

```
Traceback (most recent call last):
  File "/home/gseastre/pyomo/src/pyomo/pyomo/solvers/tests/checks/test_pickle.py", line 23, in <module>
    from pyomo.solvers.tests.models.base import test_models
  File "/home/gseastre/pyomo/src/pyomo/pyomo/solvers/tests/models/__init__.py", line 11, in <module>
    import pyomo.solvers.tests.models.base
  File "/home/gseastre/pyomo/src/pyomo/pyomo/solvers/tests/models/base.py", line 15, in <module>
    import pyomo.kernel as pmo
  File "/home/gseastre/pyomo/src/pyomo/pyomo/kernel/__init__.py", line 11, in <module>
    import pyomo.environ
  File "/home/gseastre/pyomo/src/pyomo/pyomo/environ/__init__.py", line 71, in <module>
    _import_packages()
  File "/home/gseastre/pyomo/src/pyomo/pyomo/environ/__init__.py", line 68, in _import_packages
    pkg.load()
  File "/home/gseastre/pyomo/src/pyomo/pyomo/repn/plugins/__init__.py", line 16, in load
    import pyomo.repn.plugins.gams_writer
  File "/home/gseastre/pyomo/src/pyomo/pyomo/repn/plugins/gams_writer.py", line 29, in <module>
    from pyomo.kernel import (block, constraint, expression, objective,
ImportError: cannot import name block
```
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyomo.kernel import block
>>> block
<class 'pyomo.core.kernel.component_block.block'>
```

**Comment by ghackebeil** [comment]
There is probably some weird circular dependency that pops up between pyomo.kernel and pyomo.repn when you import it this way. Importing directly from pyomo.core.kernel is probably appropriate here. I'm going to add some notes to your latest commit.
