### ISSUE TITLE
Narrowing down nosetests to a particular solver or test case

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#195]
Is there a way to narrow down nosetests, in this case nosetests pyomo.solvers, so that it only checks the GAMS solver or only checks one test case or test model? The furthest I can narrow it down is to run `nosetests pyomo.solvers.tests.checks.test_pickle`, but this still takes several minutes. I tried narrowing it down further to `pyomo.solvers.tests.checks.test_pickle.Test_MILP_discrete_var_bounds` but nothing gets run if I do this. I ask because it would be convenient if I could skip all these tests that I don't need every time I want to try it on my solver.

**Comment by ghackebeil** [comment]
Instead of using nosetests, try that same thing when directly executing the test file. E.g.,

    $ python test_pickle.Test_MILP_discrete_var_bounds

You can narrow that down further by adding a `.<testname>`.

**Comment by gseastream** [comment]
Are you sure it's `python test_pickle.Test_MILP_discrete_var_bounds`? I get a No such file or directory error, when executing it from pyomo/solvers/tests/checks

**Comment by ghackebeil** [comment]
Sorry:

    $ python test_pickle.py ...
