### ISSUE TITLE
Solver tests requiring 'optimal' termination condition instead of 'locallyOptimal'

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#197]
In testing the GAMS solver, I found that some tests required that my solver return TerminationCondition.optimal, when GAMS was telling me that it found a locally optimal solution instead. Those tests are the following:
```
Test_MIQP_simple
Test_MIQP_simple_kernel
Test_QCP_simple
Test_QCP_simple_kernel
Test_QCP_simple_nosuffixes
Test_QCP_simple_nosuffixes_kernel
Test_QP_simple
Test_QP_simple_kernel
Test_QP_simple_nosuffixes
Test_QP_simple_nosuffixes_kernel
```
Since GAMS differentiates between optimal and locally optimal, as I'm sure other solvers do too, should locally optimal be an acceptable response for these tests?

**Comment by ghackebeil** [comment]
Yes. I think that your suggestion makes sense. Go ahead and make that change to the tests on your branch.
