### ISSUE TITLE
Streamlit and Pyomo: ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by maajdl** [Pyomo/pyomo#1975]
Hello,

I was very curious to create a small Streamlit app using Pyomo with Ipopt.
Unfortunately, this leads to the following error:

```
ValueError: signal only works in main thread
Traceback:
....	
File "...\site-packages\pyomo\opt\base\solvers.py", 
line 582, in solve    _status = self._apply_solver()
File "...\site-packages\pyomo\opt\solver\shellcmd.py", 
line 244, in _apply_solver    self._rc, self._log = self._execute_command(self._command)
File "...\site-packages\pyomo\opt\solver\shellcmd.py", 
line 332, in _execute_command    self.process_soln_file(results)
File "...\site-packages\pyutilib\subprocess\processmngr.py", 
line 554, in run_command    #            = signal.signal(signal.SIGINT, handler)
File "...\lib\signal.py", 
line 47, in signal    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
```
By removing a few lines in processmngr.py, I could make it work.
These are the lines 548-556 dealing with  "define_signal_handlers" :

```
    if define_signal_handlers:
        handler = verbose_signal_handler if verbose else signal_handler
        if sys.platform[0:3] != "win" and sys.platform[0:4] != 'java':
            GlobalData.original_signal_handlers[signal.SIGHUP] \
                = signal.signal(signal.SIGHUP, handler)
        GlobalData.original_signal_handlers[signal.SIGINT] \
            = signal.signal(signal.SIGINT, handler)
        GlobalData.original_signal_handlers[signal.SIGTERM] \
            = signal.signal(signal.SIGTERM, handler)
```

This works on my laptop.
Of course, this is not a good solution once I want to publish my app  on  share.streamlit.io .

Would you have some suggestion to solve the problem without cutting lines of code in processmngr.py ?
I had a look to see if I could make use of process of threads, but this is beyond my competences and I guess there is not such solution. But who knows?
Any suggestion welcome!

Otherwise, could that be something to improve in Pyomo / pyutilib ?

Thanks

Michel

**Comment by jsiirola** [comment]
As discussed in #609 and PyUtilib/pyutilib#31, in Pyomo through 5.7.3, you can disable the stream handlers by setting:
```python
import pyutilib.subprocess.GlobalData
pyutilib.subprocess.GlobalData.DEFINE_SIGNAL_HANDLERS_DEFAULT = False
```
Beginning in Pyomo 6.0 (due out in ~week), we are removing the dependency on PyUtilib, so this particular issue will go away.

**Comment by maajdl** [comment]
Thanks!
