### ISSUE TITLE
Revisit whether 'six' is still necessary

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#20]
According to this blog, we should be able to forgo the use of the 'six' package now that we're not supporting Python 2.5.  I'm not sure I believe that, but it's probably worth considering this.

http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/

**Comment by jsiirola** [comment]
I don't understand the motivation to remove six. Note that in the linked blog post, they had to implement a `_compat` module that reimplemented the parts from six that they needed. Personally, I would rather use a standard module than go around reimplementing parts of it.


On Aug 10, 2016, at 6:36 AM, William Hart <notifications@github.com<mailto:notifications@github.com>> wrote:


According to this blog, we should be able to forgo the use of the 'six' package now that we're not supporting Python 2.5. I'm not sure I believe that, but it's probably worth considering this.

http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/

-

**Comment by whart222** [comment]
Yeah, it wasn't clear how much of 'six' we need to recreate.  The blog suggested it wouldn't be much, which is why I created this ticket.

**Comment by whart222** [comment]
I'm closing this issue.  This isn't worth making a priority.
