### ISSUE TITLE
Documentation Testing

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#201]
In trying to add documentation testing to our testing infrastructure I've come across a few issues that need to be hashed out by the team. First, when we think about documentation testing there are two cases that need to be accounted for:

1. Testing code examples in sphinx documentation files (.rst files)
2. Testing code examples in doc strings within all of our .py files

As far as I can tell, with the `--with-doctest` option there is no way to restrict nosetest to one use case or the other. This becomes a problem for the second case because

- Our current test.pyomo script produces a nosetest command that only looks in the `tests` directories for each submodule which means that doc strings in our main class implementations are not checked
- We have many legacy .py files throughout the repo that no longer run and throw errors when nosetest checks them for doctests

I think the best temporary solution would be to modify the travis script to run a second nosetest command that only runs doctests in the sphinx documentation directory (use case 1). This would allow us to test the user documentation as we write it and wouldn't miss much in terms of doc strings since I think Gabe's kernel code is the only place where we currently have examples in the doc strings.

The long term solution is a significant clean-up of the repo such that old code is moved to archive folders without an `__init__.py` file and we can safely run nosetest on the pyomo.FOO directories instead of specific testing directories.

**Comment by whart222** [comment]
I strongly agree with your recommendation.  I think our focus first should be on doctests associated with our documentation.  And then later focus on source code doctests, if we want to make these a standard.

FWIW, I'm not sure I like source code doctests.  The separation of code from tests helps keep the code directories clean of baseline data.

**Comment by ghackebeil** [comment]
> FWIW, I'm not sure I like source code doctests. The separation of code from tests helps keep the code directories clean of baseline data.
> 

Taking NumPy as an example, the majority of the time I spend looking at NumPy documentation is within the online reference guide. For each of the major sub modules, besides a page that basically lists all of the functions, the documentation for each function is basically generated from the doc string in the source code. And usually has a "Notes:" and "Examples:" section. The examples there are usually concise but very helpful. IMO, that is the kind of documentation we should be prioritizing right now (and testing, now that we know how to), at least for core functionality.

Gabe

**Comment by blnicho** [comment]
Documentation testing has been working for some time and I think the second use-case of testing code in docstrings is covered when those modules are included in an rst file using `automodule`. Closing this.
