### ISSUE TITLE
Regression: 'inf' token no longer converted to float

### ISSUE THREAD

**Issue by staadecker** [Pyomo/pyomo#2014]
## Summary

Previously, loading a CSV through the data portal containing a cell with value `inf` would result in a float. Now, `inf` stays as a string which results in an error when the domain is checked.

### Steps to reproduce the issue

1. Create a csv file with one if it's cells having `inf` as a value.

2. Load the csv through the DataPortal.

3. If the parameter belonging to that cell has domain `NonNegativeReals` an error will be thrown.

### Faulty code

[This is the PR and lines of codes changed that introduced this regression](https://github.com/Pyomo/pyomo/pull/1366/files#diff-108383f046e901dfa905b4d69c8b804fe3ef8ece0e820cb1fe3bce5bbc076238L74-R87)

**Comment by mrmundt** [comment]
@staadecker - Could you please try this again? We are going through old bug reports to confirm that they still exist.

**Comment by staadecker** [comment]
Hi, I unfortunately don't have time to test this however I assume it is still an issue. The ability specify `inf` in the input csv is quite helpful since later one can not apply a constraint if the value of a parameter is `inf`. Feel free to close the issue if this is not a priority
