### ISSUE TITLE
`generate_standard_repn` silently fails to capture nonlinear expression

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#2046]
## Summary

In the example below, `generate_standard_repn` fails to record the nonlinear expression at all.

### Steps to reproduce the issue

```
from pyomo.environ import *
from pyomo.repn import generate_standard_repn

m = ConcreteModel()
m.x = Var()
m.y = Var()

expr = (m.x + m.y)*(m.x - m.y)*(m.x**2 + m.y**2)
repn = generate_standard_repn(expr)
print(repn)
```

### Error Message

Output from the script above:
```
constant:       0
linear vars:    []
linear var ids: []
linear coef:    []
quadratic vars:    []
quadratic var ids: []
quadratic coef:    []
nonlinear expr: None
nonlinear vars: []
```

### Information on your system

Pyomo version: main branch
Python version: 3.6.5
Operating system: linux
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable):

**Comment by PierreAttard** [comment]
Hi, 

This expression is not `quadratic`, to solve this issue, you can set `quadratic` param at `False`:
```python
expr = (m.x + m.y)*(m.x - m.y)*(m.x**2 + m.y**2)
repn = generate_standard_repn(expr, quadratic=False)
```

Output is :  
```
nonlinear expr:
(x + y)*(x - y)*(x**2 + y**2)
nonlinear vars: ['x', 'y']
```

However, if the user does not indicate that the problem is not quadratic, the user has to get an error or a warning : 
- raise an Error which tells theuser to set quadratic at False
- have an output like below : 
```
nonlinear expr:
(x + y)*(x - y)*(x**2 + y**2)
nonlinear vars: ['x', 'y']

WARNING: The problem is not quadratic
```

**Comment by jsiirola** [comment]
@PierreAttard, for the record, you are slightly mischaracterizing the meaning of the `quadratic` flag:  it has nothing to do with the polynomial degree of the expression.  Instead, when it is `False`, `generate_standard_repn()` takes an expression and separates out the constant term and all linear terms.  All other (nonlinear) terms are left in a "general nonlinear term" field.  When `True`, then  `generate_standard_repn()` also identifies and pulls the quadratic terms out of the general nonlinear "catch all" and returns them separately.
