### ISSUE TITLE
Constraint `get_value` fails for ranged inequality

### ISSUE THREAD

**Issue by Robbybp** [Pyomo/pyomo#2047]
## Summary

Trying to get tests to pass for #1613, I ran into the following bug, where I cannot get the `expr` attribute of a ranged inequality constraint. It appears to be caused by the `get_value` using the no longer supported (?) ranged inequality syntax `con._lower <= con._body <= con._upper`. A similar syntax, `con._lower <= (con._body <= con._upper)`, appears to work, but maybe we should use the `inequality` function?

### Steps to reproduce the issue

```python
import pyomo.environ as pyo 

m = pyo.ConcreteModel()
m.v = pyo.Var()

m.con = pyo.Constraint(expr=pyo.inequality(1, m.v, 3)) 

m.con.expr
```

### Error Message

The error is due to converting non-constant expression to bool:

```console
pyomo.common.errors.PyomoException: Cannot convert non-constant expression to bool. This error is usually caused by using an expression in a boolean context such as an if statement. For example, 
    m.x = Var()
    if m.x <= 0:
        ...
would cause this exception.
```

**Comment by jsiirola** [comment]
I went and put a fix for this into #1613,
