### ISSUE TITLE
[PEP] Deprecate `Set.__getitem__` and replace with `Set.card()`

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#2049]
## Summary

Deprecate `_OrderedSetMixin.__getitem__()` and replace it with `_OrderedSetMixin.card()`

## Discussion

Pyomo ordered Set objects have historically supported the `ord()` method to get the position of a set member in the Set and `__getitem__()` to get a set member from a (1-based) position.  This causes two fundamental problems:
- `model.I[1]` looks a lot like a Python list, and users would expect that `I[1]` would return the second element.  However, Set objects are 1-based, so `model.I[1] is model.I.first()`.
- A long-standing Pyomo idiom is that scalar instances of `IndexedComponent`s can still be treated as if they were indexed by the set `{None}`.  By overriding `__getitem__`, `Set` breaks this idiom and requires special implementations of `values` and `items` (see #2048).  This "nonstandard" behavior is rather confusing.

Both these issues can be resolved by replacing `Set.__getitem__()` with `Set.card()`.  This has some nice properties: the use of `card` mirrors that in GAMS and AIMMS, so is consistent with accepted practice.  Also, as "custom" methods, it is more clear to users that these are *not* Python operations, so the fact that both `ord()` and `card()` are 1-based can be documented and are not (quite) as jarring for Python programmers.

Unfortunately the `__getitem__()` behavior of ordered Sets is described in The Book.  As such, we can only deprecate the use of `__getitem__` in Sets, and not remove it until Pyomo 7.

**Comment by DLWoodruff** [comment]
I like everything about this pep except the use of the word "Unfortunately" to begin the penultimate sentence. I think it is a good thing that there will only be a deprecation message for a long time.

**Comment by Robbybp** [comment]
I use `OrderedSet.__getitem__` frequently when working with continuous sets, but still approve of this change. If I'm not mistaken, this will allow references to sets?
