### ISSUE TITLE
Intermittent Pyro-related failures

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#205]
`test_farmer_quadratic_ipopt_with_phpyro` in `pyomo.pysp.tests.unit.test_ph.TestPHParallel` fails about half the time for no apparent reason. Usually a re-run of Travis is enough to work around this, but it's annoying when each Travis run takes 15 minutes.

See for example https://travis-ci.org/Pyomo/pyomo/jobs/267180361

This is also causing master to be failing right now: https://travis-ci.org/Pyomo/pyomo/builds/267029635

**Comment by ghackebeil** [comment]
I'm attributing this to the old version of Ipopt we are testing with. Does anyone know if we have any control over the version that gets installed over the conda channel we are using? It would be good to update that for other reasons. If not, I'll just recategorize this test.

**Comment by qtothec** [comment]
Conda shows the version to be 3.12.7, which is actually newer than what I'm running locally. Is there something else going on?

https://anaconda.org/conda-forge/ipopt/files

**Comment by qtothec** [comment]
It has appeared again: https://travis-ci.org/Pyomo/pyomo/jobs/327365908

**Comment by ghackebeil** [comment]
fixed as of 5cedbff35c217b85e085431d2f89e93497568e9d and 9930927f05ef2c4257942b39866e9d2222d6369b on master
