### ISSUE TITLE
Error in solver tee output on Windows

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#2054]
## Summary

When I an solving a pyomo problem and use the "tee=True" option, and I scroll up in the CMD window on Windows to see some output displayed above, I often get the error below.

```sh
Number of objective function evaluations             = 30
Number of objective gradient evaluations             = 6
Number of equality constraint evaluations            = 31
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 6
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 5
Total CPU secs in IPOPT (w/o function evaluations)   =      0.668
Total CPU secs in NLP function evaluations           =     25.060

EXIT: Optimal Solution Found.
    solver.solve(m, tee=True)
  File "c:\users\eslickj\git\pyomo\pyomo\opt\base\solvers.py", line 578, in solve
    _status = self._apply_solver()
  File "c:\users\eslickj\git\pyomo\pyomo\opt\solver\shellcmd.py", line 246, in _apply_solver
    self._rc, self._log = self._execute_command(self._command)
  File "c:\users\eslickj\git\pyomo\pyomo\opt\solver\shellcmd.py", line 324, in _execute_command
    t.STDERR.flush()
  File "c:\users\eslickj\git\pyomo\pyomo\common\tee.py", line 390, in __exit__
    self.close(et is not None)
  File "c:\users\eslickj\git\pyomo\pyomo\common\tee.py", line 378, in close
    raise RuntimeError(
RuntimeError: TeeStream: deadlock observed joining reader threads
```

### Steps to reproduce the issue

I'm not sure this happens 100% of the time, but you just need to run a pyomo problem on windows in a cmd window and be scrolling up when the solver completes.

It's not with a specific script.  It happens with with any problem I run.  Should be reproducible with any problem using ipopt and "tee=True."   

### Error Message

```
  File "c:\users\eslickj\git\pyomo\pyomo\common\tee.py", line 378, in close
    raise RuntimeError(
RuntimeError: TeeStream: deadlock observed joining reader threads
```

### Information on your system

Pyomo version: Pyomo 6.0.2 (devel {string_args}) (CPython 3.9.4 on Windows 10)
Python version:  3.9.4
Operating system: Windows 10
How Pyomo was installed (PyPI, conda, source): source (pip with -e option)
Solver (if applicable): Ipopt

**Comment by jsiirola** [comment]
@eslickj, can you try editing the following line in `pyomo/common/tee.py`:
```diff
diff --git a/pyomo/common/tee.py b/pyomo/common/tee.py
index 170850a..b16feba 100644
--- a/pyomo/common/tee.py
+++ b/pyomo/common/tee.py
@@ -370,7 +370,7 @@ class TeeStream(object):
             if not self._threads:
                 break
             _poll *= 2
-            if _poll >= 2:  # bail after a total of 2 seconds * #threads
+            if _poll >= 10:  # bail after a total of ~10 seconds * #threads
                 if in_exception:
                     # We are already processing an exception: no reason
                     # to trigger another
```

**Comment by eslickj** [comment]
@jsiirola yes.  I will try that.  I just observed if I drag the scroll bar thing back to the end, the error message only shows up when I let go of the mouse button.  I think when I grab the scroll bar with the mouse, output to the terminal must stop and be cached until I let go.  I wonder if that is causing some conflict here.

**Comment by jsiirola** [comment]
Is this happening at the command prompt, or within an IDE (Jupyter / Spyder / PyCharm / IPython / etc)?

**Comment by eslickj** [comment]
The command prompt (CMD.exe).  I don't think it happens in iPython or Jupyter.  The change you suggested seems to make it harder to reproduce, but if I grad the scroll bar long enough it still happens.  Now that I played with it more, I'm pretty sure it has some thing to do with the the way the scroll bar works in CMD.  I'm going to try powershell, and see if it works the same.

**Comment by eslickj** [comment]
Yeah, happens in powershell too.

**Comment by jsiirola** [comment]
So the problem arises when the subprocess has exited, but Python is still waiting for the threads that handled the subprocess stdout/stderr to exit (we close the pipe that was sending data to the threads, and then wait for the threads to notice and shut down).  Holding on to the scroll bar appears to block the thread from seeing that the stream is closed.

I generally worry about "utility" methods that lead to deadlock, so had the system bail if it started taking "too long."  -- but of course, "too long" is in the eye of the beholder.

What do you think is the right behavior?  Should we just deadlock? (that seems bad).  Alternatively we could just log an error instead of raising an exception.  The output streams could be left in a messy state, but the code *could* continue -- although if the next step was to open / delete / rename the file that the stream handler was writing too, that could lead to a different set of fatal errors in Windows.

**Comment by eslickj** [comment]
Unfortunately I seem to run into this a lot.  Due to the way IDAES models work, I find myself scrolling up to see in previous solves worked right or to check on some output.  Then the whole script fails and I have to start over.  That's just to say I think it is important to fix since it can be very frustrating for users.  As for how to fix it, I don't really know.  It doesn't sound like there is a really good solution.  I'll put some more thought into this.

**Comment by jsiirola** [comment]
@eslickj: can you take a look at #2072 and see if that resolves things for you?

**Comment by eslickj** [comment]
Seems to work.  Got a warning instead of exception:

```sh
  1  0.0000000e+00 2.69e+00 3.90e+04  -1.0 9.11e+06    -  9.90e-01 1.00e+00H  1
   2  0.0000000e+00 1.89e-04 1.04e+02  -1.0 4.35e+03    -  9.90e-01 1.00e+00h  1
WARNING: Significant delay observed waiting to join reader threads, possible
    output stream deadlock
   3  0.0000000e+00 7.70e-06 1.04e+00  -1.0 2.53e+02    -  9.90e-01 1.00e+00h  1
   4  0.0000000e+00 3.46e-07 1.04e-02  -1.0 1.15e+01
```

**Comment by jsiirola** [comment]
You can still get an exception, but the exception won’t be raised until after about 200 seconds.

**Comment by eslickj** [comment]
Thanks.  It's pretty safe to say I won't hold the scrollbar that long.
