### ISSUE TITLE
[PEP] add "implicit" sets to the Block as "anonymous" components

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#2068]
## Summary

Historically, Set objects implicitly created by a component were added to the same block as the component with hard-coded names derived from the component name.  This PEP proposes we remove that behavior and allow for implicit Sets to be attached to the Block "anonymously".

### Discussion

It is important that Sets created implicitly during the process of constructing a Component (and attaching it to a Block) are also attached to the same Block.  This ensures that the Sets are properly constructed (especially in the case of AbstractModels), and ensures that `model.clone()` correctly duplicates the Sets.  However, the use of a hard-coded name causes problems when deleting and re-adding components (as the implicit sets are not removed from the Block - see #45).  Further, because this is done when the Component is added to the Block, we cannot disable access to attributes like `Var.domain` for unconstructed Components (because Block._add_implicit_sets() looks for '`domain`' to attach it to the Block).  Finally this convention obscures the model that the user wrote: both by filling it with numerous "auto" Sets (e.g., `x_index`, `y_index_0`, `z_domain`), and by reporting the name of the "auto" set as the Component index (instead of something more informative like the set expression).

This PEP proposes that we still "add" implicit Sets to the Block, but not using an explicit name.  We would add the component using a new `Block.add_anonymous_component()` method.  This would set the Component's `parent_block()` to the Block (so that `block.clone()` works correctly) and would categorize it in the Block's component data structures according to the `ctype` (so, e.g., it would be returned by `component_objects()`), however it would not add the component to the Block's `__dict__`.

We would also transfer the responsibility for constructing implicit components from the Block to the Component that created the implicit components.  Deferring it to the "originator's" construction time would allow us to deactivate interfaces like `domain` on abstract components.

**Comment by blnicho** [comment]
I really like this idea
