### ISSUE TITLE
Confusing documentation when using help(Var)

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#207]
When I call `help(Var)`, I see the following declared function:
```
 |  get_derivative(self, *args)
 |      Returns the dictionary mapping derivatives to their DerivativeVar or
 |      returns a certain DerivativeVar specified by the keyword arguments
```
This documentation gives no indication that it is part of the `Pyomo.DAE` toolset, and may be easily confused with the expression system `derivative` function.

I also have no idea how this function ended up getting inserted into `Var`.

**Comment by blnicho** [comment]
This is an artifact of a particular syntax I was trying to support for declaring derivatives using Pyomo.DAE. I have removed this functionality in the dae-simulator branch and you will no longer see this once #180 gets merged this week.
