### ISSUE TITLE
Aarch64 wheel is missing on PyPi

### ISSUE THREAD

**Issue by odidev** [Pyomo/pyomo#2075]
I have seen that the aarch64 wheel is missing in Pypi. User needs to have the development environment installed on his system. It will be useful if the aarch64 wheel is released as - 

- The Arm architecture has been available on AWS (Graviton2) for about 2 years now and has seen a lot of adoption by various organizations. The install base of Arm users is growing at a rapid pace. 

- Oracle cloud will be releasing Arm based Compute Shapes in the future. Please [see](https://www.anandtech.com/show/16100/oracle-announces-upcoming-cloud-compute-instances-ice-lake-and-milan-a100-and-altra#:~:text=OCI%E2%80%99s%20Arm%20instances%20will%20clock%20as%20high%20as,%E2%80%93%20OCI%20is%20refreshing%20its%20GPU%20compute%20instances)

- Generally, there is a lot of momentum behind various products switching to Arm based CPUs. For example, the Microsoft surface Pro X is an Arm based device. 

@Team Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by blnicho** [comment]
As of Pyomo 6.7.0 we have started distributing aarch64 wheels on PyPI.
