### ISSUE TITLE
Add support for the HiGHS solvers via scipy

### ISSUE THREAD

**Issue by mkoeppe** [Pyomo/pyomo#2094]
## Summary

scipy has started to vendor the HiGHS solvers. Providing a Pyomo solver based on this interface would give clean access to high-performance solvers, unencumbered by problematic licenses.

### Description

See https://github.com/scipy/scipy/issues/14455

**Comment by bknueven** [comment]
I would be happy to take a pass at this in my spare time, once scipy/scipy#14455 is resolved. The HiGHS/scipy developers have created Python wrappers for HiGHS [within scipy](https://github.com/scipy/scipy/tree/master/scipy/optimize/_highs), which may be better for Pyomo to interface with as opposed to going through the `linprog` scipy interface.

**Comment by jajhall** [comment]
A direct interface to HiGHS from Pyomo is in the pipeline, and 
https://github.com/Pyomo/pyomo/tree/main/pyomo/solvers/plugins/solvers
suggests that interfaces to solvers, rather than interfaces like scipy are preferred. HiGHS doesn't have infinite resources so, great a scipy is (and it's good that the scipy-HiGHS link for MIP is going ahead) we'd rather that the HiGHS were used directly from Pyomo

**Comment by mkoeppe** [comment]
> A direct interface to HiGHS from Pyomo is in the pipeline
Will a future Pyomo version include a vendored copy of HiGHS then (in source distribution and/or wheels)?

**Comment by bknueven** [comment]
> Will a future Pyomo version include a vendored copy of HiGHS then (in source distribution and/or wheels)?

I would very much doubt it. Pyomo does not currently distribute source or wheels for any other solver. In general, I point users to conda packages for various solvers, which exist for CBC, GLPK, and IPOPT, and probably others. Several commercial MIP solvers with their associated Python interfaces are also available on PyPI.

The only reason to leverage the scipy-HiGHs interface (or really, that HiGHs is distributed as part of scipy) is that it could be the most straightforward way for Pyomo users to obtain HiGHs. But if distribution via either conda or PyPI is already planned, it's a moot point.

**Comment by mkoeppe** [comment]
> The only reason to leverage the scipy-HiGHs interface (or really, that HiGHs is distributed as part of scipy) is that it could be the most straightforward way for Pyomo users to obtain HiGHs.

Yes, exactly – this was the main point why I was excited about scipy shipping HiGHs. 

> But if distribution via either conda or PyPI is already planned, it's a moot point.

Not quite. The SciPy wheels do not provide HiGHs as a shared library; instead, HiGHS is shipped only as part of the Cython extension modules in `scipy/optimize/_highs`. For example:
```
$ otool -L scipy/optimize/_highs/_highs_wrapper.cpython-39-darwin.so 
scipy/optimize/_highs/_highs_wrapper.cpython-39-darwin.so:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```
SciPy packaging on conda-forge could _theoretically_ go through a HiGHs conda package which could then be reused by Pyomo packaging on conda-forge; but this is also not what is done: https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/meta.yaml

**Comment by jajhall** [comment]
Thanks for flagging up Conda as a packaging system. The HiGHS team will look into it.

**Comment by michaelbynum** [comment]
PR #2245 adds a Pyomo interface to HiGHS through `pyomo.contrib.appsi` (https://pyomo.readthedocs.io/en/stable/library_reference/appsi/appsi.html). It uses a thin wrapper around the `Highs` c++ class, so the `Highs` model can be modified efficiently (e.g., for resolves). There is still work to do, but the basics are there. There are installation instructions in the docs in the PR. It can be used as 

```
opt = appsi.solvers.Highs()
results = opt.solve(m)
```

There is a wrapper to get a traditional Pyomo solver interface as well:

```
opt = pyo.SolverFactory('appsi_highs')
results = opt.solve(m)
```

**Comment by davebiagioni** [comment]
This is awesome, thanks to all!
