### ISSUE TITLE
Figure out location to put model introspection tools

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#211]
There is general demand for model introspection utilities like determining the number of degrees of freedom. Where should we put these utilities? People don't like `pyomo.debug`, apparently, so what is it going to be?
`pyomo.core.introspect`?

**Comment by blnicho** [comment]
How about `pyomo.diagnostics`?

**Comment by qtothec** [comment]
That sounds fine to me. Do we want to specify at all that it's model diagnostics rather than solver diagnostics?

**Comment by blnicho** [comment]
I don't think it's necessary to distinguish them. I think it would be fine to have both in the same module/folder.

**Comment by qtothec** [comment]
So, can I assume that everyone is happy with this and move forward with it? =D

**Comment by whart222** [comment]
I would assume that we'll have different introspection tools for different types of models.  Yes?

How would they be distinguished in this common directory?

**Comment by blnicho** [comment]
Discussion from the developer's meeting today:
@DLWoodruff likes 'diagnostics' instead of 'introspection'. 'Introspection' is a loaded word in Python 

Could distinguish tools for different types of models using function naming or subfolders (i.e. pyomo.diagnostics.lp or pyomo.diagnostics.nlp)

Diagnostic capabilities for special modeling components dae/gdp/etc could live in those directories (pyomo.dae.diagnostics)

**Comment by qtothec** [comment]
Sounds like a good idea to me. Where would something more general like `degrees_of_freedom(m)` go?

**Comment by blnicho** [comment]
I would say in the main diagnostics folder such that you could import it like:

    from pyomo.diagnostics import calculate_degrees_of_freedom

**Comment by whart222** [comment]
PR #217 adds diagnostic tools in pyomo.util.diagnostics.  I think we can add additional tools there, so I'm closing this issue.

**Comment by jsiirola** [comment]
I am comfortable closing this issue, but need to reference #267 and the newly-created #321 that will track the final disposition of `pyomo.util`
