### ISSUE TITLE
ImportError: pyutilib.enum has been removed.

### ISSUE THREAD

**Issue by VVDL32** [Pyomo/pyomo#2116]
## Summary

Hi,
I had used a version of pyomo last year on spyder with anaconda, and I had never had any problem. This year I also need it and it seems that I have to download it again as it is no longer on my computer. I did everything as previously, but now I get an error message and I didn't find the solution on internet. It seems that with my latest version of Python, pyutilib.enum has been removed whereas I need it to use Pyomo. Do you have any idea on how I could fix this ? 

Here are the message errors I get :

![Capture d’écran 2021-09-02 à 17 03 06](https://user-images.githubusercontent.com/89990274/131868097-66312775-430a-4753-b50c-e4671de478b4.png)

![Capture d’écran 2021-09-02 à 17 03 36](https://user-images.githubusercontent.com/89990274/131868194-cd0401b1-ac05-484e-bac9-0666068c23ad.png)

My version of spyder is 3.8.1 and I have tried to download pyomo v 6.1.2 with conda : 
I used this command : conda install -c conda-forge pyomo

Thanks by advance for helping !

**Comment by jsiirola** [comment]
This is an installation issue on your system.  It looks like your anaconda environment still has an old version of Pyomo installed in it (did you mix conda and pip installs -- or did you install Pyomo into the system Python some time?).

The giveaway is the exception from line 3 in `derivatives.py`: in 6.1.2, line 3 is a comment.

**Comment by VVDL32** [comment]
Oh yes it may come from that.  Indeed, I first try to install pyomo with conda but I got an error message that pyomo was not recognized by python. Then I tried to install it with pip installs and I got the above error message. So what would you advise me to do ? Uninstall anaconda and do the process again ? Or is there a solution which enables me not to uninstall everything ?

**Comment by VVDL32** [comment]
I used the command : "python -m pip uninstall pyomo" to uninstall it with pip and it got me rid of the previous error message. However, though I have installed pyomo with conda, I got the following error message "ModuleNotFoundError: No module named 'pyomo'". That the 1st error message I got and that was why I tried to install it with pip which gave me the other error message. So I am still stuck in some way :\

**Comment by jsiirola** [comment]
Things can get very confusing whenever you mix conda and pip. I would try something like 
```
conda remove pyomo 
python -m pip uninstall pyomo 
```
Then, I would search your system for files / directories named `pyomo`. Depending on what you find, you may have to manually remove those directories / files. 

Also, you should be aware that Python can become confused if you have a subdirectory or a Python file named the same as a package.
