### ISSUE TITLE
Pynumero Recently Stopped Working with External Functions

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#2126]
## Summary

Pynumero seems to have stopped working with external functions in the latest Pyomo.  It worked until very recently.  I suspect something probably broke in setting "AMPL_FUNC"

### Steps to reproduce the issue

I assume there is an external function that can be used for testing.  If not, I added one in PR #1904. 

If you have IDAES installed this will do it:

```python
from idaes.core.util.functions import functions_lib
from pyomo.contrib.pynumero.interfaces.pyomo_nlp import PyomoNLP
import pyomo.environ as pyo

if __name__ == "__main__":
    m = pyo.ConcreteModel()
    flib = functions_lib()
    m.cbrt = pyo.ExternalFunction(library=flib, function="cbrt")

    m.x = pyo.Var([1, 2, 3], initialize=4.0)
    m.c = pyo.Constraint(expr=m.x[3] ** 2 + m.cbrt(m.x[1]) == 25)
    m.d = pyo.Constraint(expr=m.x[2] ** 2 + m.x[1] <= 18.0)
    m.o = pyo.Objective(expr=m.x[1] ** 4 - 3 * m.x[1] * m.x[2] ** 3 + m.x[3] ** 2 - 8.0)
    m.x[1].setlb(0.0)
    m.x[2].setlb(0.0)

    nlp = PyomoNLP(m)
    f = nlp.evaluate_objective()
    assert f == pytest.approx(-504.0)

    jac = nlp.evaluate_jacobian().toarray()
    print(jac)
``` 

### Error Message

```
WARNING: The current pynumero_ASL library is version=2, but found version=1.
    Please recompile / update your pynumero_ASL library.
function cbrt not available  <--- this is the problem
```

### Information on your system

Pyomo
    Version: 6.1.3.dev0

Python
    Version: 3.9.4 (default, Apr  9 2021, 11:43:21) [MSC v.1916 64 bit (AMD64)]
    Executable: C:\Users\EslickJ\miniconda3\envs\idaes-pse\python.exe

OS
    Platform: Windows
    Release: 10
    Version: 10.0.19041

**Comment by eslickj** [comment]
Setting AMPLFUNC before running pyomo does not seem to fix the issue.  The external function is still not found.

**Comment by jsiirola** [comment]
If you rebuild the `pynumero_ASL` library, does that fix the issue?

**Comment by eslickj** [comment]
@jsiirola, I just tried this on a different computer and it worked fine.  I also just rebuilt pynumero.  I noticed on the other computer I didn't get the warning about pynumero being out of date.  I'm now about 90% sure either I did something stupid at some point or Windows just randomly decided to start acting weird.  I'm going to try to figure out if I somehow have an old Pynumero hanging around somewhere else.  I think I may have accident;y built it with Pyomo's system at some point and left it hanging around.

**Comment by Robbybp** [comment]
@eslickj I could reproduce your error with Pyomo's main branch, so it's not just you. I may also have an old `pynumero_ASL` library though, and haven't tried rebuilding, so this doesn't narrow it down much.

**Comment by jsiirola** [comment]
I was able to see the same problem when I was running with the old `pynumero_ASL` library.  I'm not entirely sure why, though.  #2114 may not be as backward compatible as I had hoped... digging now...

**Comment by jsiirola** [comment]
I think I have a fix... (see #2129), but the real fix is to update your build of `pynumero_ASL`.

**Comment by eslickj** [comment]
Okay, finally tracked it down.  I built it back in May with Pyomo's build system, and that was jumping in front of the IDAES build I meant to be using.  That really got me confused.  It's all good now.
