### ISSUE TITLE
Add Python 3.10 to our testing infrastructure

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#2154]
## Summary

Test Pyomo against Python 3.10 which was released at the beginning of October 2021

**Comment by mrmundt** [comment]
I did some initial investigation into this, and I think we need to pause on this effort. Some of our dependencies haven't caught up to 3.10, and `nosetests` has some issues with Python 3.10. It could be a bigger push than anticipated.

See my [branch](https://github.com/mrmundt/pyomo/tree/python-3.10) (and its [action](https://github.com/mrmundt/pyomo/actions/runs/1364622567)) for more details.
