### ISSUE TITLE
calculate_variable_from_constraint can fail for simple constraints due to domain violation

### ISSUE THREAD

**Issue by andrewlee94** [Pyomo/pyomo#2176]
## Summary

Using the `calculate_variable_from_constraint` method can result in unexpected failures due to trying to set the value of a `Var` outside of its domain, as shown in the example below. In this case, a simple constraint of `v == 0` can be successfully solved, but fails if the constraint is scaled by a factor of 10 (ie. `10*v == 0`).

```
# example.py
import pyomo.environ as pyo
from pyomo.util.calc_var_value import calculate_variable_from_constraint

# Create basic model
m = pyo.ConcreteModel()
m.v1 = pyo.Var(initialize=1, domain=pyo.NonNegativeReals)

m.c1 = pyo.Constraint(expr=m.v1 == 0)

# Calculate value of v1 using constraint c1
calculate_variable_from_constraint(m.v1, m.c1)

# This works as expected
assert pyo.value(m.v1) == 0

# However, if we multiply v1 by 10:
m.c2 = pyo.Constraint(expr=m.v1*10 == 0)
m.v1.set_value(1)

calculate_variable_from_constraint(m.v1, m.c2)

>>> ValueError: Numeric value `-9` (<class 'int'>) is not in domain NonNegativeReals for Var v1
```

This issue arises due to line 113 in `calculate_variable_from_constraint` which assumes that the constraint is linear with a coefficient of 1 w.r.t. x to quickly solve for trivial cases (such as the initial problem). However, in the case of the scaled problem this violates the domain on the `Var` causing `calculate_variable_from_constraint` to fail when ideally it would continue.

I think the first part of the solution is to wrap line 113 in a `try/except` to handle this case, but this leads to the question of what to do in the except. However, the next step in the method assumes that line 113 set the value of the variable to a new value such that there is also a new residual for the constraint, which is used to estimate the derivative w.r.t. the variable. I the except is just `pass`, then this next step fails due to a division by zero error (as the value of the variable is the same).

**Comment by jsiirola** [comment]
The fundamental issue was that `calculate_variable_from_constraint()` is an unconstrained solver: there is no guarantee that it will respect variable bounds / domain.  We did the bulk of the testing using unbounded variables, so never saw the issue (it not only appears with variable bounds, but if the domain was discrete).  The fix is to bypass bounds / domain checking whenever updating the variable value.

Fix is up as PR #2177.
