### ISSUE TITLE
Strip/Restore Bounds Feature

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#218]
It looks like at least in solving square problems with IPOPT it is useful to remove the bounds on variables before solving.  There are likely other situations where this would be helpful.  When solving an optimization problem with IPOPT you usually need to bring the bounds back.  A simple addition to the solve function that could send problems to the solver unbounded may suffice here. There are also strip_bounds and restore_bounds functions in the IDAES stuff that save the bounds then remove them in the Pyomo problem.

Anyway I think this would be a good addition to Pyomo.

**Comment by qtothec** [comment]
You could implement this as a reversible transformation. I've been putting things like this under `pyomo.core.plugins.transform`.
