### ISSUE TITLE
[PEP] Define standards for enforcing variable bounds / domains

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#2180]
## Summary

Currently, Pyomo is inconsistent in how strictly it applies / enforces variable domains and bounds:
- Variable domains are checked when the value is set using either assignment (`m.x = 5`) or `set_value()` (`m.x.set_value(5)`)
  - Failed checks raise an exception
- Variable domains are NOT checked when directly setting the `value` attribute (`m.x.value = 5`)
- Variable bounds are *never* checked when setting a value
   - except if the variable bounds are set by the domain (and then the bounds are implicitly checked when checking the domain)

Further, different clients use different APIs:
- Variable construction uses `set_value()` (and thus checks the variable domain)
- Solvers generally return the values from the solver using `.value` (and thus do NOT check the domain)

## Proposal:

We should be more consistent when checking variable domains / bounds:
- **Proposal 1**: when we check either the domain or the bounds, we should check both the domain *and* the bounds
- Rationale: as bounds information comes from the tighter of the domain bounds and the user bounds, it is misleading to check one without checking the other

We should decide how "egregious" violating the domain or bounds is (generally, one of {*ignored*, *info*, *warning*, or *exception*})
- **Proposal 2**: Violating the domain or bounds should always generate a user warning (through the local logger) whenever the value will be left in the variable and control returned to the user.
- Rationale: There are perfectly rational algorithmic reasons to take an infeasible path (e.g., Newton's method when solving for a variable value from a constraint, or an interior point algorithm may take steps outside the domain / bounds.  That should not cause the algorithm to halt, nor should it pollute the user's screen with warnings.  However, if an algorithm (e.g., solver) leaves a variable in a state outside its bounds / domain, then a user warning should be emitted.  This should not generate an exception, either, as there are perfectly rational reasons for an algorithm to terminate at a point not in the bounds (terminating at point of local infeasibility, using an unconstrained solver for a bounded problem, using a continuous solver for a discrete problem).  Raising an exception when setting the variable value could cause control to return to the user prematurely.

We should be more consistent with our checking, but allow users that "know better" to bypass it.
- **Proposal 3**: Both `m.x.value = 5` and `m.x.set_value(5)` should validate the domain and bounds.  Users that wish to bypass validation would call `m.x.set_value(5, skip_validation=True)`
- Rationale: We should allow users who know that they are going to adhere to the principle of the previous proposal to bypass the domain and bound checking in the name of code performance.  However, that should be a *conscious and intentional decision* (i.e., they need to make it explicit and shouldn't end up bypassing validation just because they accidentally copied an example that was setting `.value`).

## Changelog

- 8 Nov: Added third proposal to make the interface for bypassing validation require an explicit argument
- 10 Nov: Labeled the three proposals to make discussion easier
- 16 Nov: change the validation flag to `skip_validation` to match the sense of the current `valid` flag.

**Comment by michaelbynum** [comment]
While I mostly agree with the rationale, I am opposed to the proposal for performance reasons. I think checking the domain and bounds will slow down certain operations. However, I have not actually tested this, so I could be wrong. I have seen simply accessing variable bounds take significant portions of some profiles. I would prefer the default implementation be fast with an option to validate.

**Comment by michaelbynum** [comment]
It is not a perfect comparison, but it illustrates my point:

```
import pyomo.environ as pe
from pyomo.common.timing import TicTocTimer
import logging


logger = logging.getLogger(__name__)

N1 = 1000
N2 = 1000

m = pe.ConcreteModel()
a = list(range(N1))
m.x = pe.Var(a, domain=pe.Binary)

val = 0.5

timer = TicTocTimer()
timer.tic('start')

for i in range(N2):
    for v in m.x.values():
        v.value = val
timer.toc('set value without validation')


for i in range(N2):
    for v in m.x.values():
        if v.lb <= val <= v.ub:
            v.value = val
        else:
            logger.warning('outside domain')
timer.toc('set value with validation')
```

Outputs:

```
[    0.00] start
[+   0.47] set value without validation
[+   3.86] set value with validation
```

**Comment by jsiirola** [comment]
@michaelbynum I agree that there us a cost for validation, and that there should be a way for advanced users / algorithm developers to bypass it.  However, I don't think that the "default" should be to bypass validation.  One of the original arguments for things like `domain`/`within` and `bounds` was for data validation, so I think effectively turning them off for "normal" users would be asking for trouble.

I did go an do a little more extensive profiling on this, though.  The following is run on a branch where I have been trying to clean up / profile / rework the Var class (run in Python 3.7.12 on bare metal Linux):

```python
from pyomo.environ import *
from pyomo.common.timing import TicTocTimer
from pyomo.common.log import LoggingIntercept

# Important: disable the GC; otherwise GC runs significantly skew timing
# (with a million elements, the GC would normally run within the loops)
import gc
gc.disable()

m = ConcreteModel()
m.I = RangeSet(1000000)
timer = TicTocTimer()

m.x = Var(m.I)
timer.toc("Real: unbounded: construct")
for v in m.x.values():
    v.set_value(1, validate_value=True)
timer.toc("Real: unbounded: set_value(validate_value=True), valid")
for v in m.x.values():
    v.set_value(1, validate_value=False)
timer.toc("Real: unbounded: set_value(validate_value=False), valid")

m.xb = Var(m.I, bounds=(0,1))
timer.toc("Real: bounded: construct")
for v in m.xb.values():
    v.set_value(1, validate_value=True)
timer.toc("Real: bounded: set_value(validate_value=True), valid")
for v in m.xb.values():
    v.set_value(1, validate_value=False)
timer.toc("Real: bounded: set_value(validate_value=False), valid")

m.y = Var(m.I, domain=Integers)
timer.toc("Integers: unbounded: construct")
for v in m.y.values():
    v.set_value(1, validate_value=True)
timer.toc("Integers: unbounded: set_value(validate_value=True), valid")
for v in m.y.values():
    v.set_value(1, validate_value=False)
timer.toc("Integers: unbounded: set_value(validate_value=False), valid")

m.yb = Var(m.I, domain=Integers, bounds=(0,10))
timer.toc("Integers: bounded: construct")
for v in m.yb.values():
    v.set_value(1, validate_value=True)
timer.toc("Integers: bounded: set_value(validate_value=True), valid")
for v in m.yb.values():
    v.set_value(1, validate_value=False)
timer.toc("Integers: bounded: set_value(validate_value=False), valid")

m.b = Var(m.I, domain=Binary)
timer.toc("Binary: unbounded: construct")
for v in m.b.values():
    v.set_value(1, validate_value=True)
timer.toc("Binary: unbounded: set_value(validate_value=True), valid")
for v in m.b.values():
    v.set_value(1, validate_value=False)
timer.toc("Binary: unbounded: set_value(validate_value=False), valid")

#-----
print()

with LoggingIntercept():
    for v in m.yb.values():
        v.set_value(0.5, validate_value=True)
    timer.toc("Integers: bounded: set_value(validate_value=True), bad domain")
    for v in m.yb.values():
        v.set_value(11, validate_value=True)
    timer.toc("Integers: bounded: set_value(validate_value=True), bad bound")
```

Outputs:
```
[+   0.60] Real: unbounded: construct
[+   1.73] Real: unbounded: set_value(validate_value=True), valid
[+   0.58] Real: unbounded: set_value(validate_value=False), valid
[+   0.60] Real: bounded: construct
[+   2.05] Real: bounded: set_value(validate_value=True), valid
[+   0.60] Real: bounded: set_value(validate_value=False), valid
[+   0.59] Integers: unbounded: construct
[+   2.09] Integers: unbounded: set_value(validate_value=True), valid
[+   0.59] Integers: unbounded: set_value(validate_value=False), valid
[+   0.59] Integers: bounded: construct
[+   2.40] Integers: bounded: set_value(validate_value=True), valid
[+   0.59] Integers: bounded: set_value(validate_value=False), valid
[+   0.59] Binary: unbounded: construct
[+   2.10] Binary: unbounded: set_value(validate_value=True), valid
[+   0.59] Binary: unbounded: set_value(validate_value=True), valid

[+  19.96] Integers: bounded: set_value(validate_value=True), bad domain
[+  19.35] Integers: bounded: set_value(validate_value=False), bad bound
```

...my takeaway is that there is a 3-4x penalty for domain/bounds validation over just setting the variable value, assuming the validation passes.  Things get very slow if the warning is emitted (entirely due to constructing the string and sending it through the logging infrastructure).  The warning timing is actually a bit optimistic, as it assumes something like #1228 has been adopted -- without that, string generation is even slower (because we include the component name in the logged message).

**Comment by jsiirola** [comment]
One thing that surprised me as I was working on `Var`, was that when I "turned on" bounds validation, several of our performance tests slowed down -- due to the validation failing.  This included the OPF model (it has shunt loads initialized to nonzero values when the min and max are 0), and (maybe more concerning) the StochPDEgas problem where the constant initializer for `p` is not compatible with all NODE-specific `pmin`/`pmax` values.

So even we have examples with "questionable initialization" due to not checking the bounds.

**Comment by DLWoodruff** [comment]
My vote is in favor of this PEP because I think this kind of validation is central to an AML.  
For various reasons, I would be even more in favor of
v.force_value(1134)
to bypass checking instead of
v.set_value(1134, validate_value=False)

**Comment by jsiirola** [comment]
I like the idea of a new `force_value()` method, in part because the current flag to `set_value` is `valid` (which has exactly the opposite Boolean sense as `validate_value` and I was a bit worried about the correct deprecation path).

**Comment by michaelbynum** [comment]
As long as there is a way to bypass validation, I am happy.

**Comment by michaelbynum** [comment]
By the way, I have always viewed purpose of the bounds and domain as information to pass to solvers rather than for validation. However, I don't feel strongly. As I mentioned above, as long as there is a way to bypass validation, I am happy.

I do feel strongly that solver interfaces should bypass validation when loading solutions. We should have good unit tests to ensure the correct bounds and domain are going to solvers, and we should be confident the results are valid if a feasible solution was found. Loading solutions back into Pyomo models from solvers can, in some cases, take a nontrivial amount of time, and I don't want to make it any slower.

**Comment by blnicho** [comment]
I'm in favor of the proposals in this PEP. I have a slight preference for the `validate_value` option instead of introducing a `force_value()` method based on some of the comments @whart222 made. I could also envision a "performance mode" configuration for Pyomo where I think changing default options under the hood would be easier to implement than changing method names.
