### ISSUE TITLE
Variable/Constraint Scaling

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#219]
It looks like a variable scaling feature in Pyomo would be very useful.  Depending on what units of measure I'm using I can have variables with values as low as 1e-9 (maybe lower).  Right now if I really need to scale something I create a variable "something_scaled" and and expression "something" where something is like something_scaled/1e9.  Then the variable "something_scaled" has a reasonable magnitude and I use the expression in place of the original unscaled variable.

It would be nice if variables just had a scale factor to do something similar.  Although equation scaling is pretty easy, a similar thing could be done with constraints.

**Comment by carldlaird** [comment]
I am working on this feature right now. If you have a good example where it changes the convergence behavior, it would be a good test case. We could test original, your manually scaled case, the Pyomo scaled case -- and then make sure the last two have the same answer.

Send me an email if you want to discuss further.

**Comment by eslickj** [comment]
I pretty busy in the next week, and I don't have a good example off hand, but I'll pay around with the model and get some example I come up with some good cases (hopefully next week).

**Comment by carldlaird** [comment]
This issue is resolved in PR #235 (Scaling Transformation).

**Comment by blnicho** [comment]
This issue was resolved in #694
