### ISSUE TITLE
Use min() inside  optimization function

### ISSUE THREAD

**Issue by ShirsenduRyo** [Pyomo/pyomo#2190]
## Summary

I want to optimize function : max(sum(P*UC) - sum(P - min(P))), where UC is derived and P is endogenous. Here P is a list of n elements, with constraint P[i] <= P[i] <= 1.1*P[i], and Uc is calculated from P[i]. Do you think taking min_p as a variable is a good idea considering min_p depends on P[n] ?

**Comment by jsiirola** [comment]
GitHub Issues are intended for reporting and tracking Pyomo bug reports and enhancement requests.  Please direct user support questions to the channels mentioned in the [Getting Help](https://github.com/Pyomo/pyomo#getting-help) section of the main project page.  Thank you!
