### ISSUE TITLE
contrib.propagate_fixed_vars ignores constants in linear equality constraints

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#2205]
## Summary

`contrib.propagate_fixed_vars` can fix variables to the wrong value if they appear in constraints that look like `x == y + constant`.

### Steps to reproduce the issue
```
from pyomo.environ import *

m = ConcreteModel()
m.x = Var(bounds=(0,6))
m.y = Var(bounds=(-10,1))
m.z = Var(bounds=(-4,5))
m.cons = Constraint(expr=m.x==m.y + 3)
m.cons2 = Constraint(expr=m.x==0)

TransformationFactory('contrib.propagate_fixed_vars').apply_to(m)
m.x.pprint()
m.y.pprint()
```
Output:
```
x : Size=1, Index=None
    Key  : Lower : Value : Upper : Fixed : Stale : Domain
    None :     0 :   0.0 :     6 :  True : False :  Reals
y : Size=1, Index=None
    Key  : Lower : Value : Upper : Fixed : Stale : Domain
    None :   -10 :   0.0 :     1 :  True : False :  Reals
```

### Error Message

This is silently wrong! According to what the transformation claims to do in its docstring, this call should be a no-op. However, it does actually find the `x == 0` constraint and propagate that, but when it does so it ignores the constant in `m.cons`.

### Information on your system

Pyomo version: main
Python version: 3.8
Operating system: linux
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable):

### Additional information

This is a very simple fix for it to not be wrong: It just needs to check that `repn.constant == 0` in the `if` statement on line 45 of `equality_propagate.py`. However, I'm not convinced that's the fix we want because the result would be just to not fix `m.y`, whereas what one might expect is to fix `m.y` to -3.

**Comment by vova292** [comment]
Related to #2101

**Comment by emma58** [comment]
Ah, thank you @vova292, this is a duplicate issue.
