### ISSUE TITLE
Unclear error from model.write with invalid file extension

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#222]
The error given by `model.write` when the user provides an invalid file extension with the intention of relying on `guess_format` is unclear. See the following:

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.write('file.something')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gseastre/pyomo/src/pyomo/pyomo/core/base/block.py", line 1647, in write
    io_options)
TypeError: __call__() takes at most 3 arguments (5 given)
```

This appears to be due to the fact that `guess_format` returns `None` when the file extension does not match any know problem format. Thus, `model.write` is calling the return of `WriterFactory(None)`, which is a generic `PluginFactoryFunctor object`.

My feeling is that the error should indicate that no valid format could be determined from `guess_format`. I discovered this issue when I tried to input a .xlsx file without realizing I was not on my excel branch so .xlsx was not a supported format.

**Comment by qtothec** [comment]
I'm sure that a PR with the relevant change would be welcome. =)
