### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by aliule2020** [Pyomo/pyomo#2228]
from pyomo.environ import *
from pyomo.dae import *
m = ConcreteModel()
m.t = ContinuousSet(bounds=(0,10))

m.VCC0P0V=Param(initialize =12)
m.GND5P0V=Param(initialize =0)

m.VCC0P0V=Var(m.t)
m.R1P0V=Var(m.t)
m.R1P1V=Var(m.t)
m.J2I0=Var(m.t)
m.J2I1=Var(m.t)
m.J2I2=Var(m.t)
m.J2I3=Var(m.t)
m.J2P0V=Var(m.t)
m.J2P1V=Var(m.t)
m.J2P2V=Var(m.t)
m.J2P3V=Var(m.t)
m.C3P0V=Var(m.t)
m.C3P1V=Var(m.t)
m.dC3P0V=DerivativeVar(m.C3P0V)
m.dC3P1V=DerivativeVar(m.C3P1V)
m.J4I0=Var(m.t)
m.J4I1=Var(m.t)
m.J4I2=Var(m.t)
m.J4I3=Var(m.t)
m.J4P0V=Var(m.t)
m.J4P1V=Var(m.t)
m.J4P2V=Var(m.t)
m.J4P3V=Var(m.t)
m.GND5P0V=Var(m.t)
m.VP6P0V=Var(m.t)
m.VP6P1V=Var(m.t)
m.VCC0I=Var(m.t)
m.Wire7I=Var(m.t)
m.R1I=Var(m.t)
m.Wire7I=Var(m.t)
m.Wire7P0V=Var(m.t)
m.Wire7P1V=Var(m.t)
m.VCC0P0V=Var(m.t)
m.R1P1V=Var(m.t)
m.R1I=Var(m.t)
m.Wire8I=Var(m.t)
m.J2I2 = Var(m.t)
m.Wire8I=Var(m.t)
m.Wire8P0V=Var(m.t)
m.Wire8P1V=Var(m.t)
m.R1P0V=Var(m.t)
m.J2P2V=Var(m.t)
m.J2I1 = Var(m.t)
m.Wire9I=Var(m.t)
m.C3I=Var(m.t)
m.Wire9I=Var(m.t)
m.Wire9P0V=Var(m.t)
m.Wire9P1V=Var(m.t)
m.J2P1V=Var(m.t)
m.C3P1V=Var(m.t)
m.C3I=Var(m.t)
m.Wire10I=Var(m.t)
m.J4I2 = Var(m.t)
m.Wire10I=Var(m.t)
m.Wire10P0V=Var(m.t)
m.Wire10P1V=Var(m.t)
m.C3P0V=Var(m.t)
m.J4P2V=Var(m.t)
m.J4I1 = Var(m.t)
m.Wire11I=Var(m.t)
m.GND5I=Var(m.t)
m.Wire11I=Var(m.t)
m.Wire11P0V=Var(m.t)
m.Wire11P1V=Var(m.t)
m.J4P1V=Var(m.t)
m.GND5P0V=Var(m.t)
m.J2I0 = Var(m.t)
m.Wire12I=Var(m.t)
m.VP6I=Var(m.t)
m.Wire12I=Var(m.t)
m.Wire12P0V=Var(m.t)
m.Wire12P1V=Var(m.t)
m.J2P0V=Var(m.t)
m.VP6P1V=Var(m.t)
m.VP6I=Var(m.t)
m.Wire13I=Var(m.t)
m.J4I0 = Var(m.t)
m.Wire13I=Var(m.t)
m.Wire13P0V=Var(m.t)
m.Wire13P1V=Var(m.t)
m.VP6P0V=Var(m.t)
m.J4P0V=Var(m.t)

def _con1(m,t):
    return m.R1P1V[t]-m.R1P0V[t]==100.000000*m.R1I[t]
m.con1 = Constraint(m.t, rule = _con1)
def _con2(m,t):
    return m.J2I0[t]+m.J2I1[t]+m.J2I2[t]+m.J2I3[t]==0
m.con2 = Constraint(m.t, rule = _con2)
def _con3(m,t):
    return m.J2P0V[t]==m.J2P1V[t]
m.con3 = Constraint(m.t, rule = _con3)
def _con4(m,t):
    return m.J2P1V[t]==m.J2P2V[t]
m.con4 = Constraint(m.t, rule = _con4)
def _con5(m,t):
    return m.J2P2V[t]==m.J2P3V[t]
m.con5 = Constraint(m.t, rule = _con5)
def _con6(m,t):
    return m.dC3P1V[t]-m.dC3P0V[t]==1/0.010000*m.C3I[t]
m.con6 = Constraint(m.t, rule = _con6)
def _con7(m,t):
    return m.J4I0[t]+m.J4I1[t]+m.J4I2[t]+m.J4I3[t]==0
m.con7 = Constraint(m.t, rule = _con7)
def _con8(m,t):
    return m.J4P0V[t]==m.J4P1V[t]
m.con8 = Constraint(m.t, rule = _con8)
def _con9(m,t):
    return m.J4P1V[t]==m.J4P2V[t]
m.con9 = Constraint(m.t, rule = _con9)
def _con10(m,t):
    return m.J4P2V[t]==m.J4P3V[t]
m.con10 = Constraint(m.t, rule = _con10)

def _con12(m,t):
    return m.VP6I[t]==0
m.con12 = Constraint(m.t, rule = _con12)
def _con13(m,t):
    return m.VCC0I[t]==-m.Wire7I[t]
m.con13 = Constraint(m.t, rule = _con13)
def _con14(m,t):
    return m.R1I[t]==-m.Wire7I[t]
m.con14 = Constraint(m.t, rule = _con14)

def _con15(m,t):
    return m.Wire7P0V[t]==m.VCC0P0V[t]
m.con15 = Constraint(m.t, rule = _con15)

def _con16(m,t):
    return m.Wire7P0V[t]==m.Wire7P1V[t]
m.con16 = Constraint(m.t, rule = _con16)
def _con17(m,t):
    return m.Wire7P1V[t]==m.R1P1V[t]
m.con17 = Constraint(m.t, rule = _con17)
def _con18(m,t):
    return m.R1I[t]==-m.Wire8I[t]
m.con18 = Constraint(m.t, rule = _con18)
def _con19(m,t):
    return m.J2I2[t]==m.Wire8I[t]
m.con19 = Constraint(m.t, rule = _con19)
def _con20(m,t):
    return m.Wire8P0V[t]==m.R1P0V[t]
m.con20 = Constraint(m.t, rule = _con20)
def _con21(m,t):
    return m.Wire8P0V[t]==m.Wire8P1V[t]
m.con21 = Constraint(m.t, rule = _con21)
def _con22(m,t):
    return m.Wire8P1V[t]==m.J2P2V[t]
m.con22 = Constraint(m.t, rule = _con22)
def _con23(m,t):
    return m.J2I1[t]==-m.Wire9I[t]
m.con23 = Constraint(m.t, rule = _con23)
def _con24(m,t):
    return m.C3I[t]==-m.Wire9I[t]
m.con24 = Constraint(m.t, rule = _con24)
def _con25(m,t):
    return m.Wire9P0V[t]==m.J2P1V[t]
m.con25 = Constraint(m.t, rule = _con25)
def _con26(m,t):
    return m.Wire9P0V[t]==m.Wire9P1V[t]
m.con26 = Constraint(m.t, rule = _con26)
def _con27(m,t):
    return m.Wire9P1V[t]==m.C3P1V[t]
m.con27 = Constraint(m.t, rule = _con27)
def _con28(m,t):
    return m.C3I[t]==-m.Wire10I[t]
m.con28 = Constraint(m.t, rule = _con28)
def _con29(m,t):
    return m.J4I2[t]==m.Wire10I[t]
m.con29 = Constraint(m.t, rule = _con29)
def _con30(m,t):
    return m.Wire10P0V[t]==m.C3P0V[t]
m.con30 = Constraint(m.t, rule = _con30)
def _con31(m,t):
    return m.Wire10P0V[t]==m.Wire10P1V[t]
m.con31 = Constraint(m.t, rule = _con31)
def _con32(m,t):
    return m.Wire10P1V[t]==m.J4P2V[t]
m.con32 = Constraint(m.t, rule = _con32)
def _con33(m,t):
    return m.J4I1[t]==-m.Wire11I[t]
m.con33 = Constraint(m.t, rule = _con33)
def _con34(m,t):
    return m.GND5I[t]==-m.Wire11I[t]
m.con34 = Constraint(m.t, rule = _con34)
def _con35(m,t):
    return m.Wire11P0V[t]==m.J4P1V[t]
m.con35 = Constraint(m.t, rule = _con35)
def _con36(m,t):
    return m.Wire11P0V[t]==m.Wire11P1V[t]
m.con36 = Constraint(m.t, rule = _con36)
def _con37(m,t):
    return m.Wire11P1V[t]==m.GND5P0V[t]
m.con37 = Constraint(m.t, rule = _con37)
def _con38(m,t):
    return m.J2I0[t]==-m.Wire12I[t]
m.con38 = Constraint(m.t, rule = _con38)
def _con39(m,t):
    return m.VP6I[t]==-m.Wire12I[t]
m.con39 = Constraint(m.t, rule = _con39)
def _con40(m,t):
    return m.Wire12P0V[t]==m.J2P0V[t]
m.con40 = Constraint(m.t, rule = _con40)
def _con41(m,t):
    return m.Wire12P0V[t]==m.Wire12P1V[t]
m.con41 = Constraint(m.t, rule = _con41)
def _con42(m,t):
    return m.Wire12P1V[t]==m.VP6P1V[t]
m.con42 = Constraint(m.t, rule = _con42)
def _con43(m,t):
    return m.VP6I[t]==-m.Wire13I[t]
m.con43 = Constraint(m.t, rule = _con43)
def _con44(m,t):
    return m.J4I0[t]==m.Wire13I[t]
m.con44 = Constraint(m.t, rule = _con44)
def _con45(m,t):
    return m.Wire13P0V[t]==m.VP6P0V[t]
m.con45 = Constraint(m.t, rule = _con45)
def _con46(m,t):
    return m.Wire13P0V[t]==m.Wire13P1V[t]
m.con46 = Constraint(m.t, rule = _con46)
def _con47(m,t):
    return m.Wire13P1V[t]==m.J4P0V[t]
m.con47 = Constraint(m.t, rule = _con47)
def _con48(m,t):
    return m.J2I3[t]==0
m.con48 = Constraint(m.t, rule = _con48)
def _con49(m,t):
    return m.J4I3[t]==0
m.con49 = Constraint(m.t, rule = _con49)

def _init(m):
    yield m.C3P1V[0]-m.C3P0V[0] == 0
m.init_conditions = ConstraintList(rule=_init)

TransformationFactory('dae.collocation').apply_to(m, nfe=100,ncp=6,scheme='LAGRANGE-RADAU')
results = SolverFactory('ipopt').solve(m)

**Comment by aliule2020** [comment]
in fact, I have defined m.C3P0V above,but it still echo "KeyError: (1768032507272, "Variable 'C3P0V[0]' is not part of the model being written out, but appears in an expression used on this model."

**Comment by jsiirola** [comment]
@aliule2020, GitHub issues are for reporting bugs in Pyomo and requesting new features.  Please direct support questions to the Pyomo forum or StackOverflow (see [Getting Help](https://github.com/Pyomo/pyomo#getting-help)).

Your error is almost certainly because you are declaring `C3P0V` twice.  You should see a warning in the console:
```
WARNING: Implicitly replacing the Component attribute C3P0V (type=<class
    'pyomo.core.base.var.IndexedVar'>) on block unknown with a new
    Component (type=<class 'pyomo.core.base.var.IndexedVar'>).
    This is usually indicative of a modelling error. To avoid this warning,
    use block.del_component() and block.add_component().
```

**Comment by aliule2020** [comment]
> 
Thank you very much! It is generated by program,so I didn't notice it. You are right, thank you again. Because I am in C_h_i_n_a,so the web connect is not so good,so I have to post the issue here, where I can post.^_^
