### ISSUE TITLE
I have two problems.

### ISSUE THREAD

**Issue by aliule2020** [Pyomo/pyomo#2235]
1.  **Can I call pyomo in C just using PyRun_SimpleString(), such as PyRun_SimpleString("from pyomo.environ import *")      (but it failed) ? I wonder if it is designed to be used just in the way that we have to call pyomo in .py files? IF NOT, HOW SHOULD I DO? **
2. **CODE IS BELOW:**
`from pyomo.environ import *
from pyomo.dae import *

model = m = ConcreteModel()
m.t = ContinuousSet(bounds=(0, 10))

TH=2;
TL=0.8
H=1;
L=0;
Z=-1;

m.in1=Var(m.t)
m.in2=Var(m.t)
m.out1=Var(m.t)

def _init(m):
    yield m.in1[0] == 3
    yield m.in2[0] == 3
m.init_conditions = ConstraintList(rule=_init)

def _con1(m,t):
	  if(value(m.in1[t])>=(TH)):
	  	  min1=H
	  elif(value(m.in1[t])<=(TL)):
	      min1=L
	  else:
	  	  min1=Z  

	  if( value(m.in2[t])>=(TH)):
	  	  min2=H
	  elif(value(m.in2[t])<=(TL)):
	      min2=L
	  else:
	  	  min2=Z 
	  
	  if(min1==H and min2==H):
	  	  return out1[t]==5
	  else:
	  	  return out1[t]==0	  	
	  	        	  
m.con1=Constraint(m.t,rule=_con1)

TransformationFactory('dae.collocation').apply_to(m, nfe=7, ncp=6, scheme='LAGRANGE-RADAU' )
results = SolverFactory('ipopt').solve(m)`

**HOW SHOULD I CORRECT THEM?**

**Comment by blnicho** [comment]
@aliule2020, GitHub issues are for reporting bugs in Pyomo and requesting new features. Please direct support questions to the Pyomo forum or StackOverflow (see Getting Help).

**Comment by aliule2020** [comment]
I know it is not encouraged to post my question here, but if you know it is difficult even if just to post my problem here in my country and it is impossible to visit the _g_o_o_g__l_e here,  I have no way but this mehtod.
