### ISSUE TITLE
Multiple Finite Difference Transformation in Different Bounds on same ContinuousSet

### ISSUE THREAD

**Issue by chemrgineer** [Pyomo/pyomo#2270]
## Summary

Hi, I'm trying to implement NLP that contains PDE. I need to discretize my continuous set (x and y) 2 different NFE.
For better explanation, I need to divide x, 
   40 piece in (0, 0.2) 
   10 piece in (0.2, 0.8)
   40 piece in (0.8, 1.0)

I can apply one type discretization on whole domain of x with below codes:
m.x = ContinuousSet(bounds=(0, 1))
discretizer = TransformationFactory('dae.finite_difference')
discretizer.apply_to(m, nfe=20, wrt=m.x, scheme='CENTRAL')

## Rationale
With this discretization, my model will contain less equation. Its helps solver to handle boundary conditions. 
Obtained solution will be higher resolution on hot-points.

**Comment by blnicho** [comment]
You can do this by passing in the list of finite element points when declaring the `ContinuousSet`:

```
m = ConcreteModel()
m.t = ContinuousSet(initialize=[0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.5, 0.75, 1.0])
```
You can use native Python utilities or even something like Numpy or Scipy to generate the list of points you want to use.

**Comment by chemrgineer** [comment]
Thank you for your answer. Definitely will help me.
