### ISSUE TITLE
contrib.deactivate_trivial_constraints can miss trivial constraints

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#2271]
## Summary

The `contrib.deactivate_trivial_constraints` transformation uses the polynomial degree of the constraint expression to decide if the expression is constant. That's not actually a reliable method of doing so, meaning that it can miss trivial constraints like in the example below, where the polynomial degree of the constraint body evaluates to 1.

### Steps to reproduce the issue

```
from pyomo.environ import *

m = ConcreteModel()
m.x = Var()
m.y = Var()
m.y.fix(0)
m.c = Constraint(expr=m.x*m.y >= 0)

TransformationFactory('contrib.deactivate_trivial_constraints').apply_to(m)

print(m.c.active) # True
```

### Information on your system

Pyomo version: main
Python version: 3.8
Operating system: linux
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable):

### Additional information

I think you could use `generate_standard_repn` to actually detect if a constraint body is constant. This isn't a bug in the sense that it does the wrong thing, but it does fall short on its promises.

**Comment by michaelbynum** [comment]
I think using `generate_standard_repn` within `contrib.deactivate_trivial_constraints` is a good idea. Using `compute_bounds_on_expr` may work as well (in the GDPopt context, we would have to make sure we restored variable bounds before deactivating trivial constraints rather than after).

**Comment by jsiirola** [comment]
@emma58: question: is this a bug in `deactivate_trivial_constraints` or in `polynomial_degree`?

**Comment by emma58** [comment]
@jsiirola, it kind of does seem like a bug in `polynomial_degree` because it's going halfway between evaluating the values of constants and not... It feels like if it's going to go as far as saying that a fixed Var multiplied by a not-fixed Var no longer has polynomial degree 2, it might as well catch that the Var was fixed to 0 and answer 0. Perhaps whether to treat fixed variables as fixed forever should be an option when you ask for the polynomial degree? Because one could imagine a case where 2 would be the answer you wanted, if you're not sure that variable is going to stay fixed.
