### ISSUE TITLE
Make modeling checking the default behavior for the 'pyomo' command

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#23]
I'm adding this issue to force a decision about whether checking is the default behavior.  Given recent discussions regarding categories of Pyomo users, I think it makes the most sense for checking to be the default behavior.  This is a minor code change, but we should advertise it in advance of the 5.0 release if we do this.

**Comment by blnicho** [comment]
The `pyomo.checker` module was deprecated in #2734 so closing this
