### ISSUE TITLE
No binary (float) values for binary variables

### ISSUE THREAD

**Issue by amir-hoseyn77** [Pyomo/pyomo#2321]
Hi,
I have an **all binary variables** (`domain=Binary`) optimization in pyomo. My solver is **Gurobi**. When I solve the model via Gurobi, sometimes the results are neither 0 nor 1. Results are float! For example:
```
array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000072e+00, 0.00000000e+00],  
       [ 0.00000000e+00, -0.00000000e+00, -0.00000000e+00, 0.00000000e+00],  
       [ 0.00000000e+00,  0.00000000e+00, -7.21633987e-07, 1.00000000e+00],  
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00],  
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00]])
```

I don't know why this happens. Can anyone justify non-binary values for binary variables?

**Comment by jsiirola** [comment]
Gurobi (like all MIP solvers) has a non-zero Integer Feasibility Tolerance (see: https://www.gurobi.com/documentation/9.5/refman/intfeastol.html)

**Comment by amir-hoseyn77** [comment]
> Gurobi (like all MIP solvers) has a non-zero Integer Feasibility Tolerance (see: https://www.gurobi.com/documentation/9.5/refman/intfeastol.html)

If I round solution after solving, will any error occur?

Pyomo can automatically take care about this issue? I mean after, when pyomo retrieves solution from the solver, pyomo itself converts floats to variable domains?
