### ISSUE TITLE
CBC support

### ISSUE THREAD

**Issue by rsmith54** [Pyomo/pyomo#238]
How well should CBC be expected to work?

I'm using a SolverFactory like this:

`solver = SolverFactory("cbc")`  
`solver.solve(my_model)`

I'm testing CBC vs GLPK, and I'm surprised to find that GLPK is much faster than CBC.  After doing some profiling, I think this is not mostly due to solver time, but the ```pyomo``` setup steps.   Should I expect CBC to be faster?  Any ideas or hints are appreciated.

**Comment by whart222** [comment]
Do you know if Pyomo is generating NL files for CBC or LP files?  GLPK only
works with NL files, so that might be the difference.

We're in the midst of coding changes that I hope will improve this file
I/O.  I've seen performance differences writing LP and NL files that are
hard to explain.  Sometimes one is faster, and sometimes the other ...

--Bill

**Comment by rsmith54** [comment]
Yes, I see that Pyomo is creating LP files with this setup.  I switched to cbc with NL files, and I saw a significant speed boost.  I think this may not explain the full difference, but it certainly led to significant speedup over LP files anyway.

**Comment by jsiirola** [comment]
That is really interesting: based on the linear models I have seen, I would expect the LP interface (and Bill misspoke: GLPK only uses LP) to be faster than the NL - not the other way around.

Is there any way you can share your model + driver (direct mail to @whart222 or myself would be fine)?

**Comment by rsmith54** [comment]
I can't share the full model, but if I get a chance I will see if I can make a toy version showing the same behavior.  Thanks for your quick responses!

**Comment by jsiirola** [comment]
I am going to close this issue, as it does not point to / request a quantifiable action.  If @rsmith54 can identify a model showing significant discrepancy in the LP and NL interfaces, I recommend opening a new ticket.
