### ISSUE TITLE
Valid CPLEX solution raises a "Cannot load a SolverResults object with bad status: error"

### ISSUE THREAD

**Issue by PascalLesage** [Pyomo/pyomo#2387]
## Summary

I ran `pyomo solve` to optimize a LP model with CPLEX. CPLEX runs fine, and finds a solution. The head of the solution file that CPLEX generates (.sol file) is as follows:

problemName="foo/bar/tmp_a68s6z1.pyomo.lp"
   objectiveValue="-4177903795921.9199"
   solutionTypeValue="1"
   solutionTypeString="basic"
   solutionStatusValue="1"
   solutionStatusString="optimal"
   solutionMethodString="primal"
   primalFeasible="1"
   dualFeasible="1"
   simplexIterations="73645"
   barrierIterations="215"
   writeLevel="1"/>
<quality
   epRHS="9.9999999999999995e-07"
   epOpt="9.9999999999999995e-07"
   maxPrimalInfeas="1.2278178473934531e-10"
   maxDualInfeas="1.862645149230957e-09"
   maxPrimalResidual="2.9863804229535162e-07"
   maxDualResidual="1.4435499906539917e-07"
   maxX="458054325.10083282"
   maxPi="149099314451.14331"
   maxSlack="331116492.39024293"
   maxRedCost="56188111.8913645"
   kappa="2239051055.6802301"/>

Then, once CPLEX prints to standard out that "CPLEX> Solution written to file: path_to_file", pyomo raises "Cannot load a SolverResults object with bad status: error".

Pyomo version: 6.3.0
Python version: 3.10
Operating system: Windows 10
How Pyomo was installed (PyPI, conda, source): pip
Solver (if applicable): CPLEX 22.1.0

**Comment by PascalLesage** [comment]
Problem just disappeared. Happily but confusingly closing issue.

**Comment by svkawtikwar** [comment]
I still face this problem! 
What is super weird is that it is not consistent, only throws error sometimes.
