### ISSUE TITLE
Derivative variables after DAE discretization transformation

### ISSUE THREAD

**Issue by santiagoropb** [Pyomo/pyomo#242]
The following example shows what seems to be inconsistent:
    
    m = pe.ConcreteModel()
    m.t = dae.ContinuousSet(bounds=(0,1))
    m.x = pe.Var([1, 2], m.t, initialize=0.0)
    m.u = pe.Var(m.t, bounds=(None,0.8), initialize=0)
    m.xdot = dae.DerivativeVar(m.x)

    def _x1dot(M, i):
        if i == M.t.first():
            return pe.Constraint.Skip
        return M.xdot[1, i] == (1-M.x[2, i] ** 2) * M.x[1, i] - M.x[2, i] + M.u[i]
    m.x1dotcon = pe.Constraint(m.t, rule=_x1dot)

    def _x2dot(M, i):
        if i == M.t.first():
            return pe.Constraint.Skip
        return M.xdot[2, i] == M.x[1, i]
    m.x2dotcon = pe.Constraint(m.t, rule=_x2dot)

    def _init(M):
        t0 = M.t.first()
        yield M.x[1, t0] == 0
        yield M.x[2, t0] == 1
        yield pe.ConstraintList.End
    m.init_conditions = pe.ConstraintList(rule=_init)

    def _int_rule(M, i):
        return M.x[1, i] ** 2 + M.x[2, i] ** 2 + M.u[i] ** 2
    m.integral = dae.Integral(m.t, wrt=m.t, rule=_int_rule)
    m.obj = pe.Objective(expr=m.integral)

Before discretizing 

        der_vars = m.component_map(dae.DerivativeVar, active=True)
        print(len(der_vars)) # prints 1

After discretizing

        discretizer = pe.TransformationFactory('dae.collocation')
        discretizer.apply_to(m, nfe=20, ncp=3, scheme='LAGRANGE-RADAU')
        discretizer.reduce_collocation_points(m, var=m.u, ncp=1, contset=m.t)

        der_vars = m.component_map(dae.DerivativeVar, active=True)
        print(len(der_vars)) # prints 0
        der_vars = m.component_map(dae.DerivativeVar, active=False)
        print(len(der_vars)) # prints 0

Not sure if this is the desired behavior but it seems counterintuitive.

**Comment by blnicho** [comment]
This is the desired behavior. After discretization, DerivativeVar components are reclassified as Vars so that the writers know how to handle them. I agree that we should support your use-case, that there should still be a way to find all the DerivativeVars on the model after discretizing. Let me think about another way to do this.

**Comment by jsiirola** [comment]
To reinforce @blnicho's comment: to be pedantic, after you have discretized a DerivativeVar it is no longer a derivative, but an approximation of the derivative at each point, so I would argue that the reclassification is proper (not to mention necessary to make things like the writers and repeated calls to discretize a model work correctly).

You can get the list of current and formerly `DerivativeVar` objects with something like:

    der_vars = [ x for x in m.component_objects((Var, DerivativeVar)) if isinstance(x, DerivativeVar) ]
