### ISSUE TITLE
Pyomo solver.solve stuck for big problem using cbc

### ISSUE THREAD

**Issue by lucazav** [Pyomo/pyomo#2429]
I create my model for one product, I tried to solve it with cbc and all worked fine.

Then I tried to use multiple products to build a bigger model. After 10 minutes, the model was correctly defined. But when I run the following code:

```python
# Solve the model
solver = SolverFactory('cbc')

n_threads = os.cpu_count()
solver.options['threads'] = n_threads-1

# Set a timeout after that a solution is returned
solver.options['seconds'] = solver_timeout_sec * (n_threads-1)

# Set the integer tolerance. The integer feasibility tolerance determines when a fractional variable
# can be considered “automatically” integer during the branch-and-bound search (default 1E-7).
solver.options['integerTolerance'] = 1E-3

results = solver.solve(model, tee=True)
```

the execution stuck on it without trying to solve the problem. In fact I can't see any output in the console as I can in the case of the simpler problem.

Any hint? I could also privately provide the code and data to the team to find a possible bug.

I'm using coincbc 2.10.5 and pyomo 6.4.1 on an Ubuntu machine.

**Comment by jsiirola** [comment]
How big is the model you are creating (i.e., # variables, # constraints)?  If it is taking 10 minutes to build the model, it is likely to be very large.

What timeout are you using?  As a general rule of thumb, the current default LP writer takes about as long to compile / write the LP file as the model took to generate in the first place.  It sounds like you may be killing things before they even get started.

**Comment by lucazav** [comment]
There are 92,400 variables and 103,610 constraints.
Any hint on how to manage a problem like this one?

**Comment by jsiirola** [comment]
That is still rather small.  To put things in perspective, one of our standard test models is a little over 400k variables and constraints, and it takes less than 40 seconds to create and write out the model (on very old hardware).  There might be some things with how you are formulating the problem that are causing things to take longer than they need to.  The first thing to do is to call
```
pyomo.common.timing.report_timing()
```
before beginning to construct the model.  That should tell you how long each component takes to construct, and can give you hints as to where to look first.

However, this is all only talking about *formulating* the problem and not *solving* it.  MIPs solve time depends heavily on the formulation (I have seen problems with 100k variables solve in 10's of seconds with a good solver, but then the exact linearization of the 30-site QAP (about 900 binaries) took more than a CPU-*year* to solve).  Unfortunately, formulation techniques are rather outside the scope of this forum.

**Comment by lucazav** [comment]
I'm using the `model.constraint.add()` method to add my constraints. The timing report I got is the following:

```
0 seconds to construct Block ConcreteModel; 1 index total
0 seconds to construct Set OrderedScalarSet; 1 index total
0 seconds to construct Set OrderedScalarSet; 1 index total
0 seconds to construct Set OrderedScalarSet; 1 index total
0 seconds to construct Set SetProduct_OrderedSet; 1 index total
0 seconds to construct Set SetProduct_OrderedSet; 1 index total
0.23 seconds to construct Var X; 92400 indices total
0 seconds to construct Set cons_aaa_index; 1 index total
0 seconds to construct Set cons_bbb_index; 1 index total
0 seconds to construct Set cons_ccc_index; 1 index total
0 seconds to construct Set cons_ddd_index; 1 index total
0 seconds to construct Set cons_eee_index; 1 index total
0 seconds to construct Set cons_fff_index; 1 index total
```

I'm using nested for loops to define my constraints. So, I suppose the time recorded is due to that.

Regardless of the formulation of the problem, I tried with the same problem, but smaller, and all goes fine.
SO, for bigger problem, I would expect Pyomo to give me at least an error message if something is wrong. In this case, processing unexpectedly freezes indefinitely. That's weird.

**Comment by jsiirola** [comment]
It's almost certainly not freezing, but busy working on something.  If you post the model someone may have a chance to look at it.

**Comment by lucazav** [comment]
In these days I'll "anonymize" the model in order to post it here.

There is still a doubt that comes over me: if Pyomo is busy working on something, how come it can't finish the task? I tried leaving it running all night, but I always found it there in processing (I'm working on a 8 cores machine 64 GB RAM).

**Comment by lucazav** [comment]
@jsiirola I solved the model definition huge creation time. Now it takes just 5 seconds to define all the constraint.
But the solver still doesn't give any output. May I send you the pickled model so that you can understand the source of the issue? I really need to fix this problem. I thank you for any help

**Comment by jsiirola** [comment]
@lucazav: I am glad to hear that you resolve the construction time.  By chance, was the solution to change some of the data structures (like `i_of_current_a`) from lists to sets?

I'd be happy to look at the model, but due to security issues with pickles, please send a zip of raw python code and raw data if at all possible.

**Comment by lucazav** [comment]
@jsiirola I used lists and dictionaries instead of pandas dataframes. Could you write me to lucazavarella@outlook.com? I will send you all by email. Thank you so much!

**Comment by jsiirola** [comment]
@lucazav, your model is stuck solving the root LP relaxation.  If you remove the timeout, you will see:
```
Welcome to the CBC MILP Solver 
Version: 2.9.7 
Build Date: Jun 20 2019 
Revision Number: 2590 

command line - cbc -seconds 60 -integerTolerance 0.001 -printingOptions all -import test.lp -stat=1 -solve -solu test.soln (default strategy 1)
seconds was changed from 1e+100 to 60
integerTolerance was changed from 1e-06 to 0.001
Option for printingOptions changed from normal to all
Presolve 76194 (-27277) rows, 65354 (-1) columns and 696815 (-81167) elements
Statistics for presolved model
Original problem has 65354 integers (65354 of which binary)
Presolved problem has 65354 integers (65354 of which binary)
==== 10 zero objective 175 different
==== absolute objective values 175 different
==== for integers 10 zero objective 175 different
==== for integers absolute objective values 175 different
===== end objective counts


Problem has 76194 rows, 65354 columns (65344 with objective) and 696815 elements
Column breakdown:
0 of type 0.0->inf, 0 of type 0.0->up, 0 of type lo->inf, 
0 of type lo->up, 0 of type free, 0 of type fixed, 
0 of type -inf->0.0, 0 of type -inf->up, 65354 of type 0.0->1.0 
Row breakdown:
0 of type E 0.0, 0 of type E 1.0, 0 of type E -1.0, 
0 of type E other, 0 of type G 0.0, 0 of type G 1.0, 
80 of type G other, 20 of type L 0.0, 76014 of type L 1.0, 
80 of type L other, 0 of type Range 0.0->1.0, 0 of type Range other, 
0 of type Free 
Problem is infeasible - 857.92 seconds
Total time (CPU seconds):       859.87   (Wallclock seconds):       892.59
```

FWIW, you are also probably running up against some of the limitations of `cbc`, and might want to consider exploring alternative solvers.  For example, some of the commercial MIP solvers can prove infeasibility in ~15 seconds.

As this is is not a bug/issue with Pyomo, I am going to close this issue.
