### ISSUE TITLE
ModuleNotFoundError when running "pyomo install-extras"

### ISSUE THREAD

**Issue by jackjackk** [Pyomo/pyomo#243]
Starting from a new pyvenv
```
python -m venv myvenv
source myvenv/bin/activate
pip install pyomo
```
I then try to install extras with
```
pyomo install-extras
```
but I get
```
Traceback (most recent call last):
  File "/XXX/myvenv/bin/get_pyomo_extras", line 7, in <module>
    from scripts.get_pyomo_extras import main
ModuleNotFoundError: No module named 'scripts'
```

**Comment by mubashirhanif** [comment]
+1 using the virtual envs on ubuntu.

**Comment by blnicho** [comment]
This needs to be fixed or the installation documentation (http://www.pyomo.org/installation) needs to be updated

**Comment by steve-barnard** [comment]
Has this been fixed?  Still receiving the same error as OP when attempting to:

pyomo install-extras
