### ISSUE TITLE
Support for MOSEK v10

### ISSUE THREAD

**Issue by Utkarsh-Detha** [Pyomo/pyomo#2442]
## Summary

Update the Pyomo interface to support the _affine conic constraints_ and the new _domain_ types introduced in MOSEK v10.

### Rationale

[MOSEK 10 is a major version update](https://docs.mosek.com/10.0/releasenotes/changes.html) with many changes. The changes that concern this request are:

- _Affine conic constraints_ are introduced in the Optimizer API. Users can construct conic constraints like `Fx + g \in K`, where `F` is a coefficient matrix, `g` is a vector of constants, and `K` is a conic **_domain_**. It is therefore no longer necessary to introduce auxiliary variables to include expressions in a nonlinear cone. 
- The old _cone_ types will be deprecated in favor of the new affine conic constraints and the domains therein.
- The new _domains_ include the primal/dual _geometric mean conic domains_ and the _vectorized PSD cone domain_, in addition to the cones that were previously supported in the cones. The power conic domains can also handle long left-hand side terms.

### Description

I am working on passing the conic constraints from Pyomo kernel interface to MOSEK as affine conic constraints (instead of the old cone types) if MOSEK v10 is detected.

But, I would also like to suggest the following:

- Conic constraints in the Kernel interface when constructed `as_domains` should be passed to MOSEK as an ACC, without introducing any auxiliary variables. In fact, I believe it would be more intuitive if the `as_domain` option was the only way to construct conic constraints for MOSEK v10 onwards.
- Support for geometric mean cone and the vectorized PSD cones. (Support for PSD cones will let users to construct linear matrix inequalities in Pyomo)
- The conic constraints for power cones should start supporting long left-hand side terms (i.e. passing a tuple r, instead of two scalars r1 and r2).

If agreed upon, I can work on implementing these suggestions. I would welcome suggestions, especially on how to go about keeping backward compatibility (if at all) in the first suggestion mentioned above.

**Comment by mrmundt** [comment]
Hello, @Utkarsh-Detha. We appreciate your suggestion! We will discuss this request and add it to our backlog for future efforts.

_NOTE_: There is no guarantee that we will implement all suggestions. We do, however, accept external contributions. If you are interested in expediting this request, we encourage you to review our [Contribution Guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html).
