### ISSUE TITLE
error pyinstaller

### ISSUE THREAD

**Issue by cmyf122** [Pyomo/pyomo#2468]
When I used pyinstaller to package a program containing pyomo, I reported an error, which showed that I was missing a certain module. I tried to import it with --hidden -import, but I reported that other modules were missing. What should I do?

**Comment by blnicho** [comment]
@cmyf122 what version of Pyomo are you using? Could you post the full error message you're getting?

**Comment by cmyf122** [comment]
您好！您可以添加微信：canglang12001，获取相关资源。

**Comment by mrmundt** [comment]
@cmyf122 - Please post the following information:

### Information on your system

Pyomo version:
Python version:
Operating system:
How Pyomo was installed (PyPI, conda, source):
Solver (if applicable):
