### ISSUE TITLE
Appsi fbbt doesn't know about AutoLinkedBinaryVars

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#2491]
## Summary

There's a `KeyError` when using the appsi implementation of fbbt on transformed GDP models.

### Steps to reproduce the issue

```
from pyomo.environ import *
from pyomo.gdp import *
from pyomo.contrib import appsi

m = ConcreteModel()
m.x = Var(bounds=(3, 4))
m.disjunction = Disjunction(expr=[[m.x == 3.5], [m.x >= 3.9]])
TransformationFactory('gdp.bigm').apply_to(m)

it = appsi.fbbt.IntervalTightener()
it.perform_fbbt(m)
```

### Error Message

```
Traceback (most recent call last):
  File "appsi_bug.py", line 11, in <module>
    it.perform_fbbt(m)
  File "/home/esjohn/src/pyomo/pyomo/contrib/appsi/fbbt.py", line 219, in perform_fbbt
    self.set_instance(model, symbolic_solver_labels=symbolic_solver_labels)
  File "/home/esjohn/src/pyomo/pyomo/contrib/appsi/fbbt.py", line 94, in set_instance
    self.add_block(model)
  File "/home/esjohn/src/pyomo/pyomo/contrib/appsi/base.py", line 915, in add_block
    self.add_constraints([con for con in block.component_data_objects(Constraint, descend_into=True,
  File "/home/esjohn/src/pyomo/pyomo/contrib/appsi/base.py", line 842, in add_constraints
    self._add_constraints(cons)
  File "/home/esjohn/src/pyomo/pyomo/contrib/appsi/fbbt.py", line 122, in _add_constraints
    cmodel.process_fbbt_constraints(self._cmodel, self._pyomo_expr_types, cons, self._var_map, self._param_map,
KeyError: <class 'pyomo.gdp.disjunct.AutoLinkedBinaryVar'>
```

### Information on your system

Pyomo version: main
Python version: 3.8
Operating system: linux
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable):

**Comment by michaelbynum** [comment]
@emma58 Are you sure you don't just need to rebuild Appsi? The example you posted works for me, and, after checking, it looks like I have already told Appsi about `AutoLinkedBinaryVar`. If you rebuild Appsi and still get this error, please let me know.

**Comment by jsiirola** [comment]
Does APPSI embed a library version identifier into the compiled library?  We do this for `libpynumero_ASL` so that we can complain when it looks like we are attempting to load an old version of the library: we can both warn the user that they should rebuild the library and potentially put into place compatibility wrappers.

**Comment by michaelbynum** [comment]
Great suggestion @jsiirola. I will add something similar to Appsi.

**Comment by emma58** [comment]
@michaelbynum, whoops, yes, you are right. It's fine after rebuilding.
