### ISSUE TITLE
Component.reconstruct() fails

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#252]
From the [pyomo-forum](https://groups.google.com/d/msg/pyomo-forum/Qm4Iwvwuthk/Y1puNJFCAQAJ):

I am trying to update the a Set and then use reconstruct on constraints and objective functions but I am getting an error. Here's an Example:

```python
from pyomo.environ import *
from pyomo.opt import SolverFactory

# Create a solver
opt = SolverFactory('gurobi')

#
# A simple model with binary variables and
#
completeSet = [1,2,3,4]
model = ConcreteModel()
model.n = Param(default=2,mutable=True)

model.testSet = Set(initialize = completeSet[:2])

model.x = Var(model.testSet,bounds=(-4,4))
def o_rule(model):
    return sum(model.n * model.x[i] for i in model.testSet)
    # return model.n * model.x
model.o = Objective(rule=o_rule,sense=minimize)

def c1(model):
    return sum(model.x[i] for i in model.x) >=0
model.c1 = Constraint(rule=c1)

def c2(model,i):
    return model.x[i]<=3
model.c2 = Constraint(model.testSet,rule=c2)

# Create a model instance and optimize
results = opt.solve(model)

model.testSet.add(4)
model.o.reconstruct()
model.c1.reconstruct()
model.c2.reconstruct()

results2 = opt.solve(model)
``` 

But the code breaks whenever reconstruct() is used, with an error 

``` 
  File "C:\Python27\lib\site-packages\pyomo\core\base\component.py", line 309, in reconstruct
    self.construct(data=data)
  File "C:\Python27\lib\site-packages\pyomo\core\base\constraint.py", line 727, in construct
    assert None not in self._data
AssertionError
```

Is reconstruct not used anymore? is there an alternative or is there something wrong with my code?

**Comment by jsiirola** [comment]
It looks like reconstruct() silently started failing two years ago (July 31 2015 for Objective) due to a series of commits that caused the core modeling components to dispose of initialization information in an attempt to recover memory.

**Comment by jsiirola** [comment]
Right now, reconstruct() does not work anywhere.  This is due to two things:
1)	The old _data dictionary was never cleared by reconstruct().  This triggers error checking assertions in construct(), which causes reconstruct() to fail.  I don’t know when those additional error checks were added, but they are good and shouldn’t be removed [there is a subtle bug in reconstruct() that has probably existed since the dawn of time – it probably hasn’t bit any one based on how most people used reconstruct(), but it is there nonetheless]. 
2)	Starting ~2 years ago, a lot of the initialization information (passed through the component constructor) was deleted after construction (ostensibly to free up memory).  This means that the information that construct() needs is no longer available, so construct() fails.  The exception is that I forced us to keep the rules around for constraints, because removing them fundamentally breaks the discretization in pyomo.dae.

So, the workarounds:
1)	Users could make reconstruct() work *for indexed constraints only* without editing the Pyomo code by manually clearing the _data dictionary beforehand:
model.c._data = {}
model.c.reconstruct()
2)	For scalar constraints and any objectives, the above is insufficient: you also need to go in and hack pyomo.core.base.{constraint,objective} to comment out the lines in construct() that clear the initialization information.
3)	I did not look at any other components, but would expect to find something similar.

**Comment by jsiirola** [comment]
This is related to part of the problem reported in #226.

**Comment by jsiirola** [comment]
@ghackebeil: The obvious way to fix this is to stop removing initialization information from Components after construction.  Do you see problems with making this change?

**Comment by GiorgioBalestrieri** [comment]
any updates on this? I think the best would be to be able to choose whether the initialization is retained or removed. When one calls `abstract_model.create_instance`, there should be a `keep_init` keyword argument defaulting to `False` (I guess). Would this work?

By the way, not sure it's related, but I currently see `component.recostruct` failing because it tries to explicitly call `self.construct(data=data)`, but `self.construct` now has a `values` argument rather than a `data` argument.

**Comment by wenjingsu16** [comment]
Hi, I see that `component.reconstruct` is removed from pyomo. But I tried `component.clear()` and then `component.construct(data=data)`. The construct does not seem to be working and the component is still the same as the component after clear. May I ask why this happens? I defined my component as mutable and gave it an initial value.
