### ISSUE TITLE
The SolverFactory was unable to create the solver "_cplex_shell"

### ISSUE THREAD

**Issue by xiyangcanyi** [Pyomo/pyomo#2533]
The original solver was created with the following parameters:
	executable: D:\IBM ILOG CPLEX Optimization Studio\cplex\bin\x64_win64
	type: _cplex_shell
	_args: ()
	options: {'threads': 4, 'timelimit': 2000}

**Comment by jsiirola** [comment]
Please provide a minimal (code) example that reproduces the error, along with the complete error message / stack trace you are getting.  There is not enough information here for us to be able to help you.
