### ISSUE TITLE
dat file parser gives unhelpful message for two-dimensional set input

### ISSUE THREAD

**Issue by DLWoodruff** [Pyomo/pyomo#257]
[2dDat.zip](https://github.com/Pyomo/pyomo/files/1486067/2dDat.zip)
The attached example has a 2d set with the correct syntax for AMPL in the dat file, but this is the
result (at a minimum the message should indicate that it comes from the dat file parser).

$ pyomo solve 2dDAT.py 2dDAT.dat --solver=cplex

[    0.00] Setting up Pyomo environment
[    0.00] Applying Pyomo preprocessing actions
[    0.00] Creating model
[    0.02] Pyomo Finished
ERROR: Unexpected exception while running model: Unexpected comma outside of
    (), {} or [] declarations

**Comment by mrmundt** [comment]
@DLWoodruff @blnicho - I'm going through old bug reports. Is this bug still present in the most recent Pyomo version?

**Comment by mrmundt** [comment]
In an effort to clean up issues, we are moving some discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
