### ISSUE TITLE
dat file empty 2d set error

### ISSUE THREAD

**Issue by DLWoodruff** [Pyomo/pyomo#258]
[empty2d.zip](https://github.com/Pyomo/pyomo/files/1486275/empty2d.zip)
The attached files have an example of an AMPL-format dat file with an empty 2 dimensional set that results in an error. A potential fix that seems like it might work is as follows: in PyomoModel.py in _tupelize add
        if len(list(data.keys())) == 1 and list(data.keys())[0] is None and len(data[None]) == 0:
              return None
right before
        ans = {}
but there is probably something better.
To see the error, use something like:
pyomo solve 2dDAT.py empty2d.dat --solver=cplex

**Comment by mrmundt** [comment]
@DLWoodruff @blnicho - I'm going through old bug reports. Is this bug still present in the most recent Pyomo version?

**Comment by mrmundt** [comment]
In an effort to clean up issues, we are moving some discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
