### ISSUE TITLE
Integrate PySP commands into the 'pyomo' command

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#26]
A while back we integrated most of Pyomo's commands as subcommands of the pyomo command.  The exception was PySP, which was in flux at the time.  I'm not sure we can do this before the 5.0 release, but this still should be done.

I'm open to suggestions for the subcommands that are used, particularly for Pyro.

**Comment by whart222** [comment]
If we resolve this ticket before Pyomo 5.0, then we should update the book's description of the 'pyomo help' subcommand.

**Comment by blnicho** [comment]
This is duplicated in #1040 so closing this
