### ISSUE TITLE
Unable to import pyomo.environ on python 3.11

### ISSUE THREAD

**Issue by trigaut** [Pyomo/pyomo#2600]
## Summary

With pyomo 6.4.2 on python 3.11 importing pyomo.environ raises an error.

### Steps to reproduce the issue

```console
import pyomo.environ as pyo
```

### Error Message

```console
pyomo\core\base\component.py", line 471, in __getstate__
    state[key] = val
    ~~~~~^^^^^
TypeError: 'tuple' object does not support item assignment
```

### Information on your system

Pyomo version: 6.4.2
Python version: 3.11
Operating system: Windows 10
How Pyomo was installed: Pypi

**Comment by blnicho** [comment]
This was resolved in main by https://github.com/Pyomo/pyomo/pull/2596 and will be part of the next release (currently scheduled for Nov 21).
