### ISSUE TITLE
Unable to run precompiled `Highs` executable with Pyomo 6.4.3.dev0

### ISSUE THREAD

**Issue by alejandro-yousef** [Pyomo/pyomo#2604]
## Summary
I know it may be too soon and I should wait for the official release but maybe it is useful to report it...

I tried to run Highs with Pyomo 6.4.3.dev0 (from source) having previously installed the precompiled executable from https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases without success 

Anyway thank you for supporting Highs, I'm looking forward for the next release :)

### Steps to reproduce the issue

```python
import pyomo.environ as pe

opt_solver = pe.SolverFactory("highs")
opt_solver.solve(model)
```

### Error Message

```console
ERROR:   Error parsing options: Option 'A' does not exist
ERROR: Solver (asl) returned non-zero return code (4294967295)
ERROR: See the solver log above for diagnostic information.
```

### Information on your system

Pyomo version: 6.4.3.dev0
Python version: 3.9
Operating system: Windows 10
How Pyomo was installed (PyPI, conda, source): Source
Solver (if applicable): Highs

**Comment by michaelbynum** [comment]
try `pip install highspy` (https://pypi.org/project/highspy/).

**Comment by alejandro-yousef** [comment]
```console
ERROR: Could not find a version that satisfies the requirement highspy (from versions: none)
ERROR: No matching distribution found for highspy
````

There is still no wheel for Windows

**Comment by l-kotzur** [comment]
The windows wheel was added two days ago: https://github.com/ERGO-Code/HiGHS/issues/925

**Comment by alejandro-yousef** [comment]
For those who want to try, pass `appsi_highs` instead of `highs` to the SolverFactory

```python
opt = pyo.SolverFactory('appsi_highs')
```
