### ISSUE TITLE
Broken link on pyomo website

### ISSUE THREAD

**Issue by ckaldemeyer** [Pyomo/pyomo#2609]
Hi there,

our project "Open Energy Modelling Framework (oemof)" is linked on your website but the URL has changed:  http://www.pyomo.org/impact

Could you change the URL to www.oemof.org?

Best wishes and thanks for creating pyomo,
Cord

**Comment by blnicho** [comment]
@ckaldemeyer thanks for letting us know. The link has been updated.

**Comment by ckaldemeyer** [comment]
Thanks
