### ISSUE TITLE
Define Pyomo coding standards

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#267]
Desired/Required  (Decide on these)
New vs Edit

Summary of Coding Standards
- PEP8 compliant
- Core projects have higher LOF:  pyomo.core, pyomo.opt, pyomo.repn, pyomo.common
- Sphinx compliant documentation
  * Module (Required if new of heavily modified)
  * Public Classes (Required if new or heavily modified)
  * Private Classes (Required for "core", otherwise desired)
  * Public functions (Required if new or heavily modified)
  * Private functions (Required for "core", otherwise desired)

**Comment by qtothec** [comment]
What's in pyomo.common?

**Comment by carldlaird** [comment]
This is (will be) *new* and is intended to be a "better named" "dev_util" directory that you and I discussed in Pittsburgh.
