### ISSUE TITLE
Timeout on very short Optimization runs

### ISSUE THREAD

**Issue by BenediktCosmo** [Pyomo/pyomo#2671]
Very short optimizations result in a timeout error in Pyomo. Actually, the optimization problem is sufficiently solved and usable. However, the Callback from CPLEX to pyomo takes too long, so pyomo throws an timeout error. The problem lies in this line of code in shellcmd.py. 
![image](https://user-images.githubusercontent.com/80811406/208399286-b736e7da-ab2d-41dd-a7ed-aa6c3ae7b36d.png)

Here the max(1, 0.01 * self._timelimit) is taken, so the timeout for a 2 minute optimization is 1.19 seconds. This is sometimes not enough for the callback. So you could adjust this line to max(120, 0.01 * self._timelimit) and the problem would be solved... :) Thanks in advance

**Comment by jsiirola** [comment]
Please adhere to the bug report template when filing new issues, including the "Steps to reproduce the issue", "Error Message", and "Information about your system" sections.  In particular, please provide a minimal example that reproduces the observed problem (even if it is intermittent) and all information about your platform (OS, Python version, Pyomo version, installation method, solver version and installation method, etc)

**Comment by BenediktCosmo** [comment]
Steps to reproduce the issue:

- the error is not occuring every time. 
- Start optimizations in parallel (4 parallel optimization runs are sufficient) by using CPLEX as solver. In my case it is a partitioning problem as MIP Model. I start the same problem with different input data and run the optimizations in parallel.
- Set the max optimization time given to CPLEX to less than 100 seconds.
- call the solve method from pyomos SolverFactory with "solve(my_instance, timelimit=90, logfile='my_logfile')

Error message:
![Screenshot 2023-01-09 130759](https://user-images.githubusercontent.com/80811406/211306642-53f733de-a05e-4f92-8980-7156cbfc4c81.png)

System information:
- 8 vCPUs with 2.8GHz
- 32 GiB RAM
- Windows Server 2019
- Python 3.10
- CPLEX 22.10
- Pyomo 6.4.2
