### ISSUE TITLE
Add OSQP interface

### ISSUE THREAD

**Issue by amir-hoseyn77** [Pyomo/pyomo#2681]
## Summary

Please add some interface for OSQP solver. The OSQP is a good and growing solver for quadratic programming (QP) problems.

### Rationale

The OSQP is a good and growing solver for quadratic programming (QP) problems.<br/>
Also, I think it is not hard to add this interface to pyomo.

**Comment by jonas912** [comment]
Seems like this is a duplicate of #1096

**Comment by blnicho** [comment]
Closing this as a duplicate
