### ISSUE TITLE
reading solution file GLPK with interior option

### ISSUE THREAD

**Issue by pwr-srg** [Pyomo/pyomo#275]
missing function definition for reading solver output file when calling GLPK (glpsol) with the interior point option.
the function in question is "_process_soln_ipt" line: 356 of GLPK.py

`
self._process_soln_ipt(row, reader, results, obj_name, variable_names, constraint_names)
`

**Comment by blnicho** [comment]
@pwr-srg it is not clear what you meant by this issue and you didn't ask a question so I'm going to close this. If you are still having trouble please open a new issue with more information and be sure to include a minimal example pyomo model that reproduces the problem you're seeing.
