### ISSUE TITLE
HiGHS solver fails as LegacySolver is not available

### ISSUE THREAD

**Issue by SolverMax** [Pyomo/pyomo#2774]
## Summary
Calling the solver appsi_highs produces the error message:
ApplicationError: Solver <class 'pyomo.contrib.appsi.base.SolverFactoryClass.register.<locals>.decorator.<locals>.LegacySolver'> is not available (NotFound).

### Steps to reproduce the issue
Sample model at:
https://github.com/SolverMax/Random/tree/main/HiGHS-testing/Case-001

The sample model runs correctly when called using the cbc solver (specified in the data file), but fails when using appsi_highs. A few weeks ago it ran correctly with appsi_highs, but Pyomo and HiGHS versions have been upgraded since then.

### Information on your system
Pyomo version: Pyomo 6.5.0 (CPython 3.9.7 on Windows 10)
Python version: 3.9.7
How Pyomo was installed (PyPI, conda, source): PyPI
Solver (if applicable): HiGHs v1.5.1

**Comment by michaelbynum** [comment]
How did you install HiGHS? Did you install the python bindings as well? It does not look like highspy 1.5.1 is on PyPI yet, so we are not testing against it yet. I did install the latest version of HiGHS locally, and everything seems to be working.

**Comment by SolverMax** [comment]
HiGHS was originally installed using:
   pip install highspy
It was recently upgraded using:
   pip install highspy --upgrade
Testing the solvers using:
   pyomo help --solvers
used to indicate appsi_highs was available by marking it with a + but it no longer does.

**Comment by michaelbynum** [comment]
Can you try:

```
>>> import highspy
```

in a python console?

**Comment by SolverMax** [comment]
I get this:
>>> import highspy
>>> highspy
<module 'highspy' from 'D:\\OneDrive\\Python\\blog\\lib\\site-packages\\highspy\\__init__.py'>

**Comment by michaelbynum** [comment]
If you look in the highspy directory in your python site-packages, do you see any dll files?

**Comment by SolverMax** [comment]
No DLLs

**Comment by michaelbynum** [comment]
Sounds like the DLL is not getting copied from the wheel into your site-packages. I'll create an issue on the HiGHS repo. In the meantime, you can probably manually download the correct wheel from here (https://pypi.org/project/highspy/#files), unzip the wheel, and put the DLL in your site packages.

**Comment by michaelbynum** [comment]
I think you need the ".pyd" rather than the DLL. I'm not sure though.

**Comment by michaelbynum** [comment]
Strange...

**Comment by michaelbynum** [comment]
It looks like there is also a highs-*.dll in the wheel under highspy.libs. Do you see anything like that?

**Comment by SolverMax** [comment]
Yes, that's there too, along with .load-order-highspy-1.5.0.dev0

**Comment by michaelbynum** [comment]
Then I am stumped.

**Comment by SolverMax** [comment]
When I downgrade to 1.4.0dev my test model solves OK, but not with 1.5.0dev. I'll continuing using 1.4.0dev in the meantime.

**Comment by ZedongPeng** [comment]
Any updates on this? @michaelbynum

**Comment by jsiirola** [comment]
Given that this has been quiet for a year and a half (this sounds like an issue with the 1.5.0dev release and HiGHS is now up to 1.8.1; plus #3449 fixes some issues in the Pyomo HiGHS interface), I am going to close this.  

@SolverMax, if you are still seeing problems with the HiGHS distribution, please open a new issue.  Thanks!
