### ISSUE TITLE
Add Sphinx documentation for preprocessing transformations

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#279]
- [x] contrib.deactivate_trivial_constraints
- [x] contrib.detect_fixed_vars
- [x] contrib.init_vars_midpoint
- [x] contrib.init_vars_zero
- [x] contrib.remove_zero_terms
- [x] contrib.propagate_fixed_vars
- [x] contrib.propagate_eq_var_bounds
- [x] core.propagate_zero_sum
- [x] core.core.constraints_to_var_bounds

Files found under core.plugins.transform and contrib.preprocessing.plugins

**Comment by blnicho** [comment]
Completed in #653
