### ISSUE TITLE
The issue to feed CPLEX option file from Pyomo

### ISSUE THREAD

**Issue by abb-omidi** [Pyomo/pyomo#2801]
Dear support team,

I am working on the scheduling problem which is written in Pyomo and I am willing to use NEOS-CPLEX to solve the problem. I follow the notation guide to connecting Pyomo and Neos. It works well as long as I do not want to feed any CPLEX internal options. The problem is when I want to set CPLEX internal options like warm-start, log file, mip-gap, emphasis, cuts, etc. At the moment I am currently using something like **{ results = solver_manager.solve(m, solver = "cplex", tee= True, keepfiles=True,
logfile = "log.txt", options_string="mipgap=0.1") },** but only the first and the last one work.

I was wondering if, is there any robust way to feed an option file in Neos? If so, how can I do that?
Best regards
Abbas

**Comment by mrmundt** [comment]
Hello, @abb-omidi. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
