### ISSUE TITLE
Sympy expressions leaking out of differentiation code

### ISSUE THREAD

**Issue by andrewlee94** [Pyomo/pyomo#2803]
## Summary

When using the `solve_strongly_connected_components` solver, I ran into an error message about converting expressions to floats. From looking at the stack trace, the issue appears to be coming from the Pyomo differentiation tools which are being called via `calculate_variable_from_constraint`. It appears that the value returned from the differentiation code is a `sympy.core.mul.Mul`, which is causing an exception to be raised when Pyomo attempts to evaluate this derivative (there is a corresponding warning logged about dynamically registering a new numeric type).

### Steps to reproduce the issue

I do not have a simple case to replicate the issue, however the code I am running can be found here:

https://github.com/andrewlee94/idaes-pse/blob/initializers_4/idaes/models/unit_models/tests/test_pressure_changer.py

The specific failing test is at line 1023, `test_block_triangularization`

### Error Message

idaes/core/initialization/initializer_base.py:192: in initialize
    results = self.initialization_routine(model)
idaes/core/initialization/block_triangularization.py:115: in initialization_routine
    self._solve_block_data(model, solver)
idaes/core/initialization/block_triangularization.py:122: in _solve_block_data
    solve_strongly_connected_components(
../../pyomo/pyomo/pyomo/contrib/incidence_analysis/scc_solver.py:153: in solve_strongly_connected_components
    results = calculate_variable_from_constraint(
../../pyomo/pyomo/pyomo/util/calc_var_value.py:179: in calculate_variable_from_constraint
    expr_deriv = differentiate(expr, wrt=variable, mode=diff_mode)
../../pyomo/pyomo/pyomo/core/expr/calculus/derivatives.py:116: in differentiate
    res = sympy_diff(expr=expr, wrt=wrt, wrt_list=wrt_list)
../../pyomo/pyomo/pyomo/core/expr/calculus/diff_with_sympy.py:47: in differentiate
    objectMap, sympy_expr = sympyify_expression(expr)
../../pyomo/pyomo/pyomo/core/expr/sympy_tools.py:215: in sympyify_expression
    return object_map, visitor.walk_expression(expr)
../../pyomo/pyomo/pyomo/core/expr/visitor.py:256: in walk_expression
    result = self._process_node(root, RECURSION_LIMIT)
../../pyomo/pyomo/pyomo/core/expr/visitor.py:455: in _process_node_bx
    data.append(self._process_node(child, recursion_limit))
../../pyomo/pyomo/pyomo/core/expr/visitor.py:455: in _process_node_bx
    data.append(self._process_node(child, recursion_limit))
../../pyomo/pyomo/pyomo/core/expr/visitor.py:455: in _process_node_bx
    data.append(self._process_node(child, recursion_limit))
../../pyomo/pyomo/pyomo/core/expr/visitor.py:466: in _process_node_bx
    return self.exitNode(node, data)
../../pyomo/pyomo/pyomo/core/expr/sympy_tools.py:152: in exitNode
    return node._apply_operation(values)
../../pyomo/pyomo/pyomo/core/expr/numeric_expr.py:311: in _apply_operation
    return self._fcn.evaluate( result )
../../pyomo/pyomo/pyomo/core/base/external.py:216: in evaluate
    return self._evaluate(args_, None, 0)[0]
../../pyomo/pyomo/pyomo/core/base/external.py:360: in _evaluate
    arglist = _ARGLIST(args, fgh, fixed)
../../pyomo/pyomo/pyomo/core/base/external.py:654: in __init__
    self.ra = (c_double*nr)(*_reals)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = 0.055508472036053*x0

    def __float__(self):
        # Don't bother testing if it's a number; if it's not this is going
        # to fail, and if it is we still need to check that it evalf'ed to
        # a number.
        result = self.evalf()
        if result.is_Number:
            return float(result)
        if result.is_number and result.as_real_imag()[1]:
            raise TypeError("Cannot convert complex to float")
>       raise TypeError("Cannot convert expression to float")
E       TypeError: Cannot convert expression to float

../../anaconda3/lib/python3.9/site-packages/sympy/core/expr.py:345: TypeError

**Comment by michaelbynum** [comment]
It looks like this is caused by trying to do symbolic differentiation with external functions. I think you need to switch to numeric differentiation.

**Comment by michaelbynum** [comment]
I think you can do something like:

```
from pyomo.core.expr.calculus.derivatives import differentiate
solve_stringly_connected_components(
    block, 
    solver, 
    solve_kwds, 
    calc_var_kwds={'diff_mode': differentiate.Modes.reverse_numeric},
)
```

**Comment by andrewlee94** [comment]
Thanks @michaelbynum, that fixed the issue. We might want to think about a way to provide a more useful error message to users in this case, as it was not immediately apparent where the `Mul` was coming from and how to fix it.

**Comment by michaelbynum** [comment]
Good point. I will try to update the sympy walker.

**Comment by andrewlee94** [comment]
Another thought I had (which may not be worth the effort/cost) is to have the `differentiate` function try `sympy` first and then fall back to `reverse_numeric` if that fails.

For IDAES at least, the `ExternalFunctions` generally make up a small part of the model so it would be nice to use `sympy` wherever possible and only use `reverse_numeric` when we encounter an `ExternalFunction`, however the current API is all-or-nothing.
