### ISSUE TITLE
Bug in Ampl file generation

### ISSUE THREAD

**Issue by vova292** [Pyomo/pyomo#2810]
I have a model which can be successfully solved by pyomo 6.4.2

When i upgrade to 6.5.0, it generates the following ampl file ([tmpptnjgdzypynumero.nl.txt](https://github.com/Pyomo/pyomo/files/11250039/tmpptnjgdzypynumero.nl.txt) ) which has problems starting from line 1021

The constraint in question looks something like this: 
```
Member of gain_cons} : Size=72, Index=splitter.gain_cons_index, Active=True
    Key : Lower : Body : Upper : Active
      4 :   0.0      : 100.00000000000001*(- splitter.split_fraction_1_ctx_var_oper[12]) + 0.49999999999999983*(- splitter.inlet_mass_flow_ctx_var_oper[12]) + 100.00000000000001*splitter.split_fraction_1_ctx_var[12] + 0.49999999999999983*splitter.inlet_mass_flow_ctx_var[12] - (splitter.outlet_1_mass_flow_ctx_var[12] - splitter.outlet_1_mass_flow_ctx_var_oper[12]) :   0.0 :   True
```
On line 682 of nl_writer.py the `expr.const` ends up being type `NPV_SumExpression`, which may be the problem

**Comment by jsiirola** [comment]
Thank you for reporting your issue.  Unfortunately, without an example that we can use to reproduce the problem, there is little we can do to diagnose what is happening.

Have you confirmed that you see the same behavior with the current development branch?

In the future, please leverage the prepopulated bug template and provide the requested information.  This includes information about your environment, the full error message, and steps to reproduce the observed bug.

**Comment by vova292** [comment]
I am not using the kernel

**Comment by vova292** [comment]
I tested my example against the branch in the PR and it solves the issue for me. Great work!
