### ISSUE TITLE
Allow file objects as a valid DataPortal

### ISSUE THREAD

**Issue by fleimgruber** [Pyomo/pyomo#283]
This is to discuss the feature proposed [here](https://groups.google.com/forum/#!topic/pyomo-forum/5jscHaCwJSs) so that
``` python
input_dat = io.StringIO("""
param n := 672 ;
param days_horizon := 7 ;
param delta_t := 0.25 ;
""")
instance = model.create_instance(input_dat)
```

does not result in
```
ValueError: Cannot load model model data from with object of type '<class '_io.StringIO'>'
```

Initially, I was looking for the place where the [file object](https://docs.python.org/3/glossary.html#term-file-object) API would be used.  Then I found the DataPortal machinery and figured that implementing a file object DataPortal would be the way to go.  See also #284.  WDYT?

**Comment by mrmundt** [comment]
We are archiving old issues that are interesting design ideas but unlikely to be implemented by the core Pyomo team to the [Archived Design Discussion wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
