### ISSUE TITLE
how to load a SolverResults object with bad status

### ISSUE THREAD

**Issue by akramawad2022** [Pyomo/pyomo#2851]
Hi everyone,
I am using Pyomo with IPOPT solver to solve an optimization problem, I would like to load the results even though with bad status. 
Is there a way to do that??

**Comment by mrmundt** [comment]
Hello, @akramawad2022 . The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
