### ISSUE TITLE
Mosek not supporting expressions of degree None

### ISSUE THREAD

**Issue by matteodefra** [Pyomo/pyomo#2859]
## Summary

Hello, I am trying to build a model minimizing the distance between two matrices in Pyomo using the Mosek solver.
Mosek is throwing the following exception:

`ERROR: MOSEK does not support expressions of degree None. expr: -
    5420158.53/(x[0] - x[1])**2 - (y[0] - y[1])**2`

where the expression above is one of the entry in the objective function.
The error comes from here: 

`raise DegreeError(
pyomo.solvers.plugins.solvers.mosek_direct.DegreeError: MOSEK does not support expressions of degree None.`

I am using the Mosek pip installed version, as well as pyomo in a conda environment

**Comment by jsiirola** [comment]
This is expected: your expression is nonpolynomial due to the `- 5420158.53/(x[0] - x[1])**2` term.  You will need to rework your expressions to avoid variables in the denominator of expressions.

**Comment by matteodefra** [comment]
Thank you very much for your help
