### ISSUE TITLE
CPLEX direct reduced costs error when solving MIP

### ISSUE THREAD

**Issue by JasperNL** [Pyomo/pyomo#286]
https://github.com/Pyomo/pyomo/blob/f26320ac61e6cbd4dbc6bd8cb80784ea3e38ca78/pyomo/solvers/plugins/solvers/cplex_direct.py#L585

Throws error when solving MIP. Should be moved one line down, in the body of the if-statement.

**Comment by michaelbynum** [comment]
This is already fixed in a branch called “persistent_solvers”. The pull request just has not been merged yet.

Michael
