### ISSUE TITLE
Error in pyomo/repn/linear.py

### ISSUE THREAD

**Issue by strahl21** [Pyomo/pyomo#2861]
In the function `_handle_pow_ANY_constant` (line 335), while the condition checks if the value of exp is an integer, the actual exp object remains a float. Thus, line 342 throws an error when the range function tries to interpret exp as an integer:
`TypeError: 'float' object cannot be interpreted as an integer`

changing line 342 to `for i in range(1, int(exp)):`  prevents the error and is correct because of the check in the condition.

**Comment by mrmundt** [comment]
Hello, @strahl21 . Please use the "Bug report" template for bug reports.

**Comment by mrmundt** [comment]
Please resubmit. We can't begin to try to reproduce your error without the details requested in the template.

**Comment by mrmundt** [comment]
Also, as an aside, using the template helps us with traceability of when an error was reported, what version, etc., and especially because you have a PR open for this, then we can link directly to it. It helps us and future users.
