### ISSUE TITLE
Support more milp solver in mindtpy

### ISSUE THREAD

**Issue by rlacjfjin** [Pyomo/pyomo#2874]
When using mindtpy to solve MINLP, is it possible to support scip or highs solver in milp solver?

Now, there is error with:
Error: value scip not in domain ['gurobi', 'cplex', 'cbc', 'glpk', 'gams', 'gurobi_persistent', 'cplex_persistent', 'appsi_cplex', 'appsi_gurobi']

Thanks.

**Comment by bernalde** [comment]
This should be easy to do. @ZedongPeng can we work on this?
A related question: should we change the default MILP solver for our tests to highs? @michaelbynum @jsiirola ?

**Comment by ZedongPeng** [comment]
I already have a **MindtPy** version with the support of `highs` and `appsi_highs`. I will submit a PR as soon as possible.
