### ISSUE TITLE
ValueError: Cannot load a SolverResults object with bad status: error

### ISSUE THREAD

**Issue by Loukas95** [Pyomo/pyomo#2878]
I am currently using Pyomo (version: 6.4.2) with IPOPT as a solver for a nonlinear constrained optimization problem. This problem has a dimension of 408. When I run the optimization, I sometimes get the following error:

**Restoration phase converged to a point with small primal infeasibility

EXIT: Restoration Failed!

ValueError: Cannot load a SolverResults object with bad status: error**

This error does not appear every time I optimize this particular problem. I sometimes get this error and sometimes not.

I read on internet that this indicates that the restoration phase failed to find a feasible point that was acceptable to the filter line search for the original problem. This could happen if the problem is highly degenerate, does not satisfy the constraint qualification, or if the NLP code provides incorrect derivative information. Consequently, Pyomo stops the optimization and exits.

In addition, I realised that I don't get this error if I optimize problems of lower dimension.

Do you have any idea how I can solve this problem of Pyomo?

Thank you in advance!

**Comment by mrmundt** [comment]
Hello, @Loukas95 . The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.

If you believe this is a bug, please file another issue using the appropriate template.
