### ISSUE TITLE
Improve Block inheritance

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#289]
It would be useful if it was easier to create new classes that inherit Block. The main use I have in mind for this is to create reusable sub-models. Basically a Block that can be added to a model that comes pre-populated with variables and constraints. The reason this is complicated, is the IndexedBlock/SimpleBlock stuff.

This is not necessarily the best, but one possible method for this is here: https://github.com/IDAES/models/blob/master/idaes_models/core/process_base.py

An example of how it's used is here: https://github.com/IDAES/model_contrib/blob/master/idaes_model_contrib/mea_simple/flowsheet/units/hx_simple.py

The _HeatExchangeSimple class ultimately inherits from _BlockData, while the decorator creates the class that inherits from Block.  This works for indexed and simple blocks.

**Comment by qtothec** [comment]
This is related to issue #287 and may be generalized to Block-like objects (e.g. Disjuncts).
