### ISSUE TITLE
Compiling syntax error with pytest and python >3.11.2

### ISSUE THREAD

**Issue by aking-utilidata** [Pyomo/pyomo#2891]
## Summary

There is a syntax error when using pyomo (6.6.1) with python version 3.11.3 or higher and pytest 7.4.0. It occurs when first installing and never having run pyomo through the command line or in a python script, i.e. calling pytest first.  It is on line 258 of pyomo/contrib/mindtpy/util.py https://github.com/Pyomo/pyomo/blob/6.6.1/pyomo/contrib/mindtpy/util.py#L258. There may be others throughout the code, but this was the first one.  

### Steps to reproduce the issue

Install pytest and pyomo and from the command line 

`pytest test.py`

where test.py includes
```
# test.py
import pyomo.envrion as pe

def test():
    assert True

if __name__ == "__main__":
    test()

```

If I then run `python test.py` and then `pytest test.py`, the error disappears. 

### Error Message
[error_message.txt](https://github.com/Pyomo/pyomo/files/11907932/error_message.txt)

```__________________________________________ ERROR collecting tests/pyomo_test.py ___________________________________________
../Library/Caches/pypoetry/virtualenvs/der-dispatch-SkOWZWSe-py3.11/lib/python3.11/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
../Library/Caches/pypoetry/virtualenvs/der-dispatch-SkOWZWSe-py3.11/lib/python3.11/site-packages/_pytest/pathlib.py:565: in import_path
    importlib.import_module(module_name)
../.pyenv/versions/3.11.3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1206: in _gcd_import
    ???
<frozen importlib._bootstrap>:1178: in _find_and_load
    ???
<frozen importlib._bootstrap>:1149: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
../Library/Caches/pypoetry/virtualenvs/der-dispatch-SkOWZWSe-py3.11/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
der-dispatch/tests/pyomo_test.py:1: in <module>
    import pyomo.environ as pe
../Library/Caches/pypoetry/virtualenvs/der-dispatch-SkOWZWSe-py3.11/lib/python3.11/site-packages/pyomo/environ/__init__.py:84: in <module>
    _import_packages()
../Library/Caches/pypoetry/virtualenvs/der-dispatch-SkOWZWSe-py3.11/lib/python3.11/site-packages/pyomo/environ/__init__.py:81: in _import_packages
    pkg.load()
../Library/Caches/pypoetry/virtualenvs/der-dispatch-SkOWZWSe-py3.11/lib/python3.11/site-packages/pyomo/contrib/mindtpy/plugins.py:15: in load
    import pyomo.contrib.mindtpy.outer_approximation
../Library/Caches/pypoetry/virtualenvs/der-dispatch-SkOWZWSe-py3.11/lib/python3.11/site-packages/pyomo/contrib/mindtpy/outer_approximation.py:14: in <module>
    from pyomo.contrib.mindtpy.util import calc_jacobians
E     File "/Users/ashleyking/Library/Caches/pypoetry/virtualenvs/der-dispatch-SkOWZWSe-py3.11/lib/python3.11/site-packages/pyomo/contrib/mindtpy/util.py", line 256
E       """This function generates objective (PF-OA main problem) for minimum Norm Infinity distance to setpoint_model.
E       ^^^
E   SyntaxError: invalid escape sequence '\m'
```

### Information on your system

Pyomo version: 6.6.1
Python version: 3.11.3
Operating system: Mac Ventura: 13.3.1
How Pyomo was installed (PyPI, conda, source): poetry 
Solver (if applicable): cbc - not applicable

**Comment by blnicho** [comment]
Looks like the error is pointing to this docstring:
https://github.com/Pyomo/pyomo/blob/67e900c0fe05089c65d1e3bcb3bdc720661622a8/pyomo/contrib/mindtpy/util.py#L255-L260

I'm not sure how/why a syntax error would ever be thrown because of something in a docstring.

**Comment by jsiirola** [comment]
This is a bug, and something we see regularly (it's due to the LaTeX in the docstring... `\m` is not a valid escape sequence.  That currently triggers a warning, but something in the way that @aking-utilidata is runnging things has python running with `-Werror` (mapping warnings to errors).

The patch for this specific issue is trivial.  I am working on something a little more substantial (a set of tests that import every module in Pyomo with `-Werror:pyomo` to catch problems like this).  There are about ~20 files that need to be patched or re-thought.
