### ISSUE TITLE
How does pyomo represent the complex number Z=R+JX

### ISSUE THREAD

**Issue by cclcong** [Pyomo/pyomo#2907]
How does pyomo represent the complex number Z=R+JX

**Comment by mrmundt** [comment]
Hello, @cclcong . The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
