### ISSUE TITLE
Save/Load a model state to/from json

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#292]
It would be nice to save a complete model state in json format.  Everything about the model could be saved except the model itself. Options could be provided for how to load the model.  For example, you could load only unfixed variable values, and not necessarily load or save everything.

Here is an implementation that works, although it could probably be done better. https://github.com/IDAES/idaes/blob/master/idaes/core/util/model_serializer.py

**Comment by qtothec** [comment]
This would be fantastic as a PR. Note that when you say "everything about the model", you are probably excluding the functions (e.g. rules used to generate the constraints). I would want some feedback from the core devs about where in the codebase this kind of functionality belongs, since it is relevant to #187 as well.

**Comment by whart222** [comment]
I'm not sure why this capability is desirable.  How is this conceptually different from the pickle and dill capabilities in Python?

I'm quite loathe to embrace the development of a new serialization standard for Python when several good solutions already exist?

If you think that Pyomo models are a special case, then note that a user can treat a Pyomo model as a generic object and put *anything* in it.  Arguably all of that Python stuff would need to be serialized in a general manner.

**Comment by carldlaird** [comment]
This is not for serialization of the entire model, but rather just the "state" of the model. This is fundamentally different from what pickle and dill do. This could mean different things, but at a minimum, we would want to be able to store the current values of the variables to be loaded again later. Bill, I think there are many good uses for this functionality. 

For example, we may want to store a common starting point for a number of solves with slightly different parameters. In fact, it may not even be the same model instance. We may have a solution from one model that we want to store and load into a different model (with shared variable names).

I would very much like to see this functionality, especially if it is made flexible to load subsets of the variable values based on different criteria. Might also want to allow storing and retrieving of bounds - useful in many algorithms.




 I see a big benefit in having this general capability. There could be options to store variable values, bounds, and/or multipliers. There are many algorithms that could make use of this functiona

**Comment by whart222** [comment]
@carldlaird Your example seems reasonable, but it is much more constrained than the "save/load model state" statement of this issue.  I suggest that this discuss needs to articulate specific save/load capabilities that are needed.

**Comment by eslickj** [comment]
I was probably not very clear about what I meant by model state.  I mean the model is still generated by Python code, and this stores the model attributes you ask it to.  You can also conditionally save or load certain attributes as @carldlaird mentioned.  It's not really a replacement for Pickle, but it has a lot of general purpose use. If it seems useful, it may be a nice addition to Pyomo. My motivation is mostly that if it were a core feature of Pyomo it would probably be more reliable than what I have now.  If it doesn't seem like a useful core feature for Pyomo, please go ahead and close this issue.
