### ISSUE TITLE
Pyomo UI

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#293]
I have started a graphical user interface for IDAES, but it's works with general Pyomo models.  It's aimed at block structured models.  So far it's pretty simple, and runs out of a jupyter notebook to allow the user to do pretty much anything. Everything works directly on the Pyomo model, so there is no real problem keeping the notebook, UI, and model in sync. If this UI could be part of Pyomo, it's a good time to start discussing it.

Here is the UI code (as of now the flowsheet display, is in a pending pull request, so it should show up soon) https://github.com/IDAES/models/tree/master/idaes_models/ui. An example notebook is here: https://github.com/IDAES/models/blob/master/idaes_models/examples/ui_example.ipynb.

Screen-shot below give a feel for what the UI looks like. The idea is that UI will insert code for anything you do with model into the Jupyter notebook, so it is documented, easily reproducible, and can be edited later. 

![screenshot from 2017-12-22 09-10-09](https://user-images.githubusercontent.com/16341333/34301287-fb8b7458-e6f9-11e7-83be-d4223f5a9284.png)

**Comment by qtothec** [comment]
The way that connectivity works might warrant some explanation.

**Comment by eslickj** [comment]
@qtothec yeah, I know the private repo makes this a little tricky, but I'm hoping most of the Pyomo developers have access.

As for the connectivity, I have a few IDAES.  

What I really wanted to do was use an incidence matrix as suggested in https://github.com/Pyomo/pyomo/issues/291. That's pretty slow, since I'm not creating any new representation of the model, and trying to stick with only the Pyomo model as the data structure. The good thing about that is that the connections between the blocks will for sure show the real mathematical structure of the problem.

What I actually did is to assume we are only looking at one level of the model hierarchy under a given block (I'll call that the parent for now, and blocks under that children). I look for constraints with connectors in the parent block.  Then use those to draw the connections.  I also catch the case where sub-blocks of children are connected.

I think the information we are trying to convey with the connections is open for discussion, and there are probably several different options for how things could be displayed.

**Comment by whart222** [comment]
This looks like a good topic to discuss in a break in the January meeting.  Note that @carldlaird took a stab at developing a Pyomo GUI a while back, and it didn't gain any traction with either developers or users.  Hence, it was ultimately abandoned.

I think we should be very clear about the goals/objectives/complexity of doing this again.  Clearly, Jupyter makes things easier, but we should talk through the expected use cases and types of users would leverage this capability.

**Comment by qtothec** [comment]
@eslickj are these closures because they're out of scope for you, or is there something else going on?

**Comment by eslickj** [comment]
It's mostly that before the January meeting, I was thinking we should move some general IDAES stuff to Pyomo.  After the meeting it seems like the idea is probably to keep more in IDAES. So I figured I may as well close some of these Pyomo issues.
