### ISSUE TITLE
Is there a easy way to provide gradient information for external function when use trustregion solver

### ISSUE THREAD

**Issue by TheHuangs** [Pyomo/pyomo#2936]
When we use trustregion solver with ExternalFunction, it's sometimes not easy to provide gradient information, is there a build-in method to use directly?

m.EF = ExternalFunction(ext_fcn, grad_ext_fcn)

**Comment by blnicho** [comment]
Hello, @TheHuangs. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.

If you believe this is a bug, please file another issue using the appropriate template.
