### ISSUE TITLE
gurobi solver option "BestObjStop" causes ValueError

### ISSUE THREAD

**Issue by kfoerderer** [Pyomo/pyomo#294]
When using the **BestObjStop** option offered by gurobi (see [http://www.gurobi.com/documentation/7.5/refman/bestobjstop.html#parameter:BestObjStop](http://www.gurobi.com/documentation/7.5/refman/bestobjstop.html#parameter:BestObjStop)) pyomo fails to recognize the solution.

**Solver output:**
> [...]
> Explored 1 nodes (6931 simplex iterations) in 0.43 seconds
> Thread count was 4 (of 4 available processors)
> 
> Solution count 5: 72.8522 118.624 565.215 ... 881.385
> 
> **Optimization achieved user objective limit**
> Best objective 7.285215950465e+01, best bound 0.000000000000e+00, gap 100.0000%
> 15

**Error:**
> [...]\pyomo\core\base\PyomoModel.py in load_from(self, results, allow_consistent_values_for_fixed_vars, comparison_tolerance_for_fixed_vars, ignore_invalid_labels, id, delete_symbol_map, clear, default_variable_value, select, ignore_fixed_vars)
>     239             else:
>     240                raise ValueError("Cannot load a SolverResults object "
> --> 241                                 "with bad status: %s" % str(results.solver.status))
>     242         if clear:
>     243             #
> 
> **ValueError: Cannot load a SolverResults object with bad status: error**

**Comment by qtothec** [comment]
This may require some logic to be added to https://github.com/Pyomo/pyomo/blob/master/pyomo/solvers/plugins/solvers/GUROBI_RUN.py

**Comment by blnicho** [comment]
@kfoerderer how are you calling the solver, using the `pyomo` command or using a script? If using a script could you give us the exact lines you're using?

**Comment by kfoerderer** [comment]
Thank you for your answer. I'm using a script. Here is the code calling the optimizer:

 ```
    opt = SolverFactory("gurobi")
    opt.options['timelimit'] = 30
    opt.options['mipgap'] = 0.05
    opt.options['bestobjstop'] = 100

    return opt.solve(instance, tee=True)
```
Without setting 'bestobjstop' (a gurobi specific option) it works fine. When the solver stops due to reaching 'bestobjstop' pyomo fails to recognize the solution.

**Comment by blnicho** [comment]
This looks like a bug and it might be related to the discussion in #365. You could try using the workaround mentioned by Gabe in that issue, i.e. manually check the solver status that gets returned when you set the 'bestobjstop' option.

**Comment by ghackebeil** [comment]
I’ll have a fix pushed to GitHub as a PR in a few moments.

Gabe
