### ISSUE TITLE
Add Maximize() and Minimize() instead of Objective(sense=...)

### ISSUE THREAD

**Issue by MLopez-Ibanez** [Pyomo/pyomo#2945]
## Summary

Instead of writing:
```python
@model.Objective(sense=pye.maximize)
def objective(m):
     return ...
```

suggest to write:
```python
@model.Maximize()
def objective(m):
     return ...
```

Similarly for `Minimize()`.

### Rationale

 * Less typing, fewer things to remember.
 * Clear intention (no need to remember whether maximize or minimize is the default sense).

### Alternatives

I could create my own wrapper:

```python
def Maximize(*args, **kwargs):
   return Objective(*args, **kwargs, sense=pye.maximise)
```

However, this would not handle the nice decorator syntax. It would also only benefit myself, while the target audience of this change is new users.

### Additional information

I'm happy to submit a PR. This should be a very simple wrapper around `Objective' and a trivial documentation update. The traditional way using `Objective` will keep working and does not need to be deprecated.

**Comment by mrmundt** [comment]
Hello, @MLopez-Ibanez . We appreciate your suggestion! We will discuss this request and add it to our backlog for future efforts.

_NOTE_: There is no guarantee that we will implement all suggestions. We do, however, accept external contributions. If you are interested in expediting this request, we encourage you to review our [Contribution Guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and submit your requested changes.

**Comment by MLopez-Ibanez** [comment]
> _NOTE_: There is no guarantee that we will implement all suggestions. We do, however, accept external contributions. If you are interested in expediting this request, we encourage you to review our [Contribution Guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and submit your requested changes.

Does this mean that a PR following the guidelines would be acceptable? Or is the idea still under discussion?

**Comment by mrmundt** [comment]
You can submit a PR. We think it's a good idea but do not have the capacity to implement it currently.

**Comment by MLopez-Ibanez** [comment]
I created a draft PR because the [Contribution Guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) does not really explain how to build and test Pyomo besides using the github actions.

**Comment by mrmundt** [comment]
Second paragraph: https://pyomo.readthedocs.io/en/stable/contribution_guide.html#testing <- There is a copy that runs on branches on forks. You need only enable Actions on your fork.

**Comment by MLopez-Ibanez** [comment]
Apologies, I missed that this was the only way to do it. I was looking for which commands to run from the command-line. Got it now. Thanks!
