### ISSUE TITLE
flatten_dae_components missing activated constraints

### ISSUE THREAD

**Issue by dallan-keylogic** [Pyomo/pyomo#2977]
## Summary

`flatten_dae_components` fails to collect implicitly indexed `Constraints` when the component at the first index is deactivated but those at the remaining indices remain active. If you deactivate individual constraints at later indices, it will still collect the constraint as expected, so long as it's active at the first index.

This matters for IDAES because we want to deactivate certain constraints on a property block at the first time point, like sum-of-mole-fractions constraints, in order to fix the initial condition for a DAE.

### Steps to reproduce the issue

```console
import pyomo.environ as pyo
from pyomo.dae import ContinuousSet
from pyomo.dae.flatten import flatten_dae_components

m = pyo.ConcreteModel()
m.time = ContinuousSet(initialize=[0, 1, 2, 3, 4])

def block_rule(blk):
    blk.x = pyo.Var(initialize=0)
    blk.y = pyo.Var(initialize=0)
    @blk.Constraint()
    def equation1(b):
        return b.x + b.y == 0

m.block = pyo.Block(m.time, rule=block_rule)

m.block[0].equation1.deactivate()

regular_vars, time_vars = flatten_dae_components(m, m.time, pyo.Var, active=True)
regular_cons, time_cons = flatten_dae_components(m, m.time, pyo.Constraint, active=True)

print(len(time_cons))
```

```
0
```

### Information on your system

Pyomo version: 6.6.2

**Comment by blnicho** [comment]
This looks like an issue with how the `active` flag is handled.

**Comment by Robbybp** [comment]
I think the issue is that we only descend into one BlockData, and here it happens to be the first one, which happens to be deactivated. I think you can use the `indices` keyword arg, e.g. `indices=(1,)` to tell the function to descend into `block[1]` when looking for constraints.

**Comment by dallan-keylogic** [comment]
So we need to specify a "representative index" for the one set that isn't being flattened (almost always time)? Why is it being provided as a tuple? For the case where the "time" set is multi-dimensional?

**Comment by Robbybp** [comment]
Yep, if the model structure is not "uniform" (different components or different active statuses on different BlockData whose parent Block will be sliced), you need to provide a representative index. The default is to just use the first index. This is to prevent the amount of time taken by the procedure growing with the length of the "non-sliced set". 

`incides` is just passed straight to the underlying function, `flatten_components_along_sets`, which handles multiple sets, so it accepts `indices` as a tuple, just like it accepts a tuple of sets. `flatten_dae_components` should probably just accept `index`, then pass `(index,)` to `flatten_components_along_sets`. This is probably a design oversight, but I'm not sure it's worth changing as it is easy enough to work around.
