### ISSUE TITLE
Set should have an 'update' method

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#298]
This is a natural thing to pair with the existing `add` method (and mirrors that of the Python `set` class). E.g.,

```python
model = ConcreteModel()
model.s = Set()
model.s.update(range(5))
# should be equivalent to
# for i in range(5):
#    model.s.add(i)
```

Also, to clarify, when I say `Set` here I do _not_ mean this to include `IndexedSet`.

**Comment by whart222** [comment]
I agree that this seems natural.

What do you mean by ``IndexSet``?

**Comment by ghackebeil** [comment]
I mean that the thing created by `Set(some_other_index_set)` should not have an `update` method (as I don't even think it has an `add` method). Only the "_SetData" things that it stores should. I forget the notation we use to distinguish between a singleton Set, an indexed Set, and the singleton Sets stored in an indexed Set.

**Comment by blnicho** [comment]
This was fixed in the Set rewrite.
