### ISSUE TITLE
Install Pyomo through APT [Ubuntu 23.04]

### ISSUE THREAD

**Issue by deRemo** [Pyomo/pyomo#2985]
## Summary

Consider adding pyomo to `APT` due to the policy change in ubuntu 23.04 which requires a virtual environment in order to properly use `pip`

### Rationale
Many people use Ubuntu, and due to the changes in Ubuntu 23.04 it is not easy to install pyomo as it used to be (simply calling `pip install pyomo`)

**Comment by mrmundt** [comment]
Hello, @deRemo ! We appreciate your suggestion! We will not, however, be implementing this. We release Pyomo through `pip` and `conda`, as well as making the official release versions available as wheels and tarballs. If you cannot install through `pip`, please use one of the other methods.
