### ISSUE TITLE
Nondeterministic objective function values observed after bumping Pyomo from v6.5.0 to v6.6+

### ISSUE THREAD

**Issue by anamileva** [Pyomo/pyomo#3019]
### Summary
After bumping Pyomo from v6.5.0 to v6.6+, I am observing some of the [GridPath](https://github.com/blue-marble/gridpath) tests fail due to arriving to different objective function values that are non-deterministic. I expect small changes in the objective function values when upgrading Pyomo, but they should remain the same across test runs.

### Symptoms
* I am  observing several tests fail because they solve to a different objective function value after upgrading Pyomo from [v6.5.0](https://github.com/blue-marble/gridpath/actions/runs/6537736083) to [v6.6.0](https://github.com/blue-marble/gridpath/actions/runs/6537909013). The issue is still present in Pyomo [v6.6.2](https://github.com/blue-marble/gridpath/actions/runs/6551021427)
* The behavior observed is non-deterministic: the objective function values for the failing tests change between test runs.

### System Information
* I have observed this behavior in Python 3.9 and 3.10 on MacOS Ventura 13.4, Windows 11, and Ubuntu 22.04.3 LTS.
* The tests were solved with Cbc v2.10.7 on Linux and MacOS, and Cbc v2.10.10 on Windows.

### Investigation
* I have confirmed that this issue is observed when the only change is the Pyomo version, with everything else kept fixed.
* I attempted to simplify the GridPath examples until the issue disappeared (removing functionality and the number of members in various Sets) and then worked with the smallest examples I could find where the issue was still present.
* I was able to "fix" the problem, by sorting the initialization data for some Sets within GridPath.
* It appears the issue starts with the use of the Python `set()` function (which is unordered) in initializing those sets.
* In the GridPath formulation context, the affected Sets are order-agnostic (created with `Ordered=False`).

### Steps to Reproduce

**Pyomo v6.5.0**
* Create and activate Python 3.9 virtual environment.
* Clone and install GridPath with Pyomo v6.5.0.
```
git clone https://github.com/blue-marble/gridpath.git
cd gridpath
git checkout c135312
pip install -e .
```
* Run trials for the two small examples I have created in the _./pyomo_examples_ directory.
```
python run_trials.py example1
python run_trials.py example2
```
You should not see any changes in the objective function value from trial to trial (the script will tell you if it finds any).

**Pyomo v6.6.2**
* Create and activate Python 3.9 virtual environment.
* Clone and install GridPath with Pyomo v6.6.2.
```
git clone https://github.com/blue-marble/gridpath.git
cd gridpath
git checkout 2068ceb
pip install -e .
```
* Run trials for the two small examples I have created in the _./pyomo_examples_ directory.
```
python run_trials.py example1
python run_trials.py example2
```
You should see changes in the objective function value from trial to trial.

* To create the LP files, you can use the following:
`python gridpath/run_scenario.py --scenario_location ./pyomo_examples --testing --scenario example1 --log --keepfiles --symbolic --write_solver_files_to_logs_dir`
You will then be able to find the solver files in the _./pyomo_examples/example1/logs_ directory.

* Get ["fix" for example 1](https://github.com/blue-marble/gridpath/commit/a349a75134e6d1272cb24a14cf8efc5a5a36eeb3) and run trials.
```
git checkout a349a75
python run_trials.py example1
```
You should not see any changes in the objective function value for example1 (example2 still fails).
* Get ["fix" for example2](https://github.com/blue-marble/gridpath/commit/67634c83cd78e32b9844ad6e8db6ec6022d40077) and run trials.
```
git checkout 67634c8
python run_trials.py example2
```
You should not see any changes in the objective function value.

**Comment by jsiirola** [comment]
@anamileva, some questions::
- Am I correct that you are using `Set(ordered=False)` in your model, and then initializing those `Set()`s with unordered data?
- Are the LP files just "reordered", or are there any coefficients that are different? 
- Do you see the same behavior with other solvers (in particular, have you tried highs / gurobi / cplex / xpress)?

**Comment by anamileva** [comment]
> * Am I correct that you are using `Set(ordered=False)` in your model, and then initializing those `Set()`s with unordered data?

I erroneously believed the `ordered` argument had `False` as default; `ordered` is not specified for those sets, so they are declared with the default value, which is `True`. They are then initialized with unordered data.

> * Are the LP files just "reordered", or are there any coefficients that are different?

I have not seen any changes to coefficients, just reordering of the LP files.

> * Do you see the same behavior with other solvers (in particular, have you tried highs / gurobi / cplex / xpress)?

I just tested the following and did _not_ see the same behavior when solving with:
* CPLEX Community Edition 22.1.1.0
* HiGHS 1.5.3
* GLPK 5.0

**Comment by anamileva** [comment]
> I erroneously believed the `ordered` argument had `False` as default; `ordered` is not specified for those sets, so they are declared with the default value, which is `True`. They are then initialized with unordered data.

Following up on this: I tested redeclaring the Sets with `ordered=False` and the issue is still present with Cbc.

**Comment by jsiirola** [comment]
Ok. I believe that Pyomo is behaving mostly as expected. Pyomo should be deterministic up to the data that you provide. By default, Set is ordered by insertion order. If you declare the data using a no deterministic data source (eg a python set), then you should expect the row/column order to not be deterministic. The fact that you only see the problem with CBC indicates that the changes you get in the answer are more an issue with CBC rather than the model. 

`ordered=False` was the default many years ago, but we changed it for efficiency reasons (and to be less of a surprise for users) several years ago. 

You should be able to get deterministic behavior using your nondeterministic initialization by declaring the Set with `sorted=Set.SortedOrder`. 

The one thing we should do is check that we sort unordered Sets in the LP writer. I will leave this issue open until I have a chance to verify that.

**Comment by jsiirola** [comment]
I should also have mentioned that the reason you are seeing a behavior difference between Pyomo 6.5 and 6.6 is because we moved to a new version of the LP writer that does a better job of trying to honor the order that users use when declaring their model (previously we would sort things by name and index, now the LP writer uses the model declaration order to determine the row order in the LP file).

**Comment by anamileva** [comment]
@jsiirola, thank you, that makes sense. Long-time Pyomo user here and I might have missed or forgotten about a memo or two along the way. It sounds like I'll need to be more careful with / avoid unordered data or explicitly tell Pyomo to sort from now on. If it's possible to warn the user if a Python `set()` or other unordered data type is passed, that would be helpful.

**Comment by jsiirola** [comment]
We actually do emit a warning if you pass a `set` to use to initialize an ordered `Set`. Unfortunately, there is no (easy) way for us to know if you define a rule that uses an unordered source internally and returns either an ordered type (like list) or a (nondeterministic) generator.

**Comment by anamileva** [comment]
Great, I'll play around with things on our end and see what we are doing that results in this not being caught.

Thank you to the Pyomo developers and maintainers!
