### ISSUE TITLE
How to get the GAP of a pyomo model running with Gurobi solver?

### ISSUE THREAD

**Issue by LAULZ** [Pyomo/pyomo#3029]
I usually use: 'results.Solver()['Gap']' for CBC, SCIP... but I'm not being able to get the gap value solving my pyomo model with Gurobi, using last pyomo version 6.6.2.

I found there is a gap item by running 'results.Solution.items()': dict_items([('Gap', <pyomo.opt.results.container.ScalarData object at 0x7f1bccf70790>), ('Status', <pyomo.opt.results.container.ScalarData object at 0x7f1bccf714b0>), ('Message', <pyomo.opt.results.container.ScalarData object at 0x7f1bccf71480>), ('Problem', <pyomo.opt.results.container.ScalarData object at 0x7f1bccf71660>), ('Objective', <pyomo.opt.results.container.ScalarData object at 0x7f1bccf71630>), ('Variable', <pyomo.opt.results.container.ScalarData object at 0x7f1bccf71600>), ('Constraint', <pyomo.opt.results.container.ScalarData object at 0x7f1bccf715d0>)]) (

But, when I try to get the value by running 'results.Solution.gap' it shows: undefined

How could I get my model gap value?

**Comment by mrmundt** [comment]
Hello, @LAULZ . The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
