### ISSUE TITLE
Unreachable code after .load_vars() method call

### ISSUE THREAD

**Issue by juzun** [Pyomo/pyomo#3030]
Hi,
when I call the method .load_vars() on my SolutionLoaderBase object, the following code (any code) becomes unreachable. Is that intended or is it some kind of bug?

https://github.com/Pyomo/pyomo/blob/70ef6e48b763e47bcb3698cfd76ce899f269a313/pyomo/contrib/appsi/base.py#L171

**Comment by mrmundt** [comment]
Hello, @juzun. The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.

If you do believe that this is a bug, please use the appropriate template when submitting an issue.
