### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by daviskirk** [Pyomo/pyomo#304]
I think it might help new developers if there were a kind of contribution guide.  Something along the lines of:

* How to structure pull requests
* What coding guidelines to follow (I guess #267 ?) 
* Where to place / write tests

I don't think it needs to be comprehensive, but I think it would really help getting people on board that would go on to contribute regularly.

**Comment by blnicho** [comment]
In addition to #267, this is also partly being addressed in PR #299. The development team has had several discussions about the points you mentioned and we are hoping to have a contribution guide in our official Sphinx documentation in the near future.
