### ISSUE TITLE
expression evaluation error (numpy coefficient)

### ISSUE THREAD

**Issue by DLWoodruff** [Pyomo/pyomo#3091]
## Summary

The mpi-sppy tests that track Pyomo main have started failing in the last couple of days.

### Steps to reproduce the issue

0. Install mpisppy and a solver from this list: xpress, gurobi, cplex
1. cd to mpisppy/tests
2. python test_ef_ph.py

### Error Message

...
  File "/home/woodruff/Documents/Research/DLWFORKS/mpi-sppy-1/mpisppy/spopt.py", line 345, in Eobjective
    local_Eobjs.append(s._mpisppy_probability * pyo.value(objfct))
  File "/home/woodruff/software/pyomo/pyomo/common/numeric_types.py", line 316, in value
    tmp = obj(exception=True)
  File "/home/woodruff/software/pyomo/pyomo/core/base/objective.py", line 426, in __call__
    return super().__call__(exception)
  File "/home/woodruff/software/pyomo/pyomo/core/base/expression.py", line 66, in __call__
    return arg(exception=exception)
  File "/home/woodruff/software/pyomo/pyomo/core/expr/base.py", line 118, in __call__
    return visitor.evaluate_expression(self, exception)
  File "/home/woodruff/software/pyomo/pyomo/core/expr/visitor.py", line 1322, in evaluate_expression
    if ans.__class__ not in native_types and ans.is_numeric_type() is True:
AttributeError: 'numpy.float64' object has no attribute 'is_numeric_type'

### Information on your system

Pyomo version: Pyomo 6.7.1.dev0 (devel {main}) (CPython 3.10.13 on Linux 5.15.0-91-generic)
Python version: 3.10.13
Operating system: Ubuntu
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable): cplex (both direct and command line)

### Additional information

Even though these objective functions are pretty simple, I have not been able to produce a simple example after a few hours of trying, but I will if I have to because this is a show-stopper

**Comment by jsiirola** [comment]
#3093 will resolve the issue from the Pyomo side.  That said, fixing this in mpi-sppy will require updates to mpi-sppy: mpi-sppy makes heavy use of accessing private Pyomo attributes (notably `_value`).  This practice bypasses the setter logic in Pyomo, which in turn bypasses how Pyomo detects the use of numpy types as value data.  To resolve this, mpi-sppi should do any one of:
- not access private attributes / bypass setters
- import `numpy` from `pyomo.common.dependencies` (i.e., `from pyomo.common.dependencies import numpy`)
- explicitly cast `bool(pyomo.common.dependencies.numpy_available)` somewhere before building models

**Comment by DLWoodruff** [comment]
Thanks!

**Comment by jsiirola** [comment]
#3093 is merged.  Remaining changes need to happen in mpi-sppy.
