### ISSUE TITLE
support for symphony solver

### ISSUE THREAD

**Issue by mujtabahasan** [Pyomo/pyomo#313]
Hi,

Is there a support for symphony solver going to be released. I need it for parallel optimization.

Thanks,

Mujtaba

**Comment by jsiirola** [comment]
There is currently no explicit support for Symphony and to my knowledge no developer is working to add it, but Pull Requests are always welcome.

**Comment by mrmundt** [comment]
Tracking this in the [Archived Design Discussions wiki page](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
