### ISSUE TITLE
NL Writer Errors when presolve removes all variables

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#3131]
## Summary

It would be extremely convenient if we could just return the solution somehow.

```
>>> import pyomo.environ as pe
>>> from pyomo.repn.plugins.nl_writer import NLWriter
>>> import io
>>> m = pe.ConcreteModel()
>>> m.x = pe.Var()
>>> m.y = pe.Var()
>>> m.obj = pe.Objective(expr=m.y)
>>> m.c1 = pe.Constraint(expr=m.y == m.x + 2)
>>> m.c2 = pe.Constraint(expr=m.y == -m.x + 1)
>>> writer = NLWriter()
>>> out = io.StringIO()
>>> writer.write(m, out)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../pyomo/repn/plugins/nl_writer.py", line 397, in write
    return impl.write(model)
           ^^^^^^^^^^^^^^^^^
  File "/.../pyomo/repn/plugins/nl_writer.py", line 865, in write
    raise ValueError(
ValueError: No variables appear in the Pyomo model constraints or objective. This is not supported by the NL file interface
```

**Comment by michaelbynum** [comment]
Excellent question. I actively avoided attempting to figure that out in the original issue, haha. Maybe the NL writer could have an option to skip the error and return the NLWriterInfo anyway. Then the caller can see if `info.variables` is empty and decide what to do?

**Comment by jsiirola** [comment]
I think that sounds quite reasonable.  What do you think about preserving the old behavior in the legacy "call" interface (so the old solvers don't have to be updated).  That is `__call__` will raise the exception (and delete the NL file), whereas the `write()` interface will just write and return ... and leave that particular error check up to the solver interface?

**Comment by michaelbynum** [comment]
Sounds good to me!
