### ISSUE TITLE
Unable to load HiGHS solver in Pyomo

### ISSUE THREAD

**Issue by SomajB** [Pyomo/pyomo#3146]
Hello all,

I am trying to run an optimization logic using Pyomo. I am running it in AWS Sagemaker.
I had previously used IPOPT solver in Pyomo and it worked fine but I am unable to replicate the process using Highs solver.

I have already installed Pyomo and Highs (same thing I did while using Ipopt). However when I am trying to solve it using Highs solver it is throwing an error saying solver not found. 

On further investigation, I noticed that somehow it is not picking up Highs solver. Instead it is picking up 'ASL' solver even though I am specifying it to pick up the Highs solver. 

Following are the steps I am using:
A. Installing the modules
conda install -c conda-forge pyomo
conda install conda-forge::highs

B. Importing modules
import pyomo.environ as pyomo
from pyomo.opt import SolverFactory
import pyomo.core as pycore

C, Creating a Pyomo model
model = pyomo.ConcreteModel()
I am adding a lot of constraints etc which I am skipping in this example

D. solver=pyomo.SolverFactory('HiGHS',executable='/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/highs')

After this when I print solver name it is showing 'asl' and not 'highs'

Can someone please tell me if I am doing anything wrong and how to fix this?

**Comment by mrmundt** [comment]
Hello, @SomajB . The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
