### ISSUE TITLE
Octal literals not recognized in data files

### ISSUE THREAD

**Issue by tkorvola** [Pyomo/pyomo#315]
According to the Pyomo book (Section 6.2.1): "Numeric values [in data files] are any string that can be evaluated by Python as a numeric value, e.g., integer, float, scientific notation, or boolean." Not quite, it turns out: only base 10 integer literals are accepted.

**Comment by tkorvola** [comment]
`int(token, base=0)` in `_process_token` would fix it.

**Comment by blnicho** [comment]
@tkorvola if you think you have a fix for this then please submit a PR

**Comment by mrmundt** [comment]
Due to inactivity and age, this issue is closed.
