### ISSUE TITLE
sign inconsistency in Constraint.lslack()

### ISSUE THREAD

**Issue by maajdl** [Pyomo/pyomo#317]
Below is the source code for the  Constraint.lslack  method.
If self.lower is None,  the returned value should be  float('inf')   instead of   float('-inf').
No lower bound means the lower bound is  -inf,  and running the code with lower=-inf should return lslack = +inf  by definition.

```
def lslack(self):
    """
    Returns the value of f(x)-L for constraints of the form:
        L <= f(x) (<= U)
        (U >=) f(x) >= L
    """
    if self.lower is None:
        return float('-inf')
    else:
        return value(self.body)-value(self.lower)
```

**Comment by ghackebeil** [comment]
This was fixed on master in bd75ff7c99fe718c9971e2bf75a268a74f82d2f6. It will be in the next release.
