### ISSUE TITLE
Bug in Abstract Set Creation

### ISSUE THREAD

**Issue by DLWoodruff** [Pyomo/pyomo#32]
In previous versions of Pyomo, one could use set expressions on abstract sets (which makes sense). In the current version, and on trunk, the following sort of thing:

model.S_Diff = Set()
model.S_Norm = Set()
model.ASS = model.ASS_pro|model.ASS_cst
model.ASSPRO = model.ASS|model.PRO
model.ASSPRODIS = model.ASSPRO|model.DIS
model.S = model.S_Norm|model.S_Diff

results in something like:

ERROR: Unexpected exception while loading model:
	Cannot iterate over abstract Set 'S_Norm' before it has been constructed (initialized).

This code works in previous versions of Pyomo. A example for testing is attached (if the example does not result in the error message "Cannot iterate over abstract Set ..." then it is no longer useful. It is not intended to be a working example).

[setbug.zip](https://github.com/Pyomo/pyomo/files/453315/setbug.zip)

**Comment by whart222** [comment]
Dave:

For bugs like this, what do you think about creating a PR that includes a test that exhibits the bug?

**Comment by DLWoodruff** [comment]
I attached a little example to the "ticket" (the "issue") that exhibits the
bug; however, that is all it does. It will not be a working example once
the bug is fixed, but it will quit giving the bug's stack trace once the
bug is fixed.
  It seems like attaching the example to the issue ("issue" is not a great
name, but we have live with it, I guess) seems better than a pull request
to me because that way the issue message leads the way.
  Dave
