### ISSUE TITLE
Reference Pyomo book table of contents

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#3209]
## Summary

A student recently mentioned that they couldn't figure out what was in the pyomo book relative to the online docs.

### Rationale

We could provide a link to the Springer site for users to understand the book docs:  https://link.springer.com/book/10.1007/978-3-030-68928-5

**Comment by mrmundt** [comment]
@whart222 - I don't quite understand what you mean by this. Can you please clarify?
