### ISSUE TITLE
No value for uninitialized NumericValue object

### ISSUE THREAD

**Issue by ShivKJ** [Pyomo/pyomo#3217]
Python Version: `3.11.7`
`pyomo.version.version_info`: `(6, 7, 1, 'final', 0)`

Below, we create two variables `v[0]` and `v[1]` which can take values 0 and 2 respectively given the constraints. `Solver.status` is `ok`. But still I am getting `No value for uninitialized NumericValue object`

```python
import numpy as np
from pyomo.environ import ConcreteModel, dot_product, maximize, Reals, SolverFactory, Var

if __name__ == '__main__':
    S = [0, 1]  # indices

    A = np.array([[1, 2], [3, 1]])
    B = np.array([4, 7])
    C = np.array([1, 10])

    model = ConcreteModel(name='test')

    model.v = Var(S, domain=Reals)


    @model.Objective(sense=maximize)
    def cost_function(m):
        return dot_product(C, m.v)


    @model.Constraint(S)
    def lte(m, i):
        return dot_product(A[i, :], m.v) <= B[i]


    solver = SolverFactory('cplex')  # no need to set executable

    res = solver.solve(model)
    model.pprint()
    print(f'{res.Solver.status=}, {model.cost_function()}')

    for a in model.v:
        print(f'{model.v[a]}->{model.v[a].value=}')
```

**Comment by ShivKJ** [comment]
Also note that when `C=np.array([1, 1])` then problem is solved without any exception.

**Comment by jsiirola** [comment]
You are confusing `Solver.status` with `Solver.termination_condition`.  `status` is telling you if the solver subprocess exited "normally" (using whatever definition of "normal" the solver chooses).  `termination_condition` tells you *why* the solver exited.  In this case, if you `print(res)`, you would see:
```
Problem:
- Lower bound: -inf
  Upper bound: inf
  Number of objectives: 1
  Number of constraints: 2
  Number of variables: 2
  Number of nonzeros: 4
  Sense: unknown
Solver:
- Status: ok
  User time: 0.0
  Termination condition: unbounded
  Termination message: Presolve - Unbounded or infeasible.
  Error rc: 0
  Time: 0.020587921142578125
```

**Comment by ShivKJ** [comment]
@jsiirola Thanks for the clarification.

Additionally, I also found that Objective function takes unbounded value, so as I changed `domin=` of `Var` to `NonNegativeIntegers`, it was working fine. With `domain=Reals`, `Solver.termination_condition=unbounded` and with `domain=NonNegativeIntegers`, `Solver.termination_condition=optimal`.
