### ISSUE TITLE
Broken link in Examples page

### ISSUE THREAD

**Issue by cimadure** [Pyomo/pyomo#3218]
Hi,

The link for Pyomo-Workshop-Summer-2018 seems broken on the page https://www.pyomo.org/workshop-examples

_`[Pyomo-Workshop-Summer-2018.pdf](https://software.sandia.gov/downloads/pub/pyomo/Pyomo-Workshop-Summer-2018.pdf)`_

Probably the document that was there before : https://www.osti.gov/biblio/1525944 or those slides https://github.com/jckantor/ND-Pyomo-Cookbook/tree/main/PyomoFest/slides

Regards

**Comment by jsiirola** [comment]
Resolved.  Thanks for pointing that out!.
