### ISSUE TITLE
Whether pyomo supports reading .lp or .mps files,

### ISSUE THREAD

**Issue by yp757078635** [Pyomo/pyomo#3229]
Whether pyomo supports reading .lp or .mps files, I check the interface documentation and there is no relevant material, currently there is only write, please help me take a look here

**Comment by jsiirola** [comment]
Please use the provided issue templates when opening issues here.  GitHub issues are for managing Pyomo development (i.e., for bug reports and feature requests), and are not intended for user support.  Please direct user support questions to the [established channels](https://github.com/Pyomo/pyomo#getting-help).

Pyomo does not parse LP or MPS files, and this is not a feature that is likely to be added by the core development team in the near future.  That said, pull requests from the community are always welcome!
