### ISSUE TITLE
REMINDER: Unpin `mpi4py` once fix is released

### ISSUE THREAD

**Issue by mrmundt** [Pyomo/pyomo#3237]
## Summary

There is an issue with `mpi4py==3.1.6` that makes our conda builds fail. We pinned it to 3.1.5. This is a reminder to undo that when this issue is resolved: https://github.com/mpi4py/mpi4py/issues/484

**Comment by jsiirola** [comment]
Out of curiosity, why did you not just pin the version with `"mpipy!=3.1.6"` (the we wouldn't need to unpin, plus it would leave a note in the dependencies about known bad dependencies)?

**Comment by mrmundt** [comment]
Because the logic didn't work when I tried it (in multiple different fashions and syntaxes). If you can work your magic, have at it.
