### ISSUE TITLE
Sorting mixed-type Sets fails in Python3

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#325]
PR #305 pointed out an issue with Sets in Python 3: while Pyomo allows mixed-type Sets (i.e., mixing integers and strings in a single set), doing so will likely fail when running under Python 3 due to pervasive sorting to enforce determinism.

We should propagate the more robust sorter added in #305 to the main Set class as a `sorted_values()` method, and then replace most uses of `sorted()` with `set.sorted_values()` throughout the code.

**Comment by carldlaird** [comment]
At this same time, I think we should also consider (1) defaulting all sets to ordered, or (2) removing unsorted sets altogether.

**Comment by jsiirola** [comment]
Agreed.  I would like to have a general design discussion as part of #326, and defaulting Sets to ordered is definitely part of that.
