### ISSUE TITLE
Pure Python wheel of Pyomo

### ISSUE THREAD

**Issue by harshil-patel-code** [Pyomo/pyomo#3255]
I am looking for pure python wheel (*py3-none-any.whl) of Pyomo. It will be used with [Pyodide](https://pyodide.org/en/stable/development/new-packages.html#determining-if-creating-a-pyodide-package-is-necessary)

**Comment by mrmundt** [comment]
Hello, @harshil-patel-code . We appreciate your suggestion! We will discuss this request and add it to our backlog for future efforts. If you have more information as to why this is a necessary change, please feel free to add that information.

_NOTE_: There is no guarantee that we will implement all suggestions. We do, however, accept external contributions. If you are interested in expediting this request, we encourage you to review our [Contribution Guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html).
