### ISSUE TITLE
Pyomo.DAE Simulator support for PDAEs

### ISSUE THREAD

**Issue by fahim831** [Pyomo/pyomo#3263]
## Summary

The documentation was a bit unclear to me whether differential algebraic equations (DAEs) in 2 variables can be solved or not.

### Rationale

I think the Simulator will benefit greatly if it can solve multivariable/partial DAEs.

### Description

I was not clear on whether the DAE function currently supports partial PDAEs or not and unsure if I should open this under Bugs or Feature request.

As can be seen in the first block of code under ["Declaring Differential Equations"](https://pyomo.readthedocs.io/en/stable/modeling_extensions/dae.html#declaring-differential-equations), a variable $y(t,l)$ is defined and a PDE is defined, $\frac{\partial y}{\partial t} = \frac{\partial^2 y}{\partial l^2}$. However, at the end, the page lists 4 limitations of the Simulator, one of which is "Model can only contain a single ContinuousSet". But $t$ and $x$ would be 2 separate ContinuousSet. So would it be possible to solve a DAE in both $t$ and $x$ or not?

**Comment by blnicho** [comment]
@fahim831 this is not currently supported in the pyomo.DAE simulator interface so I've modified your issue to be a feature request.

**Comment by fahim831** [comment]
Thank you for clarifying.

**Comment by Robbybp** [comment]
You can see an example of solving the gas pipeline PDE in the `stochgaspde` files [here](https://github.com/Pyomo/pyomo/tree/main/examples/dae). I'm not sure if this is the same model from the paper, but it may still be helpful.

**Comment by fahim831** [comment]
> You can see an example of solving the gas pipeline PDE in the `stochgaspde` files [here](https://github.com/Pyomo/pyomo/tree/main/examples/dae). I'm not sure if this is the same model from the paper, but it may still be helpful.

Thank you! This is a very good folder with useful examples. I will be sure to make good use of them.

**Comment by blnicho** [comment]
@fahim831 you can use Pyomo.DAE to formulate a limited set (bounded, rectangular, continuous domains) of PDAEs and  you can discretize them and solve "simulation" problems by sending a square model to a nonlinear optimization solver. The solution will give you the time-varying state profiles at the discretization points.

My previous comment was specific to the Simulator interface in Pyomo.DAE which only links to ODE and DAE integrators in SciPy and CasADi.

**Comment by fahim831** [comment]
@blnicho Yes, that's what I figured. Thanks for confirming!
