### ISSUE TITLE
Baron installation guide on Pyomo

### ISSUE THREAD

**Issue by mshahabi** [Pyomo/pyomo#330]
I am trying to install BARON solver on Pyomo + Anaconda. However, I have difficulty linking the solver executables with Pyomo?

Any suggestion?

**Comment by ghackebeil** [comment]
Pyomo supports two interfaces to Baron. In either case, all that is required is that the location of the Baron executable is in your shell's search path (e.g., by adding the directory to the PATH environment variable).

If you have the Baron executable that is **not** for AMPL, just set the Pyomo solver name to 'baron' and we will interface with it by writing a `.bar` file.

If you have a Baron executable that works with AMPL, you should set the Pyomo solver name to that executable name _if it is something other than 'baron'_. If the Baron executable is named 'baron' _and_ it is for AMPL, either rename it to something else on your system and use that as the Pyomo solver name, or set the solver name to 'asl:baron'. In this case, we interface with Baron by writing a `.nl` file.

**Comment by jsiirola** [comment]
This is not reporting an error, bug, or enhancement request; closing the issue.
