### ISSUE TITLE
`latex_printer` does not support object-oriented defined models 

### ISSUE THREAD

**Issue by alejandro-yousef** [Pyomo/pyomo#3300]
## Summary

I am currently working on a project where I am using Pyomo to define and solve optimization problems. I have noticed that the `latex_printer` function from `pyomo.contrib.latex_printer` works well with the "procedural style" of defining a model, but it does not work if the model is defined in an "object-oriented" style.

This issue might be relevant for #3048 

**Example:**

```python
class BasicFormulation(pyo.ConcreteModel):
    def __init__(self):
        super().__init__()
        self.x = pyo.Var()
        self.y = pyo.Var()
        self.z = pyo.Var()
        self.c = pyo.Param(initialize=1.0, mutable=True)
        self.objective = pyo.Objective(expr=self.x + self.y + self.z)
        self.constraint_1 = pyo.Constraint(
            expr=self.x**2 + self.y**2.0 - self.z**2.0 <= self.c
        )

print(latex_printer(BasicFormulation))
```

**Result:**

When I run this code, I encounter the error below. However, when I define the model in a procedural style (as in `latex_printer` documentation), the function works as expected.

```python
Traceback (most recent call last):
  File "C:\Users\...\Roaming\JetBrains\PyCharmCE2024.1\scratches\toto_latex_printer.py", line 30, in <module>
    print(latex_printer(BasicFormulation))
  File "C:\...\.nox\dev\lib\site-packages\pyomo\contrib\latex_printer\latex_printer.py", line 700, in latex_printer
    raise ValueError(
ValueError: Invalid type <class 'type'> passed into the latex printer

```

### Rationale
Supporting the object-oriented style of defining a model would be a good addition to `latex_printer` as this implementation enables a more modular and reusable formulation specially when working with complex models.

### Additional information

pyomo 6.7.3
python 3.10

**Comment by jsiirola** [comment]
The LaTeX printer (like all other Pyomo model interrogation / transformation tools) only works on model instances.  In your code, you are passing the latex_printer a class definition (with a function that can create a model).  There is no way for the LaTeX printer to know what your model is without parsing the Python AST (effectively, process the parsed Python source code) - which is not something we are likely to have the time / bandwidth to implement anytime in the near future.

That said, the LaTeX printer will work on your model if you pass it a concrete instance:
```python
>>> print(latex_printer(BasicFormulation()))
\begin{align}
    & \min
    & & x + y + z & \label{obj:unknown_objective} \\
    & \text{s.t.}
    & & x^{2} + y^{2} - z^{2} \leq c & \label{con:unknown_constraint_1}
\end{align}
```

**Comment by alejandro-yousef** [comment]
Thanks for such a quick response @jsiirola

For this specific example, a concrete instance could be easily passed but it is not always the case as the initialization parameters may not be know before run time. Moreover, I would like to document the class and not an specific instance

Having said that, I completely understand if you are unable to implement this anytime in the near future due to time constraints or other commitments. Thank you for considering it.
