### ISSUE TITLE
Mismatch: `OptSolver` versus `set_results_format`

### ISSUE THREAD

**Issue by sstroemer** [Pyomo/pyomo#3336]
## Summary

The `set_results_format` function checks against `_valid_results_formats`, while the attribute in `OptSolver` is called `_valid_result_formats`. Not sure if singular/plural is better since I assume it could be both _results_ as well as (a) _result_, but the respective other attribute is called `_results_format `, so I assume `_valid_results_formats` should be the way to go.

### Steps to reproduce the issue

```python
from pyomo.opt import SolverFactory
from pyomo.opt.base import ProblemFormat

opt = SolverFactory("cbc")
opt.set_results_format(ProblemFormat.cpxlp)
```

### Error Message

```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/envname/lib/python3.12/site-packages/pyomo/opt/base/solvers.py", line 473, in set_results_format
    if (self._problem_format in self._valid_results_formats) and (
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CBCSHELL' object has no attribute '_valid_results_formats'. Did you mean: '_valid_result_formats'?
```

### Information on your system

Pyomo version: 6.7.1
Python version: 3.12.4
Operating system: Ubuntu 20.04
How Pyomo was installed (PyPI, conda, source): mamba
Solver (if applicable): any that supports this (e.g., `gurobi` fails too)

### Additional information

Bug was observed in `v6.7.1` but still persists in latest (b4804976ffc032c9eccc6ac360c857eb1edeb9d2), see:

- `_valid_result_format`: [solvers.py](https://github.com/Pyomo/pyomo/blob/b4804976ffc032c9eccc6ac360c857eb1edeb9d2/pyomo/opt/base/solvers.py#L383)
- `_valid_results_formats`: [solvers.py](https://github.com/Pyomo/pyomo/blob/b4804976ffc032c9eccc6ac360c857eb1edeb9d2/pyomo/opt/base/solvers.py#L473)

**Comment by mrmundt** [comment]
Hi @sstroemer - I am truly amazed that this has never been reported before. PR is up for it. Thanks!
