### ISSUE TITLE
Ipopt not running on windows.

### ISSUE THREAD

**Issue by petrasvestartas** [Pyomo/pyomo#3395]
We have been using lpopt for [compas_cra ](https://blockresearchgroup.github.io/compas_cra/latest/installation.html)package:
conda create -n cra python=3.10 pyomo=6.4.2 ipopt=3.14.9 compas

This works for mac and linux, but not for windows, so we also need to install very first version ipopt=3.11.1
It was working for multiple years for research, but now completely broke.

Is there any way that you could provide executable for 3.14.9 version too?

**Comment by mrmundt** [comment]
Hello @petrasvestartas . Pyomo does not distribute executables for solvers, so we will not be implementing this. However, some suggestions:
1. Submit your request to https://github.com/coin-or/Ipopt to see if they will consider distributing binaries
2. Consider installing IDAES and using their `get-extensions` capability: https://idaes-pse.readthedocs.io/en/latest/tutorials/getting_started/windows.html#install-idaes-extensions

**Comment by petrasvestartas** [comment]
You do, in the initial release.

**Comment by mrmundt** [comment]
This information is new to the current development team, as none of us were aware of any past releases of executables. Given the time that has passed, it is understandable that some knowledge may have been lost. However, please note that this practice has not been in place for many years and will not be implemented.
