### ISSUE TITLE
Create a new component: MutableParam

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#34]
The discussion related to PR #33 highlighted that immutable and mutable parameters have very different semantics.  For example, PR #33 allows mutable parameters to be defined and used to create expressions without having values, which immutable parameters would generate an error in this context.

I think it may make sense to have separate components:  Param and MutableParam that segregate these two notions of "data values" in models.  What are the pros and cons?

**Comment by ghackebeil** [comment]
Oops. I referenced the wrong ticket in the commit above.

**Comment by mrmundt** [comment]
We may either want to truly have this discussion or close this issue as "not planned." There has been no update or discussion on this since 2016.

**Comment by mrmundt** [comment]
Tracking this in the [Archived Design Discussions wiki page](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
