### ISSUE TITLE
Design Documentation for Kernel

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#341]
The kernel documentation focuses on documentation of the classes, but what is missing is a description of the design of pyomo.core.kernel.  For example, issue #161 related to a design choice that was not immediately apparent.

I recommend that we start this documentation on a branch, as I expect it to precipitate a design discussion and probably changes in kernel.

**Comment by ghackebeil** [comment]
Where should this documentation go?

**Comment by mrmundt** [comment]
In an effort to clean up issues, we are moving some design discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
