### ISSUE TITLE
Merge of improvements to CPLEX/Gurobi interfaces #331 conflicting with python virtual environments

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#343]
I noticed some very strange behavior running tests after the merge of #331:
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/qichen/git/pyomo/pyomo/solvers/plugins/solvers/GUROBI_RUN.py", line 15, in <module>
    from six.moves import zip
ImportError: No module named six.moves
```
This error usually means that I haven't done `pip install six`, but my activated virtual environment does in fact have `six` installed. I found that doing the following "fixes" the problem:
```
deactivate
sudo apt install python-pip
pip install six
source /path_to_my_venv/bin/activate
# run tests again
```
This makes me wonder if the import of `GUROBI_RUN.py` happens outside of my virtual environment.

**Comment by ghackebeil** [comment]
That’s a good point. It actually does. It is run by gurobi.sh. We should remove the import.

Gabe

**Comment by michaelbynum** [comment]
@qtothec Thanks for bringing this up. Good point. I will get it fixed asap.
