### ISSUE TITLE
GAMS stream output (tee) not working after logfile option addition

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#347]
```
from pyomo.environ import *
m = ConcreteModel()
m.x = Var()
m.c = Constraint(expr=m.x >= 2)
m.o = Objective(expr=m.x)
SolverFactory('gams').solve(m, tee=True)
```
is failing to stream GAMS output after the merge of #302. Expected behavior is restored by checking out the preceding bcb316cca7f539ebe0f25f7321b5a28ccc964d51 commit.

**Comment by jsiirola** [comment]
@qtothec: which platform?

**Comment by qtothec** [comment]
My usual. Ubuntu 16.04 LTS.
