### ISSUE TITLE
Pyomo.DAE transformations looping through blocked-hierarchical models incorrectly

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#353]
This representative example from an IDAES unit model throws an AttributeError:

```
from pyomo.environ import *
from pyomo.dae import *

m = ConcreteModel()
m.t = ContinuousSet(bounds=(0,10))

m.CO1 = Block()
m.CO1.holdup = Block()
def _prop_in_rule(b, t):
    b.pressure = Var()
    return b
m.CO1.holdup.properties_in = Block(m.t, rule=_prop_in_rule)

def _prop_out_rule(b, t):
    b.pressure = Var()
    return b
m.CO1.holdup.properties_out = Block(m.t, rule=_prop_out_rule)

m.CO1.ratioP = Var(m.t)

def _ratio_rule(b, t):
    return b.ratioP[t] <= b.holdup.properties_in[t].pressure - b.holdup.properties_out[t].pressure 
m.CO1.eq_ratio_P = Constraint(m.t, rule=_ratio_rule)

disc = TransformationFactory('dae.finite_difference')
disc.apply_to(m, nfe=2)
```

```
$ python -i temp.py
Traceback (most recent call last):
  File "temp.py", line 26, in <module>
    disc.apply_to(m, nfe=2)
  File "/home/blnicho/Research/pyomo/pyomo/core/base/plugin.py", line 334, in apply_to
    self._apply_to(model, **kwds)
  File "/home/blnicho/Research/pyomo/pyomo/dae/plugins/finitedifference.py", line 187, in _apply_to
    self._transformBlock(block, currentds)
  File "/home/blnicho/Research/pyomo/pyomo/dae/plugins/finitedifference.py", line 218, in _transformBlock
    update_contset_indexed_component(c)
  File "/home/blnicho/Research/pyomo/pyomo/dae/misc.py", line 145, in update_contset_indexed_component
    _update_constraint(comp)
  File "/home/blnicho/Research/pyomo/pyomo/dae/misc.py", line 189, in _update_constraint
    con.add(i, apply_indexed_rule(con, _rule, _parent, i))
  File "/home/blnicho/Research/pyomo/pyomo/core/base/misc.py", line 61, in apply_indexed_rule
    return rule(model, index)
  File "temp.py", line 22, in _ratio_rule
    return b.ratioP[t] <= b.holdup.properties_in[t].pressure - b.holdup.properties_out[t].pressure 
  File "/home/blnicho/Research/pyomo/pyomo/core/base/block.py", line 521, in __getattr__
    % (self.__class__.__name__, val))
AttributeError: '_BlockData' object has no attribute 'pressure'
>>> 
```

**Comment by blnicho** [comment]
I think the real problem here is that we only store the component declaration order for a particular Block and not the overall declaration order for all components at all levels on a model (as far as I can tell). This makes it challenging to come up with a general way to expand block-hierarchical models in the discretization transformations because there could be a very specific order that components were added to different Blocks to ensure that dependencies are satisfied (ex. constraints involving variables at different Block levels) and this order is not recorded anywhere. This problem is exacerbated by the fact that Blocks themselves can be indexed by a ContinuousSet. 

I talked with @whart222 and he didn't see a solution for this. He suggested we start a broader discussion with the rest of the Pyomo developers on the issue of circular dependencies.

@jsiirola any ideas on how to get around this?

**Comment by blnicho** [comment]
@andrewlee94 I think this issue is now fully resolved (including logging) in the issue-353 branch. Let me know if it works for you and the new IDAES work-around you're trying out. I'm finishing up tests and will open a PR for this shortly.

**Comment by andrewlee94** [comment]
@blnicho I just ran my go to test for this, and everything worked as expected, with no warnings from the Pyomo logger. It looks like we finally got this one sorted.
