### ISSUE TITLE
Pyomo closes any open Excel windows

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#355]
As reported on StackOverflow (https://stackoverflow.com/questions/48864193/pyomo-closes-excel), running `from pyomo.environ import *` closes any open Excel windows.

This appears to be due to `pyomo.core.plugins.data.sheet.py`, and in particular:
```
if win32com_available:
    from pyutilib.excel.spreadsheet_win32com import ExcelSpreadsheet_win32com
    tmp = ExcelSpreadsheet_win32com()
    try:
        tmp._excel_dispatch()
        tmp._excel_quit()
        _excel_available = True
    except:
        pass
```

At a minimum, this shouldn't be happening during import.  Better yet, we should figure out a way to detect if we should / should not call `._excel_quit()`

**Comment by blnicho** [comment]
I copied this import check to fix a fragile test in https://github.com/Pyomo/pyomo/blob/master/pyomo/core/tests/examples/test_tutorials.py as discussed in #669. When this issue is resolved the fix should be propagated to this file.

**Comment by goroderickgo** [comment]
Hi, glad I just stumbled upon this issue, as we are still having this issue with pyomo 5.3+. 

After testing, 5.2 is the last release in which this bug doesn't cause Excel to quit. Is there a better fix than us modifying `pyomo.core.plugins.data.sheet.py`, perhaps an update to the `_excel_quit()` method?

**Comment by goroderickgo** [comment]
@jsiirola and @whart222, my organization is in a slight paradox: we need to (1) update the version of pyomo to >=5.5 to get the solver interface updates but also (2) don't want to roll out a product to users that causes the related Excel files to close every time we try to run a model. Is a fix in the works?

**Comment by jsiirola** [comment]
@goroderickgo: to my knowledge, no one is digging into this at the moment (I would very much like to fix this as I suspect that it burns most Windows users, but as the saying goes, "there are only so many hours in a day").

A PR would be most welcome if you have time to look into it.

**Comment by blnicho** [comment]
@jsiirola I think I found a simple fix for this and have opened a PR in PyUtilib.

**Comment by blnicho** [comment]
@goroderickgo could you install the master branch of PyUtilib and see if this is resolved for you? It will likely be a few days before we can get this fix into a release.

**Comment by jsiirola** [comment]
@goroderickgo: PyUtilib 5.7.1 and Pyomo 5.6.6 are now released and contain the fix for this issue.

**Comment by goroderickgo** [comment]
Thanks @jsiirola and @blnicho, seems like the update works!
