### ISSUE TITLE
Undefined variable in scenariotree manager

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#362]
The following method from `pysp/scenariotree/preprocessor.py` fails because `scenario_name` is undeclared:

```
    def remove_scenario(self, scenario):
        assert scenario._name in self._scenario_instance
        assert scenario._name not in self._scenario_to_bundle_map
        scenario_instance = self._scenario_instance[scenario_name]
```

**Comment by ghackebeil** [comment]
You must be on a branch that needs master merged into it (or are on an old release). Can you confirm?

**Comment by jsiirola** [comment]
I think it is expr_pyomo5 -- and I thought master had been merged into it, but I am likely not correct.  @whart222?

**Comment by ghackebeil** [comment]
I've fixed this on expr_dev
