### ISSUE TITLE
Update book examples on the Pyomo website

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#367]
If we make changes to the book examples (due to api or other changes in Pyomo). We need to post those changes to the Pyomo website with a brief description. I recommend we add a link and some description below the Pyomo book on the Documentation page.

**Comment by blnicho** [comment]
We have a link on the Pyomo website to a wiki page for tracking Pyomo book errata and are now testing the book examples as part of our testing suite.
