### ISSUE TITLE
IPOPT output for overspecified problems

### ISSUE THREAD

**Issue by andrewlee94** [Pyomo/pyomo#381]
When solving a model using ipopt, if the problem is over-specified, the shown below is produced. It would be useful if a report of the number of variables and constraint in the model were provided to help identify the problem (similar to when a problem is successfully solved).

Discussing this with Pyomo developers, it is believed that this is because the Exception is being returned too early, before the degrees of freedom are evaluated and reported by Pyomo.

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.6, running with linear solver ma27.

Number of nonzeros in equality constraint Jacobian...:      470
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:      153

Exception of type: TOO_FEW_DOF in file "/home/alee/src/Ipopt-3.12.6/Ipopt/src/Interfaces/IpIpoptApplication.cpp" at line 890:
 Exception message: status != TOO_FEW_DEGREES_OF_FREEDOM evaluated false: Too few degrees of freedom (rethrown)!

EXIT: Problem has too few degrees of freedom.
WARNING: Loading a SolverResults object with a warning status into
    model=fs_obj;
        message from solver=Too few degrees of freedom (rethrown)!
INFO - Flowsheet initialisation finished.

Solver: 
- Status: warning
  Message: Too few degrees of freedom (rethrown)!
  Termination condition: other

**Comment by blnicho** [comment]
I thought this was a problem with IPOPT throwing an exception before the number of variables and constraints are printed. I'm pretty sure Pyomo does not print or evaluate the degrees of freedom before sending the model to a solver.

**Comment by qtothec** [comment]
I think that @eslickj has some code to give you this kind of information.

**Comment by jghouse88** [comment]
Yes. I think @jsiirola mentioned once that to resolve this it was a minor change to the location of the print statement to display the variables/constraints from IPOPT. 

This will definitely be useful for us to figure out how many variables to unfix. "TOO FEW DEGREES OF FREEDOM" is not particularly useful.

**Comment by eslickj** [comment]
I do have some code to evaluate the degrees of freedom before you solve.  It's currently in the UI, but I can move it to the core, if it helps.  It's probably easier than getting IPOPT changed, and it would work for other solvers as well.

**Comment by jghouse88** [comment]
@eslickj That sounds great! However, that would put it part of just IDAES core but I feel this may be something useful for Pyomo itself.

**Comment by blnicho** [comment]
@andrewlee94, you could add a check for this return status and then automatically call @eslickj's code to print the degrees of freedom. I agree that this could be a useful tool for general Pyomo models. @eslickj feel free to submit a PR if you want to move it into Pyomo. I'm going to close this issue. I think further discussion should be moved to the IDAES repo.

**Comment by qtothec** [comment]
@jghouse88 @eslickj You can look at #217 to see what the first pass at these diagnostic utilities looks like.
