### ISSUE TITLE
Unbounded constraints for AMPL solvers

### ISSUE THREAD

**Issue by PavloMuts** [Pyomo/pyomo#388]
Hello,

I have been using Pyomo 5.2 until now, and yesterday decided to update to 5.4.3. In the version 5.2 it was possible to have unbounded constraints, namely, I could have something like this `sum(x) < float('inf')`. Now it is not possible to have this kind of constraints and I get `AssertionError` from the `ampl_.py` when the method `has_ub()` is invoked. I read in the changelog that methods `has_ub()` and `has_lb()` are present starting from 5.3 version. Is it possible to have the unbounded constraints in the current/next version? 

Best,
Pavlo

**Comment by ghackebeil** [comment]
It looks like we currently have some inconsistency across our solver interfaces in how these constraints are handled, some skip over them and some raise an exception. I’ll open up a PR with a patch to make things consistent (and that they will be skipped over).

In the meantime, you can patch your local installation to make the NL-writer ignore them by adding the following to line 951 of pyomo/repn/plugins/ampl/ampl_.py

                if (not constraint_data.has_lb()) and \
                   (not constraint_data.has_ub()):
                    continue  # non-binding, so skip    

Gabe

**Comment by jsiirola** [comment]
@ghackebeil: what should the expectation be for things like duals when the solver / writer omit constraints?

**Comment by ghackebeil** [comment]
The expectation is that it might not have a value stored in the suffix.

It turns out that this can happen with the NL interface even with constraints that are sent to the solver. This is because the ASL only writes nonzero suffix data into the solution. That is, you get a sparse suffix solution back.

Gabe
