### ISSUE TITLE
Review objects exposed by environ

### ISSUE THREAD

**Issue by andrewlee94** [Pyomo/pyomo#390]
At the request of @jsiirola after I brought this to his attention, some Pyomo objects are not exposed by environ that would otherwise be expected. One that I have encountered is `TerminationCondition`, which needs to be imported from `pyomo.opt`.

**Comment by whart222** [comment]
Aside from TerminationCondition, what else appears to be missing?  I'm not sure what the action is for this ticket other than exposing that object?

**Comment by jsiirola** [comment]
I am reopening this issue. While we now export TerminationCondition and SolverStatus through pyomo.environ, we still need to go through and review all the symbols exported through environ (both for symbols that don’t belong and symbols that should be added).

**Comment by whart222** [comment]
FWIW, I don't find open-ended tickets like this particularly useful.  We've resolved the specific issue noted by the user.  What remains is an open ended activity, for which there is no clear criteria for closing.  Thus, I've assigned this to @jsiirola since he re-opened it.

**Comment by mrmundt** [comment]
@jsiirola - I have moved this issue to our internal tracking board so that it does not need to remain open forever.
