### ISSUE TITLE
ApplicationError pyutilib / Ipopt for some models, disappears if print_level option is specified

### ISSUE THREAD

**Issue by maajdl** [Pyomo/pyomo#399]
Hello,

I am reposting this from [google groups](https://groups.google.com/forum/#!topic/pyomo-forum/oVIrEvT_DIs) because it looks like an issue in Pyomo.

I had  a model involving   Expr_if   expressions that  was triggering an exception (see below).
Strange enough, this problem  disappeared  by simply  specifying any value for the  print_level  option, even with  tee=False, and the solution found was correct.

I then found an interresting test:

I moved to a folder the  NL   file generated by Pyomo when the solver failed within Pyomo.
I then solved this  NL  file from the command line:    ipopt test.nl   .
(one such file in attachment)

**Big surprise**:  ipopt succeeds without any error!
(EXIT: Optimal Solution Found. Ipopt 3.11.1: Optimal Solution Found)

I made a few more other tests and could not get any error from the command line! 

This suggests that the error occurs because of some communication problem from Pyomo to Ipopt.
The good news is that the  Ipopt  solver does probably work well on these models,
and that the print_level  workaround is probably not too bad, if it works!
The bad news is that there is a small bug in Pyomo, probably.

Could you have a look?
Would you have some suggestion?

Thanks,

Michel

**errors from pyomo**

A windows warning screen "ipopt.exe has stopped working, ... , Windows will close the program ... "

and this in Jupyter:

ERROR: "[base]\site-packages\pyomo\opt\base\solvers.py", 616, solve
	Solver (ipopt) returned non-zero return code (255)
ERROR: "[base]\site-packages\pyomo\opt\base\solvers.py", 621, solve
	Solver log:
	Ipopt 3.11.1: halt_on_ampl_error=no

I also read the solver exception:
status:  exception (<class 'pyutilib.common._exceptions.ApplicationError'>, ApplicationError('Solver (ipopt) did not exit normally',), <traceback object at 0x0000004538AF9E48>)

**Sample nl file generated by a model that fails within pyomo**
[test_1004.nl.zip](https://github.com/Pyomo/pyomo/files/1828646/test_1004.nl.zip)
[model.pickle.zip](https://github.com/Pyomo/pyomo/files/1829637/model.pickle.zip)

**Comment by jsiirola** [comment]
We need a (hopefully minimal) Pyomo example that reproduces the reported error to diagnose this.

**Comment by maajdl** [comment]
The model is small, but uses some database.
Is there a way to generate a  "slim" model or a script from a an exisiting built ConcreteModel?

**Comment by jsiirola** [comment]
You could try pickling the model after you build it.  Depending on how you define the model, that might work.

**Comment by maajdl** [comment]
Attached is a pickle file of the concrete model .

The snippet below will solve without problem.
Removing the "option 2" line  will lead to an exception.
Then removing the "option 1" line will also remove this exception.
Maybe that's an ipopt problem?


import sys
import pickle
from pyomo.environ import *
print(sys.getrecursionlimit())
sys.setrecursionlimit(10000)
print(sys.getrecursionlimit())
pickle_in = open("model.pickle","rb")
mdl = pickle.load(pickle_in)
solver = SolverFactory("ipopt")
solver.options["halt_on_ampl_error"] = "yes"     #  option 1
solver.options["print_level"] = 1                          # option 2
solver.solve(mdl)

**Comment by ghackebeil** [comment]
I don't think the attachment made it into the GitHub issue. Are you replying via email? You might need to attach it through the web interface.

**Comment by maajdl** [comment]
I had troubles to attach the file.
I managed to do it by adding it to the original post.
And now I can add the link here:

[model.pickle.zip](https://github.com/Pyomo/pyomo/files/1829637/model.pickle.zip)

**Comment by ghackebeil** [comment]
Unfortunately we can't un-pickle the model because there are things on it that reference 'cementPy'. These are likely things like constraint rule definitions. You might try applying the following to your model before pickling it:
```python
# Delete all possible references to "rules"
# declared in the original model file so we
# don't have to reference it when we unpickle
for block in scenario_instance.block_data_objects():
    if isinstance(block, Block):
        block._rule = None
    for var in block.component_objects(Var):
        var._domain_init_rule = None
    for con in block.component_objects(Constraint):
        con.rule = None
    for obj in block.component_objects(Objective):
        obj.rule = None
    for param in block.component_objects(Param):
        param._rule = None
        param._validate = None
    for set_ in block.component_objects(Set):
        set_.initialize = None
        set_.filter = None
    for ba in block.component_objects(BuildAction):
        ba._rule = None
```

Can you also attach the NL file you generated?

**Comment by ghackebeil** [comment]
Sorry, I just saw that you attached an NL file above.

**Comment by ghackebeil** [comment]
Just to provide some insight, the only difference between what Pyomo does to launch Ipopt and what you did directly on the command line is that Pyomo adds the "-AMPL" flag to the end of the command, which causes a solution file to be written.

If that is the temporary NL file that was created by Pyomo prior to launching Ipopt, then I really can't see how Pyomo is the cause of this issue. What version of Ipopt are you using?

**Comment by maajdl** [comment]
I am using Pyomo 5.3 .
The pickle file will need a bit more time before I can do it.

Thanks!

**Comment by maajdl** [comment]
I am using Ipopt 3.11.1

**Comment by ghackebeil** [comment]
Okay. So Ipopt had a pretty nasty memory bug between 3.11.0 and 3.11.8 that could cause non-deterministic failures like what you are seeing. I would highly recommend updating to the most recent version (currently 3.12.10) to see if that fixes things.

**Comment by maajdl** [comment]
Thanks, I will try that.

**Comment by maajdl** [comment]
I could not find the binary for version 3.12.10 .
Therefore, I tried the version 3.10.1 , and this version made no problem.
This shows that the problem is related to Ipopt.
I occured probably because my problem has a rather large depth (blocks within block within block), and specially for the Expr_if that are recursively called. Maybe this pressures somewhat to the memory leak.

Thanks for you help. I am very happy to work with Pyomo.

Michel

**Comment by maajdl** [comment]
Back again!
I restarted my PC and then I got the problem with Ipopt 3.10 even without specifying any solver option.
Switching to 3.11, and without solver options, removed any error as before.
So are memory leaks!
I need to find a way to test 3.12 .

**Comment by ghackebeil** [comment]
I think we can rule out a Pyomo issue at this point. Feel free to reopen if you find evidence of that.
