### ISSUE TITLE
Model-wide declaration order

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#407]
Looking at issue: #353 and the corresponding PR: #406, there were some problems associated with the fact that decl order is maintained at the scope of a block only, and not at the scope of the entire model. When users add components to blocks in an arbitrary order (e.g., add x to block 1, then y to block 2, then z to block 1, then a to block 2, etc...) we do not maintain this overall ordering. This can cause problems if we need to fire rules later and those rules depend on the overall decl order.

We should explore the idea of maintaining a global (or model-wide) decl order...

**Comment by blnicho** [comment]
Relevant comments from an email from @jsiirola:

>  Some additional thoughts:
> 
> I do not think that a model-wide decl_order would either be tractable nor sufficient. First, it is not clear where that list should be maintained: the top level block is insufficient, as for cases like the PySP extensive form, the individual scenarios are created independently and then “glued” together into the EF model after the fact (how to we merge the individual decl_orders? Alternatively we could maintain a global list ... but that screams of pain and memory leaks. I suppose we could have a global counter that could assign a unique decl ID to every component that is created... and leave sorting to whatever consumer cares. 
> 
> Even if we had a global decl order, I don’t necessarily think that reconstructing the correct order for the DAE expansion will be all that straightforward. You could end up with some pretty crazy orders, especially when some components are added to a block during the rule, others after the fact (e.g. in build()), and others are added during a transformation. Case in point: figure the decl order when a block (say an absorber) has already been expanded in space and is now being expanded in time? (Or worse ... time first then space?)

**Comment by ghackebeil** [comment]
Perhaps the way to handle this is to allow users to annotate components with a dependency list (or allow them to provide some kind of dependency graph when a certain function is called). Declaration order would be the default, but if you have these crazy cases where that breaks down, maybe the only way to truly avoid issues is to allow users (partially) specify the order in some way.

**Comment by mrmundt** [comment]
In an effort to clean up issues, we are moving some design discussion to our [Archived Design Discussion wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
