### ISSUE TITLE
Automate tests for cythonized *.c files

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#415]
It's recommended that Python packages leveraging Cython embed their associated *.c files.  We need to find a way to test that these files are up-to-date w.r.t. changes in their associated *.py files.

**Comment by mrmundt** [comment]
In an effort to clean up old issues, we are moving some design discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
