### ISSUE TITLE
Review logic/expectations for management of named expressions

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#416]
Using Pyomo5 expressions, the named expression objects are the only sub-expressions that are mutable.  This form of mutability explicitly represents user expectations that these sub-expressions can change after being used to form an expression tree.

There are two contexts where the implication of this mutability are not clear:

1. Replacing a terms in an expression with a walker:  If we descend into a named expression and replace terms there, then is that named expression replaced in the original expression or preserved?

2. Cloning an expression:  When cloning an expression, when we clone a sub-expression that is a named expression, do we create separate clones for that expression object, or replace the named expression itself?  If the latter, then how do we manage those cloned named expressions in the model?

**Comment by mrmundt** [comment]
In an effort to clean up old issues, we are moving some design discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
