### ISSUE TITLE
Move preprocessing transformations into contrib?

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#419]
Two preprocessing transformations were added to `pyomo.core.plugins.transform.*` before we introduced `pyomo.contrib`: `zero_sum_propagator.py` and `bounds_to_vars.py`

Should we move these to `pyomo.contrib.preprocessing.plugins.*`? This would consolidate all of these similar transformations in one place.

**Comment by blnicho** [comment]
I think that they should be moved, keeping them all together makes them easier to find.
