### ISSUE TITLE
Support for threaded pyomo initialization

### ISSUE THREAD

**Issue by LukeDickenZynga** [Pyomo/pyomo#420]
Hey all,
We ran into an issue using pyomo in a multi-threaded context where the main thread listens for connections and spawns a pyomo solver to provide a response. The issue was:

>   File "/usr/local/lib64/python2.7/site-packages/pyomo/opt/base/solvers.py", line 608, in solve
>     _status = self._apply_solver()
>   File "/usr/local/lib64/python2.7/site-packages/pyomo/opt/solver/shellcmd.py", line 242, in _apply_solver
>     self._rc, self._log = self._execute_command(self._command)
>   File "/usr/local/lib64/python2.7/site-packages/pyomo/opt/solver/shellcmd.py", line 305, in _execute_command
>     tee   = self._tee
>   File "/usr/local/lib/python2.7/site-packages/pyutilib/subprocess/processmngr.py", line 525, in run_command
>     signal.signal(signal.SIGINT, verbose_signal_handler)
> ValueError: signal only works in main thread

After some debug, we fixed this locally by adding "define_signal_handlers=False" to the list of arguments passed to 'run' on line 300 of shellcmd.py, but there is probably a better (or at least more general) solve that actually detects the context and handles things appropriately dependent on that.

**Comment by blnicho** [comment]
Is this related to https://github.com/PyUtilib/pyutilib/issues/31?

**Comment by LukeDickenZynga** [comment]
Yep that looks like exactly the solve we needed! Thanks for pointing it out @blnicho :)

**Comment by blnicho** [comment]
Great, I'm going to close this then. As stated in the linked PyUtilib issue, the fix will make it into PyUtilib and a Pyomo release in the very near future.
