### ISSUE TITLE
unsupported operand type(s) for *: '_IndexedSetData' and 'SimpleSet'

### ISSUE THREAD

**Issue by Ringo-0** [Pyomo/pyomo#43]
Hi,

John told me it's probably a bug and I should open an issue here.
### in the model

    model.Dummy = Set(model.Jobs, within=model.Jobs)
    model.Cars = Set()

### in the dat-file

    ...
    set Dummy[A_E] := A_E B_E;
    ...
    set Cars := Car1 Car2 Car3;

Now  the following constraint wouldn't work:

    def JobOnlyOnce_rule(model,j):
        return sum(model.x[i,k] for (i,k) in model.Dummy[j]*model.Cars) <= 1
    model.JobOnlyOnce = Constraint(model.Jobs, rule=JobOnlyOnce_rule)

**Comment by jsiirola** [comment]
I can confirm that this is still failing on trunk.  Also, note that while
```
model.Dummy[j]*model.Cars
```
fails,
```
model.Cars*model.Dummy[j]
```
works correctly.  This needs to be fixed before 5.0.  I believe that the fix is a relatively straightforward refactoring of the `Set` hierarchy to match that used by `Var`, etc.

**Comment by whart222** [comment]
Given our timeline for the 5.0 release, I don't see this being completed for this release.
