### ISSUE TITLE
Coordinating conversion of external packages to Pyomo5 expressions

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#433]
We need to enumerate the packages that will be impacted by the change to the new expression system.

**Comment by qtothec** [comment]
Given that we are now on the Pyomo5 expression system by default, I think we can close this issue?

**Comment by jsiirola** [comment]
Agreed.  Pyomo5 expressions were merged 12 months ago and released 6 months ago.  We can close this issue.
