### ISSUE TITLE
Pyomo expression design issues

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#439]
The following design issues should be addressed after we merge the expr_dev branch:

- [x] Evaluate whether division expressions would be better than reciprocal expressions
- [ ] Review whether identify_components should use ctypes
- [x] Reorganize pyomo.core.expr and eliminate support for swapping in/out a new expression system.  (We can simply develop alternatives in a branch, so the 'current' module isn't needed.)  This reorganization should eliminate the inclusion of '_*' symbols from all modules.
- [ ] Review clone_expression, which is only used to expand connectors.  Is this logic needed?
- [x] Add a logical expression that is separate from non-logical expressions.
- [ ] Evaluate the known constants and as_numeric() logic.  These may not be needed now that we include numbers in expression trees.

**Comment by qtothec** [comment]
`clone_expression` has uses beyond just connector expansion, because of its `substitute` functionality (e.g. for a variable aggregator)

**Comment by carldlaird** [comment]
I suspect that this functionality ('substitute') is handled through a new API in the new expression system.

**Comment by blnicho** [comment]
The design issues above were related to the Pyomo5 expression system. We are now using the Pyomo6 expression system so this list of design issues is out-dated. I'm going to close this and we can open new issues for these design discussions as-needed.
