### ISSUE TITLE
Look at naming of methods in the expression walkers

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#451]
During a design discussion, it was brought up that the names of the "virtual" methods in the walkers was confusing and did not clearly indicate their purpose. A few names changes were discussed.

o	SimpleExpressionVisitor -> ExpressionVisitor
o	ExpressionValueVisitor -> ExpressionGatherVisitor
o	visit_and_maybe_descend
o	visit_or_descend 

Please comment on your choice of names, and we can look at renaming things in the API.

**Comment by qtothec** [comment]
When would `visit_or_descend` be used?

**Comment by whart222** [comment]
@qtothec This is the proposed name change for the walker API.

**Comment by qtothec** [comment]
@whart222 To clarify, I'm asking what exactly the purpose is that we're trying to convey. I wasn't intimately involved in the walker API development, so if you want to use me as a test case for what makes sense as a name for describing things, I'm offering myself up.

**Comment by mrmundt** [comment]
There was a new walker written, so this can be closed.
