### ISSUE TITLE
Resolving pyomo5 expected failures

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#455]
This issue documents discussions related to the expr_expected_failures branch.

**Comment by whart222** [comment]
@blnicho @ghackebeil I'm seeing test failures on my Mac laptop.  I'll confirm the differences with Travis.  Thx.

**Comment by whart222** [comment]
@ghackebeil @jwatsonnm I am regularly seeing the following error on my laptop, which doesn't show up on Travis:

> FAIL: test_init6 (pyomo.pysp.tests.unit.test_instancefactory.Test)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Users/wehart/home/src/pyomo/py36/src/pyomo/pyomo/pysp/tests/unit/test_instancefactory.py", line 314, in test_init6
>     pass
> AssertionError: TypeError not raised

I think that JP was able to replicate this on his laptop.  Yes?

**Comment by ghackebeil** [comment]
@whart222: Can you send me the exact output from running the code below?

```python
import pyomo.environ as aml
from pyomo.pysp.scenariotree.instance_factory import \
    ScenarioTreeInstanceFactory

print(dir(int))

model = aml.ConcreteModel()
ScenarioTreeInstanceFactory(model=model,
                            scenario_tree=int)
```

**Comment by ghackebeil** [comment]
@whart222: I fixed the issue that was causing test_init6 to fail on the branch that reconfigured Travis to use docker images. It is now merged into master.

**Comment by jsiirola** [comment]
I believe that with the merge of #514 that everything is working.  If @blnicho, @whart222, and @ghackebeil agree, then I think this can be closed.

**Comment by blnicho** [comment]
I agree
