### ISSUE TITLE
Subclassing Param

### ISSUE THREAD

**Issue by daviskirk** [Pyomo/pyomo#458]
I am trying to extend some pyomo components and are having trouble subclassing `Param`.  Subclassing the `Var` class seems to be straightforward but the `Param` class  seems to have hardcoded a few class names (`Param` and `SimpleParam`) which makes it extremely hard to get consistent behavior out of subclasses.

At the moment, my solutions would be to copy the entire `Param` and `SimpleParam` classes and make the modifications accordingly.

Is there a nicer or more established way of doing this?

**Comment by jsiirola** [comment]
Are you working against master?  There was a pretty significant refactor of IndexedComponent several months age that should make things easier. For example, I don’t see any explicit uses of SimpleParam that would complicate subclassing. That said, I just looked at Param and it didn’t adopt the _ComponentDataClass idiom to make subclassing indexed components easier. That is something that we can add pretty quickly.

**Comment by mrmundt** [comment]
Hi there, @daviskirk - has this question/request been satisfied?

**Comment by mrmundt** [comment]
Hello, @daviskirk . The GitHub Issues are intended for bug reports and enhancement/feature requests. For help or use questions, we refer you to review our documentation for [ways to get help](https://github.com/Pyomo/pyomo#getting-help). If this is still an issue for you, please post your question on one of the preferred forums and we can engage with you there.
