### ISSUE TITLE
Different results when using Pyomo on master vs. IDAES branch. 

### ISSUE THREAD

**Issue by jghouse88** [Pyomo/pyomo#465]
A variable that is calculated is off by a factor of 1000 when using Pyomo installed from the main branch vs. Pyomo installed from the IDAES branch. To run the sample problem, please follow the steps below:

1. Download this branch: https://github.com/IDAES/idaes/tree/pyomo_version_error
2. Move to directory (idaes/contrib/properties/iapws95/ ) and run the following to compile the IAPWS prop pack:
      (i) make
3. Move to directory (examples/contrib/properties/iapws95/) and run the flash4.py file. 

Depending on the Pyomo version installed (master vs. IDAES), you will notice a difference in the value of the variable "enth_mol" in the "prop" block. If using the Pyomo - IDAES version this value will be 20958 but if using Pyomo - master branch version, this value will be 20.958.  The correct value is 20958 as obtained with the IDAES branch. 

John Eslick was seeing some similar errors with other simulations. Let us know if you need more information or help in running the examples.

**Comment by jsiirola** [comment]
@jghouse88: To confirm, which hash (commit) on the master branch are you testing?

**Comment by jghouse88** [comment]
@jsiirola It was the latest commit 8002169 that was merged 22 hours ago. For the IDAES branch, it is  f8e1efa merged 8 days ago.

**Comment by blnicho** [comment]
@jghouse88 not sure this matters but just so we can be sure we're testing the same thing, which version of Python are you using?

**Comment by jsiirola** [comment]
@whart222 can you take a look at this and make sure it is not related to expr_dev?

**Comment by blnicho** [comment]
@jghouse88 a bug in the expression system was fixed in #471. Could you update your Pyomo checkout and check if this fixed your issue too?

**Comment by jghouse88** [comment]
@blnicho Yes, I just checked and it did fix the error. Thanks!

**Comment by whart222** [comment]
FYI, I manually confirmed that this fixed the reported issue in IDAES.
