### ISSUE TITLE
Resolving discrepancy in Pyomo expressions

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#466]
I recently noted some discrepancies in how Pyomo evaluates expressions.  The following script illustrates these discrepancies:

```
from pyomo.environ import *

m = ConcreteModel()
m.v = Var()

e = m.v
try:
    print(e())
    print("HERE - Prints 'None'")
except:
    print("NOT HERE")
try:
    print(value(e))
    print("NOT HERE")
except:
    print("HERE - Raises an exception;  no message printed")

e = m.v + 1
try:
    print(e())
    print("NOT HERE")
except:
    print("HERE - Raises an exception;  no message printed")
try:
    print(value(e))
    print("NOT HERE")
except:
    print("HERE - Raises an exception;  prints an error message")
```

We should evaluate these discrepancies.  I'm inclined to define a consistent approach to managing these errors.

**Comment by carldlaird** [comment]
My initial thought is that they should be consistent. However, if they should be identical, then why have both approaches, and maybe we consider deprecating one?

On the other hand, if they intended to be different (e.g., fewer checks for e() than value(e)), then maybe consistency is not critical?

**Comment by carldlaird** [comment]
My initial thought is that they should be consistent. However, if they should be identical, then why have both approaches, and maybe we consider deprecating the `__call__` approach?

On the other hand, if they intended to be different (e.g., fewer checks for e() than value(e)), then maybe consistency is not critical, and we should just document the differences?

**Comment by michaelbynum** [comment]
I think one important distinction is that the value function can handle python ints and floats. However, why does the value function use as_numeric rather than __call__ under the hood?

**Comment by whart222** [comment]
@carldlaird I'm OK with __call__ and value() having different behavior.  For example, if value() logs errors.  But even that consistency isn't supported now.

**Comment by mrmundt** [comment]
There has been consistency invoked in the error messages across these different calls.
