### ISSUE TITLE
Clarify pow test names

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#473]
PR #471 introduced a number of new tests into `pyomo/repn/tests/test_standard.py` numbered `test_pow1` through `test_pow6`.  These test should be renamed to provide documentation of what they are testing.  For example, `test_pow_var_param` or `test_pow_fixed_var_fixed_var`.

**Comment by whart222** [comment]
I think that this is a broader issue.  If I had to focus on test documentation and semantics, this isn't where I'd start.  More generally, before embarking on this activity, I think we should document best practices for testing documentation.

**Comment by jsiirola** [comment]
I agree, but in the mean time, can you do a quick PR to provide more informative names for those 6 tests before we collectively forget the motivation for 6 "pow" tests.

We can later open an issue to discuss "best practices" elsewhere.

**Comment by whart222** [comment]
No.  This is inconsequential w.r.t. the operation of Pyomo, and this is a *very* low priority relative to every thing else on my TODO list.

**Comment by mrmundt** [comment]
@jsiirola - I made an internal issue on our tracker board to clean up and standardize test naming/documentation.
