### ISSUE TITLE
nan's in Pyomo expressions

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#477]
It is possible to get NaNs in Pyomo expressions and, at least in some cases, these get sent to the solver with difficult to interpret errors - maybe we should capture NaNs in Pyomo and give a better error message.

**Comment by whart222** [comment]
Can you give an example?  I agree that we need to manage these.

**Comment by blnicho** [comment]
NaN handling was recently improved in #2930 and since this issue doesn't include a minimal example recreating the issue I think this can be closed.
