### ISSUE TITLE
Clarifying semantics of Pyomo relational expressions

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#478]
@ghackebeil recently noted that the semantics of Pyomo relational expressions seemed to have changed.  I think he may be right, but I'd like to discuss that here and confirm how we should document this.

**Comment by ghackebeil** [comment]
Here is the behavior we need to discuss:
```python
>>> import pyomo.kernel as pmo
>>> m = pmo.block()
>>> m.x = pmo.variable()
>>> m.x.value = 1
>>> bool(m.x == 1)
True
>>> m.x.value = 0
>>> bool(m.x == 1)
False
```
To summarize, equality expressions now behave in a natural way (maybe they always have). I had assumed this also meant inequality expressions now behaved this way, but I just checked, and that is wrong. That is, `bool(m.x <= 1)` triggers a warning the first time, and triggers an exception the second time.

Should we make the behavior of equality expressions consistent with the current behavior of inequality expressions (i.e., raise an exception when cast to bool)? Or, once chained inequality support is completely dropped, should we make inequality expression behave like equality expressions.

**Comment by michaelbynum** [comment]
I think ``bool(m.x == 1)`` should raise an error. My primary motivation is that many users try to use if statements like this in constraint rules.

**Comment by michaelbynum** [comment]
At the developer meeting we seemed to all agree that ``bool(m.x == 1)`` should raise either a warning or an expression.

**Comment by whart222** [comment]
What's the rationale for raising a warning or exception?

**Comment by qtothec** [comment]
```
def constraint_rule(m):
    if m.x == 1:
        return m.y >= 1
    else:
        return m.y <= 1
```
This is why

**Comment by jsiirola** [comment]
The problem is that users frequently write things like:
```
model.production = Var()

@model.Constraint()
def cost_model(m):
    if m.production >= m.cutoff:
        return m.cost = m.production * m.lowCostPerMW
    else:
        return m.cost = m.production * m.highCostPerMW
```
or
```
model.x = Var()

def sinc(x)
    if x == 0:
        return 1
    else:
        return pyomo.core.sin(x*numpy.pi)/(x*numpy.pi)

@model.Constraint()
def con(m):
    return sinc(model.x) >= 0.5
```
If the relational expressions silently return the correct `True` / `False` value, then the user thinks their function is returning the "right" expression -- which it is not.  We want to warn users that using potentially variable expressions in a Boolean context is probably not what they want because this is an AML and not a callback/function-based model.  If they really want to get the current logical value of a relational expression like `m.x >= 0` without a warning or error, then they can do either `value(m.x) >= 0` or `value(m.x >= 0)`.

**Comment by jsiirola** [comment]
I believe that two PRs have resolved this issue:
- #1840: ranged (chained) inequality support has been removed fro Pyomo
- #1954: casting all relational expressions to `bool` now either return the correct value (if they are constant), or raise an exception.
