### ISSUE TITLE
Blank space in project path leads to wrong file type in CPLEX

### ISSUE THREAD

**Issue by phaabe** [Pyomo/pyomo#480]
When path to python file is '/Users/XXX/Desktop/…/Pyomo Spam/eggs.py' 
(blank space after …/Pyomo)

CPLEX will throw an error containing:

`Logfile '/Users/XXX/Desktop/…/Pyomo' open.
CPLEX> Cannot interpret file type.`

when path is  '/Users/XXX/Desktop/…/Pyomo_Spam/eggs.py'  it works.

But when path to python file is '/Users/XXX/Desktop/…/Pyomo Spam/e g g s.py' so when the file itself contains the spacing, no problems occur.

**Comment by qtothec** [comment]
@phaabe This looks like a bug on the CPLEX side, not parsing a space in the file name given to it by Pyomo properly. Are you sure this should be a Pyomo bug report?

Separately, I tend to avoid using spaces in programming contexts: https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names

**Comment by phaabe** [comment]
I agree, it’s more likely to be a bug in CPLEX. I also agree, that white spaces should be avoided anyway. 

Maybe it would be useful, pyomo triggers a warning. It took me a while to figure that out since blank spaces in the file name didn’t cause the type error. Just the path is problematic. 

What do you think?

**Comment by qtothec** [comment]
What was the original error message? We want to consider the balance between providing helpful error messages to the user and adding to the maintenance burden and complexity of this code base.

**Comment by ghackebeil** [comment]
Is it possible we just need to add quotes around the file name inside the CPLEX run file that we create? Can someone try doing this manually to see if that fixes the problem?

**Comment by phaabe** [comment]
@qtothec thing is, there was no error message. [Have a look(PDF of my jupyter notebook)](https://drive.google.com/open?id=1SmbrXw9vMcVIf5lrOvHQnn3EWYReA2GM)

As you can see, all that what happens:
- solver doesn't print the solution section
- no new values in the model

**Comment by ghackebeil** [comment]
Actually, this is in master now. Feel free to test that and reopen this issue if things are still broken.
