### ISSUE TITLE
Discussion: Refactoring the new expr folder in Pyomo

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#483]
Discussion: Maybe we should consider changing the name of current.py. Should we also consider partitioning expr_pyomo5.py into smaller parts?

**Comment by whart222** [comment]
Yep to both.  @jsiirola suggested that we eliminate 'current' altogether, so I think it's worth doing that.

**Comment by blnicho** [comment]
This was completed in #888
