### ISSUE TITLE
Discussion: Document development procedure associated with the cython files in expr

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#484]
We should discuss the development procedures associated with the cython files in expr. When / how are they rebuilt, and what are the nuances with setup.py develop/install, etc.

This should be documented in the expr directory, or in readthedocs.

**Comment by whart222** [comment]
Note that this issue is related to #415

**Comment by mrmundt** [comment]
@jsiirola - There is an internal issue already in existence on my tracker board ("Cythonization: The Good, The Bad, The Ugly") to address broader questions about the benefit of cythonization. I have linked this issue there.
