### ISSUE TITLE
Reorganize Sphinx documentation

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#492]
Our Sphinx documentation needs a significant reorganization. I put together a tentative outline which I will link to this issue and I welcome feedback from the team.

**Comment by blnicho** [comment]
The proposed outline can be found in a temporary wiki [here](https://github.com/Pyomo/pyomo/wiki/Proposed-Sphinx-Documentation-Outline).

**Comment by qtothec** [comment]
Any thoughts on having a section that's "My model has a problem, what do I do?"

**Comment by carldlaird** [comment]
The old outline can be found in the wiki [here](https://github.com/Pyomo/pyomo/wiki/Z-Old-Sphinx-Documentation-Outline). I added this to make sure we had a record of the existing outline to make sure we didn't lose anything as we reorganize.

**Comment by michaelbynum** [comment]
Qi,

Isn’t this the purpose of the forum? Although I agree that it might be valuable to condense answers to the most common questions here.

Michael

On May 17, 2018, at 5:53 PM, Qi Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


Any thoughts on having a section that's "My model has a problem, what do I do?"

**Comment by qtothec** [comment]
@michaelbynum Yes. Let me clarify: we don't know which place a user will look first when trying to solve their problem, so we should have appropriate "funnels" to direct them towards the right resources. I think, as you said, some of the most common questions could be put there, and maybe some of the most common error messages. I'm not advocating for an exhaustive list.

**Comment by carldlaird** [comment]
This would be a good spot to put helpful things like "tee=True" to see if the solver is having trouble, report timing, pprint or display to check the expanded model, try a small example first, print your data to make sure it looks like what you expect, etc....

**Comment by blnicho** [comment]
I updated the outline to include a section for getting help
