### ISSUE TITLE
Implementation of disjunctive variable bounds

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#500]
@jsiirola We had earlier talked about using the following paradigm.
```
disj.disj_map = ComponentMap()
   var --> (lb_Param, ub_Param, lb_Constr_ref, ub_Constr_ref)
disj.disj_val = Param(Any, mutable=True)
disj.disj_constr = Constraint(Any)
```
There's a problem with doing this. For some of them, the value of `lb_Param` is going to be `None`. Having a lot of `m.x >= None` constraints in the model is probably not ideal. I think it might make more sense to separate out the computation/manipulation of the values from the insertion of constraints to explicitly enforce them.

**Comment by jsiirola** [comment]
@qtothec: I see your point.  That said, I am not sure that the two steps are conceptually separate transformations.  I still think you want to implement this as a single transformation, even if the analysis is done in two passes (one to compute and one to implement).

Separately, is there a reason this is a separate issue and not just a discussion on #481?  Unless you object, we should close this issue and move the discussion there.

**Comment by qtothec** [comment]
Sure, let's move the discussion.
