### ISSUE TITLE
AttributeError: type object 'ConfigBlock' has no attribute '_all_slots'

### ISSUE THREAD

**Issue by amirhoseinsh** [Pyomo/pyomo#505]
hi i use `pip` for install pyomo and i get this error:

  File "/usr/local/lib/python2.7/dist-packages/pyomo/pysp/util/config.py", line 151, in __setattr__
    if name in ConfigBlock._all_slots:

AttributeError: type object 'ConfigBlock' has no attribute '_all_slots'

I need help .

**Comment by amirhoseinsh** [comment]
No it doesn't work for me! all things are in last version

**Comment by jsiirola** [comment]
@qtothec is correct: you almost certainly have an old version of pyutilib somewhere on your system.

When are you getting this error: with the pip install, or are you running a command after installing?  Please provide the full command and the full stack trace.

For debugging, I would start with:
```
% pip uninstall pyomo
% pip uninstall pyutilib
% python -c "import pyutilib"
```
If that doesn't result in an ImportError exception, you have another copy of pyutilib lingering around.  You can try running "`pip uninstall pyutilib`" again to see if it removes it. Then reinstall pyomo and see if that clears things up.

**Comment by amirhoseinsh** [comment]
in the `pip install pyomo` I don't get the error, after that when I use pyomo I get this error.

**Comment by amirhoseinsh** [comment]
you're right I have two `pyutilib`, I do that and my error change to this : 
 File "/usr/local/lib/python2.7/dist-packages/pyomo/pysp/util/config.py", line 2007, in <module>
    if pyutilib.misc.config.argparse_is_available:

AttributeError: 'module' object has no attribute 'config'

**Comment by jsiirola** [comment]
This looks like you may have a *very* old copy of pyutilib installed.  You can try using [pyomo-uninstall.py](https://software.sandia.gov/trac/pyomo/downloader/download/file/79) to clean up your system. Running it more than once wouldn't hurt, either.

**Comment by amirhoseinsh** [comment]
my problem solved, I re install all packages and it worked, thanks

**Comment by jsiirola** [comment]
User problem solved. No further action needed.

**Comment by jsiirola** [comment]
User problem solved. No further action needed.

**Comment by jsiirola** [comment]
Resolved.
