### ISSUE TITLE
pyomo.dae transformations ignore Piecewise blocks

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#52]
The issue should be explained near the end of the following thread:
https://groups.google.com/forum/#!topic/pyomo-forum/Q_60FKCXqkw

It looks like Piecewise does not get re-constructed over the expanded `ContinuousSet` .

**Comment by ghackebeil** [comment]
@jsiirola, @blnicho: I dug into the dae code a little and noticed that only components of type Var, Constraint, and Expression get expanded with the new index elements. In order for this to work with Piecewise (or other Blocks) it would have to include the Block type (see `update_contset_indexed_component` in pyomo/dae/misc.py)

In the short term, that function should probably be updated to raise an exception when it encounters types it does not handle. It could probably also alert users that a workaround is to add certain model components after applying the dae transformation.

**Comment by jsiirola** [comment]
Fixed by #111
