### ISSUE TITLE
Move pyomo.core.kernel.util

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#521]
This is the only part of pyomo.core.kernel that imports from pyomo.core.base.  This module defines the pprint() function, which probably should be generalized to include other parts of pyomo.  Hence, I'd recommend moving this to pyomo.common.

**Comment by jsiirola** [comment]
I am ok moving it, but not to common - common should not import any other part of Pyomo.

**Comment by ghackebeil** [comment]
It would take a lot to generalize that function until we get some common base class structure between the two interfaces. I would recommend we move it to the pyomo.kernel module. This is where all delayed ctype assignments take place that "break" the linkage between core.kernel and core.base.
