### ISSUE TITLE
Improve Time to expand Connectors with TransformationFactory

### ISSUE THREAD

**Issue by sbruche** [Pyomo/pyomo#523]
The time to expand the connectors increases significantly if a large number of connectors needs to be considered (e.g. by using many time steps).

The time for expansion is increasing quadratically and not linearly as expected (see attached pdf for a plot [source-connector-sink.pdf](https://github.com/Pyomo/pyomo/files/2057641/source-connector-sink.pdf)).

For the discussion in the Google Group see: https://groups.google.com/forum/#!topic/pyomo-forum/AQhhJPbN4_c

**Comment by qtothec** [comment]
@gseastream Does the new `Port/Arc` expander address this issue?

**Comment by jsiirola** [comment]
@gseastream: did you also apply those patches to the original Connector/ConnectorExpander code?  I realize the intent is to deprecate Connector / ConnectorExpander in favor of Port/Arc, but we should still patch that code to get away from the quatratic runtime of the original expander...

**Comment by gseastream** [comment]
I can do that

**Comment by blnicho** [comment]
Fixed in #583
