### ISSUE TITLE
GAMS solver initial expression evaluation checking

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#527]
When GAMS is run on a model, it requires that all expressions evaluate at their initial values. So, for example, if you don't warmstart a variable `x` and then you have a constraint that contains `log(x)`, then GAMS will have an `Execution error` because `x` is initially 0 by default and GAMS can't evaluate `log(0)`. The same is true for division by zero. To aid in this type of error, if GAMS fails a solve, then the GAMS solver will proceed to try to evaluate every expression in the model at their initial or default values, and throw a helpful warning if it finds an expression it thinks GAMS failed on. The current code to do this is as follows:

```python
try:
    value(expr)
except ValueError:
    logger.warning("While evaluating model.%s's expression, GAMS solver "
                   "encountered an error.\nGAMS requires that all "
                   "equations and expressions evaluate at initial values.\n"
                   "Ensure variable values do not violate any domains, "
                   "and use the warmstart=True keyword to solve()." % name)
    if solver_io == 'shell':
        # For shell, there is no previous exception to worry about
        # overwriting, so raise the ValueError.
        # But for direct, the GamsExceptionExecution will be raised.
        raise
```

This works for `log` and `log10`, since errors in evaluating those raise `ValueError`, but I just found out for expressions that try to divide by 0, it raises `ZeroDivisionError`, so it was not caught and the helpful warning was not sent. This will be a simple fix, but I wanted to ask, should we change the `except` to catch any error that arises from `value(expr)` (i.e. put nothing after `except`)? Or change it to include exactly `ValueError` and `ZeroDivisionError`? I wasn't sure if we wanted to anticipate more situations like this where a different kind of error we weren't expecting showed up, but I also didn't want to stomp out some other error that actually means something else went wrong not having to do with domain issues.

**Comment by qtothec** [comment]
I would suggest having specific `except`s where possible. You don't want to inadvertently `except` something that you didn't mean to. We can add more cases as they come up.
