### ISSUE TITLE
Pyomo should be able to load external functions from .so file in LD_LIBRARY_PATH 

### ISSUE THREAD

**Issue by shreddd** [Pyomo/pyomo#53]
Currently pyomo only loads external function property definitions from a phys_prop.so file in the current directory. It should search LD_LIBRARY_PATH (or equivalent) location for this file.

**Comment by blnicho** [comment]
@jsiirola you've done a lot of work on external functions since this issue was opened. Has this been resolved?

**Comment by jsiirola** [comment]
No.  To my knowledge, no work has been done on this.

The trick is that in the usual mode of operation, Pyomo is not responsible for loading the library.  The library is loaded by the ASL (i.e., is compiled into the solver), and we don't have control over how the ASL located the library.  That said, I think we *can* mock this up by attempting to convert relative library path to an absolute path (by searching LD_LIBRARY_PATH) before generating the NL file.  The open design question is *when* to do that expansion: when the external function is declared or when the NL file is generated.  I think the former will produce more consistent (and understandable to a user) behavior.  However, it could cause problems in parallel environments where the model is generated on one node, but solved somewhere else (the LD_LIBRARY_PATH would be checked locally and not remotely).

**Comment by mrmundt** [comment]
@jsiirola @blnicho - It's been a few years. Any idea if work has been done to resolve this?
