### ISSUE TITLE
Simulator fails when passed a discretized model

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#531]
This is caused by the Simulator identifying DerivativeVar components based on their ctype which is reclassified to Var after applying a discretization.

@jsimkoff is working on a bug fix

**Comment by ksbeattie** [comment]
@blnicho any news on what the alternative fix for this will be (as mentioned in the closed PR #545)?

**Comment by blnicho** [comment]
@ksbeattie, I have this fixed on a local branch I just haven't had time to fully test it and write tests for it yet.
