### ISSUE TITLE
Double builds on travis and appveyor for branches with a PR

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#532]
For both Travis and AppVeyor, we currently get 2 builds of the same thing when commits are pushed to a branch of the main repo that also has a PR, since we a get a build for both the branch and for the PR. This is particularly painful for AppVeyor since it takes so long anyway. I found different solutions to both.

**Travis** ([reference](https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches))
Travis does not have a functionality to specifically skip branch builds when a PR is open for that branch, so the best option would be to skip all branches entirely, except for master. Unless, do we care to have automatic builds on branches that do not have PR's open for them? My thinking is, if one cares about testing for a branch, then it should be close enough to merging that a PR should be open for it anyway, so testing is already done for it. Restricting tests to just master is done by adding the following to `.travis.yml`:

```
branches:
  only:
  - master
```

I believe a specific branch could even add their name to their version of `.travis.yml` in order to get automatic tests run for it, if desired (or we could at least add it to master's version of the file, whatever the effective way to do that is).

**AppVeyor**
AppVeyor does have a functionality to specifically skip tests of branches with PR's open ([reference](https://github.com/appveyor/ci/issues/882)). This is done by adding the following to `.appveyor.yml`:

```
skip_branch_with_pr: true
```

However, we could also decide to skip branches except master entirely, as is the option we may pursue for Travis. This would save even more time, which again is pretty important to AppVeyor since it's so slow. This is done with by adding this to `.appveyor.yml` ([reference](https://www.appveyor.com/docs/branches/#white--and-blacklisting)):

```
branches:
  only:
    - master
```

Thoughts on all this?

**Comment by whart222** [comment]
I like having the testing on branches.  But the only reason I don't create a PR right away is to avoid this duplicate testing.  I'm OK disabling testing on branches as long as we agree that it's fine to create PRs right away.

**Comment by gseastream** [comment]
@jsiirola Do you have any thoughts on this issue and/or @whart222's comment?
