### ISSUE TITLE
Obtain column names from `cursor.description()` in sql query

### ISSUE THREAD

**Issue by jotaigna** [Pyomo/pyomo#537]
Dear Pyomo team:

I came across legacy issue [#4480](https://software.sandia.gov/trac/pyomo/ticket/4480) and I would like to ask whether it is possible to "revive" it. I have tested and had success with the suggestion proposed in the legacy ticket of removing the code that extracts column names from the data file query, or fetches them from the database with a `SELECT *` type statement. I have removed that code and replaced it thus with a statement that obtains column names from the cursor. The portion of the code in question in `core/plugins/data/db_read.py` (for Pyomo 5.5.0) reads as follows:
```python
def read(self):
        #
        # Get the table from the database
        #
        if self.db is None:
            return
        cursor = self.db.cursor()
        tmp = []
        if self.options.query is None:
            if self.options.table is None:
                raise IOError("Must specify 'query' or 'table' option!")
            self.options.query = 'SELECT * FROM %s' % self.options.table
        elif self.options.query[0] in ("'", '"'):
            self.options.query = self.options.query[1:-1]
        cursor.execute(self.options.query)
        try:
            rows = cursor.fetchall()
            for col in cursor.description:
                tmp.append(col[0])
            tmp=[tmp]
        except: # subsequent code remains the same in db_read.py
```

The reason for this request is that I do not have control over the name of the columns in the database I need to access, and renaming sets and variables in pyomo to match results in code that is less readable.

In fact when using pyomo with the modified functionality as above, 
I am able to simply put an alias on all the columns I need. 
For example: a query to query for the value of a parameter `P` that is indexed over 3 sets `A`. `B` and `C` would read:
```sql
SELECT database_column_name1 as A, database_column_name2 as B, 
database_column_name3 as C,database_column_name4 as P
FROM dabatase_table
WHERE ... 
```
 
Best regards

**Comment by blnicho** [comment]
@jotaigna if you have a solution to the legacy issue you mentioned, we invite you to open a pull request with your code changes and the Pyomo team will review it and get it merged in.

**Comment by jotaigna** [comment]
Thank you. Will do. Just a quick question: do I need to fork pyomo and push a branch or can i push a branch to the pyomo repository directly?

**Comment by michaelbynum** [comment]
You should fork pyomo, but I don’t think you need to create a branch. You can make your changes in master of your fork and then submit a pull request.

Michael

On Jun 4, 2018, at 8:07 PM, jotaigna <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you. Will do. Just a quick question: do I need to fork pyomo and push a branch or can i push a branch to the pyomo repository directly?
