### ISSUE TITLE
AttributeError when using glpk with mipgap option

### ISSUE THREAD

**Issue by jrlooker** [Pyomo/pyomo#54]
Hi,

After passing the mipgap option to glpk (and glpk terminating with message "RELATIVE MIP GAP TOLERANCE REACHED; SEARCH TERMINATED"), the following error is produced: 

 File "/Users/username/anaconda/lib/python3.5/site-packages/pyomo/solvers/plugins/solvers/GLPK.py", line 481, in _process_soln_mip
    solv.termination_condition = TerminationCondition.feasible
AttributeError: 'Enum' object has no attribute 'feasible'

Is this a bug? Can you suggest a solution?

Thanks,
Jason

**Comment by ghackebeil** [comment]
This is indeed a bug. I suppose the only fix is to add a 'feasible' value to the TerminationCondition enum.

**Comment by ghackebeil** [comment]
Fixed in cc1ddee591e0efa099102bb08c4fabb34a4984fe (which references the wrong ticket).

**Comment by jrlooker** [comment]
Great! Thanks, Gabriel.
