### ISSUE TITLE
AttributeError solving BlockData objects

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#550]
I have this model:
```
from pyomo.environ import *

opt = SolverFactory('gurobi')

def give_me_a_block():
    m = ConcreteModel()
    m.someVar = Var(within=Binary)
    m.someCons = Constraint(expr=m.someVar >= 1)
    m.obj = Objective(expr=m.someVar)

    return m

m = ConcreteModel()

m.Scenarios = Set(initialize=['scen1','scen2'])
@m.Block(m.Scenarios)
def ScenarioSubproblems(m, s):
    model = give_me_a_block()
    return model

# solve my subproblems
for s in m.Scenarios:
    opt.solve(m.ScenarioSubproblems[s])
```
I get this traceback when it tries to solve the first subproblem:
```
Traceback (most recent call last):
  File "minimaler_example.py", line 23, in <module>
    opt.solve(m.ScenarioSubproblems[s])
  File "/home/esjohn/src/pyomo/pyomo/opt/base/solvers.py", line 659, in solve
    default_variable_value=self._default_variable_value)
  File "/home/esjohn/src/pyomo/pyomo/core/base/PyomoModel.py", line 282, in load_from
    default_variable_value=default_variable_value)
  File "/home/esjohn/src/pyomo/pyomo/core/base/PyomoModel.py", line 450, in add_solution
    for vdata in instance.component_data_objects(Var):
AttributeError: 'NoneType' object has no attribute 'component_data_objects'
```
This is on master. But this code ran on my Windows machine with Pyomo 5.5 (and Python 2.7). So should this be allowed? And if not, what should the error be?

**Comment by qtothec** [comment]
On my machine (Windows, master https://github.com/Pyomo/pyomo/commit/7417b6f2b513de052e2b3df1325d43e6b092ae84, python 3.6) the first subproblem appears to solve, but the second gives the same error message.

**Comment by michaelbynum** [comment]
I think what you want is something like:

def build_me_a_block(b):
    b.someVar = Var(within=Binary)
    b.someCons = Constraint(expr=b.someVar >= 1)
    b.obj = Objective(expr=b.someVar)

m = ConcreteModel()

m.Scenarios = Set(initialize=[‘scen1’, ‘scen2’])
@m.Block(m.Scenarios)
Def ScenarioSubproblems(b, s):
    Build_me_a_block(b)

When you create an indexed block, the individual blocks are automatically created. The blocks themselves are passed to your rule, not the top level model.

Michael

On Jun 6, 2018, at 4:13 PM, Emma Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


I have this model:

from pyomo.environ import *

opt = SolverFactory('gurobi')

def give_me_a_block():
    m = ConcreteModel()
    m.someVar = Var(within=Binary)
    m.someCons = Constraint(expr=m.someVar >= 1)
    m.obj = Objective(expr=m.someVar)

    return m

m = ConcreteModel()

m.Scenarios = Set(initialize=['scen1','scen2'])
@m.Block(m.Scenarios)
def ScenarioSubproblems(m, s):
    model = give_me_a_block()
    return model

# solve my subproblems
for s in m.Scenarios:
    opt.solve(m.ScenarioSubproblems[s])


I get this traceback when it tries to solve the first subproblem:

Traceback (most recent call last):
  File "minimaler_example.py", line 23, in <module>
    opt.solve(m.ScenarioSubproblems[s])
  File "/home/esjohn/src/pyomo/pyomo/opt/base/solvers.py", line 659, in solve
    default_variable_value=self._default_variable_value)
  File "/home/esjohn/src/pyomo/pyomo/core/base/PyomoModel.py", line 282, in load_from
    default_variable_value=default_variable_value)
  File "/home/esjohn/src/pyomo/pyomo/core/base/PyomoModel.py", line 450, in add_solution
    for vdata in instance.component_data_objects(Var):
AttributeError: 'NoneType' object has no attribute 'component_data_objects'


This is on master. But this code ran on my Windows machine with Pyomo 5.5 (and Python 2.7). So should this be allowed? And if not, what should the error be?

**Comment by michaelbynum** [comment]
Also,

I cannot reproduce this error on master. What version of Pyomo are you using?

Michael

On Jun 6, 2018, at 5:06 PM, Bynum, Michael Lee <mlbynum@sandia.gov<mailto:mlbynum@sandia.gov>> wrote:

I think what you want is something like:

def build_me_a_block(b):
    b.someVar = Var(within=Binary)
    b.someCons = Constraint(expr=b.someVar >= 1)
    b.obj = Objective(expr=b.someVar)

m = ConcreteModel()

m.Scenarios = Set(initialize=[‘scen1’, ‘scen2’])
@m.Block(m.Scenarios)
Def ScenarioSubproblems(b, s):
    Build_me_a_block(b)

When you create an indexed block, the individual blocks are automatically created. The blocks themselves are passed to your rule, not the top level model.

Michael

On Jun 6, 2018, at 4:13 PM, Emma Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


I have this model:

from pyomo.environ import *

opt = SolverFactory('gurobi')

def give_me_a_block():
    m = ConcreteModel()
    m.someVar = Var(within=Binary)
    m.someCons = Constraint(expr=m.someVar >= 1)
    m.obj = Objective(expr=m.someVar)

    return m

m = ConcreteModel()

m.Scenarios = Set(initialize=['scen1','scen2'])
@m.Block(m.Scenarios)
def ScenarioSubproblems(m, s):
    model = give_me_a_block()
    return model

# solve my subproblems
for s in m.Scenarios:
    opt.solve(m.ScenarioSubproblems[s])


I get this traceback when it tries to solve the first subproblem:

Traceback (most recent call last):
  File "minimaler_example.py", line 23, in <module>
    opt.solve(m.ScenarioSubproblems[s])
  File "/home/esjohn/src/pyomo/pyomo/opt/base/solvers.py", line 659, in solve
    default_variable_value=self._default_variable_value)
  File "/home/esjohn/src/pyomo/pyomo/core/base/PyomoModel.py", line 282, in load_from
    default_variable_value=default_variable_value)
  File "/home/esjohn/src/pyomo/pyomo/core/base/PyomoModel.py", line 450, in add_solution
    for vdata in instance.component_data_objects(Var):
AttributeError: 'NoneType' object has no attribute 'component_data_objects'


This is on master. But this code ran on my Windows machine with Pyomo 5.5 (and Python 2.7). So should this be allowed? And if not, what should the error be?

**Comment by emma58** [comment]
I'm getting it on master. I'm wondering if maybe there is a difference across platforms though? Because it does run on Windows with Pyomo 5.5. (I'm getting the error with linux.)

Also, your suggestion makes sense, maybe more sense than what I was trying. But it still seems odd to me that with my previous strategy I can create a model that *looks* like what I want, but I can't solve it in the same way.

**Comment by emma58** [comment]
Sorry for the delay... So it seems windows is always alright, and linux is not:

Windows, Pyomo 5.5 - works 
Windows, Pyomo master - works 
Linux, Pyomo 5.5 - Error on the first subproblem solve
Linux, Pyomo master - Error on first subproblem solve

**Comment by blnicho** [comment]
Just checked if this is still an issue on master and I'm intermittently seeing the error @emma58 originally reported when running on Linux with Python 3.6. If I repeatedly run the posted script it works with no errors half of the time and throws the AttributeError half of the time.

**Comment by blnicho** [comment]
It looks like this has been resolved. I'm no longer seeing intermittent errors on Linux.
