### ISSUE TITLE
Proposal: Anonymous Block Components

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#555]
**Summary:**

Allow adding components to a block that do not have a name (thereby avoiding potential name clashes). This might look something like
```python
x = Var()
model.add_component(x, name=None)
model.del_component(x)
```

Note that it is up to the user to keep an external reference to an anonymous component. That is, an anonymous component cannot be obtained through an attribute access on the block. It can, however,  be removed by passing it into `block.del_component`, which is not itself new functionality. Finally, anonymous components will be included in the general component iterators on block so that they are seen as part of the model by any solver plugin (`block.component_data_objects`, etc.).

**Motivation**

In PySP and other sub-packages, we frequently have the need to add components to a user-provided model or block (and then later remove them). When doing so, it is important to use names that do not clash with existing block attributes.

**Current Approach:**

Generate a unique name. Historically, we have done things like
```python
setattr(model, '.some_name')
```
Note the '.' at the beginning of the string. This is important as it is an attribute on the model that can only be accessed using `gettattr`. That is, the following does not work:
```python
model..some_name
```
This vastly lowers the chances of a name conflict because users would be very unlikely to do this, but it is not full proof (and we also might no longer allow it). There are, of course,  are other ways to create a unique name, but the proposed "anonymous" approach seems cleaner.

**Additional Use Cases**

- Make variables declared on deactivated Disjunct blocks appear as variables on the model (without modification of the writers to collect new variables within expressions on the fly). That could be accomplished by having the GDP transformation add all variables declared on Disjuncts as anonymous components on the top-level model. It would also make transformed GDP models compatible with transformations that do not scan through all expressions to collect variables.

**Comment by carldlaird** [comment]
Can we discuss the alternative you also indicated above, which is to generate a unique name? It seems like we use component names in many places (and they can be quite helpful). I think I would be more in favor of a unique name generator that allowed a defined prefix.

**Comment by jsiirola** [comment]
I agree with @carldlaird: I think an API that looked more like:

```
model.add_component(x, "x", ensure_unique_name=True)
```

would cover the use case that Gabe wants without opening new issues around "name-less" components or component aliases (hinted at under the "additional use cases".  After another (longer, separate) discussion with @ghackebeil and @michaelbynum, I believe that we reached a consensus that aliases are not the way to address the issue of disjunct indicator variables (and instead, refining our definition of what constitutes a "model" in the context of the solver interfaces can resolve the issue cleanly)

**Comment by qtothec** [comment]
@jsiirola Can you elaborate on:

> refining our definition of what constitutes a "model" in the context of the solver interfaces

**Comment by jsiirola** [comment]
@qtothec: we were discussing whether a solver interface should be defined as either:
  - the list of all components reachable on active blocks
  - the list of all things reachable through active components on active blocks.
The distinction has mostly to do with how Vars are collected (is it OK to have a Var sitting on a deactivated component referenced in an active constraint on an active block?).  Currently, several writers require that Vars be reachable from the root (model) object through active blocks (the former).  The latter allows Vars to sit on deactivated things (i.e. Disjuncts) or even not be in the (sub)tree that is being solved.

I believe the consensus (among @michaelbynum, @ghackebeil, and myself) was to move to the second view.

**Comment by ghackebeil** [comment]
With the downside of the second view being that if you want to do something that requires collecting all variables in this definition of a model (e.g., to relax integrality), then you need to walk all expression trees on active components (which would be relatively slow compared to the first view of a model).

**Comment by qtothec** [comment]
I'm ok with the second option.

@ghackebeil - there's an open question (to me) of whether you can then just collect _all_ the variables on the model and relax their integrality for that kind of transformation.

**Comment by ghackebeil** [comment]
Bringing this back to the original topic...

I don't know that I see the utility of something like
```python
model.add_component(x, "x", ensure_unique_name=True)
```
because all that takes is doing
```python
if not hasattr(model, "x"):
    ...
```
I do, however, see how a function that returns a guaranteed unique name with a given prefix or suffix can provide for more informative debugging than anonymous components with no name (which might show up as something like <anonymous[1]> in output). I imagine it's use would look something like:
```python
vname = unique_model_name(model, prefix="something_")
model.add_component(x, vname)
```

I think I'm convinced at this point why that is better than the original proposal (i.e., no changes to core code and more informative debugging).

**Comment by ghackebeil** [comment]
@qtothec: I think the problem is that once you are in the second world view, there is nothing stopping someone creating a model with constraints that use variables on a completely separate model. Then they are truly only reachable through the constraint expressions. We should probably move this discussion to another ticket.

**Comment by jsiirola** [comment]
@ghackebeil: I agree.  I was envisioning `ensure_unique_name` as just being
```
def add_component(self, obj, name, ensure_unique_name=False):
    if ensure_unique_name:
        name = unique_model_name(model, name)
    # .....
```

**Comment by qtothec** [comment]
@ghackebeil Oh. Right.

On the original topic, I think the idea of `model.add_component(x, "x", ensure_unique_name=True)` is exactly what you have with `unique_model_name`. Also, `unique_component_name` already exists: https://github.com/Pyomo/pyomo/blob/master/pyomo/common/modeling.py#L23.

**Comment by ghackebeil** [comment]
Also, although I've been using `add_component` in my examples, I never use it in practice, because I don't understand why it exists. All it does is eat up another public attribute or method name that users can use for their own purposes. Adding this functionality would be the first thing that distinguishes `add_component` from `setattr`, and I don't know that that is a good justification for its existence.

**Comment by ghackebeil** [comment]
@qtothec: Thanks for pointing out where that function lives.

**Comment by carldlaird** [comment]
And I always thought add_component should return the component.
