### ISSUE TITLE
Variable fixing does not check value against domain

### ISSUE THREAD

**Issue by jwatsonnm** [Pyomo/pyomo#557]
Consider the following snippet:

import pyomo.environ as pe
m = pe.ConcreteModel()
m.v = pe.Var(within=pe.NonNegativeReals)
m.v = -1.0

This yields, as one would like/expect, a domain error during the variable-value assignment.

However, consider instead the following snippet:

import pyomo.environ as pe
m = pe.ConcreteModel()
m.v = pe.Var(within=pe.NonNegativeReals)
m.v.fix(-1.0)

In contrast to the first snippet, this example runs clean on master - with no exception.

At a minimum, this is inconsistent behavior. This is biting @DLWoodruff and I, as we work on alternative methods for candidate solution generation in PySP. We feel that the behavior should be identical - an exception being thrown - in both cases. If anything, we would have expected fix() to simply do the variable-value assignment, at which point the exception would have been triggered.

**Comment by dallan-keylogic** [comment]
I've just encountered this issue myself on version 6.0.1a0 of Pyomo. I want to put some basic model sanity checking into IDAES, but don't want to duplicate features from Pyomo. Since it appears that variable bound checking is an intended feature of Pyomo, it's better to handle it in Pyomo than IDAES.

**Comment by blnicho** [comment]
This behavior was discussed in https://github.com/Pyomo/pyomo/issues/2180 and the two example code snippets above are now consistent in throwing a warning when trying to set the variable value outside of its domain.
