### ISSUE TITLE
Using AbstractModel() with Parameter rule leads to empty abstract model

### ISSUE THREAD

**Issue by phaabe** [Pyomo/pyomo#561]
Hi, 

I have noticed a difference between creating an abstract model from a rule and without rule. This leads to restrictions using the DataPortal().

I couldn't research it further more(Nothing in the online documentation and I didn't get an answer to it at the Pyomo google group). 
Here is what I discovered what I don't understand, and maybe it's an issue:

```
from pyomo.environ import *

# creation without rule
model = AbstractModel()
model.T = Set(ordered=True)
model.dt = Param()

# creation with rule
def Storage(s):
    s.T = Set(ordered=True)
    s.dt = Param()
Storage = AbstractModel(rule=Storage)
```

After running this code **_model_** and **_Storage_** are two different models. **_model_** has 2 declarations. **_Storage_** is empty (zero declarations):

```
model.pprint()
1 Set Declarations
    T : Dim=0, Dimen=1, Size=0, Domain=None, Ordered=Insertion, Bounds=None
        Not constructed

1 Param Declarations
    dt : Size=0, Index=None, Domain=Any, Default=None, Mutable=False
        Not constructed

2 Declarations: T dt
```

versus: 

```
Storage.pprint()
0 Declarations: 
```

Why is the the model **_Storage_** empty? 
Using `Storage.create_instance('storage.dat')` the set **_T_** and the Param **_dt_** are declared and initialized. Is the rule only applied after using create_instance()? 

Can they be declared before being converted into a concrete model? Unless it is not possible to use the DataPortal correctly. 

Thanks!

**Comment by whart222** [comment]
@jsiirola I *think* we could cover this sort of question by documenting rules in models.  Perhaps we should have a ticket for such documentation?  I'm not sure where we'd want to include that, since rules are not commonly used to construct models in this fashion.  In fact, I don't think I'd recommend this except for advanced users.

**Comment by blnicho** [comment]
This is an old question about functionality that we don't recommend using. For that reason I don't think it's worth documenting. I'm going to close this.
