### ISSUE TITLE
Errors in problem writers - Missing variable

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#566]
In an example like this, the problem writer should generate an error because expressions contain variables that are not defined on the model:
```
from pyomo.environ import *

m1 = ConcreteModel()
m1.x = Var()

m2 = ConcreteModel()
m2.o = Objective(expr=m1.x)

m2.write("foo.bar")
```
However, writers for LP, NL, GMS and BAR files generate different errors ... or do not generate an error at all!

**Comment by blnicho** [comment]
A detailed design discussion on this behavior can be found in #1032 so closing this.
