### ISSUE TITLE
Should Pyomo allow indexing sets whose members are not comparable?

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#567]
The following code generates a consistent ordering by sorting indexing sets, which causes an error when the set members are not comparable:
```
from pyomo.environ import *

m = ConcreteModel()
m.A = Set(initialize=[1, '1'], within=Any)
m.x = Var(m.A)
m.o = Objective(expr=m.x[1]+m.x['1'])

m.pprint()
m.display()
```
Here, the pprint() method is sorting to create a consistent output.

Worse yet, the LP writer garfs for the same reason:  it's trying to sort an indexing set to force a consistent output.
```
from pyomo.environ import *

m = ConcreteModel()
m.A = Set(initialize=[1, '1'], within=Any)
m.x = Var(m.A)
m.o = Objective(expr=m.x[1]+m.x['1'])

m.write('foo.lp')
```

NOTE:  These errors do not occur if the set is ordered, since that ordering is sufficient.  Hence, these issues go away if Pyomo switch to tacitly using ordered sets.

**Comment by jsiirola** [comment]
Short answer: Yes. Pyomo should allow Sets of objects that are not comparable.  There is no reason to not allow it.

There is a `sorted_robust` function (currently in `pyomo.core.base.misc`) that will robustly sort Set members, even when they are not comparable.  This function is being integrated into Set objects as part of the `set-rewrite` branch.

**Comment by carldlaird** [comment]
I am not sure I agree that there is "no reason to not allow it". The fact that we need a special sorting function might be a reason. I think I agree that we should allow it if the robust sorting approach does not cause any performance degradation.

However, I am also concerned about developers not realizing that they may need a special sorting function. Do we have any idea how many places this is done in Pyomo?

**Comment by jsiirola** [comment]
The “robust” sorter starts by using `sorted`, and only does something special if `sorted` fails, so in 99.9% of the cases the only overhead is an extra function call. 

In `set-rewrite`, there are `sorted` and `ordered` methods on SetData that are even more intelligent: they are aware of the “orderedness” of the set and only re-sort if needed. The idea is that users and developers would always use those methods and avoid the whole issue.

**Comment by carldlaird** [comment]
That seems reasonable to me.

**Comment by whart222** [comment]
As I noted above, this error does not arise if we implicitly use an ordered representation in Pyomo. I think we're going to move to support that functionality.  Hence, I don't see a clear motivation for supporting a order_all_sets() functionality.  It would only be used when a user specifies a sorted ordering, right?  And in that case it's very reasonable to generate an error if the set they are using is not comparable.  (In fact, I think I would argue that that is the better behavior, since the user might not recognize that that is an issue.)

**Comment by qtothec** [comment]
I'm a bit confused. I thought that #568 would make the example at the top work:
```
from pyomo.environ import *

m = ConcreteModel()
m.A = Set(initialize=[1, '1'], within=Any)
m.x = Var(m.A)
m.o = Objective(expr=m.x[1]+m.x['1'])

m.pprint()
m.display()
```
As it turns out, this is not true. I get the following error on `m.pprint()`:
```
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\base\block.py", line 1882, in pprint
    Block.pprint(self, filename, ostream, verbose, prefix)
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\base\block.py", line 1835, in pprint
    prefix=prefix+'    ' if subblock else prefix)
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\base\block.py", line 1578, in pprint
    ostream=ostream, verbose=verbose, prefix=prefix + '    ')
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\base\component.py", line 391, in pprint
    tabular_writer( ostream, prefix+tab, _data, _header, _fcn )
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\base\misc.py", line 193, in tabular_writer
    _rowSet = row_generator(_key, _val)
  File "c:\cygwin64\home\qchen\git\pyomo\pyomo\core\base\sets.py", line 854, in <lambda>
    else sorted(v), ] )
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by whart222** [comment]
The problem is #568 merely changes the underlying representing.  Pyomo continues to sort based on indexing sets in its pretty printing and display functionality.  Hence, resolution of this issue will require a bit more work.

**Comment by whart222** [comment]
NOTE:  I am closing PR #602 since we haven't acted on it, and I've moved the branch issue_567 to here: https://github.com/whart222/pyomo/tree/issue_567

**Comment by emma58** [comment]
Is it possible to get around this when the set is composed of tuples? As far as I can tell, even if you create an ordered set, you hit the `TypeError`. For example,
```
m.ick = Set(initialize=[(1, 'str1'), ('str2', 'str3')], ordered=True, within=Any)
```
can't be used as an index set--pprinting a Var indexed by it results in the same `TypeError`. (Though actually it looks like the original example of `Set(initialize=['1', 1], within=Any)` now works.)

**Comment by blnicho** [comment]
This was fixed at some point.
