### ISSUE TITLE
Ipopt has_capability('integer') returns True

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#572]
```
>>> import pyomo.environ as pe
>>> pe.SolverFactory('ipopt').has_capability('integer')
True
```

I think this should return False. There is a comment in the code that says returning False might create headaches for some people, but I don't see how. Can I change this?

**Comment by ghackebeil** [comment]
I think you should change it. It was probably False because there used to not be separate Ipopt solver plugin. It just used the generic asl plugin, which had to support integer output.

**Comment by DLWoodruff** [comment]
My option: change it so it is correct.

The people for whom it might cause headaches should either use the relax
integers transformation and/or hack the code so that has_capability returns
the incorrect value.
  Dave
P.S. Having it return the incorrect value is causing many people headaches.

**Comment by michaelbynum** [comment]
Thanks for the background and opinions. I submitted a pull request.
