### ISSUE TITLE
XPRESS.py always uses lpsolve irrespective of problem type

### ISSUE THREAD

**Issue by kdheepak** [Pyomo/pyomo#58]
The XPRESS.py plugin using [lpsolve](https://github.com/Pyomo/pyomo/blob/master/pyomo/solvers/plugins/solvers/XPRESS.py#L159) irrespective of the problem type. This results in an incorrect solution when solving MILP problems. The correct solver is `mipoptimize` for MILP problems. XPRESS.py should either

1) Ask the user for the problem type
2) Have `pyomo` figure out the problem type

**Comment by ghackebeil** [comment]
Pyomo would definitely be able to figure out the problem type (it checks everything about the model inside of the LP writer). The only challenge here is figuring out how to get that information out of the LP writer and into this method.

The easiest thing to try would be to just change that line to `mipoptimize` and see if XPRESS is smart enough to fall back to `lpoptimize` when the problem is an LP. I'm mean, surely it can solve a MIP that just _happens_ to have no discrete variables. Can you test if this works?

It's also important that this change would not cause XPRESS to no longer return dual solution information if the problem is an LP. Can you test this as well?

**Comment by kdheepak** [comment]
😄 What a great idea! I'll check this out and let you know. Is there a model.py + model.dat that you can share that I can use for testing?

**Comment by ghackebeil** [comment]
No need for a `.dat` file. Just paste this code into a file and run it as a python script (not using the pyomo command):
```python
from pyomo.environ import *

m = ConcreteModel()
m.x = Var()
m.y = Var(bounds=(0,1))
m.o = Objective(expr= m.x + m.y)
m.c = Constraint(expr= m.x >= 1)
m.dual = Suffix(direction=Suffix.IMPORT)
m.rc = Suffix(direction=Suffix.IMPORT)
m.slack = Suffix(direction=Suffix.IMPORT)

solver = SolverFactory("xpress",
                       solver_io="lp")
results = solver.solve(m)

print(m.o())
print(m.x())
print(m.y())
print(m.dual[m.c])
print(m.rc[m.y])
print(m.slack[m.c])

# should print                                                                                 
# 1                                                                                            
# 1                                                                                            
# 0                                                                                            
# 1                                                                                            
# 1                                                                                            
# 0  
```

**Comment by kdheepak** [comment]
I changed the example to the following to run the above test.

```
from pyomo.environ import *

m = ConcreteModel()
m.x = Var()
m.y = Var(bounds=(0,1))
m.o = Objective(expr= m.x + m.y)
m.constraint1 = Constraint(expr= m.x >= 1)
m.dual = Suffix(direction=Suffix.IMPORT)
# m.rc = Suffix(direction=Suffix.IMPORT)
# m.slack = Suffix(direction=Suffix.IMPORT)

solver = SolverFactory("xpress",
                       solver_io="lp")
results = solver.solve(m)

print(m.o())
print(m.x())
print(m.y())
print(m.dual[m.constraint1])
# print(m.rc[m.y])
# print(m.slack[m.c])
```

Results with `lpoptimize`

```
$ python test.py
1.0
1.0
0.0
1.0
```

Results with `mipoptimize`

```
$ python test.py
1.0
1.0
0.0
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    print(m.dual[m.constraint1])
  File "/Users/dkrishna/anaconda/lib/python2.7/site-packages/pyomo/core/base/suffix.py", line 199, in __getitem__
    " (id=%s)" % id(component))
KeyError: 'Component with name: constraint1 (id=4492808720)'
```

So it doesn't appear to be working, `mipoptimize` does not appear to be a drop in replacement for `lpoptimize`.

**Comment by kdheepak** [comment]
Any thoughts on why the above did not work?

**Comment by ghackebeil** [comment]
Well that's unfortunate.

It didn't work because XPRESS did not return a dual solution, which is what any other MIP solver would do).

Looks like we'll have to go with the more difficult fix. Unless we can find some other command in the XPRESS docs that automatically determines the problem type, and solves accordingly.

**Comment by GiorgioBalestrieri** [comment]
@ghakebeil any updates?

**Comment by ghackebeil** [comment]
Sorry, no update. I'll scan the code and see if I can describe a solution that someone with an XPRESS license can try to implement.

**Comment by ghackebeil** [comment]
Here is a pretty self-contained hack that one could add to XPRESS.py to get around this issue. I haven't tested it at all, so there may be typos.

```python
    def _presolve(self, *args, **kwds):
        # this is a hack so that the create_command_line                                                                                                                                                    
        # method has access to the model argument. so we can                                                                                                                                                
        # check the symbol map that is added to it                                                                                                                                                          
        assert not hasattr(self, "_model_for_xpress")
        self._model_for_xpress = args[0]
        try:
            return super(XPRESS_shell, self)._presolve(*args, **kwds)
        finally:
            del self._model_for_xpress

    def create_command_line(self, executable, problem_files):

        # this is a hack so that we can check if the                                                                                                                                                        
        # symbol_map contains any components that make it                                                                                                                                                   
        # discrete, which influences the command-line                                                                                                                                                       
        # arguments for XPRESS                                                                                                                                                                              
        from pyomo.core.base.sos import SOSConstraint
        from pyomo.core.kernel.sos import ISOS

        self.is_map = False
        if self._smap_id is not None:
            model = self._model_for_xpress
            if isinstance(model, IBlock):
                smaps = getattr(_model, "._symbol_maps")
                assert smaps is not None
            elif isinstance(model, _BlockData):
                smaps = model.solutions.symbol_map
            symbol_map = smaps[self._smap_id]
            for _,obj in symbol_map.bySymbol.values():
                if obj.is_variable_type() and \
                   not obj.is_continuous():
                    self.is_mip = True
                    break
                elif (obj.ctype is SOSConstraint) or \
                     (obj.ctype is ISOS):
                    self.is_mip = True
                    break
```

With these changes, one would hope that all tests in `pyomo/solvers/tests/checks/test_writers.py` would pass (xpress may have some bugs that we need to add expected failures for).

**Comment by ghackebeil** [comment]
@GiorgioBalestrieri, @kdheepak: We are hoping to do a release in a day or two. It would be great if one of you (or anyone with an XPRESS license) could put together a pull request with the patch I included above before then. Let us know the result of running `python test_writers.py` (in `pyomo/solvers/tests/checks`) and we can decide from there if it is ready to include.

**Comment by Crueda96** [comment]
Any solution ?

**Comment by lleeoo** [comment]
Hi Folks, Leo here from FICO. I will forward this to someone in our internal team. But FYI: you don't need a special Xpress license for most testing. The community license allows up to 5000 variables + constraints. Cheers!

**Comment by ghackebeil** [comment]
@blnicho: If it's not too late, I might take a shot at putting the above hack into the XPRESS plugin before the 6.0 release. Is there still time?

**Comment by blnicho** [comment]
@ghackebeil sorry just saw your comment but we were already partway through cutting the release when you posted this.

**Comment by ghackebeil** [comment]
No worries. I was able to get a community license for testing and it turns out this interface is still very broken for other reasons. I wonder if we should just retire it, as the xpress_direct solver interface is fully functional.
