### ISSUE TITLE
Export test results from Jenkins to GitHub (Linux + Windows)

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#591]
Currently, AppVeyor tests take a long time to run. When we have Jenkins tests running for windows, we should look at exporting their status as part of the gitHub PR process. Then we could reduce the testing done in AppVeyor and speed up the cycle time for new PRs.

**Comment by whart222** [comment]
Is there a plan for getting windows tests running with Jenkins?  We are using Appveyor specifically because that has proven difficult.

**Comment by blnicho** [comment]
Closing this. We now have Windows tests running with GitHub Actions (instead of Jenkins) and I think there is a separate issue for disabling Appveyor completely once we figure out how to report test coverage from the Windows GitHub Actions jobs.
