### ISSUE TITLE
GAMS writer - passing current values for variables from Pyomo

### ISSUE THREAD

**Issue by jghouse88** [Pyomo/pyomo#592]
@qtothec  @blnicho For the GAMS writer, it will be useful to set  the level for the variables when writing the GAMS file from Pyomo. Currently, the bounds are being passed to the GAMS file from Pyomo but not the initial values. This feature will be useful to initialize large models when custom routines are used in Pyomo to initialize a model and then sent to GAMS for solving. 

@MAZamarripa please add anything I have missed.

**Comment by MAZamarripa** [comment]
I would say that without an initial value most nonlinear models will fail to solve (especially the ones with log, 1/x, ... functions). Passing the initial values or current level of the variables will fix this issue.

**Comment by gseastream** [comment]
@jghouse88 could you please provide an example where values are not being initialized in the model file? The writer is supposed to write initial values for any variables with a value that is not None when `warmstart=True`, and `warmstart` is True by default. The following model:

```python
from pyomo.environ import *

m = ConcreteModel()
m.x = Var()
m.c = Constraint(expr=m.x == 10)
m.o = Objective(expr=m.x)
m.x = 5

opt = SolverFactory("gams")
opt.solve(m, keepfiles=True, tmpdir="tmp")
```

Produces the following in the model file:

```
EQUATIONS
	c1
	c2;

VARIABLES
	GAMS_OBJECTIVE
	x1;

c1.. x1 =e= 10.0 ;
c2.. GAMS_OBJECTIVE =e= x1 ;

x1.l = 5;

MODEL GAMS_MODEL /all/ ;
SOLVE GAMS_MODEL USING lp minimizing GAMS_OBJECTIVE;
```

**Comment by jghouse88** [comment]
@gseastream Does that example work when declared as follows:

```
from pyomo.environ import *

m = ConcreteModel()
m.x = Var(initialize=5)
m.c = Constraint(expr=m.x == 10)
m.o = Objective(expr=m.x)

opt = SolverFactory("gams")
opt.solve(m, keepfiles=True, tmpdir="tmp")
```

**Comment by qtothec** [comment]
@jghouse88 I just ran your code on master (currently e34a057277638fad4c5c7e4e716504ab225d2b64) and it sets `x1.l = 5;` in model.gms as expected.

**Comment by jghouse88** [comment]
@qtothec OK, that is good to know. Let @MAZamarripa and me check the Pyomo versions just to be sure that it is not because of the version. We tried this on the distillation models. Before writing it to GAMS, we solved the model using the initialization routines we had in Pyomo and then called the GAMS writer. We expected the variables to have the levels set to the current values i.e. after solving it in Pyomo. But that was not the case. I guess levels get set only when I do either of the two (correct me if I am wrong):

```
m.x = Var(initialize=5)
```
or 
```
m.x = 5
```

What happens if I solve the model in Pyomo first and then pass it to GAMS? 

```
from pyomo.environ import *

m = ConcreteModel()
m.x = Var(initialize=5)
m.c = Constraint(expr=m.x == 10)
m.o = Objective(expr=m.x)

opt = SolverFactory("ipopt")
opt.solve(m)

opt = SolverFactory("gams")
opt.solve(m, keepfiles=True, tmpdir="tmp")
```

Will the level be set to 5 or the solution obtained from the first solve?

**Comment by gseastream** [comment]
The code above will write in the GAMS file to initialize x to 10. That is because with this model, the optimal value of x obtained from ipopt is 10, and solvers by default set the solution values onto the values of the model variables. So after running the ipopt solve, `print(m.x.value)` will print out 10. Thus when you call the gams solve, the value of `m.x` is 10 so the GAMS file contains the line `x1.l = 10.0`.

As long as the value attribute is set before calling the gams solver, the gams file will initialize the variable to that value. You can see if the attribute is set on a particular variable by inserting `print(m.x.value)` before the line that calls `opt.solve`.

**Comment by jghouse88** [comment]
@gseastream OK, that is good. I think then this is a pyomo version problem. Let me check and get back.

**Comment by gseastream** [comment]
I think I found the issue. The warmstart option used to default to False, and the IDAES branch is outdated enough that that version of Pyomo has the old default. So if you continue to use that version, you'll need to pass the `warmstart=True` keyword to the solve method.

**Comment by jghouse88** [comment]
@gseastream Just checked and it works when setting the `warmstart=True`. Thanks!

**Comment by gseastream** [comment]
Excellent. Then this issue can be closed?

**Comment by jghouse88** [comment]
Yes. Thanks for the help.
