### ISSUE TITLE
Minor Release for Python 3.7

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#604]
There are fixes in master that make Pyomo compatible with Python 3.7. We should get those into a release ASAP.

**Comment by ghackebeil** [comment]
@whart222, @jsiirola: I've created a branch (pyomo-5.5.1_python-3.7_patch) starting from the commit just after the 5.5.0 release (2e028339384925dd17b6ae2171484f29cfdcfb65) that applies the necessary PySP patches along with updates to the travis and appveyor configurations to enable Python 3.7 support with testing.

Unfortunately, it looks like the magic reference counting numbers used by the coopr3 expression system need to change again in order to support 3.7. Since you two are the most familiar with this system, I'll leave it to you to decide if it's worth the effort of further patching the coopr3 expression system to get a release out that supports Python 3.7.

**Comment by whart222** [comment]
@jsiirola You would need to update the magic reference counting numbers.  I've never been sure how you did that.

**Comment by jsiirola** [comment]
I will look at that this morning.  It should only take a few minutes.

**Comment by sjpfenninger** [comment]
@ghackebeil @jsiirola what's the status of this? Would be nice to have Py3.7 support!

**Comment by ghackebeil** [comment]
We created a branch that patched that previous release. It was just never pushed to PyPi. At this point, I think it’s more likely that a release based on master will go out first, but the other one is still ready to go. Any thoughts @wehart?

**Comment by uvchik** [comment]
> Would be nice to have Py3.7 support!

:+1:

**Comment by ckaldemeyer** [comment]
Me too!

**Comment by uvchik** [comment]
Thank you for the release. Works fine now with Python 3.7. :clap: :tada:

**Comment by jsiirola** [comment]
Excellent. 5.5.1 is out and confirmed to be working.
