### ISSUE TITLE
Using name buffer with getname can mess up later calls

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#608]
When using the `name_buffer` option on `component.getname`, if you first call with `fully_qualified=True` and then you later call with `fully_qualified=False`, the second call will incorrectly return the fully qualified name because it was stored that way in the name buffer. Consider the following:

```python
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.b = Block()
>>> m.b.x = Var()
>>> buf = {}
>>> m.b.x.getname(fully_qualified=True, name_buffer=buf)
'b.x'
>>> m.b.x.getname(fully_qualified=False, name_buffer=buf)
'b.x'
```

While this may not matter very much because you can just use `.local_name` (which does not use any name buffer), I imagine we would still want to rely on getname for non fully qualified names with a buffer to still be correct.

**Comment by gseastream** [comment]
Note: the reverse is also messed up in a similar way. Example:

```python
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.b = Block()
>>> m.b.x = Var()
>>> buf = {}
>>> m.b.x.getname(fully_qualified=False, name_buffer=buf)
'x'
>>> m.b.x.getname(fully_qualified=True, name_buffer=buf)
'x'
```

**Comment by gseastream** [comment]
Actually I think it might matter more than I thought. It looks like you can save yourself a couple function calls by using a name buffer, even for non fully qualified names.

**Comment by blnicho** [comment]
The `name_buffer` argument to `getname` is deprecated so closing this.
