### ISSUE TITLE
Should the type() method actually be called ctype?

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#613]
Continuing discussion brought up in #593.

For pyomo components, the way to get the ctype is a method called `type()`, but for kernel components it's a property called `ctype`. Should we move to make these consistent with each other? This could mean both having a property called `ctype`, a method called `ctype()`, or either of the same for `type`. I think I agree with @jsiirola that calling it `ctype` would be a lot clearer since I for one was confused at first when `.type()` wasn't the same as its actual type. As for whether it should be a property or a method, the only information I have on that would be that I noticed kernel components much more often use properties instead of methods. I don't know if this is an actual design choice or if it's faster or something, so I'll let @ghackebeil weigh in on that.

**Comment by blnicho** [comment]
I'm also in favor of this change. I think having a `type()` method causes a lot of confusion with Python's built-in `type()` function.

**Comment by whart222** [comment]
I concur.

**Comment by ghackebeil** [comment]
Should we go with a normal method (`ctype()`) or a property method (`ctype`)? In kernel, it is currently the latter. What I said on the phone yesterday was that the `ctype()` form might make more sense if this is always going to be a class level property (i.e., we could implement it as a `classmethod`).

However, if there is functionality that requires re-categorizing model objects, then it would be more consistent to implement it as a property method because all of the other instance level attributes are implemented that way.

**Comment by jsiirola** [comment]
As we currently implement it in `core.base`, `ctype()` is an instance-level attribute.  Pyomo transformations make use of re-categorizing objects within transformations.  Right now, I don't think that you can get a class-level ctype... although I don't see why we couldn't support it.  That might actually be useful in some situations.  For example, we re-categorize `Disjunct`s as `Block`s in the GDP transformations to get around limitations in the writers.  One of the consequences is that it is tricky to know which objects *used* to be Disjuncts.  If we add a class-level method, you could recover the reclassified object's original ctype with `type(component_in_question).ctype()` - which might be useful functionality, particularly in solution back-mapping.  @qtothec, @gseastream?

**Comment by ghackebeil** [comment]
Currently in all kernel components `ctype` is _implemented_ by returning a private class-level attribute, but that is independent of the interface. If GDP was currently implemented on top of kernel today, I would likely need to start declaring instance level storage of ctype on block, but the interface wouldn't need to change.

On the kernel cleanup PR, I've removed the metaclass junk which now means doing something like `<class>.ctype` does not work (it returns the property method).

> One of the consequences is that it is tricky to know which objects used to be Disjuncts

Coundn't this be done using `isinstance` / by checking the objects class?

**Comment by gseastream** [comment]
I'm sure being able to track down the original Disjuncts that have since been reclassified (and the same for other types of transformations) would be useful, so I wouldn't oppose that, but as @ghackebeil pointed out you can already pretty much do this by looking at the class itself and seeing if it's one of the Disjunct types. However, maybe an even more useful feature would be a model component walker like `component_data_objects` but it looks at the original ctype instead of the current ctype. I don't know if that's something people think is worth implementing.

As for property vs method, I think either is fine and we can go with whatever fits in better with our needs in terms of having class level and instance level callbacks. All else equal, I feel like a property would make more sense than a method since it's more like an attribute as opposed to a function, but again we can do whatever is easier.

**Comment by ghackebeil** [comment]
@jsiirola: Are you okay with using a different method name for accessing the class-level ctype once that functionality is added (e.g., `x.class_ctype()`)? That would allow the instance level ctype access syntax to remain consistent with all of the other "read-only" attributes in kernel (and I believe core.base).
