### ISSUE TITLE
Proposal: NotInitialized instead of ERROR for expression.display()

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#616]
As illustrated by [this StackOverflow question](https://stackoverflow.com/questions/51362762/pyomo-inialization-error-error-evaluating-expression-no-value-for-uninitializ) and interactions with collaborators that I have had, the `ERROR` when trying to `display()` a model that has uninitialized variables in expressions causes confusion.

I think that we should distinguish between "**No value**" vs. "**your model has a fatal flaw**" in our `display()` output. Any thoughts?

**Comment by blnicho** [comment]
I'm always in favor of more informative error messages although I'm not sure how this would be implemented.

**Comment by qtothec** [comment]
I am not intimately familiar with this part of the codebase, but I would think that whatever walker collects expression values for `display()` either catch the error or return a `NoValue` enum/object when they encounter. Therefore, the display would read:
```
  Constraints:
    c : Size=1
        Key : Lower : Body                : Upper
          1 :  None : No value: feed.flow :   0.0
```

**Comment by jsiirola** [comment]
It's doable.  The "`No value`" part is relatively easy.  You would need to turn the `lambda` in `Constraint.display()` to a proper function that wrapped the `value()` calls in try-except blocks.  Getting the name of the uninitialized object would be trickier.  The easiest thing might be to change the `ValueError` that `NumericValue` raises to be a new class (`UninitializedValueError`?) that is derived from `ValueError` that also stores the component that triggered the error.  That way, the (new) `try-except` in `display()` could interrogate the exception object and print out the component name.
