### ISSUE TITLE
Constraints do not set equality to True for 3-tuples with equal bounds

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#618]
Related: #107

In constraint.py around [line 420](https://github.com/Pyomo/pyomo/blob/ae3c6d4577ea2de5c767b00db08f0afb30917da9/pyomo/core/base/constraint.py#L420), the logic currently decides that if a 2-tuple was used then it's an equality, but if a 3-tuple was used then it must be an inequality even if the lower and upper are equal. This is highlighted in the (soon deprecated) Connector expander where it creates a constraint with a 3-tuple and passes the lower and upper of the constraint it's expanding, and due to this bug the resulting constraint has the equality property return False even if lower was equal to upper (i.e. it was an equality). We should probably change this so that if `lower == upper` then equality is True. As far as I know that's the only bug in the current logic. Here is an example:

```python
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.x = Var()
>>> m.y = Var()
>>> m.c = Constraint(expr=(m.x, m.y))
>>> m.c.pprint()
c : Size=1, Index=None, Active=True
    Key  : Lower : Body  : Upper : Active
    None :   0.0 : x - y :   0.0 :   True
>>> m.c.equality
True
>>> m.d = Constraint(expr=(0, m.x - m.y, 0))
>>> m.d.pprint()
d : Size=1, Index=None, Active=True
    Key  : Lower : Body  : Upper : Active
    None :   0.0 : x - y :   0.0 :   True
>>> m.d.equality
False
```

**Comment by gseastream** [comment]
Actually I realized that you can't just check that `upper == lower` since you also need to have passed a sum expression with two terms like `m.x - m.y` for that to mean an equality.

That being said, playing around with expressions more I found that for equality to be True for an expression you pass, it only needs to be an EqualityExpression at the top level. So the `.equality` property is not as comprehensive as one might think.

```python
>>> m.x, m.y, m.z = Var(), Var(), Var()
>>> m.c = Constraint(expr=m.x * 5 / m.y == m.x ** m.x - m.z * m.y)
>>> m.c.equality
True
```

**Comment by qtothec** [comment]
I thought that `equality` simply meant that `upper == lower`, without the requirement that it is a `x = y` variable relationship. However, that check has two weaknesses:
1. `upper = lower = None`
2. `abs(upper - lower) <= eps`, but `abs(upper - lower) > 0`. How do you define `eps`?

**Comment by ghackebeil** [comment]
I don't like the idea if implicitly converting a ranged inequality constraint with equal bounds into an equality constraint. Historically, this had been done by the expression system with for `lb <= f(x) <= ub` when `lb is ub` was True. I believe we have removed that behavior in the Pyomo5 expression system.

Although these two cases are equivalent, they can have different numerical properties for solvers and we should leave it to the user to decide exactly what constraint form makes it to the solver.

**Comment by gseastream** [comment]
@ghackebeil I can see your argument for allowing the user to determine which form makes it to the solver, so I suppose the versatility is worth keeping. @whart222 @jsiirola do you have thoughts on this?

@qtothec I wouldn't think we should define equalities as expressions with *almost* equal bounds, since that takes away from the fact that there is actually some range of values the body can vary by. Regardless, we currently don't define equalities as something with equal bounds anyway but rather it just being an EqualityExpression (for when you pass something like `expr=m.x + m.y == m.z`).

**Comment by qtothec** [comment]
@ghackebeil I'm fine with having that distinction for the solvers. It's an easy transformation between the two.

@gseastream I'm curious then what happens if you pass `expr=m.x + m.y == m.z` and then later modify `constraint.lower`.

**Comment by ghackebeil** [comment]
> I'm curious then what happens if you pass expr=m.x + m.y == m.z and then later modify constraint.lower

When you pass something like this to build the constraint, we reorganize the expression so that nothing appearing to contain variables appears in the bound. That is, the constraint body becomes `x+y-z` or `z-x-y`. If you care about that final form appearing in the body (e.g., if the sign of the dual matters to you), then it is always better to write the constraint such that the bounds don't need to be adjusted. In kernel, I allow you to do something like `constraint(body=x+y-z, rhs=0)`, which guarantees nothing will be changed.

**Comment by ghackebeil** [comment]
@gseastream: I've encountered most these odd behaviors before, and I believe the re-implementation I've provided in Kernel takes care of all of them. What I've been pushing for for a while now is a re-implemetnation of the AML classes on top of Kernel rather than continuing to copy-paste fixes, but that will be a slow process. I know it's frustrating but I would recommend checking if the kernel implementation takes care of the issues you are encountering and providing design discussion on that interface if you think it should be changed. Here is some example usage (please let me know if you can break it):
```python
import pyomo.kernel as pmo
c = pmo.constraint()
x = pmo.variable()
# define a range constraint
c.lb = 1
c.ub = 2
c.body = x**2
assert c.equality == False
# change it to an equality constraint constraint
c.rhs = 3
assert c.lb == 3
assert c.ub == 3
assert c.rhs == 3
assert c.equality == True
# change it to a range constraint with equal bounds
c.equality = False
assert c.lb == 3
assert c.ub == 3
assert c.equality == False
# note that you cannot access c.rhs when c.equality == False
```

**Comment by gseastream** [comment]
These issues haven't gotten in my way yet so I haven't been too frustrated, I've mostly just started discovering things and pointing them out. It would be interesting if we implemented AML on top of kernel, but I don't have much input on that discussion.

All that being said, I think I agree with your opinion on the original issue, that we should keep the distinction between an equality and an inequality with equal bounds. If that sounds right to everyone, should we close this issue?

**Comment by blnicho** [comment]
This design discussion has been moved to #2105 so closing this.
