### ISSUE TITLE
method to display "active" components of the model "model.display()"

### ISSUE THREAD

**Issue by MAZamarripa** [Pyomo/pyomo#624]
The current display method displays all the variables (not sure if all the constraints). 
I am running into the case where there are a lot of constraints and variables. However, for initialization I've deactivated most of the constraints. Then, I am solving a small problem (4 vars and 4 constraints), but, if I call the display method (for debugging), it shows all the variables (for example 100 vars, even if they are not used). 
Do you think it would be possible to have a flag in the method to show only what is being passed to the solver [model.display(active) or model.display(all)]

**Comment by mrmundt** [comment]
This is a duplicate / primarily similar to #307 .
