### ISSUE TITLE
Question about labels in LP file generated using Pyomo

### ISSUE THREAD

**Issue by kdheepak** [Pyomo/pyomo#63]
Is there a way to force the labels in the LP file to use names similar or identical to that in the model? Currently all the names are `xN` where `N` is a number. It will make it easier to check if a problem is being formulated as expected.

**Comment by jwatsonnm** [comment]
Assuming you are invoking the solver from a script, you can set the solver plugin option “symbolic_solver_labels” to True. This will translate from the x-prefixed symbols to symbols that are human-readable, based closely on the model names.

jpw

**Comment by kdheepak** [comment]
@jwatsonnm Thanks for the quick reply! It works great!
