### ISSUE TITLE
Enhancement: dicts as valid arguments for indexed components

### ISSUE THREAD

**Issue by mlangiu** [Pyomo/pyomo#632]
When **initializing** a variable or parameter you can simply pass a dict, as in

    from pyomo.environ import ConcreteModel, Var
    m = ConcreteModel()
    m.x = Var([1,2,3], initialize={1: 0, 2: 42, 3: 5})

However the same is not possible with other initializer arguments such as the `bounds` or `domain`:

    y_bounds = {1: (0, 1), 2: (-1, 3), 3: (None, None)}
    m.y = Var([1, 2, 3], bounds=y_bounds)

results in:

     ValueError: Variable 'bounds' keyword must be a tuple or function

and

    from pyomo.environ import Reals, Integers, Binary
    z_domains = {
         'myBinaryVariable': Binary
         'myIntegerVariable': Integers
         'myRealVariable': Reals
    }
    m.z = Var(['myBinaryVariable','myOtherBinaryVariable','myRealVariable'], domain=z_domains

results in the lengthy error:

    ValueError: {'myBinaryVariable': <pyomo.core.kernel.set_types.BooleanSet object at 0x000001F3178C5080>, 'myIntegerVariable': <pyomo.core.kernel.set_types.IntegerSet object at 0x000001F3178ACEF0>, 'myRealVariable': <pyomo.core.kernel.set_types.RealSet object at 0x000001F3178ACCF8>} is not a valid domain. Variable domains must be an instance of one of (<class 'pyomo.core.kernel.set_types.RealSet'>, <class 'pyomo.core.kernel.set_types.IntegerSet'>, <class 'pyomo.core.kernel.set_types.BooleanSet'>), or an object that declares a method for bounds (like a Pyomo Set). Examples: NonNegativeReals, Integers, Binary

While I understand that specifying distinct domains for each index of one variable may not be the most common thing from an applicational point of view, it can be when implementing certain algorithms. Index-specific bounds on the other hand seem like a commonly useful thing to have.

of course we can define lambdas to loop over the dicts, but that gets tiring and unnecessarily requires the model to be passed as the first argument due to convention...

**Comment by blnicho** [comment]
This enhancement was added at some point so closing this.
