### ISSUE TITLE
Strange behaviour for mutable Param indexed by Set with dimen=None

### ISSUE THREAD

**Issue by mlangiu** [Pyomo/pyomo#636]
There seems to be a bug in the index generation for mutable `Param`s that are indexed with `Set`s which have the dimen set to `None`:

    m = ConcreteModel()
    m.constr_index = Set(dimen=None, initialize=constraints)
    m.x_index = Set(dimen=None, initialize={'x1', 'x2'})
    m.A = Param(m.constr_index * m.x_index, default=0, mutable=True)
    constr = ('constr', 1)
    var = 'x1'
    param1 = m.A[(*constr, var)]
    param2 = m.A[constr, var]
    print(param1 is param2)  # >>> False

    print(param1.index())  # >>> ('constr', 1, 'x1')
    print(param2.index())  # >>> None

    print(param1)  # >>> A[constr,1,x1]
    print(param2)  # >>> RuntimeError: Fatal error: cannot find the component data in the owning component's _data dictionary.

I stumbled across this when trying to write a generic algorithm that takes user data and writes pyomo models. My thinking was that a user might decide to use mixed dimensional `constraints` such as:

    constraints = {('c1', 1), ('c1', 2), 'c2'}

In which case the dimen=None becomes necessary. In my own case I could refactor but I suppose it would still be good to find the root of this problem.

I'm using Pyomo version 5.5.0

**Comment by qtothec** [comment]
Looking at your example, I wonder if the issue is actually with `m.A[constr, var]`. Param indices are accessed either with a tuple or singleton. During construction of `A`, the set product is flattened. Therefore, the index `('constr', 1, 'x1')` exists, but not `(('constr', 1), 'x1')`.

**Comment by mlangiu** [comment]
As I understand flattening (usually) also occurs when indexing, consider:

    m = ConcreteModel()
    constraints = {('c1', 1), ('c1', 2)}
    m.constr_index = Set(initialize=constraints)
    m.x_index = Set(initialize={'x1', 'x2'})
    m.A = Param(m.constr_index * m.x_index, default=0, mutable=True)
    m.A[('c1', 1), 'x1'] is m.A['c1', 1, 'x1']  # >>> True
    m.A[('c1', (1), 'x1')] is m.A['c1', 1, 'x1']  # >>> True

**Comment by blnicho** [comment]
This looks like a subtle bug related to checking if an index is valid and if it appears in an IndexedParam's data dictionary. Looks like [('c1', 1), 'x1'] is being correctly identified as a valid member of the indexing set but not correctly identified as equivalent to ['c1', 1, 'x1']. Because the Param has a default value specified, that value is returned and when I pprint the Param in Python 2.7 I see both the flattened and unflattened index.

**Comment by blnicho** [comment]
Looks like this was fixed at some point.
