### ISSUE TITLE
Does Pyomo have any support for solution pools?

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#639]
I am wondering if there is any capability for getting the whole pool of solutions from any of our solvers, but particularly cplex since I know cplex has its own support for "solution pools" where it will collect every optimal solution it finds. I found [this post](https://groups.google.com/forum/#!topic/pyomo-forum/be0WNbezwvI) in the google group, but it doesn't look like there was any conclusion. If we don't support solutions pools, would anyone know where that could most easily be inserted, if possible?

This would be useful for something in IDAES where it would be nice if the user could get every possible tear set from the MIP solver if they wanted to see all their options, but I imagine this could have a broader set of use cases as well.

**Comment by qtothec** [comment]
@michaelbynum is working on that.

**Comment by blnicho** [comment]
Closing this for now. If/when solution pools are supported, it will be noted in the corresponding PR and the CHANGELOG.

**Comment by michaelbynum** [comment]
Pyomo's persistent interface to Gurobi now has support for solution pools. See https://pyomo.readthedocs.io/en/stable/library_reference/solvers/gurobi_persistent.html for details (see the `set_gurobi_param` method).
