### ISSUE TITLE
Template expression substituter doesn't work for non-templated string indices

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#64]
The template expression substituter does not work when one of the non-templated indexing sets is a set of strings. For example:

```python
m = ConcreteModel()

m.s = Set(initialize=['A','B'])
m.j = RangeSet(1,10)
m.x = Var(m.j,m.s,initialize=1)
t = IndexTemplate(m.j)

def _con(m,j,s):
    return m.x[j,s] == m.x[j+1,s]**2

e = _con(m,t,'A')

_map = {}
E = substitute_template_expression(e,substitute_getitem_with_param, _map)

# t.set_value(5)
# E = substitute_template_expression(e,substitute_template_with_value)
```
@jsiirola it looks like the problem is in the clone_expression function for both coopr3 and pyomo4 expressions (I can send the stack trace if needed). I don't know enough about the expression cloning/copying logic to fix this.

**Comment by jsiirola** [comment]
This was fixed by the changes to cloning in the Connector rewrite branch (merged as part of PR #66).
