### ISSUE TITLE
Fix NEOS interface behind proxy in Anaconda Python 3.x

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#646]
As was observed in #644, the NEOS interface cannot connect to the NEOS server when running on a Python 3.x version of Anaconda.  As a result, `pyomo help --solvers` returns:
```
NEOS Solver Interfaces
----------------------
The neos solver manager supports solver interfaces that can be
executed remotely on the NEOS optimization server.  This server is not
available with your current system configuration.
```

**Comment by blnicho** [comment]
I just tested this again with Anaconda on Windows running Python 3.7.1 and as long as I have the `https_proxy` environment variable set `pyomo help --solvers` seems to work and pick up the NEOS solvers. I'm going to close this as resolved.
