### ISSUE TITLE
Disjunction shortcut syntax enhancement

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#652]
@jsiirola What are your thoughts on supporting the following syntax:
```
model.modes = Disjunction(expr={
    'off': [model.flow == 0, model.cost == 0],
    'low': [model.flow <= 25, model.cost == 10 * model.flow],
    'high': [model.flow >= 25, model.cost == 8 * model.flow]
})
```

**Comment by jsiirola** [comment]
What would the resulting model look like?  More specifically, what is the difference with this syntax:
```
model.modes = Disjunction(expr=[
    [model.flow == 0, model.cost == 0],
    [model.flow <= 25, model.cost == 10 * model.flow],
    [model.flow >= 25, model.cost == 8 * model.flow]
])
```
Is the idea that the `['off','low','high']` would be the indexes for the automatically-created Disjunct blocks?

**Comment by qtothec** [comment]
Yes, because `model.modes.disjuncts[0]` just seems too anonymous, but the concise notation is nice. It could even be `model.modes.off` rather than `model.modes.disjuncts['off']` if that's easier.

**Comment by mrmundt** [comment]
While this request is fair, we have decided that this is not something we will implement in order to manage technical debt.
