### ISSUE TITLE
Issue exporting model to gams with power operator

### ISSUE THREAD

**Issue by pazochoa** [Pyomo/pyomo#663]
Hi,
I am exporting an expression with a negative power operator to gams:
pyomo exports: m.Eq1=Constraint(expr=m.B+ m.A * m.T1**-1.0==0)
gams receives:   Eq1..        B+ A* T1**- 1.0 =e= 0.0 

And I am getting the following error in gams:

445  More than one operator in a row. You need to use parenthesis
       if you want to use such statements. For example
           x := x + - not y;  ->  x := x + (- (not y));
           sum(i$not x, ..)   ->  sum(i$(not x),..)
Best, 
Paz

**Comment by qtothec** [comment]
@gseastream Didn't we fix something similar not too long ago?

**Comment by gseastream** [comment]
Yes, there was a similar issue when variables were fixed to negative values. The fix for this should be very similar.

**Comment by qtothec** [comment]
Ok. Relevant issues are #306 and #510. I'll get to this after I'm finished putting out fires, if nobody else does first.

**Comment by qtothec** [comment]
Incidentally, #698 fixes this.
