### ISSUE TITLE
differentiate() is slow

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#665]
It was a design decision when we first implemented `differentiate()` using `sympy` to keep things simple as a first pass. With myself and other users now attempting to solve problems of sufficient size for this to be a bottleneck, we should look into ways to improve performance:

1. Go through GJH, ala Pynumero: #474 
2. Look into an interface to Casadi
3. something else?

**Comment by jsiirola** [comment]
We currently have 2 ways of getting numerical derivatives from the ASL:
  1. through a proper GJH solver (implemented in `pyomo.controb.trustregion`)
  2. through `pyomo.contrib.pynumero` (currently a PR)

(1) is simpler, but could use some more work to generalize how we get the derivative information back.  It also requires a new NL file to be written for every evaluation.  (2) can support multiple evaluations using only a single NL file, but is waiting for some other code to be finished before it can be merged into master.

`pyomo.dae` has an interface to CasADi that converts Pyomo expressions to CasADi expressions, and only needs the additional interface to query the derivatives.

I also believe that @michaelbynum has prototyped a pure-python (pure-pyomo?) AD package as well (which may not require any expression tree conversions).

**Comment by michaelbynum** [comment]
First, I am assuming you do not need symbolic derivatives. Second, the best way to get derivative information depends on your exact needs. 

If you need to evaluate the derivative once, I think it makes the most sense to implement AD with pyomo expressions directly. I have not implemented this in Pyomo, but I have toyed with it with my own "toy" expression systems. It is quite easy to implement. It will not be very efficient, but it would avoid a transformation to another system that can do the AD efficiently. 

If you need to evaluate the derivatives many times at many different points, it makes sense to transform the expressions into another form (e.g., CasADi). 

@jsiirola I thought pynumero also used an nl interface to ASL?

**Comment by michaelbynum** [comment]
@jsiirola Ignore my question. I misread your post.

**Comment by michaelbynum** [comment]
Another important question is whether or not we expect model structure to change between derivative evaluations.

**Comment by jsiirola** [comment]
@qtothec: I am not sure what to do with this issue.  As it doesn't report a specific problem, it is unclear to me when (if?) we can close it.  #719 goes a long way toward improving the performance of `differentiate()` (for common Pyomo expressions.  Other approaches to AD (GJH, Pynumero, CasADi) are all actively being explored.

Thoughts?

**Comment by qtothec** [comment]
That is true. We can close this for lack of specificity, until the next person complains.
