### ISSUE TITLE
Unusual behavior when using Pyomo and Pandas (?)

### ISSUE THREAD

**Issue by kdheepak** [Pyomo/pyomo#68]
Hi all,

I'm getting an extremely unusual behavior when using Pyomo with a Pandas Series object. Specifically, when I convert a Pandas Series object to a dictionary and pass it to a `Param` initialization, I get a error when I create a constraint rule.

```
import pandas as pd
from pyomo.environ import *

model = ConcreteModel()

model.Set1 = Set(initialize=[0, 1, 2, 3, 4, 5])

# model.Parameter1 = Param(model.Set1, initialize=pd.Series({0: 400.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 240.0}).to_dict())
model.Parameter1 = Param(model.Set1, initialize={0: 400.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 240.0})

model.Variable1 = Var(model.Set1, initialize=0)

def rule(m, l):
    return -m.Parameter1[l] <= m.Variable1[l]

model.Constraint1 = Constraint(model.Set1, rule=rule)
```

The above works fine. However, if I replace the `initialize` argument for Parameter1 with a Series object converted to a dictionary, I get the following error. 

```
ERROR: Constructing component 'Constraint1' from data=None failed:
        ValueError: Constraint 'Constraint1[0]' does not have a proper value. Found 'True'
        Expecting a tuple or equation. Examples:
           summation(model.costs) == model.income
           (0, model.price[item], 50)
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model.Constraint1 = Constraint(model.Set1, rule=rule)
  File "/Users/$USER/anaconda/lib/python2.7/site-packages/pyomo/core/base/block.py", line 483, in __setattr__
    self.add_component(name, val)
  File "/Users/$USER/anaconda/lib/python2.7/site-packages/pyomo/core/base/block.py", line 849, in add_component
    val.construct(data)
  File "/Users/$USER/anaconda/lib/python2.7/site-packages/pyomo/core/base/constraint.py", line 752, in construct
    cdata = self._check_skip_add(ndx, tmp)
  File "/Users/$USER/anaconda/lib/python2.7/site-packages/pyomo/core/base/constraint.py", line 900, in _check_skip_add
    condata.set_value(expr)
  File "/Users/$USER/anaconda/lib/python2.7/site-packages/pyomo/core/base/constraint.py", line 442, in set_value
    raise ValueError(msg)
ValueError: Constraint 'Constraint1[0]' does not have a proper value. Found 'True'
Expecting a tuple or equation. Examples:
   summation(model.costs) == model.income
   (0, model.price[item], 50)
```

In the example above, I've commented out the line that converts a dictionary to a Series object and back to a dictionary. To reproduce this error, uncomment that line and comment the following line. 

I'm using Pyomo 4.4.1 and Pandas 0.17.1

I've also verified that the two arguments are equivalent.

```
In [1]: import pandas as pd

In [2]: {0: 400.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 240.0} == pd.Series({0: 400.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 240.0}).to_dict()
Out[2]: True
```

 Any idea what is going on? Most of the data I have is in Pandas Dataframes / Series. It is puzzling to me why this does not work.

**Comment by kdheepak** [comment]
So I did some more sleuthing, and it appears that on calling the `to_dict` method of a Series object, Pandas stores the keys and values of the dictionary as numpy types, specifically as `numpy.int64` and `numpy.float64`, whereas Python's default dictionary stores these as `int` and `float` types.

```
In [1]: import pandas as pd

In [2]: x = pd.Series({0: 400.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 240.0}).to_dict()
   ...:
   ...: for k,v in x.items():
   ...:     print(type(k), type(v))
   ...:
(<type 'numpy.int64'>, <type 'numpy.float64'>)
(<type 'numpy.int64'>, <type 'numpy.float64'>)
(<type 'numpy.int64'>, <type 'numpy.float64'>)
(<type 'numpy.int64'>, <type 'numpy.float64'>)
(<type 'numpy.int64'>, <type 'numpy.float64'>)
(<type 'numpy.int64'>, <type 'numpy.float64'>)


In [3]: x = {0: 400.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 240.0}
   ...:
   ...: for k,v in x.items():
   ...:     print(type(k), type(v))
   ...:
(<type 'int'>, <type 'float'>)
(<type 'int'>, <type 'float'>)
(<type 'int'>, <type 'float'>)
(<type 'int'>, <type 'float'>)
(<type 'int'>, <type 'float'>)
(<type 'int'>, <type 'float'>)
```

It appears that this is causing the error. I was able to narrow the root of the problem down to the value portion of the dictionary. The following seems to work in the example above.

```
x = pd.Series({0: 400.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 240.0}).to_dict()
model.Parameter1 = Param(model.Set1, initialize={k: float(v) for k,v in x.items()})
```

So for some reason, Pyomo doesn't seem to like numpy.float64 values when forming Constraints.

**Comment by qtothec** [comment]
At its heart, this issue is then equivalent to an existing issue #31. There's a detailed discussion between the Pyomo devs in there. I have personally come across this problem working with pandas and PyOMO as well, and the float() casting seems to work well.

**Comment by kdheepak** [comment]
Thanks for that comment, that issue has more discussion on this topic. I'll close this issue.

**Comment by jsiirola** [comment]
Actually, I am re-opening this issue.  While it is related to #31, I think this is fixable by changing how Param._initialize_from() works for immutable parameters.  We could perform the cast implicitly for the user to bring the value out of the numpy space.  I am hoping that @whart222 or @ghackebeil will weigh in on that thought.

**Comment by ghackebeil** [comment]
It seems like that is really the only choice as long as singleton Pyomo objects look like they are indexed. I just tested this behavior with the components on the component_storage_interface branch, and it doesn't look like any special handling of numpy types are needed there (because singleton types are not indexed).

**Comment by qtothec** [comment]
I just ran full-speed into this issue again working with pandas, too.
