### ISSUE TITLE
Implement functions to call different visitor implementations

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#681]
I believe that all (most) of the expression visitors should have a function that creates the visitor and calls the walk function for a user. 

For example, instead of the user needing to call:
visitor = ExpressionReplacementVisitor(substitute=submap)
my_constraint.body = visitor.dfs_postorder_stack(other_constraint.body)

that call would look like:
my_constraint.body = replace_expression(other_constraint.body, substitute=submap)

(This is mostly to avoid the need for a user to know that "dfs_postorder_stack" is what executes the visitor.

**Comment by mrmundt** [comment]
@jsiirola - Does the stream based expression visitor address this?

**Comment by jsiirola** [comment]
This is not inherent in the `StreamBasedExpressionVisitor`: it still uses the create / call syntax (just with a different function name):
```python
visitor = StreamBasedExpressionVisitor()
result = visitor.walk_expression(other_constraint.body)
```

That said, many visitors *do* have a function to generate / call the visitor.  That function is convenient, but not very performant, as the visitor is created, used, and thrown away every time the function is called.  The visitors that the users are most likely to encounter (`replace_expression`, `evaluate_expression`, and `identify_variables`, `polynomial_degree`, `expression_to_string`) all have functions.  I believe that it should be OK to close this.
