### ISSUE TITLE
Recent change broke online docs

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#682]
I just happened to looking at the Pyomo Network documentation at:

https://pyomo.readthedocs.io/en/latest/modeling_extensions/network.html

and noticed a significant issue that must have been caused by some recent merges. Namely, none of the autoclass generation executed; they are completely missing from the page. I glanced at the DAE page and the issue seems to have affected it there too. I would guess perhaps for some reason the imports in the rst files are failing. But it's even weirder because when I recompile everything locally using an up-to-date master branch, the autoclasses do work (although I notice an import failure with GurobiPersistent, which may or may not be related).

Also there's a typo in line 112, it should read "At the end of the transformation" (the second "the" is missing).

**Comment by qtothec** [comment]
The docs being broken is in fact quite problematic, since often the users we'd point to online docs are the ones who we would not want trying to build docs themselves.

**Comment by blnicho** [comment]
A quick update on this issue, we're working on a major documentation reorganization in the `docconversion` branch of Pyomo following the new outline discussed in #492. This branch is also being built on readthedocs here: https://pyomo.readthedocs.io/en/docconversion/index.html

I'm hoping to open a PR to get this merged this week which will fix this issue but in the meantime please point users to the docconversion branch.

@gseastream I fixed the typo you pointed out in the `docconversion` branch
