### ISSUE TITLE
Cannot define branch-and-bound order of variables when using CPLEX

### ISSUE THREAD

**Issue by ikonikon** [Pyomo/pyomo#684]
This is an issue regarding the CPLEX solver interface.
According to CPLEX's documentation [here](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.8.0/ilog.odms.cplex.help/CPLEX/Parameters/topics/MIPOrdInd.html) I should be able to define the variable order in the branch-and-bound. However, it is not clear what kind of argument should be provided.

In other words, how do i set up`???` in  the example below? 
```python
solver = SolverFactory("cplex")
results = solver.solve(model, options="mip strategy order = ???", tee=True)
```

Note that this question was also posted in StackOverflow [here](https://stackoverflow.com/questions/47887602/pyomo-setting-variable-branching-priorities) but no clear answer was given.

**Comment by blnicho** [comment]
@ikonikon see the online documentation for how to pass options to a solver: https://pyomo.readthedocs.io/en/stable/working_models.html#sending-options-to-the-solver

If you are still unable to get it working, please ask additional questions on the Pyomo forum.
