### ISSUE TITLE
Cannot do simple scalar variable multiplication...

### ISSUE THREAD

**Issue by anyacastillo** [Pyomo/pyomo#685]
I am unable to multiply numpy.float64 * SimpleVar, but I am able to multiply SimpleVar * numpy.float64. The error is as follows:

KeyError: "Cannot treat the scalar component 'x'as an indexed component"

where 'x' is of type pyomo.core.base.var.SimpleVar.

I am using Pyomo 5.5.1. Do we have support for numpy parameters in the models?

**Comment by blnicho** [comment]
@anyacastillo this is a known bug. See the discussion in #31 for more information.

**Comment by anyacastillo** [comment]
ok, I don't believe that I run into this method when building constraints on block(). Any idea why? E.g., with the matrix_constraint I use the numpy ndarrays for parameterization.

**Comment by sashwatroy11** [comment]
Any progress on this issue?
