### ISSUE TITLE
Unable to get slack with XPRESS.py

### ISSUE THREAD

**Issue by kdheepak** [Pyomo/pyomo#69]
``` python
from pyomo.environ import *

m = ConcreteModel()
m.x = Var()
m.y = Var(bounds=(0,1))
m.o = Objective(expr= m.x + m.y)
m.c = Constraint(expr= m.x >= 1)
m.dual = Suffix(direction=Suffix.IMPORT)
m.rc = Suffix(direction=Suffix.IMPORT)
m.slack = Suffix(direction=Suffix.IMPORT)

solver = SolverFactory("xpress",
                       solver_io="lp")
results = solver.solve(m)

print(m.o())
print(m.x())
print(m.y())
print(m.dual[m.c])
print(m.rc[m.y])
print(m.slack[m.c])

# should print                                                                                 
# 1                                                                                            
# 1                                                                                            
# 0                                                                                            
# 1                                                                                            
# 1                                                                                            
# 0  
```

The output is below.

```
1.0
1.0
0.0
1.0
1.0
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-090dcfa991bb> in <module>()
     19 print(m.dual[m.c])
     20 print(m.rc[m.y])
---> 21 print(m.slack[m.c])
     22 
     23 # should print

/Users/$USER/miniconda2/lib/python2.7/site-packages/pyomo/core/base/suffix.pyc in __getitem__(self, component)
    197             raise KeyError("Component with name: "
    198                            +cname+
--> 199                            " (id=%s)" % id(component))
    200 
    201     def __setitem__(self, component, value):

KeyError: 'Component with name: c (id=4484422800)'
```

The above uses `lpoptimize` in XPRESS.py. Any thoughts on what the problem might be?

**Comment by jotaigna** [comment]
I have an idea about this issue, I faced a similar problem extracting duals. The problem in question had several equalities whose dual had a value of zero. The current XPRESS plugin extracts variables by detecting the type `C` in the second column of a wrtsol solution file. 

All other variables (i.e. `L` for less than constraints, `G` for greater than constraints and `E` for equality constraints) are treated the same: not scanning their type and extracting slacks and duals only if their value is different from zero: https://github.com/Pyomo/pyomo/blob/7beec1ba8b37c4f7b0b666db3d20c8675b0784ae/pyomo/solvers/plugins/solvers/XPRESS.py#L389-L392

They will show in the component map as `None` and return a `KeyError` when read.

I currently work around this by putting a try statement catching the key error when requesting the dual. I could put a PR where I add some more thorough logic to extract duals and slacks:

- positive for duals and non negative for slacks in  `L`
- negative for duals and non positive for slacks in  `G`
-  free for duals and slacks in  `E`.

We could use the example in this thread to add a unit test for slacks but my example is much to big to be included for duals. Would developers accept a PR with limited testing or know a small example where duals are zero? Is a test even feasible without an Xpress license?
