### ISSUE TITLE
Problems with NL file generation?

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#692]
I just noted the following comment in the ASL change log:

>   pfg_read.s, pfghread.c in solvers.tgz: initialize two fields for use with bogus .nl files (e.g., written by pyomo).

It's probably worth following-up to figure out what type of bogus NL files Pyomo is generating.

**Comment by mrmundt** [comment]
@whart222 - What is the status of this issue? Do you know if it has been pursued/resolved?

**Comment by whart222** [comment]
I do not think that anyone followed up on this.  We would need to reach out to Dave Gay, who wrote this log note.
