### ISSUE TITLE
How to import quicksum

### ISSUE THREAD

**Issue by harisbal** [Pyomo/pyomo#722]
Hello,

I've been recently truing to use quicksum but I cannot understand how to import it.
I've tried from `pyomo.environ import *` but I get a 

> NameError: name 'quicksum' is not defined

I'm using pyomo 5.5.0 installed by anaconda

Cheers

-Haris

**Comment by jsiirola** [comment]
`quicksum` was added as part of the `expr_dev` merge.  It is available on master and will be part of the (upcoming) 5.6 release.  It is not in the 5.5.0 release (or earlier).
