### ISSUE TITLE
Custom Solver - Remote access via ssh

### ISSUE THREAD

**Issue by neunzehnachtneun** [Pyomo/pyomo#726]
Hi together,
this isn't really an issue. But either I need some help in finding the right way or this is a feature request. Decide yourself. Anyway, thanks in advance!
We are using to solve a model. To achieve this, there are two possibilities. First we can run test cases locally on our machines with an open source solve like cbc or glpk. This works great. Second we build the whole model locally and want to run it with our (faster) commercial solver using a server, which is reachable via ssh.
As this problem is not solved yet, I would like to ask, if you have any idea, how to run pyomo with a custom remote access solver.

**Comment by blnicho** [comment]
@neunzehnachtneun take a look at the files in this directory for the NEOS solver interface: https://github.com/Pyomo/pyomo/tree/master/pyomo/neos 

NEOS is a server that provides access to several optimization solvers. I'm guessing that you could use a similar interface to invoke your remote solver.

**Comment by neunzehnachtneun** [comment]
Thank you, @blnicho !

I will take a look at NEOS and hopefully this is an approach, that helps us. I will give feedback, when solved.
