### ISSUE TITLE
AMPLFUNC Environment Variable

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#73]
It seems that when you call an ASL solver multiple times from a Python script, and you use ExternalFucntion, the AMPLFUNC environment variable accumulates a bunch of repeated copies of the .so file.  I haven't determined if this causes a real problem yet, but it causes the ASL to spew a bunch of warnings about already defined functions.  I printed the environment variables during an initialization consisting of several solves, so you can get an idea of what's happening

'PYOMO_AMPLFUNC': '../../../properties/physical/MEA_Simple/phys_prop.so'

'AMPLFUNC': '/imports/users/jeslick/git/eslickj/models/idaes_models/properties/physical/MEA_Simple/phys_prop.so\n../../../properties/physical/MEA_Simple/phys_prop.so\n../../../properties/physical/MEA_Simple/phys_prop.so\n../../../properties/physical/MEA_Simple/phys_prop.so\n../../../properties/physical/MEA_Simple/phys_prop.so\n../../../properties/physical/MEA_Simple/phys_prop.so\n../../../properties/physical/MEA_Simple/phys_prop.so\n../../../properties/physical/MEA_Simple/phys_prop.so'

**Comment by whart222** [comment]
Can you add a ticket for this?  This looks like a bug.

**Comment by eslickj** [comment]
Sorry, I'm pretty new to how github works.  I made an issue.  How do I go about adding a ticket?

**Comment by whart222** [comment]
Ah.  I missed that this email was generated from an issue.  Thanks!

**Comment by eslickj** [comment]
Thanks for looking into it.  I've been having some trouble with the solver failing mysteriously, and after a lot of searching this seems to be the culprit.  I did some more testing, and after a certain number of times importing the .so file the ipopt solver segfaults before even getting started.  I have no idea why that would happen. It may be something weird in my user function code.  Anyway this bug does seem to potentially cause more problems than just annoying warning messages.

**Comment by eslickj** [comment]
To follow up on this issue, a couple other people working on IDAES have had problems with ipopt crashing when a library gets included in AMPLFUNC too many times, so this does seem to be an important issue.  Previously I wasn't totally sure whether or not this was a serious issue.

**Comment by jsiirola** [comment]
@eslickj: can you take a look at Pyomo/IDAES-premerge (240d3f9) and see if that resolves this issue?

**Comment by qtothec** [comment]
@eslickj Has this been resolved?

**Comment by eslickj** [comment]
I don't think so.  Just pulled the latest from Master. @jsiirola sorry I probably missed when you asked me to test this back in June.

Here is a bit of code I used to test.  Works if I set AMPLFUNC myself, but not if I don't. Not sure if you have a handy test for this, but I can get you the external function code if it helps.
```Python
from pyomo.environ import *
from pyomo.opt import SolverFactory
import os 

if __name__ == "__main__":
    model = ConcreteModel()
    flib = "./phys_prop.so"
    model.z_func = ExternalFunction(library=flib, function="z_func")
    model.x = Var(initialize=3)
    model.o = Objective(expr=model.z_func(model.x))
    opt = SolverFactory('ipopt')
    os.environ["AMPLFUNC"] = flib
    res = opt.solve(model)
    display(model)
```
