### ISSUE TITLE
Pyomo dependencies

### ISSUE THREAD

**Issue by andreadelprete** [Pyomo/pyomo#731]
Hi, I am not sure this is the right place to ask this question, so I apologize in advance if it's not, but I didn't know where else to do it.

So far I've worked with the `pyomo` version installed through conda (with python 3.6). Now I'd like to start using the development version of `pyomo`, so I can benefit from the latest bug fixes. I've downloaded the code, installed it, and configured my `PYTHONPATH` so that the development version is found before the conda version. The problem is that when I execute the command `import * from pyomo.environ` I get the following error:
```
Original ModuleNotFoundError: No module named 'pyutilib.factory'
```
The library `pyutilib` is actually installed (in my conda environment), but it does not contain the module `factory`. Probably this is an issue of library versions. I guess that the `pyomo` version installed through conda depends on a certain version X of `pyutilib`, whereas the development version of `pyomo` depends on another version Y>X of `pyutilib`. Is there a way to understand the exact dependencies of the development version of `pyomo`?

**Comment by blnicho** [comment]
If you want to work off of the development version of Pyomo then you will also need the development version of Pyutilib. They are a matched set and are usually updated concurrently.

**Comment by DLWoodruff** [comment]
Short version to get started: find pyutilib on gitub and clone it, then cd
to it and do
python setup.py develop

**Comment by andreadelprete** [comment]
Thanks for the help. Now it's working!

Just a note on a problem I've encountered in this process. Modifying my `PYTHONPATH` was not enough to get the development version of `pyutilib` be found before the conda version. It seems to me that this is due to the way in which `pyutilib` is configured in conda (i.e. using a pth file), which is different from `pyomo`. The workaround I've found to make it work has been to remove the file `$ANACONDA_HOME/envs/py36/lib/python3.6/site-packages/PyUtilib-5.6.3-py3.6-nspkg.pth`. 

Maybe someone could suggest me a cleaner way of achieving the same result. I was thinking I could uninstall `pyutilib` through conda, but I'm afraid that would trigger the uninstallation of all packages depending on it, including `pyomo` and its dependencies, and so break my whole environment.

**Comment by KOLANICH** [comment]
I guess for the installations from git you should add pep 503 uri specifiers into each dependency to make pip load them from git, not fom pypi.

**Comment by andreadelprete** [comment]
> I guess for the installations from git you should add pep 503 uri specifiers into each dependency to make pip load them from git, not fom pypi.

I don't know whether it matters, but for installing I am not using pip, but conda.

**Comment by qtothec** [comment]
Closing as resolved. Follow up in https://github.com/Pyomo/pyomo/issues/734
