### ISSUE TITLE
Pyomo Network readthedocs missing code block

### ISSUE THREAD

**Issue by gseastream** [Pyomo/pyomo#741]
The code block for the Sequential Decomposition section of the [pyomo network readthedocs page](https://pyomo.readthedocs.io/en/latest/modeling_extensions/network.html) is missing. When I compile it locally it shows up properly. The other code blocks show up fine online as well, this is the only one that's missing. The only difference between this one and other code blocks is the use of relatively new sphinx `skipif` feature, so it might be a version thing, but I couldn't figure out what version our readthedocs page is using (if it's even set anywhere).

**Comment by blnicho** [comment]
Do you know if this is a Python-specific feature? Currently our documentation is built using 2.x. Are you using 3.x?

Also, it looks like readthedocs runs Sphinx 1.7.9 and I can't find a configuration option to change it.

**Comment by gseastream** [comment]
I don't think it's a python issue. According to [this](http://www.sphinx-doc.org/en/master/changes.html), the skip feature was added in Release 1.8.0 (released Sep 13, 2018), so it sounds like that's definitely the issue.

**Comment by qtothec** [comment]
Appears to be a remedy suggested at https://github.com/rtfd/readthedocs.org/issues/2149#issuecomment-373942540

**Comment by gseastream** [comment]
It all looks good now. Closing.

**Comment by blnicho** [comment]
@gseastream yes it was merged into master and I thought it was resolved. Must be something going wrong on the readthedocs side. I'll take another look.
