### ISSUE TITLE
Pyomo 5.5.1 / python 3.7 not on conda forge

### ISSUE THREAD

**Issue by mangecoeur** [Pyomo/pyomo#744]
The conda forge page doesn't have files for the latest Pyomo, and also is missing files tagged for python 3.7 compatibility.

https://anaconda.org/conda-forge/pyomo

**Comment by whart222** [comment]
I've updated the Pyomo conda-forge feedstock, and 5.5.1 is now on conda-forge.

I updated the feedstock, and only Python 3.6 is created.  I suspect that conda-forge does not yet build Python 3.7 packages, but I'm checking into that.

**Comment by jehill17** [comment]
Is it possible to revert back to an old version? I am having issues running a script in Python 3.6 using Pyomo 5.6.1. Would like to reinstall 5.5.1.

**Comment by mangecoeur** [comment]
You can always specify which version of a package you want installed with conda - see 
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-packages
