### ISSUE TITLE
Finalize migration to Pyomo5 expression system

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#75]
This ticket documents progress towards finalizing our migration to a new expression system.

**Comment by whart222** [comment]
@jsiirola @ghackebeil : I've added a branch for development to resolve this issue: new_expressions 

I have also enabled PyPy test on this branch, whose failures should illustrate the changes that are needed.

**Comment by blnicho** [comment]
Pyomo5 expressions were merged in #272 so this can be closed
