### ISSUE TITLE
Addition termination_condition and support in CBC

### ISSUE THREAD

**Issue by bertrandhaut** [Pyomo/pyomo#76]
I refer to https://software.sandia.gov/trac/pyomo/ticket/4626 and https://groups.google.com/forum/#!starred/pyomo-developers/mdxSH1SPCjg

Some additional termination_condition are need to cover some cases. In particular the support of intermediate non integer solution for CBC.

The following proposal https://github.com/bertrandhaut/pyomo/commit/6792a583ddb3e474a6ec2a6a2e0a9a03509edc52 solves this issue. 

More precisely:
 - new termination_status added: intermediateNonInteger and noSolution. I've inspired myself from GAMS status
- modification of comment associated to the maxTimeLimit to highlight the fact that a solution is nevertheless return.
- improvement for the CBC plugin:
    - support of the "Stopped on Time - no integer solution" status
    - support of the "Stopped on Time - a solution" status
    - support of the Optimum status when no discrete variable are present (the log file is formatted otherwise)
    - [security issue] switch from "eval" to "float" for string conversion when I was sure that it will have no impact on the rest of the code. All other "eval" should probably be also changed.

What do you think ?

**Comment by jsiirola** [comment]
Looks reasonable to me.  I have opened PR #77 -- let's move the discussion there.

**Comment by ghackebeil** [comment]
#77 has been merged
