### ISSUE TITLE
Pyomo and numpy.linalg.inv

### ISSUE THREAD

**Issue by alishahmohammadi** [Pyomo/pyomo#762]
Hi,
I am trying to model-based experiments for a system of ODEs. it is a simple process. It needs computation of sensitivities with respect to parameters (Z matrix) and to minimize the following objective function for selecting A-optimal experimental setting:
min trace(inv(Z'Z))
s.t odes and its constraints

Unfortunetly, Pomo doesn't accept the numpy inverse function or maybe numpy inverse doesn't accept pyomo. 
Can you please advice me what should I do?
Ali

**Comment by blnicho** [comment]
Numpy and Pyomo are not compatible in the way you describe. The numpy inverse and trace functions expect a matrix of numeric values. Objective functions in Pyomo are expected to be algebraic expressions involving Pyomo Var objects. There has been some discussion of supporting matrix operations directly in Pyomo but this is a long way off. One way to solve this using Numpy and Pyomo today is to implement your own iterative meta-algorithm that translates the value of Z between Numpy and Pyomo. However, this is outside of the scope for Pyomo Github issues so I'm closing this.

**Comment by wangyexiang** [comment]
> 

Dear sir, do you solve this problem?
