### ISSUE TITLE
SolverManagerFactory does not remove auxiliary files

### ISSUE THREAD

**Issue by GiorgioBalestrieri** [Pyomo/pyomo#770]
Hi,

I'm using `SolverManagerFactory` to send problems to the neos server, but the .nl, and .log files are not eliminated (as it happens with `SolverFactory`).

```python
with SolverManagerFactory('neos') as solver_manager:
    results = solver_manager.solve(model, opt='cbc')

print(results.solver)
```

Am I missing something? When using the same solver (cbc) locally through `SolverFactory`, the auxiliary files are removed automatically once the solver is done.
It's not much work to eliminate the files through `pathlib.Path.unlink`, of course.

**Comment by blnicho** [comment]
@GiorgioBalestrieri what version of Pyomo are you using? I believe a similar issue was fixed either in the most recent release or on master.

**Comment by blnicho** [comment]
@GiorgioBalestrieri could you update to the most recent Pyomo release (5.6) and see if this resolves the issue?

**Comment by GiorgioBalestrieri** [comment]
Hi @blnicho,

I'm using Windows 10 (x64), just updated Pyomo trough Anaconda. I have
- pyomo 5.6-py36_1001 from conda-forge
- pyutilib 5.6.4-py36_1000 from conda-forge

I just tried running:
```python
with SolverManagerFactory('neos') as solver_manager:
    results = solver_manager.solve(model, opt='cbc')

print(results.solver)
```

and got the following error: `name 'SolverFactory' is not defined`.

I'm not sure what the cause might be, but I never had this issue before.

Full trace below:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-38d89555498d> in <module>
      8     # results = solver_manager.solve(cm, opt='cbc')
      9     opt = pe.SolverFactory('cbc')
---> 10     results = solver_manager.solve(cm, opt=opt)
     11 
     12 print(results.solver)

~\AppData\Local\Continuum\anaconda3\envs\optim\lib\site-packages\pyomo\opt\parallel\async_solver.py in solve(self, *args, **kwds)
     26 
     27     def solve(self, *args, **kwds):
---> 28         return self.execute(*args, **kwds)
     29 
     30     def solve_all(self, solver, instances, **kwds):

~\AppData\Local\Continuum\anaconda3\envs\optim\lib\site-packages\pyomo\opt\parallel\manager.py in execute(self, *args, **kwds)
    105         Synchronously execute an action.
    106         """
--> 107         ah = self.queue(*args, **kwds)
    108         results = self.wait_for(ah)
    109         if results is None:

~\AppData\Local\Continuum\anaconda3\envs\optim\lib\site-packages\pyomo\opt\parallel\manager.py in queue(self, *args, **kwds)
    120         ah.status = ActionStatus.queued
    121         self.queued_action_counter += 1
--> 122         return self._perform_queue(ah, *args, **kwds)
    123 
    124     def wait_all(self, *args):

~\AppData\Local\Continuum\anaconda3\envs\optim\lib\site-packages\pyomo\neos\plugins\kestrel_plugin.py in _perform_queue(self, ah, *args, **kwds)
    109             del user_solver_options['timelimit']
    110 
--> 111         opt = SolverFactory('_neos')
    112         opt._presolve(*args, **kwds)
    113         #

NameError: name 'SolverFactory' is not defined
```

**Comment by GiorgioBalestrieri** [comment]
Wow, great to know this has already been identified!

Anyway I have GLPK, but my issue with auxiliary files not being removed was specifically related to using NEOS through `SolverManagerFactory`. 

I'm probably missing something, but I'm not sure why I would call GLPK through `SolverManagerFactory` instead of `SolverFactory`. 

If you can point me to an example of how to do that I'm happy to test it, but before closing the issue it would be good to ultimately test with NEOS.

Thanks for the support!

**Comment by blnicho** [comment]
Ok, sorry I missed the context that it was the `SolverManagerFactory` and not the `SolverFactory`. I suggest we revisit this next week after the patch release is out.

**Comment by GiorgioBalestrieri** [comment]
I tested with 5.6.1 and the temporary files seem to be cleaned up properly. This is great!

As a side note, using NEOS does not display any messages anymore, and I'm not sure where to look up the documentation about restoring the previous "verbose" behavior.

**Comment by blnicho** [comment]
Great, glad to hear that this is fixed. Try adding the `tee=True` option to your call to `solve`. That should stream the solver output to the screen.

**Comment by blnicho** [comment]
I tested my suggestion and it doesn't work, I'm not super familiar with the NEOS interface. I think streaming the solver output is tangential to this issue so I'm going to close it. I recommend asking about displaying NEOS output on the Pyomo Forum.
