### ISSUE TITLE
results = opt.solve(model, tee=True) 

### ISSUE THREAD

**Issue by quan12jiale** [Pyomo/pyomo#789]
Restoration phase converged to a feasible point that is
unacceptable to the filter for the original problem.

**Comment by jsiirola** [comment]
Unfortunately, this is a statement on the return status for an unknown problem by an unknown solver on an unknown platform.  Issues need to either clearly state the problem with enough information to reproduce the problem, or state the proposed enhancement.  I am closing this as there isn't anything we can do given the information provided.

**Comment by quan12jiale** [comment]
Use ipopt to solve a nonlinear problem, the code is as follows:results = opt.solve(model, tee=True).
The program runs as follows：
Restoration phase converged to a feasible point that is
unacceptable to the filter for the original problem.
Restoration phase in the restoration phase failed.

Number of Iterations....: 516

                                   (scaled)                 (unscaled)
Objective...............:  5.5298190807960503e+007   5.5298190807960503e+007
Dual infeasibility......:  9.9999999998304112e-001   9.9999999998304112e-001
Constraint violation....:  6.4773013031174060e-011   5.2154064178466790e-008
Complementarity.........:  9.0909090915689511e-012   9.0909090915689511e-012
Overall NLP error.......:  9.9999999998304112e-001   9.9999999998304112e-001
...
EXIT: Restoration Failed!
...
  File "H:/project/InteEnergy.py", line 203, in <module>
    results = opt.solve(model, tee=True)

  File "D:\Anaconda3\lib\site-packages\pyomo\opt\base\solvers.py", line 659, in solve
    default_variable_value=self._default_variable_value)

  File "D:\Anaconda3\lib\site-packages\pyomo\core\base\PyomoModel.py", line 249, in load_from
    % str(results.solver.status))

ValueError: Cannot load a SolverResults object with bad status: error

**Comment by jsiirola** [comment]
Ipopt returns "Restoration Failed" when it is unable to restore feasibility (technically, when it cannot reduce the primal infeasibility).  The objective value is meaningless at this point, as the constraints are not satisfied.  From the Ipopt manual, 
```
Console Message: EXIT: Restoration Failed!
This indicates that the restoration phase failed to find a feasible point that was acceptable to the
filter line search for the original problem.  This could happen if the problem is highly degenerate,
does  not  satisfy  the  constraint  qualification,  or  if  your  NLP  code  provides  incorrect  derivative
information.
```

Regardless, this is an issue with your model and not an issue with Pyomo.

**Comment by rhshadrach** [comment]
Restoration can also fail at feasible point, if the point is not acceptable to the filter. This filter is used in part to prevent the search from getting stuck in an infinite loop.
