### ISSUE TITLE
Pyomo.GDP logo

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#816]
Lianna Dang has been volunteering some of her time so that we can have a logo for Pyomo.GDP. I want to restart the conversation that I had been having with @jsiirola and a few others. Below are the current drafts. Chime in if you have opinions:

Version 5.3:
![test5 3](https://user-images.githubusercontent.com/5910700/51448199-c9834f00-1cf2-11e9-91b3-ed1ffc815486.png)

Version 5.2:
![test5 2](https://user-images.githubusercontent.com/5910700/51448203-d1db8a00-1cf2-11e9-9d4e-0d96089a7309.png)

Version 5.1:
![test5 1](https://user-images.githubusercontent.com/5910700/51448209-d738d480-1cf2-11e9-97a4-86ea5f0364a7.png)

Version 5.0:
![test5](https://user-images.githubusercontent.com/5910700/51448228-064f4600-1cf3-11e9-87eb-522315bb42c6.png)

Version 4:
![test4](https://user-images.githubusercontent.com/5910700/51448217-f33c7600-1cf2-11e9-9b03-285a2ce81b68.png)

**Comment by jsiirola** [comment]
I still like v4, but I agree that it lacks the subtlely of the other logos.  I also worry that the birds will be too small when rendered on things like stickers or presentations.  The larger birds of 5.0 are really good, but the asymmetry of the two sides of the "V" stretch the analogy to the logical or.

Another idea: would it look good to take (a few or all of) the 5 birds from Pyomo.DAE and arrange them into a V?  I think the things that bother me about 5.0 is that the birds are all in the same pose and the colors are "layered".

**Comment by carldlaird** [comment]
It is also a good idea to try and match the asset ratio of the existing logo. This was not done for the original PySP, but I believe that the aspect ratio for Pyomo, DAE, and the new PySP logos match.

**Comment by jsiirola** [comment]
Unfortunately, none of our logos are the same aspect ratio: they are all different widths. I think the best we can hope for is for all the text to be the same size if the images are scaled to the same height; which may be exactly what @carldlaird is referring to.

**Comment by bernalde** [comment]
I really like v4. The underlying OR sign in v5.* was not immediately clear to me. If I had to choose between the v5.* I would choose v5.3 (symmetry and no line underneath).

**Comment by lannydstar** [comment]
v6: incorporated DAE birds
![test6](https://user-images.githubusercontent.com/47646140/52819895-26fb8900-3070-11e9-8350-29b427553f96.png)

**Comment by jsiirola** [comment]
I like v6!  Here is a slight variation, with the birds flying more level.
![gdp-logo-v6a](https://user-images.githubusercontent.com/356359/52825660-d2a9d680-307a-11e9-8a0a-f71ef507c2af.png)

**Comment by qtothec** [comment]
I'm not sure I like the level flight as much. There's less cohesiveness to the birds that way. With v6.0, it looks like a bird landing and taking off again.

**Comment by emma58** [comment]
Oooo, I also really like v6! What about a combination: if the first bird was flying straight(er), but the others were changing level, so something like this: (Sorry, my hacking clipped the wing of the second bird...)
![image](https://user-images.githubusercontent.com/12833636/52871639-81502480-3118-11e9-9a45-f76faf737a3c.png)

**Comment by jsiirola** [comment]
I like @emma58's suggestion.  Rotating the first bird also makes them all look more "individual".

**Comment by qtothec** [comment]
Yeah, that makes a lot of sense. How much padding do we need to make it the same height as the other pictures with the same size text?

**Comment by lannydstar** [comment]
I'll call this 6.2, based on @emma58 's suggestion. The aspect ratio now matches the DAE logo quite closely. Compared to the PySP logo, the largest bird in PySP is close to the same size as the birds in 6.2 but 6.2 is slightly wider than PySP. 
![test62](https://user-images.githubusercontent.com/47646140/52881985-e2352800-312b-11e9-9170-7735ff47e77e.png)
