### ISSUE TITLE
Arithmetic error in AMPL data file error checking

### ISSUE THREAD

**Issue by DLWoodruff** [Pyomo/pyomo#82]
This is not an example that should work; it is only an example that shows an error in error reporting. The message is
"""
pyomo solve ~/software/pyomo/examples/pysp/farmer/models/ReferenceModel.py farmer/Scenario_Average.dat --solver=cplex
[    0.00] Setting up Pyomo environment
[    0.00] Applying Pyomo preprocessing actions
[    0.00] Creating model
[    0.01] Pyomo Finished
ERROR: Unexpected exception while running model:
	Syntax error at token SEMICOLON with value ';' in line 17 at column 24
"""

But both 17 and 24 seem to incorrect (line 17 is particularly incorrect).
[farmer.zip](https://github.com/Pyomo/pyomo/files/644178/farmer.zip)

**Comment by whart222** [comment]
I don't see a Scenario_Average.dat file in this ZIP file.

**Comment by DLWoodruff** [comment]
Bummer. Sorry about that. Next time I see it, I will be more careful creating the zip file.

**Comment by whart222** [comment]
Can you describe the error?  I need to fix the DAT parser, so I can try to create a test case that reflects what you saw...

**Comment by DLWoodruff** [comment]
Try this zip. The line number and column number in the error message are off by a little.
[farmer.zip](https://github.com/Pyomo/pyomo/files/656306/farmer.zip)
