### ISSUE TITLE
Maximum / Minimum between expressions

### ISSUE THREAD

**Issue by Bougeant** [Pyomo/pyomo#821]
Hi,

I am trying to create constraints and an objective function that requires a maximum function between a list of Pyomo expressions. For example, let's say I have 30 expressions: I want to be able to use the expression that has the maximum value among those 30 expressions as the objective function.

Unfortunately, the built-in IF/THEN/ELSE pyomo function doesn't work because the expression then becomes extremely long due to the large number and complexity of the expressions. This results in a lot of nested ifs: if(if(if(if(if.... and it takes forever to run.

Is there a min or max function available? If not, is there a guideline to create our own functions?

**Comment by qtothec** [comment]
I am going to close this as resolved, but if you have a use case that is not addressed by @RomeoV's answer above, then we can reopen this discussion.

**Comment by Fengyuan-Shi** [comment]
You can reformulation the max(·) and min(·) function as follows:
`z==max(x,y) equal to x<=z, y<=z, x>=z-M(1-u_1), y>=z-M(1-u_2), u_1+u_2>=1, u_1,u_2 in {0,1}`
and 
`z==min(x,y) equal to x>=z, y>=z, x<=z+M(1-u_1), y<=z+M(1-u_2), u_1+u_2>=1, u_1,u_2 in {0,1}`

**Comment by Bougeant** [comment]
Maybe I should have been clearer when describing the problem:

Let's imagine that I have 30 different tasks and that I want to allocate workers so that the maximum number of workers allocated to a task does not account for more than 10% of all workers, when possible (I cannot use a constraint because it would not always be possible and I want to optimize the allocation by making sure that the maximum fraction of workers allocated to a task is as small as possible).

It is possible do do it with IF/THEN/ELSE statements but you basically need N! of them (in this case 30! = 2.7e32). I don't understand how to use RomeoV and Fengyuan-Shi's proposed solutions to solve this.

**Comment by Fengyuan-Shi** [comment]
The procedure depend on your design of formulation. Decision maker have to allocate workers to tasks and optimize the allocation solution, so the worker set is `W`, the task set is `T`, the work number allocated to task `t` is `n_t`, which is a nonnegative integer decision variable. In your describe, the constraints as follows:
`sum(n_t for t in T) <= |W|`
`max(n_1, n_2, ...) <= 0.1|W|`
by the way, `|M|` denotes number of compoments in the set `W`. 
The second constraint should be a group of constraints, reformulation of the second constraint as follows:
`e1: z == max(n_1, n_2, ...)` -->`n_t <= z, n_t >= z-M(1-u_t), sum(u_t for t in T) >= 1, u_t in {0,1}`
`e2: z <= 0.1|W|`
constraint `e1` in your procedure should be:
`for t in T:`
`   model.Constraint( n_t <= z, n_t >= z-M(1-u_t) )`
`end for`
`sum(u_t for t in T) >= 1`
The constraint `e2`:
`model.Constraint(z <= 0.1|M|)`

**Comment by QinBa** [comment]
This is a closed issue. But I post my doubts here. Please ignore me if what I would say does not make any sense. I am still trying to understand the boundary of Pyomo's applicability. 

The comments by @RomeoV seems to imply that Pyomo can not handle non-differentiable functions. (Note the typo in @RomeoV's comments: max operation is not differentiable, but continuous). However, at the same, I notice Pyomo has built support for _Piecewise Functions_, which makes me confused. Any clarification on this is appreciated. 

I understand the problem posted by @Bougeant can be solved by problem reformulation. However, in many cases, non-differentiable functions can be useful. It would be a pity that Pyomo, as a modeling tool, does not support them. In my opinion, the difficulty from non-differentiability should be handled by solvers and users. Pyomo may raise a warning if it wish to provide some guidance on how to effectively model a problem. 

A situation I find myself dealing with non-differentiable functions even for differentiable problems is in studying penalty methods. Some solvers do solve problems by penalizing constraints. There are some user cases that people may wish be able control how to penalize constraints. It would be great if Pyomo can still be useful there.

**Comment by qtothec** [comment]
I am aware of increasing interest in my part of the optimization field with respect to handling non-differentiable functions, e.g. from Prof. Barton's group. I think that the support (or lack thereof) that you may see is a consequence of the fact that none of the main package contributors have critical applications that require such built-in capabilities.
I believe Piecewise was created to help with some programmatic reformulations, but someone else would need to comment on the nature of its support.

**Comment by joseortiz3** [comment]
Pyomo could have a maximum operator that can only be used in objective functions
`pe.max_over_expressions(f[i] for i in model.num_expressions)`

that would then use @RomeoV's trick to create a new variable to be maximized and new constraints that the variable must be less than any of the expressions. Just an idea.
