### ISSUE TITLE
Consistent-ifying our doc strings

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#828]
There are inconsistencies in the code regarding the docstring format (e.g., numpydoc or google). We should decide on the format we prefer and work to move the documentation towards the single format.

Note that this is more than just a style issue since there is significant cleanup required to make sure the docstrings are rendering correctly in the online documentation.

**Comment by blnicho** [comment]
We had this exact discussion last year: https://groups.google.com/forum/#!searchin/pyomo-developers/numpydoc%7Csort:date/pyomo-developers/_GWsbowflIQ/CzOsmmmgBwAJ

I thought we had settled on numpydoc format but we should probably take an official vote at our next dev meeting.
