### ISSUE TITLE
Appveyor Failure on Python 3.7

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#829]
Looks like Appveyor started failing on Python 3.7 with the error message:

    conda-script.py: error: unrecognized arguments: --no-update-dependencies

I think this might be caused by the new conda version (4.6.1) that was just released but I haven't been able to figure out why or how to fix it. I can't find any evidence that `--no-update-dependencies` was deprecated or removed.

**Comment by jsiirola** [comment]
This was hard to track down, but `--no-update-dependencies` was removed from the conda script in April 2018 by [3f32ae5](https://github.com/conda/conda/commit/3f32ae527863bf0b7b6ab0b3fe4df7062d9621e0#diff-aa5c1e6732e4802903e91fe909341fd0).  As @carldlaird pointed out elsewhere, `--no-update-deps` appears to be supported  both before and after that commit, so should be safe for our build harness.
