### ISSUE TITLE
Non-deterministic behavior with Set (shouldn't the default be ordered)

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#835]
I thought that pull request https://github.com/Pyomo/pyomo/pull/568 was going to make Sets be ordered by default. However, the following behavior illustrates that this is not the case.

Please see the following code:
```
from pyomo.environ import *
a = ["a", "x", "c", "b"]

model = ConcreteModel()
model.S = Set(initialize=a)
model.OS = Set(initialize=a, ordered=True)

model.S.pprint()
model.OS.pprint()

print('set not ordered: {}'.format([i for i in model.S]))
print('set ordered: {}'.format([i for i in model.OS]))
```

The first time I run this, I get:
```
S : Dim=0, Dimen=1, Size=4, Domain=None, Ordered=False, Bounds=None
    ['a', 'b', 'c', 'x']
OS : Dim=0, Dimen=1, Size=4, Domain=None, Ordered=Insertion, Bounds=None
    ['a', 'x', 'c', 'b']
set not ordered: ['c', 'a', 'x', 'b']
set ordered: ['a', 'x', 'c', 'b']
```

and the second time, I get:
```
S : Dim=0, Dimen=1, Size=4, Domain=None, Ordered=False, Bounds=None
    ['a', 'b', 'c', 'x']
OS : Dim=0, Dimen=1, Size=4, Domain=None, Ordered=Insertion, Bounds=None
    ['a', 'x', 'c', 'b']
set not ordered: ['c', 'a', 'b', 'x']
set ordered: ['a', 'x', 'c', 'b']
```

To me, this implies the following:
1) ordered does not appear to be the default (see the Set pprint)
2) If you mark a set as ordered, then the order in the set appears to be the same as the initialize list and the order is maintained during iteration.
3) If you do not mark a set as ordered, then the order in the set is not the same as the initialize list (although it appears to be consistent), but the order during iteration is not consistent (and does not match the order in the Set).

**Comment by carldlaird** [comment]
@jsiirola indicated that there is sorting done in the Set's pprint method, so that explains why the order appears consistent in the set even if ordered is not set to True. The concern is still present that ordered does not appear to be the default behavior.

**Comment by carldlaird** [comment]
Quoting a comment in the conversation from the original pull request,

>After thinking about this and the response to my thoughts about 'ordered=True', I realized that we shouldn't change the default value of 'ordered'.  Instead, we should change the storage mechanism when 'ordered=False'.  I've commit these changes, which should be reviewed.
>
>The basic idea is that even when the user doesn't specify 'ordered=True', the insertion order is preserved and used when iterating over the set.  When specifying 'ordered=True', not much more happens;  there's an API change allowing methods like next() and prev(), since the user has indicated that these are valid operations on their set.

_Originally posted by @whart222 in https://github.com/Pyomo/pyomo/pull/568#issuecomment-397881930_

I think that "the insertion order is preserved and **used when iterating over the set**." is not working. I think that this behavior is the desired behavior, but not what is being observed.

**Comment by andrewlee94** [comment]
@carldlaird Should we talk about this next week when we are at Sandia?
