### ISSUE TITLE
Clarify documentation for updating a Param value

### ISSUE THREAD

**Issue by mfripp** [Pyomo/pyomo#838]
The [online documentation](https://pyomo.readthedocs.io/en/latest/working_models.html#changing-the-model-or-data-and-re-solving) recommends that we do repeated solutions with different parameter values by updating instance data like `instance.ParamName[idx].value`. However, at least in Pyomo 5.1.1 or 5.6.1, `instance.ParamName[idx]` is a simple value with no `.value` attribute, so attempting this gives an `AttributeError`. Here is some example code:

    import pyomo.environ as pyo
    i = pyo.ConcreteModel()
    i.param = pyo.Param(['a', 'b'], initialize=lambda m, k: 1)
    i.param.display()
    i.param['a'].value = 2  # AttributeError: 'int' object has no attribute 'value'
    type(i.param['a']) # int

I don't know if this worked in some earlier version of Pyomo, but it doesn't seem to now. So I assume the online documentation needs to be updated.

**Comment by DLWoodruff** [comment]
Thanks. I will update the documentation. For the record, there are two
mistakes in that documentation (the Param needs to be mutable as well).
Here's something that works:

import pyomo.environ as pyo
i = pyo.ConcreteModel()
i.param = pyo.Param(['a', 'b'], initialize=lambda m, k: 1, mutable=True)
i.param.display()
i.param['a'] = 2
type(i.param['a']) # int
i.param.display()

**Comment by mfripp** [comment]
The [page I linked to](https://pyomo.readthedocs.io/en/latest/working_models.html) doesn't mention the `mutable` flag, so it may be helpful to add that. I was already familiar with the `mutable` flag, but when I read this, I thought it was introducing a more general approach (that's what I get for skimming!).

**Comment by mfripp** [comment]
For what it's worth, the approach I have always used was more like this:

    i = pyo.ConcreteModel()
    i.param = pyo.Param(['a', 'b'], initialize=lambda m, k: 1, mutable=True)
    i.param['a'] = 2

Are we now advised to use ` i.param['a'].value = 2` instead of ` i.param['a'] = 2`?

**Comment by DLWoodruff** [comment]
(and, actually, if the Param is mutable, the .value does work for
assignment; I'll still fix the documentation to remind folks that a Param
needs to be mutable if you want to change its value and to document the
"direct" assignment of a value). Thanks again for your report.

**Comment by mfripp** [comment]
No problem. Looks like our postings are crossing each other. 

I also just noticed that when `i.param` is not mutable, trying to assign `i.param['a'] = 2` gives "TypeError: Attempting to set the value of the immutable parameter param[a]..." (correct behavior), but trying to assign `i.param['a'].value = 2` gives a much less helpful error message: "AttributeError: 'int' object has no attribute 'value'".

**Comment by jsiirola** [comment]
Agreed.  I generally avoid the `.value` attribute, both for setting and retrieving the value for exactly the reasons @mfripp lays out.  @DLWoodruff, if you are going to take a stab at updating the examples, I advocate promoting
```
m.param['a'] = 5
m.var['a'] = 5
```
for setting values and 
```
value(m.param['a'])
value(m.var['a'])
```
for retrieving values.

**Comment by blnicho** [comment]
I changed the title of this issue to match the current plan for closing it.

**Comment by carldlaird** [comment]
Good idea. Thanks.

**Comment by DLWoodruff** [comment]
I'm slowed down a little bit by the need to deal with .default() because it is documented alongside value; however .default() is a little more complicated because i.myparm['a'].default() does not work, but
i.myparm.default() does, which is a bit of a mouthful to say in general.
