### ISSUE TITLE
Problem declaring indexed component with a generator

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#84]
Consider the following simple example:
```
from pyomo.environ import *

A = {(1,2):3, (4,5):6}

M = ConcreteModel()
M.x = Var(A.keys())
```

This examples with Python 3.5 because keys() is a generator.  Also, Pyomo cannot figure out what to do with a generator that returns tuple index values.

**Comment by blnicho** [comment]
This appears to have been fixed at some point. I confirmed that the MWE above works as expected in Python 3.5. Closing this.
