### ISSUE TITLE
Multiple methods for differentiation in different locations

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#840]
There are multiple functions for differentiation (pyomo/core/base/symbolic.py and pyomo/contrib/derivatives/differentiate.py). Consider putting these in the same location and possibly adding a wrapper function.

**Comment by qtothec** [comment]
How do you intend to have the "user" indicate which implementation of differentiation they want to use?

**Comment by michaelbynum** [comment]
@qtothec I'm not sure yet... Do you have opinions?

**Comment by qtothec** [comment]
Naive approach would be just to add a flag to the end of the current function, but how many users would want to specify that who wouldn't also just be able to import a different differentiate function?

More useful would be API stability between the different potential functions.

**Comment by jsiirola** [comment]
I am wondering if this should all be moved into `pyomo.core.expr`.  We could provide a standard "wrapper" interface class that allows for plug-in backends.  A user could then do something like:
```
from pyomo.core.expr import Differentiation
# ...
derivative = Differentiation(backend="sympy")
dfdx = derivative(m.f.body, wrt=m.x)
```

I am open to making the API almost anything.  For example, the above is basically a Factory, so maybe we should omit the "`backend=`" keyword.

**Comment by whart222** [comment]
I agree that pyomo.core.expr is a natural place for this.
