### ISSUE TITLE
Reaffirm changes to basic step code

### ISSUE THREAD

**Issue by RomeoV** [Pyomo/pyomo#844]
## Summary
I am implementing a GDP Basic Steps example. So far, none of the basic steps examples I found actually reformulated/solved the problem. When I tried to solve the problem, the problem turned out to be infeasible after applying the basic step.
Originally the problem was solved by going to [the basic_steps.py file](/RomeoV/pyomo/blob/implementing_basic_step_example/pyomo/gdp/basic_step.py) and replacing `d.deactivate()` by `d._deactivate_without_fixing_indicator()`: [see here](https://github.com/RomeoV/pyomo/blob/8acaa8135e2cd2d9afc61324a75cc3637cb18fc9/pyomo/gdp/basic_step.py#L113-L119)
This originally fixed the problem, until I merged the current master branch (f93e439ce51350c26f62bf66ee6164ad13560635). Afterwards the probem reappeared. After consulting with @qtothec, I changed a line in the [gdp_var_mover.py file](/RomeoV/pyomo/blob/implementing_basic_step_example/pyomo/gdp/plugins/gdp_var_mover.py), see [here](https://github.com/RomeoV/pyomo/blob/b9b6cd9010f35e60d4520bc69ac2aeac7ece8ce2/pyomo/gdp/plugins/gdp_var_mover.py#L103).
Now the example works so far, but I would prefer for someone to recheck if those changes can be made like this or influence something else.

## Steps to reproduce
Check out [the branch on my fork](/RomeoV/pyomo/tree/implementing_basic_step_example) and run [the example file](/RomeoV/pyomo/blob/implementing_basic_step_example/examples/gdp/small_lit/basic_step.py)

**Comment by qtothec** [comment]
Making this change does not appear to break anything in GDPopt tests or most of my models.

**Comment by qtothec** [comment]
The motivation behind the edit is that `gdp.reclassify`calls `deactivate()` on disjuncts that were never expanded.
However, after a basic step `[Y1] OR [Y2] and [Y3] OR [Y4]` is applied, the original disjuncts (e.g. `[Y1]`) do not get expanded, and the linking logical relations `[Y1] --> ([Y1 AND Y3] OR [Y1 AND Y4])` end up resolving to `FALSE --> ([Y1 AND Y3] OR [Y1 OR Y4])`, leading to infeasibilities.

**Comment by blnicho** [comment]
@RomeoV if you open a PR with this change it will trigger our automated testing infrastructure and we'll have a better idea if this change breaks anything. It will also make it easier for us to look at the code changes you're proposing.
