### ISSUE TITLE
Improvements needed for feasibility based bounds tightening

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#846]
The fbbt module has a list of expressions that it handles. However, this list is not complete (for example, it is missing all the NPV_... expressions and many others). These should be added at some point for completion.

**Comment by michaelbynum** [comment]
The NPV expressions have been included in #825.

**Comment by michaelbynum** [comment]
Need to add support for Expressions, and external functions.

**Comment by michaelbynum** [comment]
1) Add support for more expression types (e.g., external functions).
2) Bounds can probably be improved further when binary variables are encountered. For example, if the upper bound of a binary variable comes out to 0.75, then the value really has to be 0.

**Comment by michaelbynum** [comment]
I think the remaining expression types that need support are 
- [ ] ```ExternalFunctionExpression```
- [ ] ```LinearExpression```
- [ ]  ```Expr_ifExpression```
- [ ] ```AbsExpression```
- [ ] ```GetItemExpression```

**Comment by mrmundt** [comment]
@michaelbynum - Can we get an update on this / which expressions still need support?

**Comment by michaelbynum** [comment]
So, the remaining expression types will just get "skipped", which is fine for now, I think. By skipped, I just mean the bounds will not get improved. I think we can close this.
