### ISSUE TITLE
„Name model is not required“

### ISSUE THREAD

**Issue by MemoWalk** [Pyomo/pyomo#85]
In my Opinion you should add a hint on how to change the model name in the documentation.

In the PDF Version of the PyomoOnlineDocs on page 6 there is written
 > The use of the name model is not required.

However, this is not the case, as far as I have experienced it. The Jupyter Notebook on [The Transport Problem](http://nbviewer.jupyter.org/github/Pyomo/PyomoGallery/blob/master/transport/transport.ipynb) says on the contrary
> We have little imagination here, and we call our model "model". You can give it whatever name you want. _However, if you give your model an other name, you also need to create a model object at the end of your script:_

Both OnlineDocumentantion and Jupyter-Notebook fail to mention that you have to specify the model name on the command line, if you do not use the name „model“. 

**For everyone who does not know the solution (like me some five hours ago):** Assuming I had called my model `mdl`, the model-file `my-model.dat`, data-file `my-model.dat` and want to use `glpk`-solver, then I would have to run the solver as follows:

    pyomo solve --solver='glpk' --model-name='mdl' my-model.py my-model.dat

**Comment by whart222** [comment]
This is a very good point!  I think we can change the script to automatically find the model object, regardless of its name.
