### ISSUE TITLE
how multiple ContinuousSets with different bounds are defined for each indexed decision variable e.g., x?

### ISSUE THREAD

**Issue by asifhasnain** [Pyomo/pyomo#866]
I have to integrate multi-indexed decision variable x e.g.,

`\int_{0}^{e} x^c (t) dt \geq v^c`

where the t has different ContinuousSet bound [0, e] for every x^c.

Any idea, how this can be done? The [given example](https://pyomo.readthedocs.io/en/latest/modeling_extensions/dae.html#pyomo.dae.Integral) does not helped.

**Comment by blnicho** [comment]
This is more of a formulation question and outside the scope intended for Pyomo issues so I'm going to close this. If you still need help I welcome you to ask a question on the [Pyomo forum](https://groups.google.com/forum/?hl=en#!forum/pyomo-forum) but please provide more details on the model you're trying to implement and what you have tried so far. 

As a hint, you might be able to use the same ContinuousSet for every x^c bounded between (0,1) and use an indexed scaling factor to impose a different upper bound `e` for each index. See the [car example](https://github.com/Pyomo/pyomo/blob/master/examples/dae/car_example.py).
