### ISSUE TITLE
Python hangs up (cannot stop running) when execute `from pyomo.environ import *`

### ISSUE THREAD

**Issue by lyjge** [Pyomo/pyomo#869]
I got stuck when I use pyomo in my office computer, the problem is the kernel hangs up (keeps running) forever when I execute `from pyomo.environ import*`, however there is no error reported as shown in the picture link.

[importing problem](https://drive.google.com/open?id=14Ztj7z592v_MH0fUJgsfVrO1AHhV0Oo-)

I am using win10 64 bit, anaconda (python 3.7.1), pyomo 5.6.1.

I have tried installing the necessary modules using either pip or conda specified in pyomo website. It is expected that `from pyomo.environ import *` should work as I can do it in my win10 laptop under the same setting (anaconda version, module version, etc). So it seems that there is a problem of my office computer but I cannot figure out.

Can anyone help? Thanks!

**Comment by RainSunGone** [comment]
Are you sure the kernel is actually hanging. I've found jupyter sometimes leaves things looking like they're running (marked with a star) despite actually being finished.
Please may you try opening another cell and run something such as a print statement just to double check.

If that fails, can you try running the same thing from a python console to see if this is localised to jupyter.

**Comment by lyjge** [comment]
> Are you sure the kernel is actually hanging? I've found jupyter sometimes leaves things looking like they're running (marked with a star) despite actually being finished.
> Please may you try opening another cell and run something such as a print statement just to double check.
> 
> If that fails, can you try running the same thing from a python console to see if this is localised to jupyter.
@RainSunGone 

Thanks for your reply, I have added a print command under the import line `from pyomo.environ import *`, however as you see in the picture link below, the execution is really stuck in the import line.

[problem of import in jupyter](https://drive.google.com/open?id=1IAHtBuLiKqTKHAGhxntgrO88a9SdOub0)

Also, I have tried `from pyomo.environ import *` in the Anaconda Prompt console, and the console also hangs up as shown in the link below.

[problem of import in console](https://drive.google.com/open?id=1ZDHru-a9tYWbzX0Ebc8lU14QWooncDm0)

Thanks!

**Comment by jsiirola** [comment]
This sounds like a (very long) network timeout issue. 

Some additional questions:
  - if you hit Ctrl-C at the anaconda prompt, do you get a stack trace?
  - is the Python process in the background running flat out, or is the CPU effectively idle (I.e. have you found an infinite loop, or have you been caught by a really long network timeout?)
  - can you run this test with no network connection? In particular, if you are running in a VM, please disable the VM’s network connection (not the host’s)
  - how long have you waited to see if it clears up and completes?  More than a couple minutes?

**Comment by lyjge** [comment]
> This sounds like a (very long) network timeout issue.
> 
> Some additional questions:
> 
> * if you hit Ctrl-C at the anaconda prompt, do you get a stack trace?
> * is the Python process in the background running flat out, or is the CPU effectively idle (I.e. have you found an infinite loop, or have you been caught by a really long network timeout?)
> * can you run this test with no network connection? In particular, if you are running in a VM, please disable the VM’s network connection (not the host’s)
> * how long have you waited to see if it clears up and completes?  More than a couple minutes?
@jsiirola 

Thanks for your reply, please see the picture below showing infomation after hitting Ctrl-C in anaconda prompt.
![pyomo_problem_console](https://user-images.githubusercontent.com/33368912/53122858-9b8e6600-354f-11e9-8681-2371ceabd057.jpg)

It seems that the python is not running flat out in background and the CPU is idle as I checked the system tasks manager.

Based on my observation, the execution of `from pyomo.environ import *` last for as long as I keep the terminal open (more than a few days)...

**Comment by blnicho** [comment]
I'm closing this as it seems like an individual system configuration issue and not a wide-spread issue with Pyomo and Anaconda. @lyjge try updating to the most recent Pyomo release and ask a question on the Pyomo forum if you're still having trouble.
