### ISSUE TITLE
bug in core/base/sos.py

### ISSUE THREAD

**Issue by DLWoodruff** [Pyomo/pyomo#875]
# taken from core/base/sos.py docstring and modified slightly
```
import pyomo.environ as pyo
model = pyo.ConcreteModel()
model.A = pyo.Set(initialize = range(2))
model.B = pyo.Set(model.A, initialize={1: "hello", 2: "goodbye"})
model.X = pyo.Var(model.B)
model.C1 = pyo.SOSConstraint(model.A, var=model.X, set=model.B, sos=1)
```
According to the docstring in core/base/sos.py:

    This constraint actually creates one SOS-1 constraint for each
    element of model.A (e.g., if |A| == N, there are N constraints).
    In each constraint, model.X is indexed by the elements of
    model.B[a], where 'a' is the current index of model.A.

But, this example cannot run at all because a Var cannot be indexed by an 
indexed Set.
```
#So maybe this is sort of what was meant :
import pyomo.environ as pyo
model = pyo.ConcreteModel()
model.A = pyo.Set(initialize = range(2))
model.B = pyo.Set(initialize=["hello", "goodbye"])
model.C = model.A * model.B
model.X = pyo.Var(model.C)
model.C1 = pyo.SOSConstraint(model.A, var=model.X, set=model.C, sos=1)
```
This example results in:
```
ValueError: Unexpected keyword options found while constructing 'IndexedSOSConstraint':
	set
```

**Comment by tkorvola** [comment]
More bugs in the SOSConstraint docstring:
- The keyword for SET is `index`; `set` is not recognized.
- N does not default to 1 but must be specified.
- There is an alternative way to call the constructor, which is not documented at all: instead of `var`, `index` and `weights` one specifies a `rule`, which is called in the usual manner.

**Comment by mrmundt** [comment]
This theoretically was addressed in the linked PR, so closing this issue. Please open a new one if there are still concerns.
