### ISSUE TITLE
Passing initial solution to CBC solver

### ISSUE THREAD

**Issue by quimey** [Pyomo/pyomo#881]
Hello!
While working on a personal project I needed to pass an initial solution for a MIP problem (for example a solution generated with an heuristic) to the CBC solver. CBC supports that with the 'mipstart' option (passing a soln file with the variables' values). I couldn't find support for this in pyomo. Is there a way to achieve that?
I implemented a workaround:
I'd first set up the initial values in the concrete instance and then call this function:
```python
def write_solution(instance):
    with open('solution.soln', 'w') as solution:
        for v in instance.component_objects(Var, active=True):
            for index in v:
                if str(v[index].domain) == 'Binary' and v[index].value:
                    trans = str.maketrans('[,]', '(_)')
                    print(
                        '0 {} {}'.format(
                            v[index].name.translate(trans), v[index].value
                        ),
                        file=solution
                    )
```
If you think this could be useful, I could clean it up a little bit and submit a PR, what do you think?

**Comment by jsiirola** [comment]
I think this could be very useful and Pull Requests are always welcome! Some thoughts as you work on it:
  - For this to work, I believe that your “.soln writer” will need to use the same symbol_map as the LP writer. Your example hints that you are using symbolic solver labels (which is not the default). If you include this as part of the CBC Solver, you should be able to get access to the symbol_map. @michaelbynum: we should add his use case to the list for the new solver API. 
  - For robustness, if you cannot get the symbol msp that the LP writer generated, you should at least use the same labeler that the LP writer uses. 
  - Be cautious comparing to strings. It would probably be better to compare against the actual domain, or to use the “is_*” methods in the domain. 
  - Is there a reason you are only outputting the Binary variables? My understanding is that some solvers will only accept the warm start if it is completely feasible - I don’t know if that is the case for CBC. 
  - several Pyomo solvers accept a `warmstart=True` option to enable this kind of behavior. It would’ve great to hook into that api.

**Comment by quimey** [comment]
Thank you for the comments. The section of code I pasted is what I'm using now in my project. I'll make it generic if I'm going to submit  a PR.
I'll try to access the symbol map, remove the hacky string comparison (I added because var.domain == Binary yield false in my code). 
I think cbc only wants initial values for the integer variables (which in my case were all binary). I'll make that generic as well.
I'd try to add it this to the warmstart option as well.
Do you happen to have any code pointers of any of the other solver plugins doing similar things?

**Comment by RainSunGone** [comment]
Was just about to raise this issue.

Search for def _warm_start(self, instance) for inspiration on how this is done for Gurobi and CPLEX.

**Comment by RainSunGone** [comment]
@quimey Are you considering doing a PR for this? Because I wouldn't mind having a crack at it.

**Comment by quimey** [comment]
I started working at it but then I realize I was mostly going to copy a bunch of code from the cplex wrapper. I thought that some refactoring would be appropriate but I haven't had the time to read and understand the code well enough to do that.
What do you think?

**Comment by RainSunGone** [comment]
I think it would be useful to stick up a WIP branch with whatever stage you got to, then we can look over the changes and discuss :)

**Comment by quimey** [comment]
I don't have much done but let me clean it up and push it after.

**Comment by quimey** [comment]
I just checked and I have basically nothing. Also I'm busy right now, so go ahead and have your crack at it!
I'll be open to discuss some details if that'd helpful for you

**Comment by lapseofreason** [comment]
I was looking through the source for the CBC plugin, but I could not figure out where symbol_map is used there. I noticed that passing `symbolic_solver_labels` to `solver.solve` for CBC will use them in the temporary LP-File, but I'm not sure how to get the map.

@jsiirola: Given an instance, how does one get the symbol_map that is used?

**Comment by jsiirola** [comment]
It depends on the model, and whether the top block comes from kernel or the normal aml.  Looking at the `_warm_start()` method in the CPLEX / Gurobi interfaces, the idiom appears to be:
```
if isinstance(instance, IBlock):
    smap = getattr(instance,"._symbol_maps")[self._smap_id]
else:
    smap = instance.solutions.symbol_map[self._smap_id]
```

**Comment by lapseofreason** [comment]
@jsiirola Thanks, that was helpful. I'm working on this.

**Comment by lapseofreason** [comment]
I've created an implementation here:
https://github.com/lapseofreason/pyomo/tree/cbc-warmstart

It works fine for some simple examples I tried, but it is not thoroughly tested yet. Please test and provide feedback, so I can create a PR.

**Comment by RainSunGone** [comment]
Do you want to stick up a WIP PR? Then we can move the conversation to there.
