### ISSUE TITLE
DAE: expand blocks indexed by a ContinusSet

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#89]
We need to update `pyomo.dae.misc.update_contset_indexed_component()` to also expand `Block`s that are indexed by `ContinuousSet`s.  This is an issue with models like a packed column whose length is specified as a continuous set.  Things like the physical properties for each "stage" (finite element) will need to be expanded.

Reported by @eslickj and @andrewlee94.

**Comment by ghackebeil** [comment]
related to #52
