### ISSUE TITLE
failed to index the parameter using another Param

### ISSUE THREAD

**Issue by fredwangwang** [Pyomo/pyomo#890]
example:

```python
from pyomo.environ import *

model = AbstractModel()

model.I = Set()

model.b = Param(model.I)
model.c = Param() # a value from set I
model.d = Param(initialize=lambda m: m.b[m.c])

i = model.create_instance("data_test.dat")
```

`data_test.dat`:
```
# dat file:
set I := 1 2;
param b :=
1 10
2 20;
param c := 2;
```

When running the script, it returns the error saying:
```
ValueError: Error retrieving immutable Param value (b[2]):
        The Param value is undefined and no default value is specified.
```

Which is not quite expected.

Is this a bug or this is known, and how to work around it?

**Comment by jsiirola** [comment]
The short answer is that Param modeling objects (scalar immutable Params or any mutable Params) cannot currently be implicitly used as indices into other indexed components.  I think this is a bug in the IndexedComponent logic that we will look into.

The simple workaround is to convert the modeling object to it's (current) numeric value using tho `value()` function from `pyomo.environ`:

```python
model.d = Param(initialize=lambda m: m.b[value(m.c)])
```

**Comment by DLWoodruff** [comment]
You need to put value() around m.c, as in lambda m: m.b[value(m.c)]).

For technical reasons that probably aren't worth addressing in this
particular case, the error message was misleading.

from pyomo.environ import *
model = AbstractModel()
model.I = Set()
model.b = Param(model.I)
model.c = Param(within=model.I)
model.d = Param(initialize=lambda m: m.b[value(m.c)])

i = model.create_instance("data_test.dat")
i.pprint()

**Comment by fredwangwang** [comment]
@jsiirola @DLWoodruff Thanks both of you for the help ❤️ ! It solved my problem. Closing this issue now
