### ISSUE TITLE
Problem reloading results into cloned models

### ISSUE THREAD

**Issue by andrewlee94** [Pyomo/pyomo#900]
As part of IDAES, I have been trying to clone a model so that I can compare the state of the model before and after applying an initialization method. However, when I try to do this on an IDAES model, I am getting an error loading the results of a solve back into the original model (see example below). Without the `clone`, the solve (inside the `initialize` method) runs correctly and returns values, but adding the `clone` results in the error shown.
 
```
from pyomo.environ import ConcreteModel
from idaes.core import FlowsheetBlock
from idaes.unit_models.cstr import CSTR
from idaes.property_models.examples.saponification_thermo import (
    SaponificationParameterBlock)
from idaes.property_models.examples.saponification_reactions import (
    SaponificationReactionParameterBlock)

m = ConcreteModel()
m.fs = FlowsheetBlock(default={"dynamic": False})

m.fs.properties = SaponificationParameterBlock()
m.fs.reactions = SaponificationReactionParameterBlock(default={
                        "property_package": m.fs.properties})

m.fs.cstr = CSTR(default={"property_package": m.fs.properties,
                          "reaction_package": m.fs.reactions,
                          "has_equilibrium_reactions": False,
                          "has_heat_transfer": True,
                          "has_pressure_change": False})

orig_state = m.clone()

m.fs.cstr.initialize(outlvl=0,
                     optarg={'tol': 1e-6})
```

Returns:
```
Traceback (most recent call last):
  File "clone_test.py", line 43, in <module>
    optarg={'tol': 1e-6})
  File "/home/alee/idaes/idaes-dev/idaes/core/unit_model.py", line 565, in initialize
    results = opt.solve(blk, tee=stee)
  File "/home/alee/pyomo/pyomo/pyomo/opt/base/solvers.py", line 629, in solve
    default_variable_value=self._default_variable_value)
  File "/home/alee/pyomo/pyomo/pyomo/core/base/PyomoModel.py", line 297, in load_from
    ignore_fixed_vars=ignore_fixed_vars)
  File "/home/alee/pyomo/pyomo/pyomo/core/base/PyomoModel.py", line 530, in select
    if vdata.fixed is True:
AttributeError: 'NoneType' object has no attribute 'fixed'
```

I have tried the same procedure on a simple model (no Block hierarchy, two Vars and 1 Constraint) and it worked correctly, so something seems to be happening with the more complex model. I also looked into the `clone` method to try to find which stage the error occurred at, and it appears to arise from something in the `deepcopy` - I did a `deepcopy` (copying the code from `clone` without the stuff for the parent block) and got the same result.

**Comment by qtothec** [comment]
So, what you're saying is that `clone()` had a side effect causing `initialize()` to break? Oh, that's fun.

**Comment by andrewlee94** [comment]
More specifically, it is that when doing a solve within the initialize method, there is a problem loading the result back into the model for some reason - the error looks like a VarData component no longer has the `fixed` attribute, which would imply that the original model has changed somehow, which makes no sense as the original model should have been untouched.

**Comment by jsiirola** [comment]
@andrewlee94: close. The problem is that the _VarData itself is not getting created (it is the _VarData pointed to is None, and None has no attribute “fixed”).

Can you attach a (simple) model that reproduces this to the issue so we can take a look at it?

**Comment by andrewlee94** [comment]
@jsiirloa I could understand this happening for the cloned model (somehow), but the fact that this is occurring on the original model seems very strange to me (not knowing exactly what happens inside deepcopy). I tried reproducing this on (much) simpler models, but could not reproduce the issue.

**Comment by blnicho** [comment]
Seems like this was fixed at some point. I just tested it on the following model (updated to match the latest IDAES version) and the initialization ran fine.
```
from pyomo.environ import ConcreteModel
from idaes.core import FlowsheetBlock
from idaes.models.unit_models.cstr import CSTR
from idaes.models.properties.examples.saponification_thermo import (
    SaponificationParameterBlock)
from idaes.models.properties.examples.saponification_reactions import (
    SaponificationReactionParameterBlock)

m = ConcreteModel()
m.fs = FlowsheetBlock(dynamic=False)

m.fs.properties = SaponificationParameterBlock()
m.fs.reactions = SaponificationReactionParameterBlock(property_package=m.fs.properties)

m.fs.cstr = CSTR(property_package=m.fs.properties,
                 reaction_package=m.fs.reactions,
                 has_equilibrium_reactions=False,
                 has_heat_transfer=True,
                 has_pressure_change=False)

orig_state = m.clone()

m.fs.cstr.initialize(outlvl=0,
                     optarg={'tol': 1e-6})

```
