### ISSUE TITLE
Fix gdp_bounds

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#901]
I just pulled from master and I'm getting a strange error when importing pyomo:
```
../Pyomo/pyomo/pyomo/kernel/__init__.py:16: in <module>
    import pyomo.environ
../Pyomo/pyomo/pyomo/environ/__init__.py:95: in <module>
    _import_packages()
../Pyomo/pyomo/pyomo/environ/__init__.py:93: in _import_packages
    pkg.load()
../Pyomo/pyomo/pyomo/contrib/gdpopt/plugins.py:2: in load
    import pyomo.contrib.gdpopt.GDPopt
../Pyomo/pyomo/pyomo/contrib/gdpopt/GDPopt.py:12: in <module>
    from pyomo.contrib.gdpopt.iterate import GDPopt_iteration_loop
../Pyomo/pyomo/pyomo/contrib/gdpopt/iterate.py:4: in <module>
    from pyomo.contrib.gdpopt.cut_generation import (add_integer_cut,
../Pyomo/pyomo/pyomo/contrib/gdpopt/cut_generation.py:6: in <module>
    from pyomo.contrib.gdp_bounds.info import disjunctive_bounds
../Pyomo/pyomo/pyomo/contrib/gdp_bounds/__init__.py:1: in <module>
    import pyomo.contrib.gdp_bounds.plugins
E   ImportError: bad magic number in 'pyomo.contrib.gdp_bounds.plugins': b'\n\xf3\r\n'
```
I see that there is a directory namesd `plugins` and a file named `plugins.py` at the same level inside `pyomo/contrib/gdp_bounds`. I suspect this has something to do with it.

**Comment by ghackebeil** [comment]
I just cleared out my .pyc files and noticed that the directory is now empty. Only after deleting the directory did the problem go away.

I'll leave this issue open for a few days as I imagine other developers will run into the same thing upon updating.

**Comment by qtothec** [comment]
Good catch, Gabe. The directory seemed quite unnecessary, so I moved things up a level, but I forgot about the residual *.pyc file effect.
