### ISSUE TITLE
BARON writer parentheses issue (arithmetic operator after unary operator) causing "NonLinearity Error in POW expression" error

### ISSUE THREAD

**Issue by chrlan90** [Pyomo/pyomo#902]
I believe that one reason for causing the "NonLinearity Error in POW expression" error message is the omission of (for BARON necessary) parentheses by sympy/pyomo. If e.g. a constraint in pyomo is defined the following way:
model.con = Constraint(expr=model.x1 - 60*model.x2**(-1) * 50*model.x3 == 0)
the constraint's expression will be written (by baron_writer.py):
con: x1 - 60*x2^-1 * 50*x3 == 0;
The expression, however, is (unitentionally) misinterpreted by BARON the following way:
x1 - 60*x2^(-1 * 50*x3) == 0; (see attached screenshot of BARON manual)
![page in baron manual on arithmetic operators in exponents](https://user-images.githubusercontent.com/48587611/54521868-23f40100-496c-11e9-8a04-303859138131.PNG)

In this simplified case it is of course easy to fix by defining the constraint differently. However, if constraint expressions are generated by e.g. pyomo.core.base.symbolic.differentiate(), I believe the best option to fix this problem, is in constraint section of the baron_writer.py

**Comment by qtothec** [comment]
This is related to https://github.com/Pyomo/pyomo/issues/663, which addressed the same issue in the GAMS writer.
