### ISSUE TITLE
MC++ should fail gracefully for domain errors

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#906]
Assigned: @johnnybatesjr

Current outcome: script crashes
```
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.x = Var(bounds=(-1, 1))
>>> from pyomo.contrib.mcpp.pyomo_mcpp import McCormick as mc
>>> mc(log(m.x))
WARNING: Var x missing value. Assuming midpoint value of 0.0
terminate called after throwing an instance of 'mc::McCormick<mc::Interval>::Exceptions'
Aborted (core dumped)
```

Desired outcome:
- Warning that a domain violation occurs and skipping computations, or
- Python exception generated that identifies the errant sub-expression and variables involved.

**Comment by jsiirola** [comment]
I believe this was resolved by #968.  @qtothec, please reopen is this is not the case.
