### ISSUE TITLE
Incorrect value from Param.default() when there is no default

### ISSUE THREAD

**Issue by tkorvola** [Pyomo/pyomo#907]
When no default value is provided `Param.default()` returns `pyomo.core.base.param._NotValid`. According to its documentation the method should return `None`, as it used to do. Please update the documentation, in particular document how to determine if a default value exists.

**Comment by blnicho** [comment]
See the related discussions in #300 and #301. @tkorvola , could you add a link to the documentation that you think is wrong?

**Comment by tkorvola** [comment]
I was referring to the docstring of `Param.default()`. It is also unclear how one should now check if a default is set: #301 just replaced `is None` with `is _NotFound` but underscore names are usually not regarded as public API.

**Comment by tkorvola** [comment]
Alternatively, perhaps preferably, please change `Param.default()` to behave (again) as documented, i.e., return `None` if no default is provided. `None` is after all the canonical missing value in Python.

**Comment by jsiirola** [comment]
#1927 renames `_NotValid` to `Param.NoValue`.

One additional implementation note, as Params are historically allowed to contain non-numeric data -- *including `None`* -- we need a "special" indication of "not set", as a user could legitimately want `None` as the default Param value.
