### ISSUE TITLE
BigM transformation raises an error when encountering Ports

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#913]
When the BigM transformation encounters a Port component, it raises an error. What should happen? Should they be ignored? It is important that and Arcs on Disjuncts are expanded before the BigM transformation. If that is done, then I think the Ports can be ignored. Maybe there should be a mechanism to explicitly specify components that should be ignored? Thoughts @jsiirola ?

**Comment by jsiirola** [comment]
I think that ignoring Port is reasonable.  The BigM transformation is "paranoid" (safe) in that if complains about any active components that it doesn't know about.  The rationale is that it can't guarantee the validity of the transformation if the user stuck a new modeling component onto the Disjunct (but if the component is deactivated, then it is OK).

The quick solution is to add `Port: False` to the `handlers` dict in `BigM_Transformation`.

The more general solution comes back to "what does it mean to be a model" and "what is the significance of `ActiveIndexedComponent` versus just `IndexedComponent`"?  If you take the position that "a model is defined by the set of active components reachable through active components on the model", then an extension to that position is that the GDP transformations should only complain if they reach active "Activatable Components" that they don't know about and silently ignore other Components.  Implementing this is a bit trickier, as other contexts (namely searching for components) caused us to put a default (read only) implementation of the `.active` property on `Component` to always return True.

**Comment by emma58** [comment]
This was fixed by #1961
