### ISSUE TITLE
Incorrect string representation of nested powers

### ISSUE THREAD

**Issue by mlangiu** [Pyomo/pyomo#916]
When I assessed an expression containing nested powers from a pyomo model pprint() I was confused to see that it apparently did not uphold right associativity that is assumed by python, thaty is, a ** b ** c should be a ** (b ** c).

```python
from pyomo.environ import *
m = ConcreteModel()
m.x = Var(initialize=2)
x = m.x
exprs =    [2 ** x ** 3, (2 ** x) ** 3, 2 ** (x ** 3)]
expected = [2 ** 2 ** 3, (2 ** 2) ** 3, 2 ** (2 ** 3)]

# This gives the expected numerical results, but the string representation of all expr is identical
for expr, expe in zip(exprs, expected):
    print(f'{expr} gives {expr()}, should be {expe}')
```
gives me
```text
2**x**3 gives 256, should be 256
2**x**3 gives 64, should be 64
2**x**3 gives 256, should be 256
```

So it turned out that the operator precedence acually agrees with python but the string representation is wrong:

```python
# Here's the expected output:
def expect(expr):
    try:
        expr.args
        return f'({expr})'
    except AttributeError:
        return str(expr)
for expr in exprs:
    base, exponent = expr.args
    print(f'{expr}, should be printed as {expect(base)} ** {expect(exponent)}')
```

gives me
```text
2**x**3, should be printed as 2 ** (x**3)
2**x**3, should be printed as (2**x) ** 3
2**x**3, should be printed as 2 ** (x**3)
```

---

- pyomo '5.6.1' 
- python '3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]'

**Comment by jsiirola** [comment]
Note that this is a problem with the *string representation* and not the expression:
```
>>> m = ConcreteModel()
>>> m.x = Var()
>>> exprs =    [2 ** m.x ** 3, (2 ** m.x) ** 3, 2 ** (m.x ** 3)]
>>> [str(x) for x in exprs]
['2**x**3', '2**x**3', '2**x**3']
>>> [x.to_string(verbose=True) for x in exprs]
['pow(2, pow(x, 3))', 'pow(pow(2, x), 3)', 'pow(2, pow(x, 3))']
```

I will argue that the only string representation that is incorrect is `exprs[1]`, as `exprs[2]` can be implied using Python's operator precedence and associativity rules.

**Comment by mlangiu** [comment]
You're rightq, I changed the title to make this more clear.
I agree about only `exprs[1]` being incorrect, although for clarity and since some people have trouble with the right associativity, I would suggest to always add the parentheses, but that's just a personal taste.

**Comment by qtothec** [comment]
@jsiirola Is there a chance this might also affect the string-based solver writers, or should we be ok there?

**Comment by jsiirola** [comment]
@qtothec: Yes - there is definitely a chance that there are problems with the GAMS/BARON writers, although it depends on how the string-based writers generate their strings.  For the NL writer, we should be fine, as the NL file is unambiguous (it uses prefix and not infix notation).  The GAMS and BARON writers may have problems as they are both infix.  I also do not know the associativity rules for either of their parsers.  I am pretty sure BARON won't allow `c0 ** x ** c1`, although other cases may or may not be correctly simplified.  Regardless, we should probably update those writers to be less "human readable" and more unambiguous (in particular, they should not rely on associativity rules for correctness).
