### ISSUE TITLE
[PEP] Use super() for Component initialization

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#918]
## Proposal
This PEP proposes that we move to the "standard" Python approach of calling `super(ThisClass, self).__init__()` within the Pyomo Component class hierarchy for ensuring that all `__init__` methods get called.

## Discussion
Currently, Components (derivatives of `pyomo.core.base.component.Component` and `pyomo.core.base.component.ComponentData`) use hand-crafted implementations mof `__init__` that make explicit calls to base class `__init__` methods.  They also frequently "inline" base class `__init__` methods to avoid function calls.

This causes the following problems:
  - DRY (Don't Repeat Yourself) violation (changing a base class implementation means locating and updating everywhere that base class' `__init__` was inlined)
  - It is difficult to derive additional Components from existing components (calling explicit base classes' `__init__` can cause some base classes to have their `__init__` called more than once (due to the diamond hierarchy for scalar components).
  - Adding additional inheritance mechanisms (like mixin classes) can become very difficult.

Fixing the Component hierarchy to use `super()` is involved, but not too complicated, with the exception of the following classes (which require special handling due to their use of non-Set positional arguments):
  - _VirtualSet
  - Piecewise
  - DerivativeVar

Making this change will impact anyone who declared derived components (as they will almost certainly need to make the corresponding change to their classes) [e.g., @eslickj, @andrewlee94]

**Comment by eslickj** [comment]
In IDAES we use super everywhere but here https://github.com/IDAES/idaes-pse/blob/master/idaes/core/process_block.py, in the metaclasses.  If you look at the code there, you see that the indexed and scalar metaclasses define their own \_\_init\_\_ functions.  I think the reason its there and not in ProcessBlock using super, is that the Block and _BlockData class \_\_init\_\_ take a different set of arguments.  I think this is something that would need to be worked out in Pyomo too, so we should be okay if we coordinate.  At least in IDAES it should be a very isolated piece that will need updated.

**Comment by jsiirola** [comment]
I drafted a prototype implementation (available on [jsiirola/rework-component-init](https://github.com/jsiirola/pyomo/tree/rework-component-init)) and the results were mixed.  While the code is arguably cleaner, it is also 10-15% slower (on pmedian8).  My initial thought was the cost was due to making and breaking apart the `**kwargs` dicts; however, I drafted an implementation that passed the dicts by reference ... and things got 50% slower.  I now believe the crux of the issue appears to be allowing dicts to pass / be processed by _Data objects (there are just so many of them).  A performant implementation of this will require more thought.

**Comment by michaelbynum** [comment]
Wow... That is unfortunate...

**Comment by carldlaird** [comment]
@jsiirola Are you advocating for this change or not after seeing the performance numbers?

**Comment by jsiirola** [comment]
I still think this is a good thing to keep on the radar, but to accept the PEP, I would think that we would first need to take the time to resolve the performance issues.

**Comment by mrmundt** [comment]
In an effort to clean up old issues, we are moving some design discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
