### ISSUE TITLE
Duplicate ExternalFunctions Cause Problems

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#92]
I think there is a problem in Pyomo if you include an external function with the same name more than once in a Pyomo model.  Ordinarily I don't think this would be a problem, but I'm working with a complicated model structure, pulling in independent pieces, and it is hard to ensure that I model only creates one ExternalFunction object for each reference to a particular external function.  The issue is even more complicated because the models have a hierarchical block structure and for initialization I want to solve some of the blocks independently.  If multiple blocks use the same external function, it is difficult to have a way to make sure the function gets induced without multiple ExternalFunction objects pointed at the same function.

I may be misunderstanding what happens, but the only actual problem I can find is that multiple ExternalFunction objects pointed at the same function cause the function to be defined multiple times in the *.nl file, so the ASL will not read it and raise an error.

If I understand this right, I think the solution would just be to ensure that a function is defined only once in the *.nl file.  If two functions have the same name and come from the same file, that should be fine.  If two functions have the same name, but come from different files, maybe Pyomo could raise and exception with a clear error message.

**Comment by ghackebeil** [comment]
I think this is a good idea. I'll take a look at the NL writer.

**Comment by ghackebeil** [comment]
So It looks like the NL writer already attempts to do what you are describing. Would you mind pointing me at a small example that replicates the problem?

**Comment by eslickj** [comment]
Sorry it took so long.  Just got back from vacation.  A demonstration is attached.  It works as is, but not if you uncomment the commented line in the py file.  Maybe the checking for duplicate functions doesn't work across blocks?


[example.zip](https://github.com/Pyomo/pyomo/files/685908/example.zip)
