### ISSUE TITLE
Variables not recognized as part of model instance after 1st iteration

### ISSUE THREAD

**Issue by jayacl5** [Pyomo/pyomo#928]
Hi,

I am working on a constrained non-linear optimization problem using ipopt solver in Pyomo. I need to iterate over multiple periods for different categories and generate optimal prices which are also the variables to be optimized.

I have created only one model instance and a set of variables and constraints that need to be considered during each iteration.

Some sample code is given below:

    model = ConcreteModel()

    model.A_Value = Var(within=NonNegativeReals, initialize=Max, bounds=(Min, Max))

    model.B_Value = Var(within=NonNegativeReals, initialize=Max, bounds=(Min, Max))

     model.C_Value = Var(within=NonNegativeReals, initialize=Max, bounds=(Min, Max))

    model.D_Value = Var(within=NonNegativeReals, initialize=Max, bounds=(Min, Max))

     model.B_Time = Var(within=NonNegativeReals, initialize=BT_Min, bounds=(BT_Min, BT_Max))

        model.C_Time = Var(within=NonNegativeReals, initialize=CT_Min, bounds=(CT_Min, CT_Max))

        model.D_Time = Var(within=NonNegativeReals, initialize=DT_Min, bounds=(DT_Min, DT_Max))

     model.constraints = ConstraintList()  # Create a set of constraints

    model.c1 = model.constraints.add(expr=model.A_Value <= K_Multiplier * Max)

    model.c2 = model.constraints.add(expr=model.A_Value >= model.B_Value * AV_Multiplier)

The same are repeated while looping for the different categories and periods but on a different set of data.

I could get the below solution for the first period. There is a warning on infeasibility given as well.

EXIT: Converged to a point of local infeasibility. Problem may be infeasible.
WARNING: Loading a SolverResults object with a warning status into
    model=unknown;
        message from solver=Ipopt 3.12.12\x3a Converged to a locally
        infeasible point. Problem may be infeasible.

[941.0839598753886, 934.62101415, 934.62101415, 1038.4677831265255, 22.15790917455483, 41.99138581403537, 43.24706522854493]
['A_Value', 'B_Value', 'C_Value', 'D_Value', 'B_Time', 'C_Time', 'D_Time']

From the second period I see the below error and cannot proceed:

ERROR: Variable 'D_Value' is not part of the model being written out, but
    appears in an expression used on this model.
ERROR: Variable 'A_Value' is not part of the model being written out, but
    appears in an expression used on this model.
ERROR: Variable 'B_Value' is not part of the model being written out, but
    appears in an expression used on this model.
ERROR: Variable 'C_Value' is not part of the model being written out, but
    appears in an expression used on this model.
ERROR: Variable 'B_Time' is not part of the model being written out, but
    appears in an expression used on this model.
ERROR: Variable 'C_Time' is not part of the model being written out, but
    appears in an expression used on this model.
ERROR: Variable 'D_Time' is not part of the model being written out, but
    appears in an expression used on this model.

Earlier I could run a similar model on 10 categories each with 13 periods and each period again with 70 weeks of data. But, now, the model does not recognize the model instance.

I would appreciate any suggestions in this regard.

Regards,
Jay

**Comment by qtothec** [comment]
I'm not quite sure that I follow that you are doing. Are you solving the same model instance multiple times, but with different parameter values? Are you adding additional constraints to the same model instance? Do you have multiple model copies running around? It looks like you might have multiple model copies, and you've mixed variables from one copy into a constraint in another copy.

**Comment by jayacl5** [comment]
Hi,

Are you solving the same model instance multiple times, but with different parameter values - Yes

Are you adding additional constraints to the same model instance - I have 16(price and time) constraints that change as per the data. The objective is to get the prices for different time windows (70 weeks)satisfying a High-Low-High scenario.

Do you have multiple model copies running around - No. I have only one model instance which is executed sequentially.

I have 10 cat classes - CC = ['B_D', 'B_Q', 'I_D', 'I_Q', 'N_D', 'N_Q', 'O_D', 'O_Q']

Each has 13 periods and each period has 70 weeks.

I would first run for "B_D" and period 1 and then iterate to period 2 and so on. After that I move on to "B_Q". I see an error for period 2.

Hope this helps

**Comment by blnicho** [comment]
Could you share more of your implementation? In particular it would be helpful to see how you are calling the solver, how you are implementing the multiple solves, and how you are loading data into your model. You should also try using the command `model.pprint()` right before you call the solver to verify that all the equations in the model are what you expect.

**Comment by jayacl5** [comment]
Hi,

Below is what I am doing:

        #Calling the objective function
        model.obj = Objective(rule=obj_rule, sense=maximize)
        # running the solver
        opt = SolverFactory('ipopt')  # choose a solver
        solver_manager = SolverManagerFactory('neos')  # Solve in neos server
        results = opt.solve(model, tee=True)  # solve the model with the selected solver
        model.pprint()

**Comment by jayacl5** [comment]
I am using the elasticity of demand concept to derive the new volume given elasticity, old and new prices. 

I am optimizing the  revenue (volume * price) for different cat classes during each period. The price is the new price and volume is new volume.

Data is extracted from csv files and is 10*13*70 rows (9100)

The variables to be optimized are also part of the constraints:

        model.c1 = model.constraints.add(expr=model.A_Value <= K_Multiplier * Max)

        model.c2 = model.constraints.add(expr=model.A_Value >= model.B_Value * AV_Multiplier)

        model.c3 = model.constraints.add(expr=model.B_Time <= BT_Max)

        model.c4 = model.constraints.add(expr=model.B_Time >= BT_Min)

        

       for j in CC:    # looping through cat_classes

          while(p<13):      # looping through periods

            def obj_rule(model):   # objective function

              while (i > 0 and i <= 70):       # looping through weeks

                 if (week>1 and week<25):

                 elif (week>=25 and week<43):

                 elif

                 elif

                i = i+1

              return (sum(revenue)- sum(risk))

        #Calling the objective function
        model.obj = Objective(rule=obj_rule, sense=maximize)
       # running the solver
       opt = SolverFactory('ipopt')  # choose a solver
       solver_manager = SolverManagerFactory('neos')  # Solve in neos server
       results = opt.solve(model, tee=True)  # solve the model with the selected solver
       model.pprint()

        p = p+1


Here risk is a function of volume, elasticity, new and old prices. Same is revenue

**Comment by blnicho** [comment]
Note that the objective function rule is only called once when the `obj` component is originally added to the model. From the code you posted it still isn't clear to me how the solver is being called multiple times unless the indentation is off in the code you posted.

**Comment by jayacl5** [comment]
Resolved the issue. It was an indentation mistake. 
Thank you for responding to my issue
