### ISSUE TITLE
Document deprecation decorator

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#944]
I tried deprecating pyomo.bilevel.SubModel, but when I did that calls to isinstance() failed.  This suggests that the use of @deprecated on a class changes its type, which is undesirable.

**Comment by jsiirola** [comment]
Correct.  `pyomo.common.deprecation.deprecated` is currently a function, and probably should only be used to wrap functions / methods.  Some quick searching turned up the following approach to make `isinstance()` work:

    https://stackoverflow.com/questions/7514968/making-isinstance-work-with-decorators

However, also note that much of Pyomo leverages a `type() is type()` idiom, which will still run afoul of the approach proposed on StackOverflow.

**Comment by whart222** [comment]
Perhaps the resolution of this "issue" is to include documentation for these decorators to indicate this limitation. (?)

**Comment by mrmundt** [comment]
There is a separate issue open to track this request, so we will be closing this one.
