### ISSUE TITLE
pip install pyomo corrupts python3 virtualenv

### ISSUE THREAD

**Issue by BrechtBa** [Pyomo/pyomo#95]
I've tried installing pyomo in a virtualenv running python 3.5.
Installation with pip install pyomo works fine but when I try starting the python interpreter the following error immediately occurs: `Failed to import the site module`

I'm on Ubuntu 16.04
64bit machine

Below are the steps to reproduce the error and the full error traceback

```
me@mypc:~$ virtualenv -p python3 env
me@mypc:~$ source env/bin/activate
(env) me@mypc:~$ pip install pyomo
(env) me@mypc:~$ python
Failed to import the site module
Traceback (most recent call last):
  File "~/env/lib/python3.5/site.py", line 703, in <module>
    main()
  File "~/env/lib/python3.5/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "~/env/lib/python3.5/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "~/env/lib/python3.5/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "~/env/lib/python3.5/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 574, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

**Comment by ghackebeil** [comment]
Does this happen if you do not install Pyomo?

Gabe

**Comment by BrechtBa** [comment]
Ofcourse not.
The issue is definitely pyomo related.
I can install other packages just fine and they work like they are supposed to.
But installing Pyomo breaks the virtualenv.

**Comment by BrechtBa** [comment]
I've just tested the same procedure on my windows machine which leads to a different error message.
Furthermore, the python interpreter starts.

The traceback is below:

```
(env) me@mywindowspc C:\
> python                                                                                                            
Error processing line 3 of C:\env\lib\site-packages\Pyomo-5.1-py3.5-nspkg.pth:     
                                                                                                                    
  Traceback (most recent call last):                                                                                
    File "C:\Python35\lib\site.py", line 167, in addpackage                                                         
      exec(line)                                                                                                    
    File "<string>", line 1, in <module>                                                                            
    File "<frozen importlib._bootstrap>", line 574, in module_from_spec                                             
  AttributeError: 'NoneType' object has no attribute 'loader'                                                       
                                                                                                                    
Remainder of file ignored                                                                                           
Error processing line 3 of C:\env\lib\site-packages\Pyomo-5.1-py3.5-nspkg.pth:     
                                                                                                                    
  Traceback (most recent call last):                                                                                
    File "C:\Python35\lib\site.py", line 167, in addpackage                                                         
      exec(line)                                                                                                    
    File "<string>", line 1, in <module>                                                                            
    File "<frozen importlib._bootstrap>", line 574, in module_from_spec                                             
  AttributeError: 'NoneType' object has no attribute 'loader'                                                       
                                                                                                                    
Remainder of file ignored                                                                                           
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32                      
Type "help", "copyright", "credits" or "license" for more information.                                              
>>>                                                                                                                 
```

Importing pyomo afterwards also works and I can solve example problems.
The error message remains however.

**Comment by BrechtBa** [comment]
Hmm,

I looked into the file stated in the error message `C:\env\lib\site-packages\Pyomo-5.1-py3.5-nspkg.pth`

on line 3 there is:

```
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('pyomo', 'data'));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('pyomo.data', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('pyomo.data', [os.path.dirname(p)])));m = m or not has_mfs and sys.modules.setdefault('pyomo.data', types.ModuleType('pyomo.data'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['pyomo'], 'data', m)
```

Adding a single newline afer one of the `;` beforethe `m = has_mfs and sys.modules.setdefault(...` statement like below resolves the error
```
import sys, types, os;
has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('pyomo', 'data'));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('pyomo.data', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('pyomo.data', [os.path.dirname(p)])));m = m or not has_mfs and sys.modules.setdefault('pyomo.data', types.ModuleType('pyomo.data'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['pyomo'], 'data', m)
```

I have no Idea why this resolves the error on windows but it does.
I'll try the same aproach on my ubuntu machine tonight

**Comment by jsiirola** [comment]
This is very strange.  The `Pyomo-5.1-py3.5-nspkg.pth` file is automatically generated by `setuptools` during the installation process (it is not explicitly a file that we generate).

@whart222: There seems to be something bogus going on with the Pyomo namespace package configuration.  Given that we now have the `pyomo.contrib` namespace package, do we still need the top-level `pyomo` to also be a namespace package?  I am seeing other problems with it in the HPC modules system (I have to manually add `__init__.py` files to get things to import both with Pyomo and PyUtilib - but then get very strange errors when other modules are loaded).

**Comment by BrechtBa** [comment]
I've just tested the same trick on my ubuntu machine and it works.
Very strange behavior...

**Comment by whart222** [comment]
This is related to the namespace configuration, and specifically the use of pkgutil.  Other developers have seem similar issues, starting in Python 3.4, so it's surprising that we haven't seen this issue before.

I recently tagged a Python 5.1.1 release to resolve this issue.  Specifically, I did the following:  (1) removed several namespace directories that we're not using and not likely to use (pyomo.doc and pyomo.data).  I left the top-level namespace directory since I think that may still be useful,  and (2) I monkeypatched the use of pkgutil, following the technique used by the Flask developers.

I've tested these changes, and they seem to resolve the issue described above.

**Comment by sitongsu** [comment]
> Hmm,
> 
> I looked into the file stated in the error message `C:\env\lib\site-packages\Pyomo-5.1-py3.5-nspkg.pth`
> 
> on line 3 there is:
> 
> ```
> import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('pyomo', 'data'));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('pyomo.data', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('pyomo.data', [os.path.dirname(p)])));m = m or not has_mfs and sys.modules.setdefault('pyomo.data', types.ModuleType('pyomo.data'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['pyomo'], 'data', m)
> ```
> Adding a single newline afer one of the `;` beforethe `m = has_mfs and sys.modules.setdefault(...` statement like below resolves the error
> 
> ```
> import sys, types, os;
> has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('pyomo', 'data'));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('pyomo.data', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('pyomo.data', [os.path.dirname(p)])));m = m or not has_mfs and sys.modules.setdefault('pyomo.data', types.ModuleType('pyomo.data'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['pyomo'], 'data', m)
> ```
> I have no Idea why this resolves the error on windows but it does.
> I'll try the same aproach on my ubuntu machine tonight

thanks for your answer.It did help me.

**Comment by ginhsien** [comment]
> Hmm,
> 
> I looked into the file stated in the error message `C:\env\lib\site-packages\Pyomo-5.1-py3.5-nspkg.pth`
> 
> on line 3 there is:
> 
> ```
> import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('pyomo', 'data'));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('pyomo.data', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('pyomo.data', [os.path.dirname(p)])));m = m or not has_mfs and sys.modules.setdefault('pyomo.data', types.ModuleType('pyomo.data'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['pyomo'], 'data', m)
> ```
> 
> Adding a single newline afer one of the `;` beforethe `m = has_mfs and sys.modules.setdefault(...` statement like below resolves the error
> 
> ```
> import sys, types, os;
> has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('pyomo', 'data'));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('pyomo.data', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('pyomo.data', [os.path.dirname(p)])));m = m or not has_mfs and sys.modules.setdefault('pyomo.data', types.ModuleType('pyomo.data'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['pyomo'], 'data', m)
> ```
> 
> I have no Idea why this resolves the error on windows but it does. I'll try the same aproach on my ubuntu machine tonight

How do you open the file "C:\env\lib\site-packages\Pyomo-5.1-py3.5-nspkg.pth" in windows? It did not appear in File Explorer...

**Comment by MASSKAgithub** [comment]
adding a new line fixes the script :///\\\wtf

**Comment by hmliunian** [comment]
> adding a new line fixes the script :///\\wtf

but it also work, I even don't know why
