### ISSUE TITLE
[PEP] Deprecation and Removal of Pyomo Capabilities

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#950]
## Proposal
Use deprecation warnings to denote Pyomo capabilities that will be removed in future releases.  Deprecation warnings will indicate whether these capabilities will be removed in a subsequent major or minor release.

## Motivation
There currently is no standard approach for removing capabilities from Pyomo in a graceful manner.  Deprecation warnings provide a mechanism for alerting users that Pyomo developers plan to remove capabilities in future releases.

## Note
I do not think we can identify a specific rule for deciding whether capabilities are moved in major or minor releases.  Instead, we can let developers propose the release, which is then reviewed.

**Comment by jsiirola** [comment]
I am certainly all for the use of deprecation warnings wherever possible whenever changing a public API.

I believe that this PEP was meant to discuss #943.  IMHO, this PEP not around whether to use deprecation, but rather what process we should have around discussions/determinations to deprecate functionality that would break backwards compatibility with the Pyomo Book.

**Comment by whart222** [comment]
@jsiirola Are you suggesting that we need a process to propose a deprecation?  Why/How is that different from proposing the deprecation in a PR?  I think you are imagining a specific process, so why don't you propose one.

**Comment by whart222** [comment]
Perhaps the issue is removing capability vs. deprecating?  I'm not sure I see that difference, but it seems that we should have a low bar for deprecating functionality that we know is broken.

**Comment by blnicho** [comment]
At the PMC meeting yesterday we decided that proposals to deprecate functionality documented in the Pyomo book should be discussed at the PMC meeting and put to a vote.

**Comment by whart222** [comment]
Closing this PEP, which is now superseded by #1025 .
