### ISSUE TITLE
Solver error with imaginary number in .nl file

### ISSUE THREAD

**Issue by andrewlee94** [Pyomo/pyomo#953]
I have just run into an unusual error when trying to solve a Pyomo model using IPOPT, where I get the following error message shown below. It would be nice if the Pyomo would handle this more gracefully, and ideally give some guidance on where the imaginary number was coming from.

```
bad line 59 of /tmp/tmpxhpvwgvp.pyomo.nl: 4 (1843.8165960575566+24865.83408223902j)
terminate called after throwing an instance of 'Ipopt::TNLP::INVALID_TNLP'
Ipopt 3.12.6: tol=1e-06

Cannot open .nl file
ERROR: Solver (ipopt) returned non-zero return code (-6)
ERROR: See the solver log above for diagnostic information.
Traceback (most recent call last):
  File "module_2.py", line 91, in <module>
    m.fs.R101.initialize(outlvl=5)
  File "/home/alee/idaes/idaes-dev/idaes/core/unit_model.py", line 558, in initialize
    state_args=state_args)
  File "/home/alee/idaes/idaes-dev/idaes/core/control_volume0d.py", line 1478, in initialize
    **state_args)
  File "/home/alee/idaes/idaes-dev/examples/workshops/hda_ideal_VLE.py", line 493, in initialize
    results = solve_indexed_blocks(opt, [blk], tee=stee)
  File "/home/alee/idaes/idaes-dev/idaes/core/util/initialization.py", line 66, in solve_indexed_blocks
    results = solver.solve(tmp, **kwds)
  File "/home/alee/pyomo/pyomo/pyomo/opt/base/solvers.py", line 596, in solve
    "Solver (%s) did not exit normally" % self.name)
pyutilib.common._exceptions.ApplicationError: Solver (ipopt) did not exit normally
```

As best I can tell, it seems that an imaginary number is making its way into the .nl file, which is causing IPOPT to return the -6 return code. This error message is not particularly helpful in debugging the problem, as I have no idea where the imaginary number is coming from, so I have little to work with in trying to fix the problem.

This is probably due to the age of the .nl writer, but I think this problem should not even have made its way to IPOPT. The .nl writer probably should have caught this first, in which case it could also have given more guidance on where to find the problem.

**Comment by lbonini94** [comment]
same problem here
```
ERROR: Solver (ipopt) returned non-zero return code (-6)
ERROR: Solver log: Ipopt 3.12.13: bad line 2515 of /tmp/tmpfm0c7kyt.pyomo.nl:
    250 array([ 0.6      ,  0.5946564,  0.5893128,  0.5839692,  0.5786256,
    terminate called after throwing an instance of 'Ipopt::TNLP::INVALID_TNLP'
```

**Comment by mrmundt** [comment]
The new NL writer should trap this now; if the issue still persists, please open another issue.
