### ISSUE TITLE
Reconfigure solver objects to serve as context managers

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#97]
Define the __enter__ and __exit__ methods to support solvers who have resources that need to be freed up (e.g. licenses).

**Comment by whart222** [comment]
See https://jeffknupp.com/blog/2016/03/07/python-with-context-managers/

**Comment by qtothec** [comment]
I think this was done already?

**Comment by mrmundt** [comment]
This was done already in the `OptSolver` base class.

**Comment by jsiirola** [comment]
I agree that all solvers can be used as context managers, however, to my knowledge, @whart222's original use case has not been implemented (that is, using a licensed direct solver interface in a context manager does not explicitly free the license in the context manager exit).  Perhaps we should open a new issue to track that?
