### ISSUE TITLE
Simplified Model classes

### ISSUE THREAD

**Issue by whart222** [Pyomo/pyomo#98]
What is the Model class wasn't much more than a Block until a user tried to solve with it?  We might be able to dynamically limit the memory requirements and help users treat Models like Blocks.

**Comment by jsiirola** [comment]
I don't understand what you are advocating.  Models have always been a thin vaneer over top of Blocks, and the two objects have the same memory requirements and characteristics.  Further, you have always been able to use Models as Blocks (PySP does this, as do several other examples; e.g., some of @carldlaird's models).  If anything, we are moving in the opposite direction where we want Blocks to be able to more directly behave like Models.  See, for example, #94.

**Comment by whart222** [comment]
I'm suggesting that they could be a thinner vaneer.  Or perhaps we might have no difference between Block and Model.

**Comment by mrmundt** [comment]
Tracking this in the [Archived Design Discussions wiki page](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
