### ISSUE TITLE
Request: sqrt support in FBBT

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#984]
@michaelbynum Would it be very difficult to also support `sqrt()` in FBBT?

Right now it's giving:
```
WARNING: Unsupported expression type for FBBT: <class
    'pyomo.core.expr.numeric_expr.UnaryFunctionExpression'>. Bounds will not
    be improved in this part of the tree.
```

**Comment by qtothec** [comment]
I also suggest to change the warning code to:
```
logger.warning('Unsupported expression type for FBBT: {0}. Bounds will not be improved in this part of '
    'the tree.'
    ''.format(node.getname()))
```
instead of
```
logger.warning('Unsupported expression type for FBBT: {0}. Bounds will not be improved in this part of '
    'the tree.'
    ''.format(str(type(node))))
```

**Comment by michaelbynum** [comment]
@qtothec It is not difficult at all. Good suggestions. I will do so shortly.

**Comment by qtothec** [comment]
Also, I would like to point out that this issue might have been a PR if I had been more successful in figuring out how things worked in `fbbt.py` and `interval.py`. :wink:
