### ISSUE TITLE
TranformationFactory('core.fix_discrete') doesn't work for cloned models

### ISSUE THREAD

**Issue by RomeoV** [Pyomo/pyomo#995]
# Summary
I have noticed that often times `TransformationFactory('core.fix_discrete')` doesn't work for a model, i.e. it doesn't actually fix the variables. I have found out that it happens to cloned models (whereas 'normal' models work as expected).

## Minimal working example
```python
from pyomo.environ import *
m = ConcreteModel()
m.y = Var(domain=Integers, bounds=(0,10), initialize=0)
m_clone = m.clone()
TransformationFactory('core.fix_discrete').apply_to(m_clone)
m_clone.pprint()
```
yields
```
1 Var Declarations
    y : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :     0 :    10 : False : False : Integers
1 Suffix Declarations
    _fixed_discrete_vars : Direction=Suffix.LOCAL, Datatype=Suffix.FLOAT
        Key  : Value
        None :    []
2 Declarations: y _fixed_discrete_vars
```
Notice that the variable `y` didn't actually get fixed. If the `TranformationFactory` is intead applied to model `m`, the behaviour is as expected.

## Looking into the code
When diving into the code, the problem ends up being when the domain of the variable `y` is checked against a list of domains [here](https://github.com/Pyomo/pyomo/blob/ea161615a67b93c2540384eae4cce55e998dc8cc/pyomo/core/plugins/transform/discrete_vars.py#L116-L119)

The expression `var.domain in _discrete_relaxation_map` will yield `False`, even though `var` is an Integer.

**Comment by qtothec** [comment]
I think this is related to a discrepancy between `is` and `==` in the comparison due to the fact that `Integer` in the clone will have a different `id` than in the original.

**Comment by jsiirola** [comment]
This is a fundamental problem with the current Set system (continuous sets are not first-class `Set` components, and as such do not follow the block scoping rules within `Block.clone()`)

This will be addressed by #326.

**Comment by RomeoV** [comment]
What can I do until #326 is fixed? It seems like it might be a while. I don't want to 'hand-code' the functionality again for cloned models.

**Comment by RomeoV** [comment]
I have noticed that the expression `type(m.y) is type(m_clone.y)` is `True`, so that has lead me to the following 'dirty' fix:
Replace 
```python
var.domain in _discrete_relaxation_map
``` 
with 
```python
any(type(var.domain) is type(domain) for domain in _discrete_relaxation_map)
```
This will be slightly slower (although not by that much), but the transformation shouldn't be critical for performance. Additionally, imo it doesn't sacrifice readibility - instead it indicates that we are looking for domains in `_discrete_relaxation_map`, which was not very clear before.

I can submitt a PR if you think this is acceptable (for now).

**Comment by qtothec** [comment]
This issue can be seen as a consequence of https://github.com/Pyomo/pyomo/issues/165.
