### ISSUE TITLE
Add persistent interface / callback support for CBC

### ISSUE THREAD

**Issue by ansjain8** [Pyomo/pyomo#997]
Trying to add following code :
@pyomo_callback('cut-callback')
def cut-callback(solver, model):
    print "CB-Solve"

and 
opt = SolverFactory('cbc',executable='<cbc path>/bin/cbc')
opt.set_callback('cut-callback', cut_callback)

But callback not getting executed and CB-Solve not printing.

**Comment by jsiirola** [comment]
The short answer is that we do not currently support callbacks with CBC, but interested developers / PRs are always welcome.  Developing callbacks requires a persistent python interface to CBC, which Pyomo currently does not have.  Some quick searching points to [coin-ro/CyLP](https://github.com/coin-or/CyLP) as a possible path forward.

I am going to rename this issue to reflect the fundamental question (feature request).

**Comment by ansjain8** [comment]
Thanks for info. What can be possible alternative of Callback functionality in current version of pyomo code?

**Comment by mrmundt** [comment]
We have opened #1926 to track all CBC enhancement/feature requests and will close this issue.
