### ISSUE TITLE
[Deprecation] Redundant functionality `core.relax_integrality` and `core.relax_discrete`

### ISSUE THREAD

**Issue by RomeoV** [Pyomo/pyomo#998]
# Summary
There are currently two transformations both aimed at relaxing discrete variables [here](https://github.com/Pyomo/pyomo/blob/master/pyomo/core/plugins/transform/relax_integrality.py) and [here](https://github.com/Pyomo/pyomo/blob/master/pyomo/core/plugins/transform/discrete_vars.py).
The `core.relax_integrality` transformation is very basic. It changes the domain to `Reals` for every variable, irregardless of the previous domain. It also set's the upper and lower bound.

`core.relax_discrete` is more sophisticated and tries to detect discrete variables and trnasform then to the continuous counterpart (i.e. `NonNegativeIntegers`->`NonNegativeReals`). The problem with the implementation is that is doesn't work for cloned models. See discussion in #995 and #326.

Additionally, there only exist tests for `core.relax_integrality` (as far as I can tell).

# How to fix
Imo one of the two functionalities should be deprecated - probably the `relax_integrality` implementation. It should be noted that to use the functionality on clonded models (neccesary for many algorithms), currently `relax_discrete` does not work.

**Comment by blnicho** [comment]
Both of these transformations have been deprecated and replaced by the `core.relax_integer_vars` transformation.
