### ISSUE TITLE
Bug for GAMS writer when add add_options.

### ISSUE THREAD

**Issue by hbeden** [Pyomo/pyomo#999]
I use GAMS solver to solve an IDAES model, the code is shown below.
   solver = SolverFactory('gams',solver_io='shell')
    results = solver.solve(m, tee=True, tmpdir='E:\Softwares\TEMPFILE',keepfiles=True,
                           io_options=dict(solver='Conopt4',add_options='reslim=100;'))  .

The resulted GAMS file is shown in the figure.
![image](https://user-images.githubusercontent.com/25214932/57178294-8f544c80-6ea0-11e9-9925-06ee443c1dc2.png)

Thus lead to a bug.

**Comment by qtothec** [comment]
`add_options` expects an argument of type `list`. The correct syntax is:
```
results = solver.solve(
    m, tee=True, tmpdir='E:\Softwares\TEMPFILE',keepfiles=True,
    io_options=dict(solver='Conopt4',add_options=['reslim=100;']))
```

I prefer to simplify it further:
```
results = solver.solve(
    m, tee=True, tmpdir='E:\Softwares\TEMPFILE', keepfiles=True,
    solver='Conopt4', add_options=['reslim=100;'])
```
